'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EcoAcademyScript=api;})(typeof window==='object'?window:globalThis,()=>{
 const rows=[
 ['open','Confirm the request','Подтвердить запрос','Hi [name], I’m [specialist] from EcoGrid Academy. You asked for help with [registration / your account / the wallet]. Would you prefer to continue here in Telegram or arrange a short call?','Здравствуйте, [имя]. Я [специалист] из EcoGrid Academy. Вы попросили помочь с [регистрацией / кабинетом / кошельком]. Удобнее продолжить здесь в Telegram или договориться о коротком звонке?'],
 ['goal','Choose one useful result','Выбрать один результат','What would you like to do first: join the community, open your account or learn how to use EcoCoin? We’ll take one step at a time.','С чего хотите начать: вступить в сообщество, открыть кабинет или разобраться с EcoCoin? Пройдём по одному шагу.'],
 ['register','One EcoGrid account','Один аккаунт EcoGrid','If you already have an EcoGrid account, we’ll use it. Otherwise, open the official registration page and enter your details yourself. A deposit is not required to join the community or access your account.','Если у вас уже есть аккаунт EcoGrid, используем его. Если нет — откройте официальную страницу регистрации и самостоятельно заполните данные. Для вступления в сообщество и доступа в кабинет пополнение не требуется.'],
 ['groups','Join the community','Вступить в сообщество','The Academy channel contains short lessons. The Club group is for conversations, questions and sharing ideas. Open the official links and join. Let me know if either link does not open.','В канале Академии — короткие уроки. В группе Клуба — общение, вопросы и обмен идеями. Откройте официальные ссылки и вступите. Если какая-то ссылка не открывается, помогу.'],
 ['account','Make sure account access works','Проверить вход в кабинет','Can you sign in to your account? Let’s find the profile, Academy and support sections. You can install the account app from the account page when you’re ready.','Получилось войти в кабинет? Найдём профиль, Академию и поддержку. При желании установим приложение прямо со страницы кабинета.'],
 ['wallet','Help with the wallet','Помочь с кошельком','When you’re ready, follow the approved wallet guide. Create and control your wallet yourself. Never send a password, recovery phrase or private key to me, a bot or a group. We can continue with other lessons if you want to do this later.','Когда будете готовы, пройдём официальную инструкцию по кошельку. Вы создаёте и контролируете его самостоятельно. Пароль, фразу восстановления и приватный ключ нельзя отправлять мне, боту или в группу. Этот шаг можно пройти позже.'],
 ['gift','Explain the welcome gift','Объяснить подарок','EcoCoin is a Club welcome gift. We’ll check the current program steps and supported wallet before claiming it. I’ll confirm receipt only after the actual award and show what you can use it for. The gift is not a promise of investment income.','EcoCoin — приветственный подарок участнику Клуба. Проверим действующие шаги программы и поддерживаемый кошелёк перед получением. Подтвержу выдачу только после фактического начисления и покажу, как использовать подарок. Это не обещание инвестиционного дохода.'],
 ['lesson','Complete the first useful action','Первое полезное действие','Let’s choose one short lesson and complete its practical task. For example, find a product in your account, prepare a question or use EcoGrid AI to organize an idea.','Выберем один короткий урок и выполним практическое действие: найдём продукт в кабинете, подготовим вопрос или оформим идею с помощью EcoGrid AI.'],
 ['interest','A separate project conversation','Отдельный разговор о проекте','If you would like to explore an investment project, I can arrange a separate presentation with the project team. Would that be useful, or would you prefer to continue learning for now?','Если захотите изучить инвестиционный проект, могу организовать отдельную презентацию с командой направления. Это сейчас интересно или пока продолжим обучение?'],
 ['environment','Use technology thoughtfully','Пользоваться технологиями осознанно','Our goal is to use energy and equipment more thoughtfully, reduce waste and limit environmental harm. Specific impact claims need supporting evidence.','Наша цель — бережнее использовать энергию и технику, сокращать отходы и вред для природы. Конкретные результаты нужно подтверждать документами.'],
 ['close','Agree the next step','Согласовать следующий шаг','Today we completed [step]. Your next step is [one action]. You can return to the bot or ask for help in the support chat. If you requested a call, let’s agree its purpose, time and your time zone.','Сегодня сделали [шаг]. Дальше — [одно действие]. Можно вернуться в бот или написать в поддержку. Если нужен звонок, согласуем его цель, время и ваш часовой пояс.']
 ];
 return {scripts(language='en'){const ru=language==='ru';return rows.map(([id,en,ruTitle,text,textRu])=>({id,title:ru?ruTitle:en,text:ru?textRu:text,note:''}));}};
});
