'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EcoAcademyScript=api;})(typeof window==='object'?window:globalThis,()=>{
 const rows=[
 ["open","Confirm your interest","Уточнить запрос","Hi [name], I’m [specialist] from EcoGrid Academy. You asked about [project / account / participation]. Would you like a project walkthrough or help getting started? We can continue in Telegram or arrange a call if you prefer.","Здравствуйте, [имя]. Я [специалист] из EcoGrid Academy. Вы интересовались [проектом / кабинетом / участием]. Хотите сначала посмотреть проект или нужна помощь с началом работы? Можем продолжить в Telegram или договориться о звонке."],
 ["goal","Choose the right starting point","Выбрать точку входа","Are you still exploring the projects, or have you already decided to participate? Which direction interests you: Charge, Solar or Mining? What would you need to understand before your next step?","Вы пока знакомитесь с проектами или уже решили участвовать? Какое направление интересно: Charge, Solar или Mining? Что нужно понять перед следующим шагом?"],
 ["project","Show the project before registration","Показать проект до регистрации","Let’s review how the selected project earns revenue, its costs and risks, and what participation would mean. I’ll demonstrate the account without asking you to fund it. We distinguish current capabilities from features in development.","Разберём, откуда у выбранного проекта выручка, какие есть расходы и риски и что означает участие. Покажу кабинет без требования пополнения. Действующие возможности отделяем от функций в разработке."],
 ['register','One EcoGrid account','Один аккаунт EcoGrid','If you already have an EcoGrid account, we’ll use it. Otherwise, open the official registration page and enter your details yourself. A deposit is not required to join the community or access your account.','Если у вас уже есть аккаунт EcoGrid, используем его. Если нет — откройте официальную страницу регистрации и самостоятельно заполните данные. Для вступления в сообщество и доступа в кабинет пополнение не требуется.'],
 ['groups','Join the community','Вступить в сообщество','The Academy channel contains short lessons. The Club group is for conversations, questions and sharing ideas. Open the official links and join. Let me know if either link does not open.','В канале Академии — короткие уроки. В группе Клуба — общение, вопросы и обмен идеями. Откройте официальные ссылки и вступите. Если какая-то ссылка не открывается, помогу.'],
 ['account','Make sure account access works','Проверить вход в кабинет','Can you sign in to your account? Let’s find the profile, Academy and support sections. You can install the account app from the account page when you’re ready.','Получилось войти в кабинет? Найдём профиль, Академию и поддержку. При желании установим приложение прямо со страницы кабинета.'],
 ['wallet','Help with the wallet','Помочь с кошельком','When you’re ready, follow the approved wallet guide. Create and control your wallet yourself. Never send a password, recovery phrase or private key to me, a bot or a group. We can continue with other lessons if you want to do this later.','Когда будете готовы, пройдём официальную инструкцию по кошельку. Вы создаёте и контролируете его самостоятельно. Пароль, фразу восстановления и приватный ключ нельзя отправлять мне, боту или в группу. Этот шаг можно пройти позже.'],
 ["gift","500 EcoCoin and project AI mode","500 EcoCoin и AI-режим проекта","The welcome program provides 500 EcoCoin. The planned AI mode costs 472 EcoCoin for 30 days in your selected Charge, Solar or Mining project, leaving 28 EcoCoin after activation. Receiving the gift does not require an investment; using project AI mode requires participation in that project. We confirm the gift only after actual issuance. Activation terms are still being finalized.","В приветственной программе — 500 EcoCoin. Планируемый AI-режим стоит 472 EcoCoin на 30 дней в выбранном проекте Charge, Solar или Mining; после активации останется 28 EcoCoin. Получение подарка не требует вложений, а использование проектного AI-режима предполагает участие в этом проекте. Выдачу подтверждаем только по факту начисления. Условия активации ещё готовятся."],
 ["lesson","Find the project tools","Найти инструменты проекта","Let’s find your selected project, its documents and account tools. If you have decided to participate, we can walk through the agreed setup steps. Do not activate anything or transfer funds before reviewing the terms.","Найдём выбранный проект, документы и инструменты кабинета. Если вы решили участвовать, пройдём согласованные шаги настройки. До изучения условий ничего не активируем и средства не переводим."],
 ["interest","Review the proposal with the project team","Разобрать предложение с командой проекта","Would you like the project team to walk through the proposal, costs, risks and exit terms? We can arrange a presentation, or you can continue exploring first. We contact you by phone only if you request it.","Хотите вместе с командой проекта разобрать предложение, расходы, риски и условия выхода? Можно договориться о презентации или пока продолжить знакомство. По телефону связываемся, если вы этого попросите."],
 ['environment','Use technology thoughtfully','Пользоваться технологиями осознанно','Our goal is to use energy and equipment more thoughtfully, reduce waste and limit environmental harm. Specific impact claims need supporting evidence.','Наша цель — бережнее использовать энергию и технику, сокращать отходы и вред для природы. Конкретные результаты нужно подтверждать документами.'],
 ['close','Agree the next step','Согласовать следующий шаг','Today we completed [step]. Your next step is [one action]. You can return to the bot or ask for help in the support chat. If you requested a call, let’s agree its purpose, time and your time zone.','Сегодня сделали [шаг]. Дальше — [одно действие]. Можно вернуться в бот или написать в поддержку. Если нужен звонок, согласуем его цель, время и ваш часовой пояс.']
 ];
 return {scripts(language='en'){const ru=language==='ru';return rows.map(([id,en,ruTitle,text,textRu])=>({id,title:ru?ruTitle:en,text:ru?textRu:text,note:''}));}};
});
