'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EcoAcademyScript=api;})(typeof window==='object'?window:globalThis,()=>{
 const rows=[
 ["open","Confirm your interest","Уточнить запрос","Hi [name], I’m [specialist] from EcoGrid Academy. You asked about [project / account / participation]. Would you like a project walkthrough or help getting started? We can continue in Telegram or arrange a call if you prefer.","Здравствуйте, [имя]. Я [специалист] из EcoGrid Academy. Вы интересовались [проектом / кабинетом / участием]. Хотите сначала посмотреть проект или нужна помощь с началом работы? Можем продолжить в Telegram или договориться о звонке."],
 ["goal","Choose the right starting point","Выбрать точку входа","Are you still exploring the projects, or have you already decided to participate? Which direction interests you: Charge, Solar or Mining? What would you need to understand before your next step?","Вы пока знакомитесь с проектами или уже решили участвовать? Какое направление интересно: Charge, Solar или Mining? Что нужно понять перед следующим шагом?"],
 ["project","Show the project before registration","Показать проект до регистрации","Let’s review how the selected project earns revenue, its costs and risks, and what participation would mean. I’ll demonstrate the account without asking you to fund it. We distinguish current capabilities from features in development.","Разберём, откуда у выбранного проекта выручка, какие есть расходы и риски и что означает участие. Покажу кабинет без требования пополнения. Действующие возможности отделяем от функций в разработке."],
 ['register','One EcoGrid account','Один аккаунт EcoGrid','If you already have an EcoGrid account, we’ll use it. Otherwise, open the official registration page and enter your details yourself. A deposit is not required to join the community or access your account.','Если у вас уже есть аккаунт EcoGrid, используем его. Если нет — откройте официальную страницу регистрации и самостоятельно заполните данные. Для вступления в сообщество и доступа в кабинет пополнение не требуется.'],
 ['groups','Join the community','Вступить в сообщество','The Academy channel contains short lessons. The Club group is for conversations, questions and sharing ideas. Open the official links and join. Let me know if either link does not open.','В канале Академии — короткие уроки. В группе Клуба — общение, вопросы и обмен идеями. Откройте официальные ссылки и вступите. Если какая-то ссылка не открывается, помогу.'],
 ['account','Make sure account access works','Проверить вход в кабинет','Can you sign in to your account? Let’s find the profile, Academy and support sections. You can install the account app from the account page when you’re ready.','Получилось войти в кабинет? Найдём профиль, Академию и поддержку. При желании установим приложение прямо со страницы кабинета.'],
 ['wallet','Help with the wallet','Помочь с кошельком','When you’re ready, follow the approved wallet guide. Create and control your wallet yourself. Never send a password, recovery phrase or private key to me, a bot or a group. We can continue with other lessons if you want to do this later.','Когда будете готовы, пройдём официальную инструкцию по кошельку. Вы создаёте и контролируете его самостоятельно. Пароль, фразу восстановления и приватный ключ нельзя отправлять мне, боту или в группу. Этот шаг можно пройти позже.'],
 ["gift","500 EcoCoin and project AI mode","500 EcoCoin и AI-режим проекта","The welcome program provides 500 EcoCoin. The planned AI mode costs 472 EcoCoin for 30 days in your selected Charge, Solar or Mining project, leaving 28 EcoCoin after activation. Receiving the gift does not require an investment; using project AI mode requires participation in that project. We confirm the gift only after actual issuance. Activation terms are still being finalized.","В приветственной программе — 500 EcoCoin. Планируемый AI-режим стоит 472 EcoCoin на 30 дней в выбранном проекте Charge, Solar или Mining; после активации останется 28 EcoCoin. Получение подарка не требует вложений, а использование проектного AI-режима предполагает участие в этом проекте. Выдачу подтверждаем только по факту начисления. Условия активации ещё готовятся."],
 ["lesson","Find the project tools","Найти инструменты проекта","Let’s find your selected project, its documents and account tools. If you have decided to participate, we can walk through the agreed setup steps. Do not activate anything or transfer funds before reviewing the terms.","Найдём выбранный проект, документы и инструменты кабинета. Если вы решили участвовать, пройдём согласованные шаги настройки. До изучения условий ничего не активируем и средства не переводим."],
 ["interest","Review the proposal with the project team","Разобрать предложение с командой проекта","Would you like the project team to walk through the proposal, costs, risks and exit terms? We can arrange a presentation, or you can continue exploring first. We contact you by phone only if you request it.","Хотите вместе с командой проекта разобрать предложение, расходы, риски и условия выхода? Можно договориться о презентации или пока продолжить знакомство. По телефону связываемся, если вы этого попросите."],
 ['environment','Use technology thoughtfully','Пользоваться технологиями осознанно','Our goal is to use energy and equipment more thoughtfully, reduce waste and limit environmental harm. Specific impact claims need supporting evidence.','Наша цель — бережнее использовать энергию и технику, сокращать отходы и вред для природы. Конкретные результаты нужно подтверждать документами.'],
 ['close','Agree the next step','Согласовать следующий шаг','Today we completed [step]. Your next step is [one action]. You can return to the bot or ask for help in the support chat. If you requested a call, let’s agree its purpose, time and your time zone.','Сегодня сделали [шаг]. Дальше — [одно действие]. Можно вернуться в бот или написать в поддержку. Если нужен звонок, согласуем его цель, время и ваш часовой пояс.']
 ];
 function scripts(language='en',context={}){
  const ru=language==='ru',state=context.state||{},crm=context.crm||{},j=context.journey||context.context?.journey||state.journey||{};
  const active=state.plan?.status==='active'||state.miningPositions?.some(p=>p.status!=='closed'&&p.capital>0),presented=crm.presentationComplete||state.academy?.presentationComplete||state.planDraft?.savedBy==='manager',member=crm.clubMember||state.academy?.clubMember,clubEntry=j.topic==='club';
  const result=rows.map(([id,en,ruTitle,text,textRu])=>({id,title:ru?ruTitle:en,text:ru?textRu:text,note:''}));
  const get=id=>result.find(r=>r.id===id);
  get('open').text=ru?'Здравствуйте, [имя]. Я [специалист] из EcoGrid Academy. Продолжим с вашего текущего шага: знакомство с проектом, обсуждение предложения или помощь с продуктами? Если вам интересно сообщество, помогу вступить в Клуб.':'Hi [name], I’m [specialist] from EcoGrid Academy. Let’s continue from your current step: exploring a project, reviewing a proposal or using your products. I can also help you join the Club if you want.';
  get('goal').text=ru?'Уточните цель и выбранный проект. Готовому участнику не повторяйте вводную: разберите предложение и следующий согласованный шаг. Если запрос только о Клубе — сначала помогите с сообществом.':'Confirm the goal and selected project. For someone ready to participate, continue with the proposal and agreed next step. For a Club-only request, help with community access first.';
  get('groups').text=ru?'Клуб — добровольное продолжение знакомства с EcoGrid: общение, совместное обучение AI и обсуждения. Онлайн-сессии, живые встречи и гольф-сообщество планируются; конкретные мероприятия предлагаем только по подтверждённому анонсу. Для участия в проекте вступать в Клуб не обязательно.':'The Club is an optional way to stay involved: conversations, learning about AI together and project discussions. Online sessions, meetups and golf activities are planned; offer specific events only when announced. Club membership is not required to participate in a project.';
  get('account').text=ru?'Откройте Академию внутри кабинета. Новый посетитель видит демонстрацию, участник Клуба — помощь и сообщество, после презентации — предложение и документы, действующий участник — инструменты проекта. Установку приложения предложите после первого полезного действия.':'Open the Academy inside the account: newcomers see a demonstration, members get community and product guidance, presented clients continue with their proposal and documents, and active participants get project tools. Offer app installation after a useful first action.';
  get('gift').text+=' '+(ru?'Говорим о подарке после объяснения Клуба. Участник сам решает, нужен ли дополнительный режим.':'Explain the gift after introducing the Club. The member chooses whether the additional mode is useful.');
  const proposal={id:'proposal',title:ru?'Предложение и первое пополнение':'Proposal and first funding',text:ru?'Вернёмся к выбранному проекту и документам: сумма, расходы, права, выплаты и выход. После реальной демонстрации отметьте в CRM «Презентация проекта проведена». Если клиент сам решил участвовать, помогите выполнить первое пополнение через официальный кабинет и дождитесь подтверждения. Не повторяйте регистрацию и не делайте Клуб или AI обязательным условием.':'Return to the chosen project and its documents: amount, costs, rights, payouts and exit. Mark the presentation as completed in CRM only after it actually happened. If the client chooses to participate, guide first funding through the official account and wait for confirmation. Do not repeat registration or require Club membership or AI.',note:''};
  let ids=active?['open','lesson','account','wallet','groups','gift','close']:presented?['open','account','proposal','groups','gift','close']:member?['open','account','groups','wallet','gift','interest','close']:clubEntry?['open','goal','register','groups','account','wallet','gift','interest','close']:['open','goal','project','interest','register','account','proposal','groups','wallet','gift','close'];
  const mapped=new Map([...result,proposal].map(r=>[r.id,r]));return ids.map(id=>mapped.get(id));
 }
 return {scripts};
});
