'use strict';
window.EcoCallerGuide=(()=>{
 const {t,esc:E,money,api}=EcoCentral,M=EcoCallerModel;
 const labels={entry_new:['First visit','Первый вход'],entry_draft:['Saved option','Обсуждённый вариант'],stations:['Station','Станция'],compare:['Comparison','Сравнение'],terms:['Conditions','Условия'],funding:['Funding','Пополнение'],activation:['Activation','Активация'],next_contact:['Next contact','Следующий контакт']};
 const screens={dashboard:['Overview','Обзор'],map:['Stations','Станции'],tariffs:['My plan','План'],money:['Money','Деньги'],documents:['Documents','Документы'],help:['Help','Помощь']};
 let root,user,clientId=null,account=null,articles=[],mode='new',step=0,lang,notice='',poller,sequence=0,busy=false,compare;
 const L=v=>t(...v),button=(label,attrs='',primary=false)=>`<button type="button" class="crm-button ${primary?'primary':'outline'}" ${attrs}>${label}</button>`;
 const current=()=>articles.find(a=>a.journeyStep===M.route(mode)[step]);
 const path=()=>{const a=current();return a?new URL(EcoNavigation.destination('client',new URLSearchParams({tab:a.screen}),window.EcoLocale?.language),document.baseURI).href:'';};
 function initializeComparison(){const p=M.context(account?.state).plan,tier=EcoFinance.tiers.find(t=>t.id===p?.tierId)||EcoFinance.tiers[0];compare={amount:String(p?.capital||EcoFinance.minimum),tier:tier.id,alternative:String(p?.capital||EcoFinance.minimum),alternativeTier:EcoFinance.tiers[Math.min(EcoFinance.tiers.indexOf(tier)+1,EcoFinance.tiers.length-1)].id};}
 function message(text){notice=text;const el=root?.querySelector('[data-guide-notice]');if(el)el.textContent=text;}
 function context(){const c=M.context(account?.state),p=c.plan;return `<section class="cg-context"><div><small>${t('CONVERSATION CONTEXT','КОНТЕКСТ РАЗГОВОРА')}</small><strong>${E(account?.client.name||t('General walkthrough','Общий сценарий'))}</strong><span>${account?`${t('Available','Доступно')}: ${money(c.available)}${p?` · ${c.planKind==='active'?t('Active plan','Активный план'):t('Saved option','Сохранённый вариант')}: ${money(p.capital)} · ${E(p.rate)}%`:''}`:t('Open a client card to use their saved selection.','Откройте карточку клиента, чтобы учесть его сохранённый выбор.')}</span></div>${clientId?button(t('Client card','Карточка клиента'),`data-client="${E(clientId)}"`):button(t('Choose client','Выбрать клиента'),'data-tab="clients"')}</section>`;}
 function comparator(){if(!compare)initializeComparison();const select=(name,value)=>`<select name="${name}">${EcoFinance.tiers.map(v=>`<option value="${v.id}" ${v.id===value?'selected':''}>${E(window.EcoLocale?.t(v.name)||v.name)} · ${v.rate}% / ${t('calendar month','календарный месяц')} · ${v.count} ${t(v.count===1?'station':'stations',v.count===1?'станция':v.count<5?'станции':'станций')}</option>`).join('')}</select>`;return `<section class="cg-comparison"><h3>${t('Compare the weekly model','Сравнить недельную модель')}</h3><div class="cg-compare-grid"><fieldset><legend>${t('Starting option','Исходный вариант')}</legend><label>${t('Amount · USD','Сумма · USD')}<input name="amount" inputmode="decimal" maxlength="24" value="${E(compare.amount)}"></label><label>${t('Station group','Группа станций')}${select('tier',compare.tier)}</label></fieldset><fieldset><legend>${t('Alternative','Альтернатива')}</legend><label>${t('Amount · USD','Сумма · USD')}<input name="alternative" inputmode="decimal" maxlength="24" value="${E(compare.alternative)}"></label><label>${t('Station group','Группа станций')}${select('alternativeTier',compare.alternativeTier)}</label></fieldset></div><div data-compare-result aria-live="polite"></div><small>${t('Calculation only. The client’s saved plan and balance do not change.','Только расчёт. Сохранённый план и баланс клиента не меняются.')}</small></section>`;}
 function paintComparison(){const el=root?.querySelector('[data-compare-result]');if(!el)return;const c=M.comparison(compare.amount,compare.tier,compare.alternative,compare.alternativeTier);if(!c){el.innerHTML=`<p class="kb-warning">${t('Enter both amounts from','Введите обе суммы от')} ${money(EcoFinance.minimum)} ${t('to','до')} ${money(EcoFinance.maximum)}.</p>`;return;}
  const p=account?.state.plan?.status==='active'?account.state.plan:null;
  el.innerHTML=`<div class="cg-totals"><div><span>${t('Starting option / week','Исходный / неделя')}</span><strong>${money(c.base.weekly)}</strong></div><div><span>${t('Alternative / week','Альтернатива / неделя')}</span><strong>${money(c.alternative.weekly)}</strong></div></div><p>${t('Difference in model accrual','Разница модельного начисления')}: <b>${money(c.weeklyDelta)}</b> · ${t('Capital difference','Разница капитала')}: <b>${money(c.capitalDelta)}</b></p><p>${t('Monthly amount: capital × rate / 100. Weekly amount uses calendar days. Company fee in this model','За месяц: капитал × ставка / 100. За неделю — по календарным дням. Комиссия компании в модели')}: ${money(EcoFinance.companyFee)}.</p><p>${t('Larger capital means more funds committed. External fees and real returns are not verified.','Больший капитал означает большую сумму участия и риска. Внешние комиссии и реальный доход не подтверждены.')}</p>${p?`<p>${t('Existing active terms remain','Действующие условия сохраняются')}: ${money(p.capital)} · ${E(p.rate)}% / ${p.ratePeriod===EcoFinance.ratePeriod?t('calendar month','календарный месяц'):t('week','неделю')} → ${money(EcoFinance.planWeekly(p))} / ${t('week','неделя')}. ${t('The comparison does not replace them.','Сравнение их не подменяет.')}</p>`:''}`;
 }
 function paint(){if(!root?.isConnected)return;const route=M.route(mode),a=current();root.innerHTML=`<div class="kb-heading"><div><span class="kb-eyebrow">EcoGrid / ${t('CALLER DESK','РАБОЧЕЕ МЕСТО КОЛЛЕРА')}</span><h1>${t('Charge · presentation to FTD','Charge · презентация до FTD')}</h1><p>${t('Charge → proposal → documents → confirmed deposit','Charge → предложение → документы → подтверждённый депозит')}</p></div>${button(t('Knowledge base','База знаний'),'data-tab="knowledge"')}</div><div class="kb-notice" role="status" data-guide-notice>${E(notice)}</div>${context()}<div class="cg-mode" role="group" aria-label="${t('Entry scenario','Сценарий входа')}">${button(t('Choose after registration','Выбор после регистрации'),'data-guide-mode="new" aria-pressed="'+(mode==='new')+'"')}${button(t('Review saved option','Обсуждённый вариант'),'data-guide-mode="draft" aria-pressed="'+(mode==='draft')+'"')}</div>${mode==='draft'&&!account?.state.planDraft?`<p class="kb-warning">${t('No saved option is loaded. Use this route for rehearsal; confirm the client’s actual selection before presenting it.','Сохранённый вариант не загружен. Это просмотр сценария; перед презентацией проверьте фактический выбор клиента.')}</p>`:''}<div class="cg-layout"><nav class="cg-steps" aria-label="${t('Conversation steps','Шаги презентации')}">${route.map((key,i)=>button(`<span>${i+1}</span>${L(labels[key])}`,`data-guide-step="${i}" aria-current="${i===step?'step':'false'}"`)).join('')}</nav><div class="cg-stage" id="cg-stage">${a?article(a):`<section class="kb-empty"><h2>${L(labels[route[step]])}</h2><p>${t('No published material is available for this step. Ask the administrator to review it in the knowledge base.','Для этого шага нет опубликованного материала. Администратор проверяет и публикует его в базе знаний.')}</p>${button(t('Open knowledge base','Открыть базу знаний'),'data-tab="knowledge"')}</section>`}<div class="cg-navigation">${button(t('Previous','Назад'),'data-guide-move="-1" '+(step===0?'disabled':''))}<span>${step+1} / ${route.length}</span>${step<route.length-1?button(t('Next step','Следующий шаг'),'data-guide-move="1"',true):clientId?button(t('Record contact','Результат контакта'),'data-guide-contact',true):button(t('Client list','Список клиентов'),'data-tab="clients"',true)}</div></div></div>`;paintComparison();}
 function article(a){const source=a.sourceRef.startsWith('https://')?`<a href="${E(a.sourceRef)}" target="_blank" rel="noopener noreferrer">${E(a.sourceRef)}</a>`:E(a.sourceRef);return `<article class="kb-article"><div class="kb-detail-top"><span class="kb-badge" data-state="${a.status}">${a.status==='published'&&!a.hasDraft?t('Published','Опубликовано'):t('Draft · review','Черновик · проверка')} · v${a.version}</span><span>${t('Account screen','Экран ЛК')}: ${L(screens[a.screen])}</span></div><h2>${E(t(a.titleEn,a.titleRu))}</h2><section class="kb-prompt"><h3>${t('Ask first','Сначала уточните')}</h3><p>${E(t(a.promptEn,a.promptRu))}</p></section><section class="kb-answer"><div><h3>${t('Say · EN-US','Реплика · EN-US')}</h3>${button(t('Copy wording','Копировать реплику'),'data-guide-copy="answer"')}</div><p lang="en-US">${E(a.answerEn)}</p></section><details ${window.EcoLocale?.allowRussian===false?'hidden':''} class="kb-explanation" ${window.EcoLocale?.language==='ru'?'open':''}><summary>${t('Screen actions · RU','Что показать · RU')}</summary><p lang="ru">${E(a.explanationRu)}</p></details>${a.journeyStep==='compare'?comparator():''}<section class="kb-next"><h3>${t('Next step','Следующий шаг')}</h3><p>${E(t(a.nextEn,a.nextRu))}</p><div class="cg-link"><a class="crm-button outline" target="_blank" rel="noopener" href="${E(path())}">${t('Open screen','Открыть экран')} ↗</a>${button(t('Copy client link','Скопировать ссылку клиенту'),'data-guide-copy="link"')}</div><small>${t('The link opens the client’s own signed-in account or sign-in page. It does not sign you in as the selected client.','Ссылка открывает собственный аккаунт клиента или страницу входа. Она не выполняет вход от имени выбранного клиента.')}</small></section><section class="kb-source"><h3>${t('Source','Источник')}</h3><strong>${E(a.sourceTitle)}</strong><p>${source}</p><small>${t('Version','Версия')} ${a.version} · ${t('Workflow guide','Сценарий работы')}</small></section>${button(t('Answer and source in knowledge base','Ответ и источник в базе знаний'),`data-knowledge-article="${E(a.id)}"`)}</article>`;}
 async function refresh(){const key=++sequence;try{const [list,snapshot]=await Promise.all([api('staff/knowledge'),clientId?api('staff/clients/'+clientId):null]);if(key!==sequence||!root?.isConnected)return;const next=list.articles.filter(a=>a.journeyStep&&['draft','published'].includes(a.status));const changed=JSON.stringify(next)!==JSON.stringify(articles)||snapshot?.version!==account?.version||snapshot?.crm?.version!==account?.crm?.version;articles=next;account=snapshot;if(changed)paint();}catch(e){if(key!==sequence||!root?.isConnected)return;articles=[];account=null;paint();message(t('Unable to refresh access or materials. Return to the client list and try again.','Не удалось обновить доступ или материалы. Вернитесь к списку клиентов и повторите.'));}}
 async function click(e){const b=e.target.closest('button');if(!b||busy)return;
  if(b.dataset.guideMode){mode=b.dataset.guideMode;step=0;notice='';paint();}
  if(b.dataset.guideStep!==undefined||b.dataset.guideMove){step=b.dataset.guideStep!==undefined?Number(b.dataset.guideStep):step+Number(b.dataset.guideMove);step=Math.max(0,Math.min(M.route(mode).length-1,step));notice='';paint();if(innerWidth<850)root.querySelector('#cg-stage').scrollIntoView({behavior:'instant',block:'start'});}
  if(b.dataset.guideCopy){busy=true;try{const old=current(),fresh=await api('staff/knowledge/'+old.id);if(fresh.version!==old.version||fresh.status!==old.status||fresh.status==='needs_review')throw Error();if(clientId)await api('staff/clients/'+clientId);await navigator.clipboard.writeText(b.dataset.guideCopy==='answer'?fresh.answerEn:path());message(t('Copied.','Скопировано.'));}catch{await refresh();message(t('The material or access changed. Review the current version.','Материал или доступ изменился. Проверьте актуальную версию.'));}finally{busy=false;}}
 }
 function input(e){const el=e.target;if(!el.closest('.cg-comparison')||!Object.hasOwn(compare,el.name))return;compare[el.name]=el.value;paintComparison();}
 return {
  mount(host,actor,selected,snapshot){user=actor;const language=window.EcoLocale?.language,changedClient=clientId!==selected;clientId=selected||null;
   if(changedClient||!compare){account=snapshot||null;mode=M.context(account?.state).mode;step=0;initializeComparison();}
   if(!root||!root.isConnected||root.parentElement!==host){host.innerHTML='<div id="kb-root" class="cg-root" translate="no"></div>';root=host.firstElementChild;root.addEventListener('click',click);root.addEventListener('input',input);root.addEventListener('change',input);lang=language;paint();refresh();clearInterval(poller);poller=setInterval(()=>{if(!document.hidden&&!busy)refresh();},5000);}
   else if(lang!==language||changedClient){lang=language;notice='';paint();refresh();}
  },
  unmount(){++sequence;clearInterval(poller);root=null;},
 };
})();
