'use strict';
(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('../account-finance.js'):root.EcoFinance,typeof module==='object'&&module.exports?require('./club-model.js'):root.EcoClubModel);if(typeof module==='object'&&module.exports)module.exports=api;else root.EcoCallScripts=api;})(typeof window==='object'?window:globalThis,(finance,club)=>{
 const business=typeof module==='object'&&module.exports?require('../business-model.js'):globalThis.EcoBusiness;
 const funnel=typeof module==='object'&&module.exports?require('./funnel-model.js'):window.EcoFunnel;
 const zones=['America/Toronto','America/Vancouver','America/Halifax','America/Regina','America/St_Johns','America/New_York','America/Chicago','America/Denver','America/Los_Angeles','America/Phoenix','America/Anchorage','Pacific/Honolulu'];
 function parts(time,zone){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(time)).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));}
 function clock(zone,time=Date.now()){if(!zone)return {known:false,within:false};try{const p=parts(time,zone);return {known:true,within:Number(p.hour)>=9&&Number(p.hour)<20,local:`${p.year}-${p.month}-${p.day} ${p.hour}:${p.minute}`,hour:Number(p.hour)};}catch{return {known:false,within:false};}}
 function callback(local,zone){if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d$/.test(local)||!clock(zone).known)throw Error('Confirm the client timezone and callback time.');const target=Date.parse(local+'Z');if(!Number.isFinite(target)||new Date(target).toISOString().slice(0,16)!==local)throw Error('Enter a valid callback time.');const offsets=new Set();for(const d of [-36,-12,0,12,36]){const time=target+d*3600000,p=parts(time,zone);offsets.add(Date.parse(`${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:00Z`)-time);}const matches=[...offsets].map(o=>target-o).filter(time=>clock(zone,time).local===local.replace('T',' '));if(matches.length!==1)throw Error('This local time is missing or ambiguous due to daylight saving. Choose another time.');if(!clock(zone,matches[0]).within)throw Error('Choose a callback between 09:00 and 20:00 client time.');return new Date(matches[0]).toISOString();}
 function notes(input){if(!input||typeof input!=='object')throw Error('Complete the call notes.');const out={};for(const key of ['region','situation','problem','implication','needPayoff']){if(typeof input[key]!=='string'||input[key].length>(key==='region'?80:600))throw Error('Call notes are too long.');out[key]=input[key].trim();}if(!['ftd','club','retention','solar','mining','academy'].includes(input.script)||!['unknown','interested','later','declined','issue'].includes(input.clubInterest))throw Error('Choose a call script and Club interest.');if(typeof input.timezone!=='string'||input.timezone.length>80||input.timezone&&!clock(input.timezone).known)throw Error('Choose a valid client timezone.');const amount=input.amount===null||input.amount===''?null:finance.parseAmount(input.amount);if(amount!==null&&(!Number.isFinite(amount)||amount<0||amount>finance.maximum))throw Error('Enter a valid discussed amount.');return {...out,script:input.script,timezone:input.timezone,amount,clubInterest:input.clubInterest,serviceIssue:input.serviceIssue===true,textSent:input.textSent===true,seenWeek:input.seenWeek===true,seenWithdrawal:input.seenWithdrawal===true};}
 function clubReadiness(state={},crm={},time=Date.now()){state=state||{};crm=crm||{};if(crm.status==='do_not_contact')return 'do_not_contact';if(crm.callData?.serviceIssue||crm.callData?.clubInterest==='issue')return 'issue';if(crm.callData?.clubInterest==='declined')return 'declined';const f=club.firstFunding(state);if(!f||f.receiptChecked!==true)return 'no_funding';if(!funnel.firstWithdrawal(state,time))return 'no_withdrawal';return 'ready';}
 function baseScripts(kind,language='en',context={}){const ru=language==='ru',t=(en,r)=>ru?r:en,amount=context.crm?.callData?.amount||context.state?.planDraft?.capital,amountText=amount?new Intl.NumberFormat(ru?'ru-RU':'en-US',{style:'currency',currency:'USD'}).format(amount):t('[agreed amount]','[согласованная сумма]'),r=context.rules||{},bonus=new Intl.NumberFormat(ru?'ru-RU':'en-US',{style:'currency',currency:'USD'}).format((r.referrerCents||5000)*(r.campaign?.multiplier||1)/100);
 const section=(id,en,rus,textEn,textRu)=>({id,title:t(en,rus),text:t(textEn,textRu),note:id==='economics'?business.evidence(language):''});
 if(kind==='academy')return (typeof module==='object'&&module.exports?require('./academy-script.js'):window.EcoAcademyScript).scripts(language);
 const j=context.journey||context.state?.journey;
 if(kind==='ftd'&&j){const names={charge:'EcoGrid Charge',solar:'EcoGrid Solar',mining:'EcoGrid Mining',ai:t('EcoGrid technology','технологии EcoGrid'),ecocoin:'EcoCoin',club:'EcoGrid Club',energy:'EcoGrid'},name=names[j.topic]||'EcoGrid';
 if(j.route==='nurture')return [section('explore','Exploration preference','Самостоятельное знакомство','This person saved an interest in '+name+'. They did not request a sales call. Use the relevant guide; wait for a consultation request before entering the call queue.','Человек сохранил интерес к '+name+'. Он не запрашивал звонок продавца. Ориентируйте на материал по теме; в очередь звонка переводите после запроса консультации.')];
 return [section('open','Confirm the request','Подтвердить запрос','Hi [name], this is [manager] with EcoGrid. You requested details about '+name+'. Is now a good time to discuss that specific direction?','Здравствуйте, [имя]. Это [менеджер] EcoGrid. Вы запросили информацию по '+name+'. Удобно сейчас обсудить именно это направление?'),
 section('objective','Understand the objective','Уточнить задачу','What would you like to understand before making a decision? Confirm whether this is project participation, equipment for your property or a business partnership.','Что хотите понять до принятия решения? Подтвердите задачу: участие в проекте, оборудование для своего объекта или деловое партнёрство.'),
 section('context','Keep the original context','Сохранить контекст входа','Which guide or page brought you here, and what questions remain? Do not make the person repeat information already recorded in the request.','Какая страница или материал привели вас сюда и какие вопросы остались? Не просите повторять сведения, которые уже есть в заявке.'),
 section('details','Discuss the selected project','Обсудить выбранный проект','Review the relevant site, equipment, operating stage, responsible team and proposed terms. Separate confirmed information from estimates and planned features.','Разберите площадку, оборудование, стадию работы, ответственную команду и условия. Отделяйте подтверждённые сведения от расчётов и планируемых возможностей.'),
 section('next','Agree one useful next step','Согласовать полезный следующий шаг','Would project information, a technical discussion or account access be useful next? Confirm the contact channel and timing. Record a qualified lead only after confirming the need and next step.','Что полезнее дальше: сведения о проекте, техническая консультация или доступ в кабинет? Согласуйте канал связи и время. Квалифицируйте заявку после подтверждения задачи и следующего шага.')];}
 if(kind==='mining')return [
section('open','Mining inquiry','Заявка о майнинге','Hi [name], this is [manager] with EcoGrid. You asked about mining. Is now a good time to compare project participation with owning an ASIC?','Здравствуйте, [имя], это [менеджер] EcoGrid. Вы интересовались майнингом. Удобно сравнить участие в общем проекте и собственный ASIC?'),
section('qualify','Format and budget','Формат и бюджет','Would you like participation in a shared project, your own machine with hosting, or equipment for your site? What budget and time horizon should we consider? Which coin interests you, and what experience do you have with mining?','Вам ближе участие в общем проекте, свой майнер с размещением или оборудование для вашей площадки? Какой бюджет и срок рассматриваете? Какая монета интересует и есть ли опыт с майнингом?'),
section('model','Explain the operating model','Объяснить экономику','Each ASIC supports a specific algorithm. More units increase potential revenue and costs together; efficiency affects the net result. ASICs contribute computing power to a mining pool. The project receives mining revenue, then pays for electricity, the pool fee and operations. Any distribution follows the signed project terms; it is not a fixed monthly return.','У каждого ASIC свой алгоритм. Больше устройств — больше потенциальной выручки и расходов; эффективность влияет на чистый результат. ASIC передаёт вычислительную мощность в майнинг-пул. Из полученной выручки оплачиваются электричество, комиссия пула и эксплуатация. Распределение идёт по подписанным условиям проекта; это не фиксированный месячный процент.'),
section('compare','Review three scenarios','Разобрать три сценария','Let us review the ASIC, hashprice, electricity price, uptime and all fees together. The calculator is an illustration, not current pool data. Hardware cost, depreciation, taxes and exit expenses must also be considered before discussing a return on capital. Results can be negative.','Давайте сверим ASIC, выручку на мощность, тариф энергии, время работы и комиссии. Калькулятор показывает пример, а не данные пула. До расчёта доходности капитала учитываем стоимость оборудования, амортизацию, налоги и выход. Результат может быть отрицательным.'),
section('terms','What the written proposal includes','Что будет в предложении','For shared participation, review the project entity, site, ownership rights, share, reporting, distribution and exit terms. For your own ASIC, also review the serial number, warranty, hosting charges, repair rules and equipment removal. Which items would you like to check first?','Для общего проекта проверяем юридическое лицо, площадку, права, долю, отчётность, распределение и выход. Для своего ASIC — также серийный номер, гарантию, плату за размещение, ремонт и вывоз. Что хотите проверить в первую очередь?'),
section('close','Agree the next step','Согласовать следующий шаг','I will record your preferred format and budget and prepare the proposal for review. This request takes no payment and creates no mining position. When should we review the details together?','Я сохраню формат и бюджет и подготовлю предложение для изучения. Заявка не принимает оплату и не создаёт участия в майнинге. Когда удобно вместе разобрать условия?')
];
 if(kind==='retention')return [
 section('open','Third call · after withdrawal','Третий звонок · после вывода','Hi [name], this is [manager] with EcoGrid. Is this a good time to review your first withdrawal experience?','Здравствуйте, [имя], это [менеджер] из EcoGrid. Удобно обсудить опыт первого вывода?'),
 section('confirm','Confirm receipt and context','Уточнить получение и контекст','Our workspace records the first withdrawal as approved. Did it complete as you expected? In the current account model, approval is a model entry; it does not prove a real bank or wallet transfer. Confirm the actual receipt only if a real payment record exists.','В кабинете первый вывод отмечен подтверждённым. Всё прошло так, как вы ожидали? В текущей модели счёта подтверждение — запись модели, не доказательство перевода в банк или кошелёк. Фактическое получение подтверждаем только по реальному платежу.'),
 section('service','Resolve issues first','Сначала решить вопросы','Was anything slow, unclear or inconvenient? If money has not arrived or there is an unresolved issue, I will record it and focus on fixing it. We will not discuss funding or referrals today.','Что было долго, непонятно или неудобно? Если средства не поступили или есть нерешённый вопрос, зафиксирую его и займусь решением. Сегодня пополнение и рекомендации не обсуждаем.'),
 section('permission','Permission for the next topic','Разрешение перейти дальше','If everything is clear, would you prefer to leave things as they are, review your current plan, or hear about the optional Club? Any of those is fine.','Если всё понятно, как вам удобнее: оставить всё как есть, посмотреть текущий план или узнать про необязательный Club? Подходит любой вариант.'),
 section('club','Optional Club introduction','Необязательное приглашение в Club','If you want to share the information with someone, we can review the Club terms together. Rewards apply to direct referrals only. The referral trigger remains first checked funding of at least $250; your withdrawal changes the timing of this conversation, not the reward rules. Check the current program status and budget before quoting a bonus.','Если хотите поделиться информацией со знакомым, можем вместе посмотреть условия Club. Денежный бонус — только за личное приглашение. Условие остаётся прежним: первое подтверждённое пополнение друга от $250. Ваш вывод меняет время этого разговора, а не правило бонуса. Перед озвучиванием бонуса проверяем состояние программы и бюджет.'),
 section('repeat','Optional additional funding','Необязательное повторное пополнение','Would you like to compare your current plan with an additional amount you already intended to allocate? There is no need to increase it. I will not suggest using borrowed money, emergency savings, or an amount you need for expenses.','Хотите сравнить текущий план с дополнительной суммой, которую вы и так рассматривали для участия? Увеличивать её не обязательно. Я не предлагаю использовать кредит, резерв на непредвиденные расходы или деньги на текущие нужды.'),
 section('compare','Compare before deciding','Сравнить до решения','Tell me the amount you want to compare. I will show current capital, additional funds, total capital, the selected monthly model rate and its calendar-based estimate. A higher amount does not automatically mean a different tariff. Preparing a draft neither funds nor activates it.','Назовите сумму для сравнения. Покажу текущий капитал, добавление, общий капитал, ставку выбранного тарифа за месяц и календарный расчёт. Большая сумма сама по себе не переключает тариф. Подготовка черновика не пополняет и не активирует план.'),
 section('limits','Keep risks visible','Сохранить границы','One completed withdrawal does not guarantee future returns or protect capital. The Energy Lab and displayed rates are models, not verified station revenue. You can review the terms independently or stop without changing the plan.','Один завершённый вывод не гарантирует будущую доходность и сохранность капитала. Energy Lab и ставки на экране — модель, не подтверждённая выручка станций. Можно самостоятельно проверить условия или закончить разговор без изменения плана.'),
 section('close','Agree one next step','Согласовать один шаг','What would be useful now: keep the current plan, receive the comparison, or review the Club link? I will only prepare what you asked for. If you want more time, let’s agree a callback in your time zone.','Что сейчас полезнее: оставить текущий план, получить сравнение или посмотреть ссылку Club? Подготовлю только то, что вы попросили. Если нужно время, согласуем перезвон по вашему часовому поясу.'),
 section('wrap','Record the outcome','Записать итог','Confirm the agreed next step, any service issue and the callback time. Mark a Club invitation only if it was actually discussed during a connected call. No deposit, message, or plan change is created by these notes.','Подтвердите согласованный шаг, сервисный вопрос и время перезвона. Приглашение в Club отмечайте только если действительно обсудили его при дозвоне. Эти заметки не создают депозит, сообщение или изменение плана.')];
 if(kind==='club')return [
 section('open','Opening','Открытие','Hi [name], this is [manager] with EcoGrid. After reviewing your first approved withdrawal, would you like a short conversation about your experience and the optional referral program?','Здравствуйте, [имя]! Это [менеджер] из EcoGrid. После первого подтверждённого вывода удобно обсудить ваш опыт и отдельную программу приглашений?'),
 section('situation','Situation · experience','Situation · опыт клиента','How is the account working for you? Is anything unclear or inconvenient? Have you mentioned it to anyone you know? If there is an unresolved issue, let’s deal with that first.','Как вам кабинет? Что непонятно или неудобно? Вы кому-нибудь уже рассказывали о нём? Если остался нерешённый вопрос, сначала разберём его.'),
 section('problem','Problem · sharing','Problem · рекомендация','Would anything make you uncomfortable about sharing the information: explaining the details, the risks, or sounding like a salesperson?','Что мешает поделиться информацией: сложно объяснить детали и риски или не хочется выглядеть продавцом?'),
 section('implication','Implication · practical barrier','Implication · препятствие','What would you need to feel comfortable sharing it without making promises on the company’s behalf?','Что вам нужно, чтобы спокойно поделиться информацией, не давая обещаний от имени компании?'),
 section('payoff','Need-payoff · permission','Need-payoff · согласие','Would a short description and your personal link help? Your friend can review it independently and decide whether to ask for more information.','Помогли бы короткое описание и личная ссылка? Знакомый сможет самостоятельно всё изучить и решить, нужно ли ему узнавать больше.'),
 section('terms','Referral program terms','Условия программы приглашений',r.enabled?`The workspace program is configured for ${bonus} for a personal invitation, once after the friend’s first confirmed funding of at least $250. The payment receipt must be checked. It does not wait for their first week. Both program budgets and eligibility checks apply. ${r.welcomeCents?'The current welcome bonus is $'+(r.welcomeCents/100).toFixed(2)+'.':'A welcome bonus has not been set, so I cannot promise one.'}`:`The referral program screen and personal link are available. The planned direct invitation reward is ${bonus} after first confirmed funding of at least $250, but rewards are currently paused pending program activation and a budget. A welcome bonus has not been set. I cannot promise a payout.`,r.enabled?`Программа предусматривает ${bonus} за личное приглашение — разово после первого подтверждённого пополнения друга от $250 и проверки поступления. Ждать первую неделю не нужно. Действуют бюджеты программы и проверка условий. ${r.welcomeCents?'Текущий приветственный бонус: $'+(r.welcomeCents/100).toFixed(2)+'.':'Приветственный бонус не задан, обещать его нельзя.'}`:`Раздел приглашений и личная ссылка доступны. Предусмотрен бонус ${bonus} после первого подтверждённого пополнения друга от $250, но начисления приостановлены до включения программы и задания бюджета. Приветственный бонус не задан. Обещать выплату нельзя.`),
 section('status','Separate referral terms','Отдельные условия приглашений','The referral program is separate from community membership. One bonus applies to a direct invitation. There are no ranks or commissions from another generation. Plan rates and withdrawal terms stay the same.','Программа приглашений действует отдельно от членства в сообществе. За личное приглашение предусмотрен один бонус. Ступеней и комиссий со следующего круга нет. Ставки плана и условия вывода не меняются.'),
 section('limits','Important conditions','Важные условия','Only the first confirmed funding counts; smaller payments are not added together. Self-referrals and duplicates are not eligible. A pending reward is not available balance. A confirmed refund or dispute needs an administrator’s review; reversal is not an automatic payment-provider integration. Ask your tax adviser about any actual reward income. This build uses model credits, not real payments.','Учитывается первое подтверждённое пополнение; маленькие платежи не складываются. Самоприглашения и дубли не подходят. Ожидающий бонус не входит в баланс. Подтверждённый возврат или спор рассматривает администратор; автоматической связи с возвратами платёжного провайдера нет. Налоги с фактически полученного вознаграждения уточняйте у налогового консультанта. В этой сборке средства модельные.'),
 section('close','Close','Завершение','Would you like a short description you can edit and share yourself? I can prepare it for the account chat. There is no need to name your contacts. If you are not interested, that is fine; I will note your preference.','Хотите короткий текст, который можно поправить и отправить самому? Я могу подготовить его для чата кабинета. Называть контакты знакомых не нужно. Если неинтересно, зафиксирую это и не буду возвращаться к предложению.'),
 section('objections','Objections','Возражения','Why no second-level payments? — The program pays only for a personal referral from its acquisition budget.\nI do not want to sell to friends. — Then do not promise returns or recommend a payment. You may simply share information if you choose.\nWill you personally handle my friend? — The administrator assigns their manager. I cannot promise their assignment or disclose their private account details.','Почему нет выплат со второго уровня? — Программа платит только за личное приглашение из бюджета привлечения.\nНе хочу продавать друзьям. — Не обещайте доход и не уговаривайте платить. Можно просто поделиться информацией по своему желанию.\nВы лично займётесь другом? — Менеджера назначает администратор. Я не могу обещать закрепление за мной или раскрывать сведения чужого кабинета.'),
 section('wrap','Wrap-up','Итог','Thanks, [name]. I have noted your preference: [interested / later / not interested]. If you asked for the sharing text, we will agree when I will send it in your account chat. If you requested a follow-up, let’s confirm the date, your local time and time zone. You do not need to invite anyone to use your plan.','Спасибо, [имя]. Зафиксировал ваше решение: [интересно / позже / неинтересно]. Если вы попросили текст рекомендации, согласуем, когда я отправлю его в чат кабинета. Если нужен следующий разговор, подтвердим дату, ваше местное время и часовой пояс. Для пользования планом никого приглашать не нужно.')];
 return [
 section('open','Opening and permission','Открытие и разрешение','Hi, is this [client name]? This is [manager] with EcoGrid. You requested information on our website about the solar, battery storage and EV charging participation model. Is now a good time for a couple of minutes? If not, what callback time and time zone work for you?','Здравствуйте, это [имя клиента]? Меня зовут [менеджер], я из EcoGrid. Вы оставляли заявку на сайте об участии в солнечной генерации, накопителях и зарядной инфраструктуре. Удобно сейчас пару минут? Если нет, на какое время и в каком часовом поясе договоримся о звонке?'),
 section('situation','Situation','Situation','What caught your attention? What would you like to understand before deciding whether to continue? Are you mainly looking to understand risks, access to funds or the model calculation? What amount, if any, would you like to compare? You do not need to disclose your account balances or retirement savings.','Что заинтересовало на сайте? Что хотите понять, прежде чем решать, стоит ли продолжать? Важнее разобраться с рисками, доступом к деньгам или расчётом модели? Какую сумму, если вообще рассматриваете участие, хотите сравнить? Раскрывать остатки на счетах или пенсионные накопления не нужно.'),
 section('problem','Problem','Problem','What information is missing or difficult to verify? Have you previously seen an offer where the explanation of returns did not match the documents?','Какой информации не хватает или что сложно проверить? Встречались предложения, где объяснение дохода расходилось с документами?'),
 section('implication','Implication','Implication','How would an unclear source of returns or access-to-funds rule affect your decision? Which point would you need resolved before considering any commitment?','Как непонятный источник дохода или порядок доступа к деньгам влияет на ваше решение? Какой вопрос нужно закрыть до обсуждения участия?'),
 section('payoff','Need-payoff','Need-payoff','Would a comparison of the amount, selected plan, calculation and available documents help you make your own assessment? The animation itself is not evidence of ownership or revenue.','Поможет ли сравнение суммы, тарифа, расчёта и доступных документов сделать собственную оценку? Сама анимация не подтверждает владение станциями или выручку.'),
 section('economics','How the current model works','Как работает текущая модель',''+business.copy('en')+' The full calendar-month model is capital × the selected plan rate: Single 13% from $250, Network 14% from $500, Portfolio 15% from $800, and Custom 16% for an amount from $1,000. Weekly credits are prorated across UTC calendar days (28–31 per month). Club status adds no rate increase. These figures are not verified station returns.',''+business.copy('ru')+' Модель за полный календарный месяц: капитал × ставка тарифа. Single — 13% от $250, Network — 14% от $500, Portfolio — 15% от $800, Custom — 16% при сумме от $1 000. Недельное начисление считается по календарным дням UTC с учётом длины месяца (28–31 день). Статус Club не добавляет процент. Это не подтверждённый доход станций.'),
 section('evidence','Documents and limits','Документы и границы','We can review the directory, plan calculation and available documents. Station directory entries and photos do not establish company ownership or an investment right. Legal terms and real payment connections have not been completed in this build. I will record any missing evidence instead of making assumptions.','Можем посмотреть справочник станций, расчёт плана и доступные документы. Карточки и фотографии станций не устанавливают владение компании или право на доход. Фактические условия продукта и реальные платежи в этой сборке ещё не подключены. Отсутствующие подтверждения я запишу отдельным вопросом.'),
 section('close','Saved plan and next step','План и следующий шаг',`You mentioned ${amountText} as an amount to compare. With your agreement, I can prepare a plan for that amount. I will confirm it is saved before asking you to review it. Funding and activation are separate steps; the weekly period begins only after activation. In this build, payment submission is a preview request for staff review, not an automatic real deposit. Would you prefer to review the account now or agree on a callback?`,`Вы назвали ${amountText} для сравнения. С вашего согласия подготовлю план на эту сумму. Сначала проверю, что он сохранён, затем предложу его посмотреть. Пополнение и активация — разные шаги; недельный период начинается только после активации. В этой сборке отправка платежа — заявка для проверки сотрудником, а не автоматическое реальное пополнение. Удобнее посмотреть кабинет сейчас или договориться о звонке?`),
 section('objections','Objections','Возражения','Is this a pyramid scheme? — A screen or calculation cannot resolve that question. The funding source, rights and operator documents must be independently verified; I do not have proof of real station-funded returns in this build.\nWhat is guaranteed? — I cannot promise returns or capital protection. The displayed rates are model inputs, not a guarantee.\nI need to think or consult an adviser. — Please do. Which documents or unanswered questions would help you assess it?\nI do not have spare money. — Then let’s not discuss a deposit. You can stop here or review the information without a payment.\nDo not call again. — Understood. I will record that now and cancel the callback.','Это пирамида? — По экрану или расчёту это определить нельзя. Нужно независимо проверить источник средств, права и документы оператора. В этой сборке у меня нет подтверждения реального дохода от станций.\nКакие гарантии? — Я не могу обещать доход или сохранность капитала. Ставки на экране — параметры модели, а не гарантия.\nНадо подумать или посоветоваться. — Разумеется. Какие документы или ответы помогут оценить предложение?\nНет свободных денег. — Тогда депозит не обсуждаем. Можно остановиться или посмотреть информацию без оплаты.\nНе звоните больше. — Понял. Зафиксирую это сейчас и отменю перезвон.'),
 section('wrap','Wrap-up','Итог','Let me confirm what we actually agreed: [saved plan, if saved], [open questions], and [callback date, client-local time and time zone, if requested]. Registered clients can message their assigned manager through the account chat.','Подтвержу, о чём договорились: [план, если действительно сохранён], [открытые вопросы] и [дата, местное время и часовой пояс перезвона, если согласован]. Зарегистрированный клиент может написать закреплённому менеджеру в чате кабинета.')];
 }

 // The same operational explanation appears on the site and in the account.
 function scripts(kind,language='en',context={}){
  const rows=baseScripts(kind,language,context),j=context.journey||context.state?.journey;
  if(kind==='academy'||kind==='ftd'&&j?.route==='nurture')return rows;
  const ru=language==='ru',topic=kind==='mining'?'mining':kind==='club'?'club':j?.topic==='ai'?'energy':j?.topic||'energy',c=business.ai(topic,language);
  if(kind==='ftd'&&['energy','solar','charge'].includes(topic)){
   const text=ru?'Нестабильность мировых поставок влияет на цены нефти, бензина и дизеля. Их сжигание также создаёт выбросы. Поэтому есть практический смысл изучать солнечную генерацию и зарядную инфраструктуру: панели производят энергию без закупки топлива для генерации, а зарядные станции обслуживают электротранспорт. Для участника проекта важен следующий шаг — понять, кто покупает энергию или зарядку, какие есть расходы и как устроен выход. Давайте разберём это на выбранном проекте.':'Global supply disruptions affect oil, gasoline and diesel prices, and burning those fuels produces emissions. That gives us a practical reason to examine solar generation and EV charging: panels generate power without fuel purchases, and charging sites serve electric vehicles. For someone considering a project, the next step is to understand who pays for the power or charging, what it costs to operate and how an exit works. Let’s review those points for the project you selected.';
   const at=rows.findIndex(r=>['details','economics','payoff'].includes(r.id));rows.splice(at<0?2:at,0,{id:'energy-market',title:ru?'Почему сейчас · топливо и инфраструктура':'Why now · fuel costs and infrastructure',text,note:ru?'Контекст: EIA, сентябрь 2026. Перед актуальной ценовой цифрой обновите источник: https://www.eia.gov/outlooks/steo/report/ . Дорогая нефть не доказывает рост тарифа на электричество, прибыль или высокую ликвидность проекта. Прибыль обсуждаем по выручке и расходам, ликвидность — по документированным условиям и срокам выхода. Не обещать гарантированный профит или быстрый выход.':'Context: EIA, September 2026. Refresh any current price claim at https://www.eia.gov/outlooks/steo/report/ . Higher oil prices do not establish higher electricity tariffs, project profits or liquidity. Discuss profit using project revenue and costs; discuss liquidity using documented exit terms and timing. Do not promise guaranteed gains or a quick exit.'});
  }
  if(['ftd','mining'].includes(kind)&&['energy','charge','solar','mining'].includes(topic)&&(!j?.purpose||j.purpose==='participation')){
   const offer=business.programCopy(topic,language);
   rows.push({id:'project-ai-program',title:ru?'EcoCoin · 30 дней AI-режима':'EcoCoin · 30 days of project AI mode',text:[offer.body,offer.price,offer.gift,offer.rules,offer.supplement,offer.availability].join(' '),note:ru?'В концепции пользователя AI дополняет базовую ставку. Диапазон 3–6 требует определения: процентные пункты или относительная прибавка, период и источник расчёта. Не озвучивать его как измеренный или гарантированный эффект. В Mining сохраняется отдельная переменная экономика; фиксированную ставку к нему не переносить. Реальное распределение, списание монет и начисление надбавки не подключены.':'The concept adds AI to the base terms. The proposed 3–6 range still needs a unit, period and calculation basis. Do not present it as measured or guaranteed performance. Mining retains its separate variable economics; do not apply a fixed plan rate to it. Allocation execution, coin redemption and additional credits are not connected.'});
  }
  const memberBenefit=business.ai('club',language);
  if(kind==='retention')rows.push({id:'club-ai',title:ru?'EcoGrid Club · бесплатный AI':'EcoGrid Club · free AI',text:memberBenefit.body,note:''});
  const ai={id:'ecogrid-ai',title:ru?'EcoGrid AI · польза для клиента':'EcoGrid AI · client benefit',text:c.body,note:''};
  const at=rows.findIndex(r=>['details','compare','economics','close'].includes(r.id));rows.splice(at<0?Math.min(3,rows.length):at,0,ai);
  if(['ftd','mining'].includes(kind))rows.push({id:'ai-questions',title:ru?'Если клиент спрашивает об AI':'If the client asks about AI',text:ru?'За счёт чего это помогает прибыли? — Например, дневную солнечную энергию можно сохранить для вечернего спроса вместо закупки в дорогие часы. AI сопоставляет варианты с учётом тарифов, нагрузки и ограничений оборудования. Меньше лишних расходов — лучше операционный результат. Для майнинга дополнительно учитываем мощность, охлаждение и стоимость энергии.\nВ чём ваше преимущество? — Мы связываем генерацию, накопители и потребление общим инструментом управления. Обсуждаем конкретный объект и показываем расчёт, на каких затратах можно сэкономить.\nДоход гарантирован? — Нет. AI помогает управлять затратами и оборудованием, а итог зависит также от спроса, тарифов, рынка и условий проекта.':'How can this support profit? — Daytime solar energy can be stored for evening demand instead of buying power at expensive hours. AI compares the options against tariffs, demand and equipment limits. Lower avoidable costs improve the operating result. Mining also requires computing output, cooling and energy costs to be considered.\nWhat is your advantage? — We connect generation, storage and consumption through one operating tool. We discuss the actual site and show which costs the calculation could reduce.\nAre returns guaranteed? — No. AI helps manage costs and equipment; the outcome also depends on demand, tariffs, market conditions and project terms.',note:''});
  rows.push({id:'environment',title:ru?'Климат, ресурсы и отходы':'Climate, resources and waste',text:ru?'Глобальное потепление, добыча металлов и электронный мусор — часть проблем, которые мы хотим учитывать в развитии EcoGrid. Наша цель — более эффективное использование энергии, долгая служба техники, ремонт и ответственная переработка. Для конкретного проекта экологические результаты нужно подтверждать документами.':'Global warming, metal extraction and electronic waste are issues we want EcoGrid projects to address. Our goal is more efficient energy use, longer-lasting equipment, repair and responsible recycling. Environmental results for a specific project need supporting evidence.',note:''});
  return rows;
 }
 function shareText(language='en'){return language==='ru'?'Я изучаю кабинет EcoGrid: там можно посмотреть модель распределения нагрузки и расчёт плана. Это не подтверждение реального дохода и не моя рекомендация вкладывать деньги. Если интересно, вот ссылка на информацию: [моя ссылка из Club]. Условия и документы лучше проверить самостоятельно.':'I’m exploring the EcoGrid workspace and its charging-load and plan models. This does not verify real returns and is not my recommendation to invest. If you want to review the information: [my link from Club]. Please assess the terms and documents independently.';}
 return {zones,clock,callback,notes,clubReadiness,scripts,shareText};
});
