'use strict';
if(window.ECO_SHARED_CONTEXT)(()=>{
 const $=s=>document.querySelector(s),t=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en,E=escapeHtml;
 let profileDraft=null,profileDirty=false,profileNotice='',pending=false,operation=null,composer=null,threadId=null;
 const drafts=new Map();
 const date=value=>new Intl.DateTimeFormat(window.EcoLocale?.locale||'en-US',{dateStyle:'medium',timeStyle:'short',timeZone:demo.ecosystem?.timezone||'UTC'}).format(new Date(value));
 const zoneSelect=(id,value)=>{const selected=EcoProfileModel.selectedZone(value);return `<select id="${id}" name="timezone" required><option value="" disabled ${selected?'':'selected'}>${t('Choose a time zone','Выберите часовой пояс')}</option>${EcoProfileModel.zoneGroups(window.EcoLocale?.language).map(g=>`<optgroup label="${E(g.label)}">${g.zones.map(z=>`<option value="${z.id}" ${z.id===selected?'selected':''}>${E(z.label)}</option>`).join('')}</optgroup>`).join('')}</select>`;};
 const topicName=topic=>({general:t('Question for my manager','Вопрос менеджеру'),plan:t('Plan question','Вопрос по плану'),station:t('Station question','Вопрос по станции'),documents:t('Documents & terms','Документы и условия'),account:t('Account question','Вопрос по счёту'),call:t('Callback request','Запрос звонка')})[topic]||t('Question for my manager','Вопрос менеджеру');
 function currentContext(topic='plan'){const p=demo.plan?.status==='active'?demo.plan:demo.planDraft;return {topic,...(p?{tierId:p.tierId,capital:p.capital,stationIds:p.stationIds}:{} )};}
 function profile(){
  const v=profileDraft||{name:demo.client.name,email:demo.client.email,phone:demo.acquisition?.phone||'',language:window.EcoLocale?.allowRussian===false?'en':demo.preferences?.language||window.EcoLocale?.language||'en',timezone:demo.ecosystem?.timezone||'UTC'};
  return `<header class="eg-profile-header">${window.EcoProfileAvatar.control()}<div><h1>${t('Your profile','Ваш профиль')}</h1><p>${t('Your details and preferences','Ваши данные и настройки')}</p></div></header><div class="care-profile-grid"><section class="eco-card"><form id="care-profile" novalidate>
   <h2>${t('Contact details','Контактные данные')}</h2><p>${t('Your assigned manager sees these details. Your sign-in username stays the same.','Эти данные видит ваш менеджер. Логин для входа остаётся прежним.')}</p>
   ${[['name',t('Full name','Имя и фамилия'),'text',100],['email',t('Contact email','Контактная почта'),'email',160],['phone',t('Phone · optional','Телефон · необязательно'),'tel',40]].map(([key,label,type,max])=>`<label for="care-${key}">${label}</label><input id="care-${key}" name="${key}" type="${type}" autocomplete="${key==='name'?'name':key==='phone'?'tel':'email'}" maxlength="${max}" value="${E(v[key])}" aria-describedby="care-${key}-error"><small id="care-${key}-error" class="care-field-error"></small>`).join('')}
   <div class="care-settings"><h2>${t('Preferences','Настройки')}</h2><label for="care-language">${t('Preferred interface language','Предпочитаемый язык интерфейса')}</label><select id="care-language" name="language"><option value="en" ${v.language==='en'?'selected':''}>English (US)</option>${window.EcoLocale?.allowRussian===false?'':`<option value="ru" ${v.language==='ru'?'selected':''}>Русский</option>`}</select><label for="care-timezone">${t('Time zone for account activity','Часовой пояс операций')}</label>${zoneSelect('care-timezone',v.timezone)}</div>
   <p id="care-profile-feedback" class="care-feedback" role="status">${E(profileNotice)}</p><button class="eco-button" type="submit" ${pending?'disabled':''}>${t('Save profile','Сохранить профиль')}</button></form></section>
   <aside class="eco-card care-profile-links"><span class="eco-kicker">${t('YOUR ACCOUNT','ВАШ АККАУНТ')}</span><h2 translate="no">${E(window.ECO_SHARED_CONTEXT.client.username)}</h2><p>${t('Contact details are separate from identity documents.','Контактные данные редактируются отдельно от документов.')}</p><button class="eco-button secondary" data-eco-route="identity">${t('Documents & personal details','Документы и личные данные')}</button><small>${t('Optional · review before sending','Необязательно · проверка перед отправкой')}</small><button class="eco-text" data-eco-route="documents">${t('Plan documents →','Документы плана →')}</button><button class="eco-text" data-eco-route="arcade">${t("Energy Run · Arcade →","Energy Run · Перерыв →")}</button><button class="eco-text" data-eco-route="invite">${t('EcoGrid Club →','EcoGrid Club →')}</button><button class="eco-text" data-action="eco-help-message">${t('Contact my manager →','Написать менеджеру →')}</button><button class="eco-button secondary" data-action="signout">${t('Sign out','Выйти')}</button></aside></div>${window.EcoInstallApp?.card()||''}`;
 }
 function compose(topic='general',context,subject=''){
  const c=context||currentContext(topic),key=JSON.stringify([topic,c,subject]);composer={topic,context:c,subject:subject||topicName(topic),key};threadId=null;
  const d=drafts.get(key)||{message:'',date:'',time:'',timezone:demo.ecosystem?.timezone||'UTC'};
  openModal(`<section class="care-dialog" translate="no"><span class="eco-kicker">${t('YOUR MANAGER','ВАШ МЕНЕДЖЕР')} · ${E(demo.manager.name)}</span><h2>${E(topicName(topic))}</h2>${subject?`<p>${E(subject)}</p>`:''}<form id="care-compose" novalidate>
   ${topic==='call'?`<div class="care-call-fields"><div><label for="care-call-date">${t('Preferred date','Желаемая дата')}</label><input id="care-call-date" type="date" name="date" value="${E(d.date)}"></div><div><label for="care-call-time">${t('Preferred time','Желаемое время')}</label><input id="care-call-time" type="time" name="time" value="${E(d.time)}"></div></div><label for="care-call-zone">${t('Time zone','Часовой пояс')}</label>${zoneSelect('care-call-zone',d.timezone)}<p>${t('Your manager will confirm the time. Sending a request does not book a call.','Менеджер подтвердит время. Отправка заявки не назначает звонок автоматически.')}</p>`:''}
   <label for="care-message">${t('Your message','Ваше сообщение')}</label><textarea id="care-message" name="message" rows="4" maxlength="1500" aria-describedby="care-message-error">${E(d.message)}</textarea><div id="care-message-error" class="care-feedback" role="alert"></div><button class="eco-button" type="submit" ${pending?'disabled':''}>${topic==='call'?t('Request a call','Запросить звонок'):t('Send to my manager','Отправить менеджеру')}</button></form><button class="eco-text" data-action="conversations">${t('My conversations →','Моя переписка →')}</button></section>`);
 }
 const awaitingReply=r=>r.messages?.length?r.messages.at(-1).from==='client'&&r.status!=='Resolved':r.status==='Open';
 function conversations(){composer=null;threadId=null;openModal(`<section class="care-dialog" translate="no"><h2>${t('My conversations','Моя переписка')}</h2><p>${t('Questions, replies and callback requests with','Вопросы, ответы и запросы звонка. Ваш менеджер:')} <strong>${E(demo.manager.name)}</strong>.</p><div class="conversation-list">${demo.tickets.length?demo.tickets.slice().reverse().map(r=>`<button class="conversation-summary" data-thread="${E(r.id)}"><span><strong>${E(r.subject)}</strong><small>${E((r.messages?.at(-1)?.text||r.reply||r.message).slice(0,130))}</small><time>${date(r.messages?.at(-1)?.date||r.repliedAt||r.date)}</time></span><span>${awaitingReply(r)?t('Awaiting reply','Ожидает ответа'):t('Answered','Есть ответ')}</span></button>`).join(''):`<p>${t('No conversations yet. Send your first question.','Переписки пока нет. Задайте первый вопрос.')}</p>`}</div><button class="eco-button" data-action="eco-help-message">${t('Write a message','Написать сообщение')}</button></section>`);}
 function thread(id,markRead=true){const r=demo.tickets.find(v=>v.id===id);if(!r)return;composer=null;threadId=id;const key='thread:'+id,message=drafts.get(key)?.message||'',rows=r.messages?.length?r.messages:[{from:'client',text:r.message,date:r.date},...(r.reply?[{from:'manager',text:r.reply,date:r.repliedAt||r.date}]:[])];
  openModal(`<section class="care-dialog" translate="no"><h2>${E(r.subject)}</h2><div class="thread-messages">${rows.map(m=>`<article class="thread-bubble ${m.from==='manager'?'from-manager':''}"><strong>${m.from==='manager'?E(m.authorName||t('Team','Команда')):t('You','Вы')}</strong><p>${E(m.text)}</p><time>${date(m.date)}</time></article>`).join('')}</div><p>${awaitingReply(r)?t('Your message is awaiting a manager reply.','Сообщение ожидает ответа менеджера.'):t('Your manager replied. You can continue below.','Менеджер ответил. Можно продолжить переписку ниже.')}</p><form id="care-followup" data-ticket="${E(id)}" novalidate><label for="care-message">${t('Continue the conversation','Продолжить переписку')}</label><textarea id="care-message" name="message" rows="3" maxlength="1500">${E(message)}</textarea><div id="care-message-error" class="care-feedback" role="alert"></div><button class="eco-button" type="submit" ${pending?'disabled':''}>${t('Send message','Отправить сообщение')}</button></form><button class="eco-text" data-action="care-refresh-thread">${t('Check for replies','Проверить ответы')}</button><button class="eco-text" data-action="conversations">${t('All conversations','Вся переписка')}</button></section>`);
  if(markRead&&r.reply&&r.readReply!==r.reply&&!pending)window.EcoClientAccount.command('support',{id:'READ-'+crypto.randomUUID(),kind:'read',ticketId:id,readReply:r.reply}).then(result=>{if(result?.error&&$('#care-message-error'))$('#care-message-error').textContent=t('Could not mark this reply as read.','Не удалось отметить ответ прочитанным.');});
 }
 const copyErrors=()=>({name:t('Enter a name of 2–100 characters.','Введите имя длиной 2–100 символов.'),email:t('Enter a valid email address.','Введите корректную почту.'),phone:t('Enter a phone number with 7–15 digits or leave it blank.','Введите телефон из 7–15 цифр или оставьте поле пустым.'),language:t('Choose English or Russian.','Выберите английский или русский.'),timezone:t('Choose a US or Canadian time zone.','Выберите часовой пояс США или Канады.')});
 function remember(form){const data=Object.fromEntries(new FormData(form));if(form.id==='care-profile'){profileDraft=data;profileDirty=true;profileNotice='';}else if(form.id==='care-compose'&&composer)drafts.set(composer.key,data);else if(form.id==='care-followup')drafts.set('thread:'+form.dataset.ticket,data);return data;}
 async function submit(form){if(pending)return;const data=remember(form),isProfile=form.id==='care-profile',feedback=form.querySelector('.care-feedback'),button=form.querySelector('button[type=submit]');let payload,endpoint;
  if(isProfile){const checked=EcoProfileModel.profile(data);for(const field of ['name','email','phone']){const error=form.querySelector('#care-'+field+'-error');error.textContent=checked.errors[field]?copyErrors()[field]:'';form.elements[field].setAttribute('aria-invalid',String(!!checked.errors[field]));}for(const field of ['language','timezone'])form.elements[field].setAttribute('aria-invalid',String(!!checked.errors[field]));if(Object.keys(checked.errors).length){feedback.textContent=Object.values(checked.errors).map(k=>copyErrors()[k]).join(' ');form.querySelector('[aria-invalid=true]')?.focus();return;}endpoint='profile';payload={profile:checked.value};}
  else{if(data.message.trim().length<3){feedback.textContent=t('Enter at least 3 characters.','Введите минимум 3 символа.');return;}endpoint='support';payload={message:data.message.trim()};if(form.id==='care-followup')payload.ticketId=form.dataset.ticket;else{payload.context=composer.context;payload.subject=composer.subject; if(composer.subject.length>100)payload.message=composer.subject+'\n\n'+payload.message;if(composer.topic==='call'){const a={date:data.date,time:data.time,timeZone:data.timezone};if(!EcoProfileModel.appointment(a,window.EcoClientAccount.now())){feedback.textContent=t('Choose a future time in this time zone. Repeated or skipped daylight-saving times are unavailable.','Выберите будущее время в этом часовом поясе. Пропущенное или повторяющееся время перехода часов недоступно.');return;}payload.appointment=a;}}}
  const key=JSON.stringify([endpoint,payload]);if(operation?.key!==key)operation={key,id:'CARE-'+crypto.randomUUID()};const sentId=operation.id,draftKey=isProfile?null:form.id==='care-followup'?'thread:'+form.dataset.ticket:composer.key,replyTo=payload.ticketId;
  pending=true;button.disabled=true;feedback.textContent=t('Saving…','Сохраняем…');
  try{const result=await window.EcoClientAccount.command(endpoint,{...payload,id:sentId});if(!result||result.error){if(form.isConnected)feedback.textContent=result?.status===409?t('Your account changed. Your input is kept. Review the latest details and save again.','Данные аккаунта изменились. Ввод сохранён. Проверьте актуальные данные и повторите сохранение.'):t('Not saved. Your input is kept. Check the connection and try again.','Не сохранено. Ввод сохранён. Проверьте соединение и повторите.');return;}
   operation=null;if(isProfile){profileDraft=null;profileDirty=false;profileNotice=t('Profile saved. Your manager sees the updated contacts.','Профиль сохранён. Менеджер видит обновлённые контакты.');window.EcoLocale?.set(data.language);if(tab==='profile')renderClientTab();}
   else{drafts.delete(draftKey);if(form.isConnected&&$('#modal')?.open)thread(replyTo||sentId,false);toast(t('Message sent.','Сообщение отправлено.'));}
  }finally{pending=false;if(button.isConnected)button.disabled=false;for(const current of document.querySelectorAll('#care-profile button[type=submit],#care-compose button[type=submit],#care-followup button[type=submit]'))current.disabled=false;}
 }
 const threadOpen=()=>!!(threadId&&$('#modal')?.open&&$('#care-followup')?.dataset.ticket===threadId);
 window.EcoClientCare={profile,compose,isReadOnly:()=>!!(threadOpen()&&!pending&&!$('#care-message')?.value.trim()),refresh(){if(threadOpen()&&!pending&&!$('#care-message')?.value.trim())thread(threadId,false);},isEditing:()=>pending||(tab==='profile'&&profileDirty)||!!($('#modal')?.open&&$('#care-message')?.value.trim())};
 contactComposer=compose;showConversations=conversations;showThread=thread;actions.conversations=conversations;actions.chat=conversations;actions.message=()=>compose();actions.call=()=>compose('call');actions['eco-help-message']=()=>{const topic=demo.plan||demo.planDraft?'plan':'general';compose(topic,currentContext(topic));};
 actions['care-refresh-thread']=async()=>{const id=threadId;if(!id)return;await window.EcoClientAccount.refresh();if(threadId===id&&threadOpen())thread(id);};
 document.addEventListener('input',e=>{const form=e.target.closest('#care-profile,#care-compose,#care-followup');if(form)remember(form);});document.addEventListener('change',e=>{const form=e.target.closest('#care-profile,#care-compose');if(form)remember(form);});
 document.addEventListener('submit',e=>{if(!['care-profile','care-compose','care-followup'].includes(e.target.id))return;e.preventDefault();submit(e.target);});
})();
