'use strict';
(()=>{const ctx=window.ECO_SHARED_CONTEXT;if(!ctx)return;let version=ctx.version,busy=false,queue=[],failed=false,remotePending=null;const lang=()=>window.EcoLocale?.language==='ru',text=(en,ru)=>lang()?ru:en;
 const bar=document.createElement('div');bar.className='central-state';bar.setAttribute('role','status');document.body.prepend(bar);const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('central/central.css',document.baseURI).href;document.head.append(css);
 function connectedCopy(){const note=document.querySelector('.cab-local-note');if(note){note.setAttribute('translate','no');note.textContent=text('Account data is saved on the shared server. No real payments.','Данные кабинета хранятся на общем сервере. Реальных платежей нет.');}}
 const previousRender=renderClientTab;renderClientTab=function(){previousRender();connectedCopy();};document.addEventListener('ecocharge:locale',connectedCopy);document.addEventListener('DOMContentLoaded',connectedCopy);
 const status=(error=false)=>{bar.dataset.error=String(error);if(remotePending){bar.innerHTML=text('Your account changed. Load the latest saved selection before saving.','Данные изменились. Загрузите актуальную подборку перед сохранением.')+'<button type="button" data-load-account>'+text('Load latest','Загрузить актуальное')+'</button>';return;}bar.textContent=error?text('Your change was not saved. Review the restored account data and try again.','Изменение не сохранено. Проверьте восстановленные данные кабинета и повторите действие.'):busy?text('Saving to your account…','Сохраняем в ваш аккаунт…'):text('Connected account · Your manager: ','Общий кабинет · Ваш менеджер: ')+demo.manager.name;};
 async function read(){const r=await fetch(new URL('api/client/account',document.baseURI),{cache:'no-store'});if(r.status===401){location.assign(new URL(EcoNavigation.login('client',new URL(location).searchParams,window.EcoLocale?.language),document.baseURI));throw Error('Session ended');}if(!r.ok)throw Error('Connection failed');const v=await r.json();if(v.client.id!==ctx.client.id){location.reload();throw Error('Account changed');}updateAccrual(v);return v;}
 function updateAccrual(v){const stamp=Date.parse(v.liveAccrual?.serverNow);if(Number.isFinite(stamp))serverOffset=stamp-Date.now();ctx.nextWeek=v.nextWeek;ctx.liveAccrual=v.liveAccrual;window.ecoLiveAccrualController?.update(v.liveAccrual);window.EcoWithdrawalUI?.refresh();}
 function apply(v,preserveBuilder=false){remotePending=null;const key=p=>p&&JSON.stringify([p.tierId,p.capital,p.stationIds]),p=v.state.planDraft||v.state.plan;
  if(!preserveBuilder&&p&&key(p)!==key(demo.planDraft||demo.plan)){chosenTier=p.tierId;investmentDraft=p.capital;chosenStations=p.stationIds.slice();}
  version=v.version;ctx.client=v.client;updateAccrual(v);demo=v.state;localStorage.setItem('ecocharge-demo-v1',JSON.stringify(demo));ensureClient();ensureManager();ensureTariffs();renderNumbers();if(stations.length&&!preserveBuilder&&!(window.EcoClientCare?.isEditing()||window.EcoEquipmentUI?.isEditing()))renderClientTab();refreshManager();window.EcoOperationDialog?.refresh();window.EcoWithdrawalUI?.refresh();window.EcoClientCare?.refresh();status(failed);}
 function acceptRemote(v){if(v.version<=version)return;const operationOpen=window.EcoOperationDialog?.isOpen(),withdrawalOpen=window.EcoWithdrawalUI?.isOpen(),careReadOnly=window.EcoClientCare?.isReadOnly();if(!operationOpen&&!withdrawalOpen&&!careReadOnly&&((window.EcoClientCare?.isEditing()||window.EcoEquipmentUI?.isEditing())||(tab==='tariffs'&&!(window.EcoPlanUI&&!window.EcoPlanUI.isComparing()&&demo.plan?.status==='active'))||document.querySelector('#modal')?.open)){remotePending=v;status();return;}apply(v,(operationOpen||withdrawalOpen)&&tab==='tariffs');}
 bar.addEventListener('click',e=>{if(e.target.closest('[data-load-account]')&&remotePending){document.querySelector('#modal')?.close();apply(remotePending);}});
 async function drain(){if(busy||!queue.length)return;busy=true;status();const item=queue.shift(),state=item.state;try{const r=await fetch(new URL('api/client/'+(item.command?.endpoint||'account'),document.baseURI),{method:item.command?'POST':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(item.command?{...item.command.input,clientId:ctx.client.id,version}:{clientId:ctx.client.id,version,state})});const data=await r.json();if(!r.ok){const error=Error(data.error||'Unable to save.');error.status=r.status;throw error;}version=data.version;failed=false;if(!queue.length)apply(data);item.resolve(data);}catch(error){for(const pending of queue)pending.resolve(null);queue=[];failed=true;let recovered;try{recovered=await read();apply(recovered,!!item.command);}catch{}if(item.command){item.resolve({error:error.message,status:error.status||0});}else if(item.requestId&&recovered?.state.requests?.some(r=>r.id===item.requestId&&r.type==='withdraw')){failed=false;item.resolve(recovered);}else{const message=window.EcoLocale?.t(error.message)||error.message;openModal(`<h2>${text('Change not saved','Изменение не сохранено')}</h2><p>${escapeHtml(message)}</p><button class="button primary" data-action="back-overview">${text('Review account','Проверить данные счёта')}</button>`);item.resolve(null);}}finally{busy=false;status(failed);if(queue.length)drain();}}
 function saveState(state,requestId){return new Promise(resolve=>{queue.push({state:structuredClone(state),resolve,requestId});drain();});}
 let serverOffset=Number.isFinite(Date.parse(ctx.liveAccrual?.serverNow))?Date.parse(ctx.liveAccrual.serverNow)-Date.now():0;
 persist=function(){localStorage.setItem('ecocharge-demo-v1',JSON.stringify(demo));renderNumbers();return saveState(demo);};
 actions.signout=async()=>{window.EcoSupportChat?.stop();window.EcoArcade?.unmount();window.EcoWithdrawalUI?.stop();window.EcoEnergyUI?.unmount();window.ecoLiveAccrualController?.destroy();await fetch(new URL('api/logout',document.baseURI),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'client'})});localStorage.removeItem('ecocharge-demo-v1');sessionStorage.removeItem('ecocharge-entry:client');sessionStorage.removeItem('ecocharge-working-plan');sessionStorage.removeItem('ecocharge-explore');location.assign(new URL(EcoNavigation.login('client','',window.EcoLocale?.language),document.baseURI));};
 actions.profile=()=>openModal(`<h2>${text('Client account','Клиентский аккаунт')}</h2><p translate="no">${escapeHtml(ctx.client.username)} · ${escapeHtml(demo.client.name)}</p><p>${text('Your manager','Ваш менеджер')}: <strong translate="no">${escapeHtml(demo.manager.name)}</strong></p><button class="button secondary" data-action="signout">${text('Sign out','Выйти')}</button>`);
 async function refreshAccount(){if(busy||queue.length||reading)return;reading=true;try{const v=await read();if(!busy&&!queue.length)acceptRemote(v);window.EcoOperationDialog?.connection(true);status(failed);}catch{window.EcoOperationDialog?.connection(false);status(true);}finally{reading=false;}}
 let reading=false;window.EcoClientAccount={command(endpoint,input){if(!['profile','support','equipment','journey'].includes(endpoint))throw Error('Unknown account action');return new Promise(resolve=>{queue.push({command:{endpoint,input:structuredClone(input)},resolve});drain();});},refresh:refreshAccount,now:()=>Date.now()+serverOffset,requestWithdrawal({id,amount}){const state=structuredClone(demo);state.requests??=[];if(!state.requests.some(r=>r.id===id))state.requests.push({id,type:'withdraw',amount,status:'Pending'});return saveState(state,id);},activate(plan){const state=structuredClone(demo);state.plan={...plan,status:'active'};delete state.planDraft;return saveState(state);}};
 window.EcoClientAccrual={refresh:refreshAccount,async closePeriod(periodStartedAt){if(busy||queue.length)return;busy=true;try{const r=await fetch(new URL('api/client/accrual/close',document.baseURI),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:ctx.client.id,periodStartedAt})});const v=await r.json();if(!r.ok)throw Error(v.error);apply(v);}finally{busy=false;if(queue.length)drain();}}};
 setInterval(()=>{if(!document.hidden)refreshAccount();},2500);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshAccount();});document.addEventListener('ecocharge:locale',()=>status(failed));status();
})();
