'use strict';
window.EcoClubAdmin=(()=>{
 const {t,esc:E,money,api}=EcoCentral,M=c=>money(c/100),D=d=>new Date(d).toLocaleString(window.EcoLocale?.locale||'en-US');
 let host=null,data=null,busy=false;
 const status=s=>({pending:t('Awaiting program / budget','Ожидает запуска / бюджета'),credited:t('Credited · model','Зачислено · модель'),held:t('Contact match · held','Совпадение контактов · удержан'),ineligible:t('Below FTD minimum','FTD ниже минимума'),rejected:t('Declined','Отклонён'),reversed:t('Reversed','Отменён')})[s]||s;
 const input=(label,name,value,type='number',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${E(value)}" ${extra}></label>`;
 const check=(label,name,value)=>`<label class="club-check"><input type="checkbox" name="${name}" ${value?'checked':''}>${label}</label>`;
 const btn=(text,attr='')=>`<button class="crm-button outline" type="button" ${attr}>${text}</button>`;
 function markup(d){const c=d.config,season=c.campaign||{},goal=c.goal||{};return `<div class="club club-admin" translate="no"><div class="club-heading"><div><span class="club-eyebrow">ADMIN · ACQUISITION</span><h1>EcoGrid Club</h1></div>${btn(t('Refresh','Обновить'),'data-club-admin-refresh')}</div><p class="club-note">${t('Direct invitations only. Funding approval can issue one model Club reward when the program and budgets allow it. No live payments are enabled here.','Только личные приглашения. Подтверждение первого пополнения может зачислить один модельный бонус, если программа включена и есть бюджет. Реальные платежи здесь не включаются.')}</p><div class="club-metrics">${[[M(c.referrerCents),t('Inviter · once','Пригласившему · разово')],[M(c.minimumCents),t('Minimum first funding','Минимальное первое пополнение')],[M(d.spentCents),t('Spent this month','Использовано за месяц')],[M(Math.max(0,c.monthlyBudgetCents-d.spentCents)),t('Budget remaining','Остаток бюджета')]].map(([v,k])=>`<div><strong>${v}</strong><span>${k}</span></div>`).join('')}</div>
 <details class="club-panel" open><summary>${t('Rules and budget','Правила и бюджет')}</summary><form data-club-config>${check(t('Enable model Club rewards','Включить модельный бонусы Club'),'enabled',c.enabled)}<div class="club-columns">${input(t('Monthly acquisition budget · USD','Месячный бюджет привлечения · USD'),'budget',c.monthlyBudgetCents/100,'number','required min="0" max="10000000" step="0.01"')}${input(t('Welcome bonus · USD (0 = off)','Бонус другу · USD (0 = выключен)'),'welcome',c.welcomeCents/100,'number','required min="0" max="1000" step="0.01"')}</div><p class="club-note">${t('Both bonuses share this budget. Reversals do not free spent budget. New amounts apply to future FTDs; queued rewards keep their original terms. Enabling does not credit the queue automatically.','Оба бонуса входят в этот бюджет. Отмена не освобождает использованный бюджет. Новые суммы применяются к будущим FTD; очередь сохраняет прежние условия. Включение не зачисляет очередь автоматически.')}</p>
 <details><summary>${t('Seasonal campaign','Сезонная акция')}</summary><fieldset>${check(t('Publish a seasonal campaign','Опубликовать сезонную акцию'),'campaign',!!c.campaign)}${input(t('Campaign ID · use a new ID for new terms','ID акции · новый ID для новых условий'),'campaignId',season.id||'','text','maxlength="60"')}${input(t('Campaign title','Название акции'),'campaignTitle',season.title||'','text','maxlength="100"')}<div class="club-columns"><label>${t('Inviter multiplier','Множитель пригласившему')}<select name="multiplier"><option value="1" ${season.multiplier!==2?'selected':''}>1×</option><option value="2" ${season.multiplier===2?'selected':''}>2×</option></select></label>${input(t('Campaign budget · USD','Бюджет акции · USD'),'campaignBudget',(season.budgetCents||0)/100,'number','min="0" step="0.01"')}</div><div class="club-columns">${input(t('Starts · UTC','Начало · UTC'),'campaignStart',season.start?.slice(0,16)||'','datetime-local')}${input(t('Ends · UTC','Конец · UTC'),'campaignEnd',season.end?.slice(0,16)||'','datetime-local')}</div><small>${t('The monthly cap still applies. Existing campaign terms are immutable; create a new ID for a new offer.','Месячный лимит также действует. Условия существующей акции неизменяемы; для нового предложения нужен новый ID.')}</small></fieldset></details>
 <details><summary>${t('Shared team access','Общий доступ команды')}</summary><fieldset>${check(t('Publish a non-cash team goal','Опубликовать неденежную цель команды'),'goal',!!c.goal)}${input(t('Access description','Какой доступ открывается'),'goalTitle',goal.title||'','text','maxlength="120"')}${input(t('Active clients · personal + next circle','Активные клиенты · личные + следующий круг'),'goalTarget',goal.target||10,'number','min="1" max="1000" step="1"')}<small>${t('Publish the promised material below with Team goal required. No automatic cash prize or station allocation.','Опубликуйте обещанный материал ниже с условием «Цель команды». Денежного приза или автоматического распределения станций нет.')}</small></fieldset></details><button class="crm-button primary" type="submit">${t('Save Club rules','Сохранить правила Club')}</button></form></details>
 <section class="club-panel"><h2>${t('Reward review','Проверка бонусов')}</h2><p class="club-note">${t('Latest 200 records. First funding is counted once; later deposits never retry a failed minimum. Credit requires a verified receipt. Reversal requires both recipients to have the full available amount.','Последние 200 записей. Первое пополнение учитывается один раз; последующие платежи не исправляют минимум FTD. Для зачисления нужна проверка поступления. Отмена возможна, когда у обоих получателей доступна вся сумма.')}</p><div class="club-rewards">${d.rewards.map(r=>`<div><div>${E(r.parentName)} ← ${E(r.childName)}<strong>${M(r.referrerCents)} + ${M(r.welcomeCents)}</strong><small>${D(r.confirmed)}</small></div><div>${status(r.status)}<small style="display:block">${E(r.campaignId||'Standard')} · ${E(EcoClubModel.message(r.reason||'',window.EcoLocale?.language))}</small></div><form data-club-review="${E(r.child)}">${['pending','held','credited'].includes(r.status)?`<label class="club-sr" for="reason-${E(r.child)}">${t('Review reason','Причина решения')}</label><input id="reason-${E(r.child)}" name="reason" required minlength="3" maxlength="300" placeholder="${t('Review reason','Причина решения')}"><div class="club-actions">${r.status==='pending'?`<button class="crm-button primary" name="action" value="credit" ${!c.enabled?'disabled':''}>${t('Credit','Зачислить')}</button>`:''}${['pending','held'].includes(r.status)?`<button class="crm-button outline" name="action" value="reject">${t('Decline','Отклонить')}</button>`:''}${r.status==='credited'?`<button class="crm-button outline" name="action" value="reverse">${t('Reverse bonus','Отменить бонус')}</button>`:''}</div>`:''}</form></div>`).join('')||`<p class="club-empty">${t('No Club reward records yet.','Записей о бонусах пока нет.')}</p>`}</div></section>
 <div class="club-columns"><section class="club-panel"><h2>${t('Publish to Club','Публикация в Club')}</h2><form data-club-post><label>${t('Type','Тип')}<select name="kind"><option value="event">${t('Event','Событие')}</option><option value="report">${t('Report','Отчёт')}</option><option value="story">${t('Member story','История участника')}</option></select></label>${input(t('Title','Заголовок'),'title','','text','required minlength="3" maxlength="120"')}<label>${t('Text','Текст')}<textarea name="text" rows="5" required minlength="3" maxlength="4000"></textarea></label><label>${t('Minimum club status','Минимальный статус')}<select name="minLevel">${EcoClubModel.levels.map((l,i)=>`<option value="${i}">${t(l.en,l.ru)}</option>`).join('')}</select></label>${check(t('Require the shared team goal','Требовать выполнения цели команды'),'teamGoal',false)}<small>${t('Publish confirmed facts and authorized member stories. Content is shown in the language you write it.','Публикуйте подтверждённые факты и согласованные истории участников. Текст показывается на языке автора.')}</small><button class="crm-button primary" type="submit">${t('Publish','Опубликовать')}</button></form></section><section class="club-panel"><h2>${t('Publication history','История публикаций')}</h2><div class="club-posts">${d.posts.map(p=>`<article><small>${E(p.author)} · ${D(p.date)} · ${t(EcoClubModel.levels[p.minLevel].en,EcoClubModel.levels[p.minLevel].ru)}</small><h4>${E(p.title)}</h4><p>${E(p.text)}</p>${p.archived?`<small>${t('Archived','В архиве')}</small>`:btn(t('Archive','В архив'),`data-club-archive="${E(p.id)}"`)}</article>`).join('')||`<p>${t('Nothing published yet.','Публикаций пока нет.')}</p>`}</div></section></div><p id="club-admin-notice" role="status"></p><p id="club-admin-error" role="alert"></p></div>`;}
 async function load(){const h=host;const d=await api('staff/club');if(host!==h||!h?.isConnected)return;data=d;h.innerHTML=markup(d);}
 async function mount(h){if(host===h&&h.querySelector('.club-admin'))return;host=h;try{await load();}catch(e){h.textContent=e.message;}}
 async function action(work){if(busy)return;busy=true;host.querySelectorAll('button').forEach(b=>b.disabled=true);const error=host.querySelector('#club-admin-error');if(error)error.textContent='';try{await work();await load();host.querySelector('#club-admin-notice').textContent=t('Saved.','Сохранено.');}catch(e){host.querySelectorAll('button').forEach(b=>b.disabled=false);if(error){error.textContent=t('Not saved: ','Не сохранено: ')+EcoClubModel.message(e.message,window.EcoLocale?.language);error.scrollIntoView({block:'nearest'});}}finally{busy=false;}}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-club-admin-refresh],[data-club-archive]');if(!b)return;if(b.hasAttribute('data-club-admin-refresh'))action(async()=>{});else action(()=>api('staff/club/post','POST',{id:b.dataset.clubArchive,archive:true}));});
 document.addEventListener('submit',e=>{const f=e.target;if(!f.matches('[data-club-config],[data-club-post],[data-club-review]'))return;e.preventDefault();const v=Object.fromEntries(new FormData(f));
  if(f.matches('[data-club-config]'))action(()=>api('staff/club/config','POST',{version:data.config.version,enabled:!!v.enabled,monthlyBudgetCents:Math.round(Number(v.budget)*100),welcomeCents:Math.round(Number(v.welcome)*100),campaign:v.campaign?{id:v.campaignId,title:v.campaignTitle,multiplier:Number(v.multiplier),budgetCents:Math.round(Number(v.campaignBudget)*100),start:v.campaignStart?new Date(v.campaignStart+'Z').toISOString():'',end:v.campaignEnd?new Date(v.campaignEnd+'Z').toISOString():''}:null,goal:v.goal?{title:v.goalTitle,target:Number(v.goalTarget)}:null}));
  else if(f.matches('[data-club-post]')){f.dataset.operation??='CLUB-POST-'+crypto.randomUUID();action(()=>api('staff/club/post','POST',{id:f.dataset.operation,kind:v.kind,title:v.title,text:v.text,minLevel:Number(v.minLevel),teamGoal:!!v.teamGoal}));}
  else{const decision=e.submitter?.value;if(decision)action(()=>api('staff/club/review','POST',{child:f.dataset.clubReview,action:decision,reason:v.reason}));}
 });
 return {mount,markup};
})();
