'use strict';
(()=>{
 const {t,esc,money,api}=EcoCentral,$=s=>document.querySelector(s);
 let data,account,lead,selected=null,leadId=null,tab=EcoNavigation.context('staff',new URL(location).searchParams).get('tab')||'today',operation=null,editingLead=null,profileVersion=null,pending=false,dialogContext=null;
 let deliveryState=null,replyOwner='',callRecord=null,menuOpen=false;
 const narrowNavigation=window.matchMedia('(max-width:1000px)');
 $('.crm-skip').addEventListener('click',e=>{e.preventDefault();$('#central-workspace-content').focus({preventScroll:true});$('#central-workspace-content').scrollIntoView({block:'start'});});
 function syncMenu(){const compact=narrowNavigation.matches,toggle=$('#central-nav-toggle');$('.crm-sidebar').classList.toggle('is-open',menuOpen);toggle.setAttribute('aria-expanded',String(!compact||menuOpen));}
 narrowNavigation.addEventListener('change',()=>{menuOpen=false;syncMenu();});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menuOpen){menuOpen=false;syncMenu();$('#central-nav-toggle').focus();}});
 let search='',statusFilter='',ownerFilter='',queueScope='',checked=new Set(),refreshing=false;
 const isAdmin=()=>data?.me.role==='admin';
 function sourceDetails(record){if(!isAdmin())return '';return '<details class="crm-detail-fold" data-source-details><summary>'+t('Source data','Данные источника')+'</summary>'+EcoJourneyUI.sources(record)+EcoFunnelUI.attribution(record.attribution||{})+'</details>';}
 const notice=s=>{$('#central-notice').textContent=s;};
 const fundingInbox=createFundingInbox({onChange:({newCount,count})=>{if(!data)return;$('#central-funding-alert').innerHTML=fundingInbox.banner();const badge=$('[data-funding-count]');if(badge)badge.textContent=count||'';if(tab==='funding'&&!$('#central-dialog').open)$('#central-main').innerHTML=fundingInbox.page();if(newCount)notice(t('New funding reports: ','Новых сообщений об отправке: ')+newCount);},onError:()=>{const root=$('#central-funding-alert');if(root)root.innerHTML='<p class="central-readonly" role="status">'+t('Funding notifications could not refresh. Retrying automatically.','Не удалось обновить пополнения. Повторим автоматически.')+'</p>';}});
 const withdrawalInbox=createFundingInbox({kind:'withdraw',onChange:({newCount,count})=>{if(!data)return;$('#central-withdrawal-alert').innerHTML=withdrawalInbox.banner();withdrawalInbox.paintRows($('#central-main'));const badge=$('[data-withdrawal-count]');if(badge)badge.textContent=count||'';if(tab==='withdrawals'&&!$('#central-dialog').open)$('#central-main').innerHTML=withdrawalInbox.page();if(newCount)notice(t('New withdrawal requests: ','Новых заявок на вывод: ')+newCount);},onError:()=>{const root=$('#central-withdrawal-alert');if(root)root.innerHTML='<p class="central-readonly" role="status">'+t('Withdrawal notifications could not refresh. Retrying automatically.','Не удалось обновить выводы. Повторим автоматически.')+'</p>';}});
 const labels={new:['New','Новая'],in_progress:['In progress','В работе'],no_answer:['No answer','Недозвон'],callback:['Callback','Перезвонить'],qualified:['Qualified','Квалифицирован'],not_qualified:['Not qualified','Не подходит'],do_not_contact:['Do not contact','Не связываться']};
 const status=s=>labels[s]?t(...labels[s]):s;
 const leadCount=n=>t(n+' '+(n===1?'lead':'leads'),n+' '+(n%100>=11&&n%100<=14?'заявок':n%10===1?'заявка':n%10>=2&&n%10<=4?'заявки':'заявок'));
 const date=s=>s?new Date(s).toLocaleString(window.EcoLocale?.locale||'en-US',{dateStyle:'short',timeStyle:'short'}):'—';
 const manager=id=>data.managers.find(m=>m.id===id)?.name||t('Unassigned','Не назначен');
 const pill=r=>`<span class="wf-status" data-status="${esc(r.status)}">${status(r.status)}</span>`;
 const button=(text,attr,primary=false)=>`<button class="crm-button ${primary?'primary':'outline'}" ${attr}>${text}</button>`;
 const dialog=(title,body)=>{$('#central-dialog-body').innerHTML=`<h2 id="central-dialog-title">${title}</h2>${body}<div class="crm-error" id="central-error" role="alert"></div>`;if(!$('#central-dialog').open)$('#central-dialog').showModal();};
 const close=()=>{$('#central-dialog').close();operation=null;dialogContext=null;};
 const {financePanel,financeHistory,editFinancialPlan,setPlanStationCount,paintFinanceStations,reviewFinancialPlan,reviewFinanceReason,reviewWeek,reviewRequest,saveFinance}=createFinanceUI({getAccount:()=>account,getClient:()=>selected,dialog,close,refresh,notice,button});
 const energyBriefUI=createEnergyBriefUI({getAccount:()=>account,getClient:()=>selected,dialog,close,refresh,notice});
 const options=(value='new')=>Object.keys(labels).map(s=>`<option value="${s}" ${s===value?'selected':''}>${status(s)}</option>`).join('');
 function contactFields(record={status:'new'}){return `<label>${t('Lead qualification','Квалификация лида')}<select name="status" required>${options(record.status)}</select></label>${EcoFunnelUI.contactFields(record)}<label>${t('Comment','Комментарий')}<textarea name="comment" required maxlength="2000" rows="3" placeholder="${t('Contact outcome and next step','Результат контакта и следующий шаг')}"></textarea></label><label>${t('Next contact · your local time','Следующий контакт · ваше местное время')}<input name="nextContact" type="datetime-local" ${record.status==='callback'?'required':''} value="${record.nextContact?localDate(record.nextContact):''}"></label>`;}
 function localDate(value){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
 function leadProfile(){dialogContext={leadId:lead.id,version:lead.crm.version};dialog(t('Edit lead','Данные заявки'),`<form id="central-lead-profile" class="central-form"><div class="wf-form-pair"><label>${t('First name','Имя')}<input name="firstName" required maxlength="50" value="${esc(lead.first_name)}"></label><label>${t('Last name','Фамилия')}<input name="lastName" required maxlength="70" value="${esc(lead.last_name)}"></label></div><label>${t('Phone','Телефон')}<input name="phone" type="tel" maxlength="40" value="${esc(lead.phone)}"></label><label>${t('Email','Почта')}<input name="email" type="email" maxlength="160" value="${esc(lead.email)}"></label>${contactFields(lead.crm)}<button type="submit" class="crm-button primary">${t('Save lead','Сохранить заявку')}</button></form>`);}
 function matchReview(){dialogContext={leadId:lead.id,version:lead.crm.version};dialog(t('Review contact match','Проверка совпадения контактов'),`<form id="central-match" class="central-form"><label>${t('Review result','Результат проверки')}<select name="originalId" required><option value="">${t('Choose a result','Выберите результат')}</option><option value="separate">${t('This is a separate person','Это другой человек')}</option>${lead.conflicts.map(id=>`<option value="${id}">${t('Duplicate of','Дубль заявки')}: ${esc(data.leads.find(l=>l.id===id)?.name||id)}</option>`).join('')}</select></label><label>${t('Comment','Комментарий')}<textarea name="comment" required maxlength="2000"></textarea></label><button type="submit" class="crm-button primary">${t('Save review','Сохранить проверку')}</button></form>`);}
 function contactPayload(values){return {...values,nextContact:values.nextContact?new Date(values.nextContact).toISOString():null};}
 async function refresh(){if(refreshing)return;refreshing=true;try{
  const initial=!data;data=await api('staff/overview');
  if(initial)EcoSupportChat.initStaff({onChange:renderReplyQueue});
  if(initial&&!new URL(location).searchParams.has('tab'))tab='today';
  if(initial){const requestedLead=new URL(location).searchParams.get('lead');if(requestedLead&&data.leads.some(l=>l.id===requestedLead)){leadId=requestedLead;tab='leads';}}
  if(selected&&!data.clients.some(c=>c.id===selected)){selected=null;account=null;}
  if(leadId&&!data.leads.some(l=>l.id===leadId)){leadId=null;lead=null;}
  if(callRecord&&!(callRecord.kind==='lead'?data.leads:data.clients).some(r=>r.id===callRecord.key)){callRecord=null;EcoCallDesk.unmount();}
  if(selected)account=await api('staff/clients/'+selected);
  if(leadId)lead=await api('staff/leads/'+leadId);
  checked=new Set([...checked].filter(id=>data.leads.some(l=>l.id===id)));refreshView();fundingInbox.refresh();withdrawalInbox.refresh();
 }finally{refreshing=false;}}
 function refreshView(){
  // A polling update must not collapse the information someone is reading.
  const root=$('#central-main'),key=d=>d.id||d.querySelector('summary')?.textContent.trim();
  const campaignForm=root.querySelector('[data-journey-link]');
  const details=[...root.querySelectorAll('details')].map(d=>({key:key(d),open:d.open,focused:document.activeElement===d.querySelector('summary')}));
  render();
  if(campaignForm)root.querySelector('[data-journey-link]')?.replaceWith(campaignForm);
  for(const d of root.querySelectorAll('details')){const previous=details.find(row=>row.key===key(d));if(previous){d.open=previous.open;if(previous.focused)d.querySelector('summary')?.focus({preventScroll:true});}}
 }
 function render(){if(!data)return;
  if(['links','club'].includes(tab)&&!isAdmin())tab='today';
  const route=new URL(location);route.searchParams.set('tab',tab);window.history.replaceState(history.state,'',route);
  $('#central-user').innerHTML='<strong translate="no">'+esc(data.me.name)+'</strong><span>'+(isAdmin()?t('Administrator','Администратор'):t('Manager','Менеджер'))+'</span>';window.EcoCRMDesign?.sync();
  const nav=[['today',t('Today','На сегодня')],['leads',isAdmin()?t('All leads','Все заявки'):t('My leads','Мои заявки')],['clients',isAdmin()?t('All clients','Все клиенты'):t('My clients','Мои клиенты')]];
  nav.push(['funding',t('Funding','Пополнения')],['withdrawals',t('Withdrawals','Выводы')]);nav.push(['funnel',t('Funnel report','Воронка')],['followups',t('No-answer follow-up','Недозвоны')]);
  nav.push(['chats',t('Chats','Чаты')]);
  nav.push(['handoffs',t('Transferred clients','Переданные клиенты')]);
  nav.push(['community',t('Client feed','Лента клиентов')]);
  nav.push(['knowledge',t('Knowledge base','База знаний')]);nav.push(['calls',t('Call scripts','Сценарии звонков')]);
  if(isAdmin())nav.push(['club',t('Referral program','Программа приглашений')]);
  if(isAdmin())nav.push(['links',t('Buyer links','Ссылки баеров')]);
  const navButton=([id,label])=>`<button data-tab="${id}" aria-current="${tab===id?'page':'false'}">${window.EcoCRMDesign?.icon(id)||''}<span class="crm-nav-label">${label}</span>${id==='today'?` <b data-awaiting-count ${EcoReplyQueue.items(EcoSupportChat.inbox()).length?'':'hidden'}>${EcoReplyQueue.items(EcoSupportChat.inbox()).length||''}</b>`:''}${id==='chats'?` <b data-chat-count ${EcoSupportChat.count()?'':'hidden'}>${EcoSupportChat.count()||''}</b>`:''}${id==='funding'?` <b data-funding-count>${fundingInbox.count()||''}</b>`:''}${id==='withdrawals'?` <b data-withdrawal-count>${withdrawalInbox.count()||''}</b>`:''}${id==='leads'?` <b>${data.leads.length}</b>`:''}</button>`;
  const groups=[[[t('Work','Работа')],['today','leads','clients','chats','funding','withdrawals','followups']],[[t('Tools','Инструменты')],['funnel','handoffs','calls','knowledge','community']],[[t('Administration','Управление')],['club','links']]];
  const navHtml=groups.map(([title,ids])=>{const items=ids.map(id=>nav.find(n=>n[0]===id)).filter(Boolean);return items.length?'<section class="crm-nav-group"><h2>'+title[0]+'</h2>'+items.map(navButton).join('')+'</section>':'';}).join('');
  const navRoot=$('#central-nav');if(navRoot.innerHTML!==navHtml){const focus=document.activeElement?.closest('#central-nav button')?.dataset.tab,scroll=$('.crm-sidebar').scrollTop;navRoot.innerHTML=navHtml;$('.crm-sidebar').scrollTop=scroll;if(focus)navRoot.querySelector('[data-tab="'+focus+'"]')?.focus({preventScroll:true});}
  navRoot.setAttribute('aria-label',t('Workspace sections','Разделы CRM'));$('#central-nav-toggle').textContent=t('Sections','Разделы')+' · '+(nav.find(n=>n[0]===tab)?.[1]||t('Workspace','Кабинет'));$('.crm-skip').textContent=t('Skip to workspace','Перейти к рабочей области');syncMenu();
  const overdue=EcoCRMWorkbench.derive(data).allFirstCalls.filter(l=>EcoFunnel.sla({...l,funnel:l.crm.funnel}).overdue).length,callAlert=$('#central-first-call-alert'),callAlertText=overdue&&tab!=='today'?'<div class="call-policy">'+t('Over 15 minutes without a first call: ','Без первого звонка более 15 минут: ')+overdue+' '+button(t('Open call queue','Открыть очередь звонков'),'data-tab="today"')+'</div>':'';if(callAlert&&callAlert.innerHTML!==callAlertText)callAlert.innerHTML=callAlertText;
  $('#central-funding-alert').innerHTML=fundingInbox.banner();$('#central-withdrawal-alert').innerHTML=withdrawalInbox.banner();
  if(tab==='community'){EcoCallDesk.unmount();EcoKnowledge.unmount();EcoCallerGuide.unmount();EcoSupportChat.unmount();EcoCommunityUI.staff($('#central-main'));return;}EcoCommunityUI.unmount();
  if(['funnel','followups'].includes(tab)){EcoCallDesk.unmount();EcoKnowledge.unmount();EcoCallerGuide.unmount();EcoSupportChat.unmount();EcoFunnelUI.mount($('#central-main'),tab,data);return;}EcoFunnelUI.unmount();
  if(tab==='calls'){EcoKnowledge.unmount();EcoCallerGuide.unmount();EcoSupportChat.unmount();EcoCallDesk.mount($('#central-main'),callRecord);return;}EcoCallDesk.unmount();
  if(tab==='chats'){EcoKnowledge.unmount();EcoCallerGuide.unmount();EcoSupportChat.mount($('#central-main'));return;}
  EcoSupportChat.unmount();
  if(tab==='guide'){EcoKnowledge.unmount();EcoCallerGuide.mount($('#central-main'),data.me,selected,account);return;}
  EcoCallerGuide.unmount();
  if(tab==='knowledge'){EcoKnowledge.mount($('#central-main'),data.me);return;}
  EcoKnowledge.unmount();
  if(tab==='club'){EcoClubAdmin.mount($('#central-main'));return;}
  $('#central-main').innerHTML=handoffPanel()+(tab==='today'?today():tab==='leads'?leads():tab==='clients'?clients():tab==='funding'?fundingInbox.page():tab==='withdrawals'?withdrawalInbox.page():tab==='handoffs'?paidHandoffs():links());
  withdrawalInbox.paintRows($('#central-main'));
  if(tab==='clients'&&account&&$('#crm-identity'))EcoIdentityUI.staff($('#crm-identity'),selected);
 }
 function handoffPanel(){return !data.handoffs?.length?'':`<section class="crm-panel"><h2>${t('Client handoffs','Передача клиентов')}</h2><p>${t('The current manager retains access until the receiving manager accepts.','Текущий менеджер сохраняет доступ, пока новый не примет клиента.')}</p>${data.handoffs.map(h=>`<article class="central-pending"><div><strong translate="no">${esc(h.client_name)}</strong><p>${esc(manager(h.from_owner))} → ${esc(manager(h.to_owner))}</p><p translate="no">${esc(h.reason)}</p></div>${h.to_owner===data.me.id?button(t('Review handoff','Проверить передачу'),'data-handoff="'+h.id+'"'):isAdmin()?button(t('Cancel handoff','Отменить передачу'),'data-handoff="'+h.id+'"'):t('Awaiting acceptance','Ожидает принятия')}</article>`).join('')}</section>`;}
 function heading(title,sub){return `<div class="central-title"><div><h1>${title}</h1><p>${sub}</p></div>${button(t('New lead','Новая заявка'),'data-new-lead',true)}</div>`;}
 function paidHandoffs(){const rows=data.handoffHistory||[],count=new Set(rows.map(r=>r.clientId)).size;return `<div class="central-title"><div><h1>${t('Transferred paying clients','Переданные оплатившие клиенты')}</h1><p>${t('Only the administrator initiates transfers. This record stays after a client moves to another manager.','Передачу назначает только админ. Эта запись остаётся после перехода клиента к другому менеджеру.')}</p></div></div><section class="crm-panel"><h2>${t('Clients with confirmed funding','Клиенты с подтверждённым пополнением')}: ${count}</h2><p>${t('A snapshot at handoff, not access to later balances or conversations. Each client is counted once; transfers are listed separately. Model entries are labeled.','Снимок на момент передачи: без доступа к дальнейшему балансу и переписке. Клиент считается один раз; передачи показаны отдельно. Модельные записи отмечены.')}</p></section>${rows.map(r=>`<article class="crm-panel"><h2 translate="no">${esc(r.clientName)}</h2><p><span translate="no">${esc(r.fromName)} → ${esc(r.toName)}</span></p><dl class="wf-facts"><div><dt>${t('First confirmed funding','Первое подтверждённое пополнение')}</dt><dd>${money(r.firstFunding.amountCents/100)}${r.firstFunding.mode==='demo'?` <small>${t('Model entry','Запись модели')}</small>`:''}</dd></div><div><dt>${t('Confirmed on','Подтверждено')}</dt><dd>${date(r.firstFunding.confirmedAt)}</dd></div><div><dt>${t('Handoff accepted','Передача принята')}</dt><dd>${date(r.acceptedAt)}</dd></div><div><dt>${t('Payment reference','Номер пополнения')}</dt><dd translate="no">${esc(r.firstFunding.requestId)}</dd></div></dl></article>`).join('')||empty(t('No transferred clients with confirmed funding yet. A payment report or a manual balance adjustment alone does not count.','Переданных клиентов с подтверждённым пополнением пока нет. Сообщение об отправке или ручная корректировка баланса сами по себе не считаются пополнением.'))}`;}
 function renderReplyQueue(){const all=EcoSupportChat.inbox(),count=EcoReplyQueue.items(all).length;document.querySelectorAll('[data-awaiting-count]').forEach(n=>{n.textContent=count||'';n.hidden=!count;});const list=$('#today-reply-list');if(list)list.innerHTML=EcoReplyQueue.list(all,{owner:replyOwner,language:window.EcoLocale?.language});const visible=$('#today-reply-count');if(visible)visible.textContent=EcoReplyQueue.items(all,replyOwner).length;const daily=$('[data-day-replies]');if(daily)daily.textContent=count;}
 function replyQueue(){const rows=EcoSupportChat.inbox();return `<section class="crm-panel wf-reply-queue" aria-labelledby="today-reply-title"><div class="wf-reply-head"><h2 id="today-reply-title">${t('Clients awaiting a reply','Клиенты ждут ответа')} <b id="today-reply-count">${EcoReplyQueue.items(rows,replyOwner).length}</b></h2>${isAdmin()?`<label>${t('Responsible manager','Ответственный менеджер')}<select id="today-reply-owner"><option value="">${t('All managers','Все менеджеры')}</option>${data.managers.map(m=>`<option value="${esc(m.id)}" ${replyOwner===m.id?'selected':''}>${esc(m.name)}</option>`).join('')}</select></label>`:''}</div><div id="today-reply-list">${EcoReplyQueue.list(rows,{owner:replyOwner,language:window.EcoLocale?.language})}</div></section>`;}
 function today(){const work=EcoCRMWorkbench.derive(data),replies=EcoReplyQueue.items(EcoSupportChat.inbox()).length;
  const metric=(label,value,hint,attr,icon,urgent=false)=>'<button '+attr+' class="'+(urgent?'is-due':'')+'"><span>'+label+'</span>'+EcoCRMDesign.icon(icon)+'<b'+(icon==='chats'?' data-day-replies':'')+'>'+value+'</b><small>'+hint+'</small></button>';
  const docs='<section class="crm-panel"><h2>'+t('Documents to review','Документы на проверке')+'</h2>'+work.documents.map(c=>'<button class="crm-button outline" data-client="'+esc(c.id)+'" translate="no">'+esc(c.name)+' →</button>').join('')+'</section>';
  const agenda='<section class="crm-panel wf-agenda" id="crm-day-agenda"><h2>'+t('Scheduled contacts','План контактов')+'</h2><p class="crm-day-note">'+(work.overdue.length?t('Overdue: ','Просрочено: ')+work.overdue.length:t('Next conversations in chronological order.','Следующие контакты по времени.'))+'</p>'+(work.scheduled.length?work.scheduled.map(r=>'<button class="wf-agenda-row" '+(r.kind==='lead'?'data-lead="':'data-client="')+esc(r.id)+'"><time class="'+(Date.parse(r.crm.nextContact)<Date.now()?'wf-overdue':'')+'">'+date(r.crm.nextContact)+'</time><span><b translate="no">'+esc(r.name)+'</b><small>'+status(r.crm.status)+'</small><small translate="no">'+esc(r.crm.comment)+'</small></span><span aria-hidden="true">→</span></button>').join(''):'<p>'+t('No contacts scheduled. Save the next step after each conversation.','Контакты пока не запланированы. Сохраните следующий шаг после разговора.')+'</p>')+'</section>';
  const latest=work.open.filter(l=>l.owner).slice(0,4);
  return heading(t('Your workday','Рабочий день'),isAdmin()?t('Distribute new leads, keep calls on time and resolve client requests.','Распределяйте заявки, следите за сроками и помогайте команде закрывать вопросы клиентов.'):t('Start with pending calls and replies. Every conversation has a next step.','Начните со звонков и ответов клиентам. После каждого разговора сохраните следующий шаг.'))+
  '<div class="crm-day-stats">'+metric(isAdmin()?t('Unassigned leads','Без менеджера'):t('Open leads','Заявки в работе'),isAdmin()?work.unassigned.length:work.open.length,isAdmin()?t('Distribute to the team','Распределить в команду'):t('Your active requests','Ваши активные заявки'),isAdmin()?'data-open-unassigned':'data-tab="leads"','leads')+
  metric(t('First call','Первый звонок'),work.allFirstCalls.length,t('Waiting for contact','Ожидают контакта'),'data-first-agenda','calls')+
  metric(t('Contacts due','Контакты на сегодня'),work.due.length,work.overdue.length?t('Overdue: ','Просрочено: ')+work.overdue.length:t('Including scheduled calls','Запланированные звонки'),'data-agenda','today',work.overdue.length>0)+
  metric(t('Awaiting reply','Ждут ответа'),replies,t('Client conversations','Переписка с клиентами'),'data-tab="chats"','chats')+'</div>'+
  '<div class="crm-today-grid"><div class="crm-today-column">'+EcoFunnelUI.queue(data)+agenda+'</div><div class="crm-today-column">'+replyQueue()+(work.documents.length?docs:'<details class="crm-panel crm-quiet-panel"><summary>'+t('Documents · no pending reviews','Нет документов на проверке')+'</summary><p>'+t('New submissions will appear here.','Новые документы появятся здесь после отправки клиентом.')+'</p></details>')+
  '<section class="crm-panel"><h2>'+t('Active conversations','Сейчас в работе')+'</h2>'+latest.map(l=>listItem(l,'lead')).join('')+(latest.length?'':'<p>'+t('No assigned leads yet.','Назначенных заявок пока нет.')+'</p>')+'</section></div></div>'+
  (data.clients.some(c=>c.firstWithdrawal&&!c.postWithdrawalCall)?EcoFunnelUI.withdrawalQueue(data):'');
 }
 function scopes(){return '<div class="crm-scopes" role="group" aria-label="'+t('Lead queues','Очереди заявок')+'">'+[['',t('All leads','Все заявки')],['fast',t('Consultations','Консультации')],['nurture',t('Exploring','Знакомятся с проектом')],['first',t('First call','Первый звонок')],['callback',t('Scheduled contact','Есть следующий контакт')],...(isAdmin()?[['unassigned',t('Unassigned','Без менеджера')]]:[])].map(([id,label])=>'<button data-queue="'+id+'" aria-pressed="'+(queueScope===id)+'">'+label+'</button>').join('')+'</div>';}
 function clearRecord(){lead=null;leadId=null;account=null;selected=null;}
 function filtered(rows){const q=search.trim().toLowerCase();return rows.filter(r=>(!statusFilter||r.crm.status===statusFilter)&&(!ownerFilter||(ownerFilter==='unassigned'?!r.owner:r.owner===ownerFilter))&&(!q||[r.name,r.email,r.phone,r.username,r.crm.comment,r.context?.solar?.name,r.context?.solar?'solar панели':'',r.context?.mining?('mining майнинг '+EcoMining.title(r.context.mining.route,window.EcoLocale?.language)+' '+(EcoMining.coins[r.context.mining.coinId]?.ticker||'')+' '+(r.context.mining.miner?.model||'')+' '+(r.context.mining.budgetUsd||'')):''].some(x=>String(x||'').toLowerCase().includes(q))));}
 function filters(){return `<div class="wf-filters"><label>${t('Search','Поиск')}<input id="wf-search" type="search" value="${esc(search)}" placeholder="${t('Name, phone, email','Имя, телефон, почта')}"></label><label>${t('Qualification','Квалификация')}<select id="wf-status"><option value="">${t('All statuses','Все статусы')}</option>${options(statusFilter)}</select></label>${isAdmin()?`<label>${t('Manager','Менеджер')}<select id="wf-owner"><option value="">${t('Everyone','Все')}</option><option value="unassigned" ${ownerFilter==='unassigned'?'selected':''}>${t('Unassigned','Не распределены')}</option>${data.managers.map(m=>`<option value="${m.id}" ${ownerFilter===m.id?'selected':''}>${esc(m.name)}</option>`).join('')}</select></label>`:''}</div>`;}
 function listItem(r,kind){return `<div class="wf-list-row">${isAdmin()&&tab==='leads'&&kind==='lead'?`<input type="checkbox" data-pick="${r.id}" aria-label="${esc(t('Select ','Выбрать ')+r.name)}" ${checked.has(r.id)?'checked':''} ${r.needsReview?'disabled':''}>`:''}<button ${kind==='lead'?`data-lead="${r.id}"`:`data-client="${r.id}"`} aria-pressed="${r.id===(kind==='lead'?leadId:selected)}"><span class="wf-list-top"><b translate="no">${esc(r.name)}</b>${pill(r.crm)}${r.identityStatus==='submitted'?`<small class="wf-status">${t('Documents to review','Документы на проверке')}</small>`:''}</span><span translate="no">${esc(r.phone||r.email||'—')}</span><small class="wf-last-comment" translate="no">${esc(r.crm.comment||t('No contact recorded','Контакт ещё не записан'))}</small>${r.context?.solar?`<small class="wf-status">${t('Energy equipment','Оборудование')} · <span translate="no">${esc(r.context.solar.name)}</span></small>`:''}${r.context?.mining?'<small class="wf-status wf-mining-intent">EcoGrid Mining · '+esc(EcoMining.title(r.context.mining.route,window.EcoLocale?.language))+' · '+esc(EcoMining.coins[r.context.mining.coinId]?.ticker||t('Selection advice','Подбор'))+(r.context.mining.budgetUsd?' · '+money(r.context.mining.budgetUsd):'')+'</small>':''}${withdrawalInbox.marker(kind==='client'?r.id:r.client_id)}${EcoJourneyUI.badge(r)}${r.created?EcoFunnelUI.elapsed(r):''}${r.crm.nextContact?`<small>${t('Next','Следующий контакт')}: ${date(r.crm.nextContact)}</small>`:''}${isAdmin()?`<small>${t('Manager','Менеджер')}: <span translate="no">${esc(manager(r.owner))}</span></small>`:''}${r.needsReview?`<small class="wf-overdue">${t('Contact match needs review','Нужна проверка совпадения контактов')}</small>`:''}</button></div>`;}
 function leads(){const rows=EcoCRMWorkbench.filter(filtered(data.leads),queueScope).sort((a,b)=>{const x=EcoFunnel.sla({...a,funnel:a.crm.funnel}),y=EcoFunnel.sla({...b,funnel:b.crm.funnel});return Number(y.waiting)-Number(x.waiting)||(x.waiting?(y.ageMs||0)-(x.ageMs||0):b.created.localeCompare(a.created));});return heading(isAdmin()?t('Lead distribution','Распределение заявок'):t('Your assigned leads','Ваши заявки'),isAdmin()?t('Review the client’s request and assign a manager.','Изучите запрос клиента и назначьте менеджера.'):t('Open a lead to record qualification and the next step.','Откройте заявку, чтобы записать квалификацию и следующий шаг.'))+filters()+scopes()+`<div class="wf-result-head"><span>${leadCount(rows.length)}</span>${isAdmin()?button(t('Assign selected','Назначить выбранные')+` (${checked.size})`,'data-assign-batch '+(!checked.size?'disabled':'')):''}</div><div class="wf-grid"><aside class="wf-list">${rows.map(l=>listItem(l,'lead')).join('')||empty(t('No leads match these filters.','По этим фильтрам заявок нет.'))}</aside><div class="wf-detail">${lead?leadCard():empty(t('Select a lead to see its details.','Выберите заявку для просмотра.'))}</div></div>`;}

 function leadCard(){const content='<button class="crm-button outline wf-back-list" data-back-record="lead">'+t('← Back to leads','← К списку заявок')+'</button>'+baseLeadCard();if(lead.conflicts?.length)return '<section class="crm-panel">'+button(t('Review contact match','Проверить совпадение'),'data-review-match',true)+'</section>'+content;if(lead.duplicateOf)return '<section class="crm-panel"><h3>'+t('Confirmed duplicate','Подтверждённый дубль')+'</h3>'+button(t('Open original lead','Открыть исходную заявку'),'data-lead="'+esc(lead.duplicateOf)+'"')+'</section>'+content.replaceAll('data-assign-lead','disabled data-assign-lead');return content;}
 const empty=text=>`<div class="central-empty">${text}</div>`;
 function solarInquiry(l){const s=l.context?.solar;if(!s)return '';const property={owner:t('Homeowner','Владелец дома'),planning:t('Building or buying','Строит или покупает'),business:t('Business or shared property','Бизнес или общий объект'),other:t('Other situation','Другая ситуация')},kind=s.requestType||'solar';const row=(label,value)=>'<div><dt>'+label+'</dt><dd translate="no">'+esc(value)+'</dd></div>';return '<section class="crm-panel wf-solar-inquiry"><span class="wf-kicker">'+t('ENERGY EQUIPMENT · INQUIRY','ЭНЕРГЕТИЧЕСКОЕ ОБОРУДОВАНИЕ · ЗАЯВКА')+'</span><h2>'+({solar:t('Solar + storage','Панели и накопители'),charging:t('EV charging','Зарядка электромобиля'),consultation:t('Specialist consultation','Подбор со специалистом')}[kind])+'</h2><dl class="wf-facts">'+row(t('Country / postal code','Страна / индекс'),(s.country==='CA'?t('Canada','Канада'):t('United States','США'))+' · '+s.zip)+row(t('Property','Объект'),property[s.property]||'—')+(s.estimateUsd?row(t('Reference estimate · USD','Ориентир · USD'),money(s.estimateUsd)+' · '+t('Qcells reference, before incentives','базовый Qcells, до льгот')):'')+(s.preferredPanel?row(t('Preferred panel','Выбранная панель'),s.preferredPanel.manufacturer+' '+s.preferredPanel.model+' · '+s.preferredPanel.arrayKw+' kW DC'):'')+(s.preferredBattery?row(t('Battery','Накопитель'),s.preferredBattery.manufacturer+' '+s.preferredBattery.model+' · '+s.preferredBattery.capacityKWh+' kWh'):'')+(kind==='charging'?row(t('Charger','Зарядное устройство'),s.preferredCharger?s.preferredCharger.manufacturer+' '+s.preferredCharger.model+' · '+s.preferredCharger.maxKW+' kW · '+s.preferredCharger.connector:t('Help me choose','Нужен подбор'))+row(t('Vehicle','Автомобиль'),s.vehicle||'—'):'')+(s.billMonthly!=null?row(t('Electricity bill / month','Счёт за электричество / месяц'),s.billMonthly+' '+(s.billCurrency||'USD')):'')+'</dl><p class="wf-warning">'+t('Confirm local availability, scope and currency in a separate written quote.','Подтвердите доступность по адресу, состав работ и валюту в отдельной смете.')+'</p>'+EcoSolarGuide.html(t('en','ru'))+'</section>';}

 function miningInquiry(l){const q=l.context?.mining;if(!q)return '';return '<section class="crm-panel"><span class="wf-kicker">EcoGrid Mining</span><h2>'+esc(EcoMining.title(q.route,window.EcoLocale?.language))+'</h2><dl class="wf-facts">'+EcoMining.rows(q,window.EcoLocale?.language).map(([k,v])=>'<div><dt>'+esc(k)+'</dt><dd translate="no">'+esc(v)+'</dd></div>').join('')+'</dl><p class="wf-mining-next"><strong>'+t('Next step: ','Следующий шаг: ')+'</strong>'+esc(EcoMining.nextStep(q.route,window.EcoLocale?.language))+'</p><p>'+t('Review project terms or an equipment and hosting quote.','Подготовьте условия проекта или смету оборудования и размещения.')+'</p></section>';}
 function requestedContext(l){const q=l.context;if(!q?.tierId&&!q?.tab&&!q?.projectCalculation)return '';const tiers={single:t('Single','Старт'),network:t('Network','Сеть'),portfolio:t('Portfolio','Портфель'),scale:t('Custom','Индивидуальный')},tabs={tariffs:t('Participation plans','Планы участия'),stations:t('Station selection','Выбор станций'),documents:t('Terms and documents','Условия и документы'),equipment:t('Equipment selection','Подбор оборудования')};return '<p class="crm-request-context"><strong>'+t('Interested in: ','Интересует: ')+'</strong>'+esc([tabs[q.tab]||t('Energy projects','Энергетические проекты'),tiers[q.tierId]].filter(Boolean).join(' · '))+'</p>'+(q.projectCalculation?'<p class="crm-request-context"><strong>'+t('Requested calculation: ','Запрошенный расчёт: ')+'</strong>'+esc(new Intl.NumberFormat(t('en-US','ru-RU'),{style:'currency',currency:'USD'}).format(q.projectCalculation.capital)+' · '+q.projectCalculation.start+' UTC')+'</p>':'');}
 function presentationControl(r,kind,key){return '<label class="crm-club-membership"><input type="checkbox" data-academy-presentation="'+kind+'" data-record-id="'+esc(key)+'" data-record-version="'+r.version+'" '+(r.presentationComplete===true?'checked':'')+'><span>'+t('Project presentation completed','Презентация проекта проведена')+'</span></label>';}
 function membershipControl(r,kind,key,registered=true){const hint=registered?t('Confirm registration and group subscriptions. A deposit is not required.','Подтвердите регистрацию и подписку на группы. Пополнение не требуется.'):t('Create the client account before confirming Club membership.','Сначала создайте клиентский аккаунт.');return '<label class="crm-club-membership" title="'+hint+'"><input type="checkbox" data-club-membership="'+kind+'" data-member-id="'+esc(key)+'" data-member-version="'+r.version+'" '+(r.clubMember===true?'checked ':'')+(registered?'':'disabled')+'><span>'+t('EcoGrid Club member','Состоит в EcoGrid Club')+'</span></label>';}
 function baseLeadCard(){const l=lead;return `<section class="crm-panel"><div class="wf-card-head"><div><span class="wf-kicker">${t('LEAD','ЗАЯВКА')} · ${date(l.created)}</span><h2 translate="no">${esc(l.name)}</h2></div>${pill(l.crm)}</div><dl class="wf-facts"><div><dt>${t('First name','Имя')}</dt><dd translate="no">${esc(l.first_name||'—')}</dd></div><div><dt>${t('Last name','Фамилия')}</dt><dd translate="no">${esc(l.last_name||'—')}</dd></div><div><dt>${t('Phone','Телефон')}</dt><dd translate="no">${esc(l.phone||'—')}</dd></div><div><dt>${t('Email','Почта')}</dt><dd translate="no">${esc(l.email||'—')}</dd></div><div><dt>${t('Manager','Менеджер')}</dt><dd translate="no">${esc(manager(l.owner))}</dd></div></dl>${membershipControl(l.crm,"lead",l.id,!!l.client_id)}${presentationControl(l.crm,"lead",l.id)}${requestedContext(l)}${EcoJourneyUI.summary(l)}<div class="wf-actions">${button(t('Record contact','Результат контакта'),'data-contact="lead"',true)}${l.context?.solar?'':button(t('Call scripts','Сценарии звонков'),`data-call-record="lead" data-call-key="${esc(l.id)}"`)}${button(t('Edit details','Изменить данные'),'data-lead-profile')}${isAdmin()?button(t('Assign manager','Назначить менеджера'),'data-assign-lead'):''}${l.client_id?button(t('Open client','Открыть клиента'),`data-client="${l.client_id}"`):l.owner&&!l.conflicts?.length&&!['solar_purchase','mining'].includes(l.context?.intent)?button(t('Create client account','Создать аккаунт клиента'),'data-create-from="'+l.id+'"'):''}</div>${contactSummary(l.crm)}${EcoFunnelUI.elapsed(l)}${sourceDetails(l)}<details class="crm-detail-fold"><summary>${t('Contact preferences','Связь с клиентом')}</summary>${EcoFunnelUI.consentCard(l.crm,'lead',l.id)}</details>${l.conflicts?.length?`<div class="wf-warning">${t('These contacts match different requests. Check them before creating an account.','Контакты совпадают с разными заявками. Проверьте их до создания аккаунта.')}<div>${l.conflicts.map(key=>button(esc(data.leads.find(r=>r.id===key)?.name||key),`data-lead="${key}"`)).join('')}</div></div>`:''}</section>${miningInquiry(l)}${solarInquiry(l)}${history(l.crm.history)}`;}
 function contactSummary(r){return `${r.funnel?.closeReason?'<p>'+t('Closing reason: ','Причина закрытия: ')+t(...EcoFunnel.reasons[r.funnel.closeReason])+'</p>':''}<div class="wf-contact-summary"><span>${t('Latest comment','Последний комментарий')}</span><p translate="no">${esc(r.comment||t('No contact recorded yet.','Контакт ещё не записан.'))}</p><small>${t('Next contact','Следующий контакт')}: ${date(r.nextContact)}</small></div>`;}
 function history(rows){const names={club_membership_updated:t('Club membership updated','Членство в Клубе обновлено'),website_request:t('Application received','Заявка получена'),assigned:t('Manager assigned','Назначен менеджер'),contact_saved:t('Contact recorded','Результат контакта'),journey_requested:t('Request updated','Запрос клиента обновлён'),client_journey_updated:t('Interests updated','Интересы клиента обновлены'),handoff_accepted:t('Client handoff accepted','Клиент принят менеджером'),lead_updated:t('Lead updated','Данные заявки изменены'),contact_match_reviewed:t('Contact match reviewed','Проверка совпадения'),contact_recorded:t('Contact recorded','Результат контакта'),owner_assigned:t('Manager assigned','Назначен менеджер'),mining_inquiry_requested:t('Mining proposal requested','Запрошено предложение по майнингу'),solar_quote_requested:t('Equipment advice requested','Запрошен подбор оборудования'),lead_received:t('Application received','Заявка получена'),lead_created:t('Lead created','Заявка создана'),client_created:t('Account created','Аккаунт создан'),profile_updated:t('Profile updated','Данные изменены'),balance_credit:t('Balance credited','Зачисление'),balance_debit:t('Balance debited','Списание'),message_replied:t('Reply sent','Ответ клиенту')};return `<section class="crm-panel wf-history"><h3>${t('Contact history','История работы')}</h3>${rows?.length?rows.map(r=>`<article><div><b>${names[r.action]||t('Record updated','Запись обновлена')}</b><time>${date(r.created)}</time></div><small translate="no">${esc(r.actor||t('Website','Сайт'))}</small>${r.action==='club_membership_updated'?'<p>'+(r.details.to?t('Club membership confirmed','Вступление в Клуб подтверждено'):t('Club membership mark cleared','Отметка о вступлении снята'))+'</p>':''}${r.details.from&&labels[r.details.from]?`<p>${status(r.details.from)} → ${status(r.details.to)}</p>`:''}${r.action==='owner_assigned'?`<p translate="no">${esc(r.details.fromName||t('Unassigned','Не назначен'))} → ${esc(r.details.toName||t('Unassigned','Не назначен'))}</p>`:''}${r.details.solar?`<p translate="no">${esc(r.details.solar.name)} · ${r.details.solar.estimateUsd?money(r.details.solar.estimateUsd):t('Specialist advice','Подбор специалиста')} · ${esc(r.details.solar.country||'US')} ${esc(r.details.solar.zip)}</p>`:''}${r.details.comment||r.details.reason?`<p translate="no">${esc(r.details.comment||r.details.reason)}</p>`:''}${r.details.nextContact?`<small>${t('Next contact','Следующий контакт')}: ${date(r.details.nextContact)}</small>`:''}</article>`).join(''):`<p>${t('No recorded changes yet.','Изменений пока нет.')}</p>`}</section>`;}
 function clients(){const rows=filtered(data.clients),a=account?.state;return heading(isAdmin()?t('All clients','Все клиенты'):t('Your clients','Ваши клиенты'),t('Contact details, qualification, and account activity.','Контакты, квалификация и операции по счёту.'))+filters()+`<div class="wf-grid"><aside class="wf-list">${rows.map(c=>listItem(c,'client')).join('')||empty(t('No clients match these filters.','По этим фильтрам клиентов нет.'))}</aside><div class="wf-detail">${a?`<button class="crm-button outline wf-back-list" data-back-record="client">${t('← Back to clients','← К списку клиентов')}</button><section class="crm-panel"><div class="wf-card-head"><div><span class="wf-kicker" translate="no">${esc(account.client.username)}</span><h2 translate="no">${esc(account.client.name)}</h2></div>${pill(account.crm)}</div><dl class="wf-facts"><div><dt>${t('Phone','Телефон')}</dt><dd translate="no">${esc(account.client.phone||'—')}</dd></div><div><dt>${t('Email','Почта')}</dt><dd translate="no">${esc(account.client.email||'—')}</dd></div><div><dt>${t('Manager','Менеджер')}</dt><dd translate="no">${esc(a.manager.name)}</dd></div></dl>${membershipControl(account.crm,"client",account.client.id)}${presentationControl(account.crm,"client",account.client.id)}${EcoJourneyUI.summary(account)}${sourceDetails({...account,attribution:data.leads.find(l=>l.client_id===selected)?.attribution})}${contactSummary(account.crm)}<div class="wf-actions">${button(t('Record contact','Результат контакта'),'data-contact="client"',true)}${button(t('Open chats','Открыть чаты'),'data-tab="chats"')}${button(t('Guided conversation','Презентация'),'data-tab="guide"')}${button(t('Call scripts','Сценарии звонков'),`data-call-record="client" data-call-key="${esc(selected)}"`)}${button(t('Edit details','Изменить данные'),'data-profile')}${isAdmin()?button(t('Reassign','Сменить менеджера'),'data-assign-client'):''}</div></section><section class="crm-balance-card"><div><span>${t('Available balance','Доступный баланс')}</span><strong translate="no">${money(EcoFinance.summary(a).available)}</strong><small>${t('Reserved','В резерве')}: ${money(EcoFinance.summary(a).reserved)}</small></div><div class="wf-actions">${button('+ '+t('Credit','Пополнить'),'data-balance="credit"',true)}${button('− '+t('Debit','Списать'),'data-balance="debit"')}</div></section>${financePanel(a)}${window.EcoMiningPortfolio?.render(a,window.EcoLocale?.language)||''}${energyBriefUI.panel(account)}<section class="crm-panel" id="crm-identity"></section>${research(a)}${requests(a)}${messages(a)}${financeHistory(a)}${history(account.crm.history)}`:empty(t('Select a client to see their account.','Выберите клиента для просмотра.'))}</div></div>`;}
 function manual(){dialogContext={kind:'manual'};dialog(t('New lead','Новая заявка'),`<form id="central-manual" class="central-form"><div class="wf-form-pair"><label>${t('First name','Имя')}<input name="firstName" required maxlength="50" autocomplete="given-name"></label><label>${t('Last name','Фамилия')}<input name="lastName" required maxlength="70" autocomplete="family-name"></label></div><label>${t('Phone','Телефон')}<input name="phone" type="tel" maxlength="40" autocomplete="tel"></label><label>${t('Email','Почта')}<input name="email" type="email" maxlength="160" autocomplete="email"></label>${contactFields()}<p class="central-readonly">${isAdmin()?t('Assign a manager after saving.','После сохранения назначьте менеджера.'):t('This lead will be assigned to you.','Эта заявка будет закреплена за вами.')}</p><button type="submit" class="crm-button primary">${t('Create lead','Создать заявку')}</button></form>`);}
 function contact(kind){const r=kind==='lead'?lead.crm:account.crm;dialogContext={kind,id:kind==='lead'?lead.id:selected,version:r.version};dialog(t('Record contact','Результат контакта'),`<form id="central-contact" class="central-form">${EcoJourneyUI.fields(kind==='lead'?lead:account)}${contactFields(r)}<button type="submit" class="crm-button primary">${t('Save contact','Сохранить результат')}</button></form>`);}
 function assign(items){dialogContext={items};dialog(t('Assign manager','Назначить менеджера'),`<form id="central-assignment" class="central-form"><p>${t('Selected records','Выбрано записей')}: ${items.length}</p>${items.some(i=>i.kind==='client')?`<p>${t('The client stays with the current manager until the new manager accepts.','Клиент остаётся у текущего менеджера, пока новый не примет передачу.')}</p>`:''}<label>${t('Manager','Менеджер')}<select name="owner" required><option value="">${t('Choose a manager','Выберите менеджера')}</option>${data.managers.map(m=>`<option value="${m.id}">${esc(m.name)} · ${leadCount(m.openLeads)}</option>`).join('')}</select></label><label>${t('Assignment comment','Комментарий к назначению')}<textarea name="reason" required maxlength="1000" rows="3"></textarea></label><button type="submit" class="crm-button primary">${t('Assign','Назначить')}</button></form>`);}
 function create(lid){editingLead=data.leads.find(l=>l.id===lid);if(!editingLead)return;dialogContext={version:editingLead.crm.version};const l=editingLead;dialog(t('Create client account','Создать аккаунт клиента'),`<p>${t('Assigned manager','Ответственный')}: <b translate="no">${esc(manager(l.owner))}</b></p><form id="central-create" class="central-form"><label>${t('Client name','Имя клиента')}<input name="name" value="${esc(l.name)}" required minlength="2" maxlength="100"></label><label>${t('Email','Почта')}<input name="email" type="email" value="${esc(l.email)}" maxlength="160"></label><label>${t('Phone','Телефон')}<input name="phone" type="tel" value="${esc(l.phone)}" maxlength="40"></label><label>${t('Username','Логин')}<input name="username" required minlength="4" maxlength="50" pattern="[a-zA-Z0-9][a-zA-Z0-9._-]{3,49}" autocomplete="off" autocapitalize="none"></label><label>${t('Password · at least 8 characters','Пароль · минимум 8 символов')}<input name="password" type="password" required minlength="8" maxlength="128" autocomplete="new-password"></label>${contactFields(l.crm)}<button type="submit" class="crm-button primary">${t('Create account','Создать аккаунт')}</button></form>`);}
 const uiError=message=>({
 'A comment is required.':t('A comment is required.','Добавьте комментарий.'),
 'A callback date and time are required.':t('A callback date and time are required.','Укажите дату и время перезвона.'),
 'This record changed. Refresh it before saving.':t('This record changed. Close this form and refresh before saving.','Запись уже изменена. Закройте форму и обновите данные перед сохранением.'),
 'Enter the first and last name.':t('Enter the first and last name.','Укажите имя и фамилию.'),
 'Enter your name, phone or email, and consent to contact.':t('Enter a name and a valid phone number or email.','Укажите имя и корректный телефон или почту.'),
 'Choose a closing reason before closing the lead.':t('Choose a closing reason before closing the lead.','Перед закрытием заявки выберите причину.'),
 'A request with this contact already exists. Ask your administrator to check it.':t('This contact already has a lead. Ask your administrator to check it.','Заявка с этим контактом уже есть. Обратитесь к администратору.'),
 'Lead not found or access denied.':t('This lead is no longer assigned to you.','Эта заявка больше не закреплена за вами.'),
 'Client not found or access denied.':t('This client is no longer assigned to you.','Этот клиент больше не закреплён за вами.')
 })[message]||window.EcoLocale?.t(message)||message;
 async function openRecord(kind,key){if(kind==='lead'){leadId=key;lead=await api('staff/leads/'+key);tab='leads';}else{selected=key;account=await api('staff/clients/'+key);tab='clients';}render();if(innerWidth<1001)$('.wf-detail')?.scrollIntoView({behavior:'auto',block:'start'});}
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||pending)return;try{
  if(b.dataset.awaitingChat){tab='chats';EcoSupportChat.selectThread(b.dataset.awaitingClient,b.dataset.awaitingChat);render();return;}
  if(b.dataset.fundingRequest){if(window.__ecoReceiptOpening)return;window.__ecoReceiptOpening=true;const label=b.textContent;b.disabled=true;b.setAttribute('aria-busy','true');b.textContent=t('Loading receipt…','Загружаем поступление…');try{await openRecord('client',b.dataset.fundingClient);if(account.state.requests.some(r=>r.id===b.dataset.fundingRequest&&r.status==='Pending'))reviewRequest(b.dataset.fundingRequest,'approve');else{notice(t('This request was already reviewed.','Эту заявку уже проверили.'));fundingInbox.refresh();withdrawalInbox.refresh();}}finally{window.__ecoReceiptOpening=false;b.disabled=false;b.removeAttribute('aria-busy');b.textContent=label;}}
  if(b.dataset.callRecord){callRecord={kind:b.dataset.callRecord,key:b.dataset.callKey,script:b.dataset.callScript||null};tab='calls';render();return;}
  if(b.dataset.callClient){await openRecord('client',b.dataset.callClient);return;}
  if(b.id==='central-nav-toggle'){menuOpen=!menuOpen;syncMenu();return;}
  if(b.hasAttribute('data-queue')){tab='leads';queueScope=b.dataset.queue;ownerFilter='';statusFilter='';search='';clearRecord();render();return;}
  if(b.hasAttribute('data-first-agenda')){$('.funnel-first')?.scrollIntoView({behavior:'auto',block:'start'});return;}
  if(b.hasAttribute('data-agenda')){$('#crm-day-agenda')?.scrollIntoView({behavior:'auto',block:'start'});return;}
  if(b.dataset.backRecord){if(b.dataset.backRecord==='lead'){lead=null;leadId=null;}else{account=null;selected=null;}render();$('#central-workspace-content').scrollIntoView({block:'start'});return;}
  if(b.dataset.tab){queueScope='';const fromSidebar=b.closest('#central-nav');menuOpen=false;if(b.dataset.tab==='calls')callRecord=null;tab=b.dataset.tab;if(['leads','clients'].includes(tab))clearRecord();search='';statusFilter='';ownerFilter='';notice('');render();if(fromSidebar&&narrowNavigation.matches){$('#central-workspace-content').focus({preventScroll:true});$('#central-workspace-content').scrollIntoView({block:'start'});}}
  if(b.hasAttribute('data-delivery-journal')){try{deliveryState=await api('staff/lead-deliveries');const host=$('#delivery-journal');if(host)host.innerHTML=deliveryMarkup();}catch{notice(t('Unable to load deliveries.','Не удалось загрузить доставки.'));}return;}
  if(b.dataset.knowledgeArticle){EcoKnowledge.open(b.dataset.knowledgeArticle);tab='knowledge';render();}
  if(b.hasAttribute('data-guide-contact')&&selected){await openRecord('client',selected);contact('client');}
  if(b.hasAttribute('data-open-unassigned')){clearRecord();tab='leads';ownerFilter='';queueScope='unassigned';search='';statusFilter='';render();}
  if(b.hasAttribute('data-new-lead'))manual();
  if(b.hasAttribute('data-review-match'))matchReview();
  if(b.hasAttribute('data-lead-profile'))leadProfile();
  if(b.dataset.lead)await openRecord('lead',b.dataset.lead);if(b.dataset.client)await openRecord('client',b.dataset.client);
  if(b.dataset.contact)contact(b.dataset.contact);if(b.dataset.createFrom)create(b.dataset.createFrom);
  if(b.hasAttribute('data-assign-lead'))assign([{kind:'lead',id:lead.id,version:lead.crm.version}]);
  if(b.dataset.handoff){const h=data.handoffs.find(h=>h.id===b.dataset.handoff);if(!h)return;dialogContext={handoff:h};dialog(t('Client handoff','Передача клиента'),`<p translate="no">${esc(h.client_name)} · ${esc(manager(h.from_owner))} → ${esc(manager(h.to_owner))}</p><p translate="no">${esc(h.reason)}</p><form id="central-handoff"><p>${isAdmin()?t('Cancel this pending request. The current owner will stay responsible.','Отменить запрос. Ответственным останется текущий менеджер.'):t('Accept responsibility for the client, existing conversations and pending requests. The previous manager will lose access.','Принять клиента, текущую переписку и ожидающие заявки. Прежний менеджер потеряет доступ.')}</p><button class="crm-button primary" type="submit">${isAdmin()?t('Cancel handoff','Отменить передачу'):t('Accept client','Принять клиента')}</button></form>`);}
  if(b.hasAttribute('data-assign-client'))assign([{kind:'client',id:selected,version:account.crm.version}]);
  if(b.hasAttribute('data-assign-batch'))assign([...checked].map(id=>({kind:'lead',id,version:data.leads.find(l=>l.id===id).crm.version})));
  if(b.dataset.correctEntry){const old=account.state.adjustments.find(x=>x.operationId===b.dataset.correctEntry);if(old)balance(old.kind==='credit'?'debit':'credit',null,old.operationId);}if(b.dataset.balance)balance(b.dataset.balance);if(b.hasAttribute('data-finance-draft'))await editFinancialPlan('draft');if(b.hasAttribute('data-finance-plan'))await editFinancialPlan();if(b.hasAttribute('data-finance-week'))reviewWeek();if(b.dataset.payment)reviewRequest(b.dataset.payment,'approve');if(b.dataset.rejectPayment)reviewRequest(b.dataset.rejectPayment,'reject');if(b.id==='central-finance-confirm')await saveFinance(b);if(b.hasAttribute('data-profile'))profile();
  if(b.dataset.ticket){profileVersion=account.version;dialog(t('Reply to client','Ответ клиенту'),`<form id="central-reply" class="central-form"><input type="hidden" name="ticketId" value="${esc(b.dataset.ticket)}"><label>${t('Message','Сообщение')}<textarea name="text" required maxlength="1500" rows="5"></textarea></label><button type="submit" class="crm-button primary">${t('Send reply','Отправить ответ')}</button></form>`);}
  if(b.id==='central-close'){close();await refresh();}
  if(b.id==='central-signout'){EcoCallDesk.unmount();EcoSupportChat.stop();fundingInbox.stop();withdrawalInbox.stop();await api('logout','POST',{kind:'staff'});location.assign(new URL(EcoNavigation.login('staff','',window.EcoLocale?.language),document.baseURI));}
  if(b.id==='central-confirm'&&operation){pending=true;b.disabled=true;account=await api('staff/clients/'+operation.clientId+'/balance','POST',operation);close();await refresh();notice(t('Balance change saved.','Изменение баланса сохранено.'));}
  if(b.dataset.copy){await navigator.clipboard.writeText(b.dataset.copy);notice(t('Link copied.','Ссылка скопирована.'));}
  if(b.hasAttribute('data-affiliate'))dialog(t('Add buyer','Добавить баера'),`<form id="central-affiliate" class="central-form"><label>${t('Buyer code','Код баера')}<input name="code" required pattern="[a-z0-9-]{3,50}"></label><label>${t('Name','Название')}<input name="label" required maxlength="100"></label><label>${t('Contact manager','Контактный менеджер')}<select name="owner">${data.managers.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></label><p>${t('Source tracking only. New leads are assigned by the administrator.','Только учёт источника. Новые заявки распределяет администратор.')}</p><button type="submit" class="crm-button primary">${t('Create buyer link','Создать ссылку баера')}</button></form>`);
 }catch(error){($('#central-dialog').open?$('#central-error'):$('#central-notice')).textContent=uiError(error.message);if(error.status===403&&!$('#central-dialog').open){lead=null;account=null;leadId=null;selected=null;await refresh();}}finally{pending=false;if(b.isConnected)b.disabled=false;}});
 document.addEventListener('input',e=>{if(e.target.id==='finance-search'){paintFinanceStations(e.target.value);}if(e.target.id==='wf-search'){search=e.target.value;clearRecord();const start=e.target.selectionStart;render();$('#wf-search').focus();$('#wf-search').setSelectionRange(start,start);}});
 document.addEventListener('change',async e=>{const field=e.target;if(!field.matches('[data-academy-presentation]'))return;if(pending){field.checked=!field.checked;return;}const presented=field.checked;pending=true;field.disabled=true;try{await api('staff/'+(field.dataset.academyPresentation==='lead'?'leads':'clients')+'/'+encodeURIComponent(field.dataset.recordId)+'/academy-presentation','POST',{version:Number(field.dataset.recordVersion),presented});await refresh();notice(t('Presentation status saved. The account continues from this step.','Статус презентации сохранён. Кабинет продолжит с этого шага.'));}catch(error){field.checked=!presented;notice(uiError(error.message));}finally{pending=false;if(field.isConnected)field.disabled=false;}});
 document.addEventListener('change',async e=>{const field=e.target;if(!field.matches('[data-club-membership]'))return;if(pending){field.checked=!field.checked;return;}const member=field.checked;pending=true;field.disabled=true;try{await api('staff/'+(field.dataset.clubMembership==='lead'?'leads':'clients')+'/'+encodeURIComponent(field.dataset.memberId)+'/club-membership','POST',{version:Number(field.dataset.memberVersion),member});await refresh();notice(t('Club membership saved.','Отметка о Клубе сохранена.'));}catch(error){field.checked=!member;notice(uiError(error.message));}finally{pending=false;if(field.isConnected)field.disabled=false;}});
 document.addEventListener('change',e=>{const el=e.target;if(el.id==='today-reply-owner'){replyOwner=el.value;renderReplyQueue();}if(el.name==='financeTier'){setPlanStationCount();}if(el.id==='wf-status'){statusFilter=el.value;clearRecord();render();$('#wf-status').focus();}if(el.id==='wf-owner'){ownerFilter=el.value;clearRecord();render();$('#wf-owner').focus();}if(el.dataset.pick){if(el.checked)checked.add(el.dataset.pick);else checked.delete(el.dataset.pick);render();}if(el.name==='status'&&el.form){const field=el.form.elements.nextContact;field.required=el.value==='callback';if(['not_qualified','do_not_contact'].includes(el.value))field.value='';}});
 document.addEventListener('submit',async e=>{if(!e.target.id.startsWith('central-'))return;e.preventDefault();if(pending)return;const form=e.target,values=Object.fromEntries(new FormData(form)),submit=form.querySelector('[type=submit]');pending=true;submit.disabled=true;try{
  if(form.id==='central-finance-plan')reviewFinancialPlan(values);
  if(form.id==='central-finance-reason')reviewFinanceReason(values);
  if(form.id==='central-manual'){const result=await api('staff/leads','POST',contactPayload(values));leadId=result.id;tab='leads';search='';statusFilter='';ownerFilter='';close();await refresh();notice(t('Lead created.','Заявка создана.'));}
  if(form.id==='central-match'){await api('staff/leads/'+dialogContext.leadId+'/resolve-match','POST',{...values,version:dialogContext.version});close();await refresh();notice(t('Contact match reviewed.','Проверка совпадения сохранена.'));}
  if(form.id==='central-lead-profile'){await api('staff/leads/'+dialogContext.leadId+'/profile','POST',{...contactPayload(values),version:dialogContext.version});close();await refresh();notice(t('Lead details saved.','Данные заявки сохранены.'));}
  if(form.id==='central-contact'){const ctx=dialogContext;await api('staff/'+(ctx.kind==='lead'?'leads':'clients')+'/'+ctx.id+'/contact','POST',{...contactPayload(values),...EcoJourneyUI.payload(values),version:ctx.version});close();await refresh();notice(t('Contact saved.','Результат контакта сохранён.'));}
  if(form.id==='central-handoff'){const h=dialogContext.handoff;await api('staff/handoff','POST',{id:h.id,version:h.version,action:isAdmin()?'cancel':'accept'});close();await refresh();notice(t('Handoff updated.','Передача обновлена.'));}
  if(form.id==='central-assignment'){const handoff=dialogContext.items.some(i=>i.kind==='client');await api('staff/assign','POST',{...values,items:dialogContext.items});checked.clear();close();await refresh();notice(handoff?t('Handoff requested.','Передача клиента запрошена.'):t('Manager assigned.','Менеджер назначен.'));}
  if(form.id==='central-create'){const result=await api('staff/clients','POST',{...contactPayload(values),leadId:editingLead.id,crmVersion:dialogContext.version});selected=result.client.id;tab='clients';close();await refresh();notice(t('Account created. Share the chosen credentials and sign-in link: ','Аккаунт создан. Передайте выбранные доступы и ссылку входа: ')+data.centralBase+'login/');}
  if(form.id==='central-balance'){operation={...operation,amount:EcoFinance.parseAmount(values.amount),reason:values.reason};const next=Math.round((operation.expectedBalance+(operation.kind==='credit'?operation.amount:-operation.amount))*100)/100;dialog(t('Confirm balance change','Подтверждение изменения'),`<dl class="crm-review"><div><dt>${t('Current balance','Текущий баланс')}</dt><dd>${money(operation.expectedBalance)}</dd></div><div><dt>${t('New balance','Новый баланс')}</dt><dd>${money(next)}</dd></div><div><dt>${t('Active plan · unchanged','Активный план · без изменений')}</dt><dd>${money(EcoFinance.summary(account.state).capital)}</dd></div></dl><p translate="no">${esc(operation.reason)}</p><button id="central-confirm" class="crm-button primary">${t('Confirm change','Подтвердить изменение')}</button>`);}
  if(form.id==='central-profile'){await api('staff/clients/'+selected+'/profile','POST',{...values,version:profileVersion});close();await refresh();notice(t('Client details saved.','Данные клиента сохранены.'));}
  if(form.id==='central-reply'){await api('staff/clients/'+selected+'/reply','POST',{...values,version:profileVersion});close();await refresh();notice(t('Reply saved.','Ответ сохранён.'));}
  if(form.id==='central-affiliate'){await api('staff/affiliates','POST',values);close();await refresh();}
 }catch(error){$('#central-error').textContent=uiError(error.message);}finally{pending=false;if(submit.isConnected)submit.disabled=false;}});
 document.addEventListener('ecocharge:locale',()=>{notice('');render();if($('#central-dialog').open)close();});
 setInterval(()=>{if(!document.hidden&&!$('#central-dialog').open&&!pending&&!document.activeElement?.matches('input,textarea,select'))refresh().catch(()=>notice(t('Connection lost. Reload to try again.','Связь потеряна. Обновите страницу.')));},5000);
 refresh().catch(error=>{if(error.status===401)location.assign(new URL(EcoNavigation.login('staff',new URL(location).searchParams,window.EcoLocale?.language),document.baseURI));else notice(uiError(error.message));});

 function research(a){const rows=a.ecosystem?.scenarios||[];return '<section class="crm-panel"><h3>'+t('Saved client scenarios','Сохранённые расчёты клиента')+'</h3>'+(rows.length?rows.map(p=>'<p translate="no">'+esc(p.name)+' · '+money(p.capital)+' · '+p.rate+'% · '+p.stationIds.length+'</p>').join(''):'<p>'+t('No saved scenarios yet.','Сохранённых расчётов пока нет.')+'</p>')+'<p>'+t('Saved stations','Сохранённые станции')+': '+(a.exploration?.saved||[]).map(id=>esc(String(id))).join(', ')+'</p></section>';}
 function requests(a){const rows=a.requests.filter(r=>r.status==='Pending');return rows.length?'<section class="crm-panel"><h3>'+t('Pending requests','Заявки на проверке')+'</h3>'+rows.map(r=>'<article class="central-pending"><div><strong>'+money(r.amount)+'</strong><small>'+t(r.type==='topup'?'Funding request':'Withdrawal request',r.type==='topup'?'Пополнение':'Вывод')+'</small><small translate="no">'+esc(r.id)+'</small></div><div class="wf-actions">'+button(t('Review','Проверить'),'data-payment="'+esc(r.id)+'"',true)+button(t('Decline','Отклонить'),'data-reject-payment="'+esc(r.id)+'"')+'</div></article>').join('')+'</section>':'';}
 function messages(a){return a.tickets.length?`<section class="crm-panel"><h3>${t('Client messages','Сообщения клиента')}</h3>${a.tickets.slice().reverse().map(ticket=>`<article class="central-pending"><div><strong style="font-size:14px" translate="no">${esc(ticket.subject)}</strong><p style="white-space:pre-wrap;overflow-wrap:anywhere" translate="no">${esc(ticket.message)}</p>${ticket.context?`<div class="eco-inquiry-snapshot"><small>${t('Selection when the question was sent','Выбор на момент вопроса')}</small><dl>${EcoWorkspace.rows(ticket.context,window.EcoLocale?.language).map(([label,value])=>`<div><dt>${esc(label)}</dt><dd translate="no">${esc(value)}</dd></div>`).join('')}</dl></div>`:''}<details class="care-crm-thread"><summary>${t('Conversation history','История переписки')} · ${ticket.messages?.length||1}</summary>${(ticket.messages?.length?ticket.messages:[{from:'client',text:ticket.message,date:ticket.date},...(ticket.reply?[{from:'manager',text:ticket.reply,date:ticket.repliedAt||ticket.date}]:[])]).map(m=>`<article><strong>${m.from==='manager'?esc(m.authorName||t('Team','Команда')):t('Client','Клиент')}</strong><time>${esc(m.date)}</time><p style="white-space:pre-wrap;overflow-wrap:anywhere" translate="no">${esc(m.text)}</p></article>`).join('')}</details></div><button class="crm-button outline" data-ticket="${esc(ticket.id)}">${t('Reply','Ответить')}</button></article>`).join('')}</section>`:'';}
 function linkRow(title,url){return `<div class="central-link-row"><h3>${esc(title)}</h3><input aria-label="${esc(title)}" value="${esc(url)}" readonly><button class="crm-button outline" data-copy="${esc(url)}">${t('Copy link','Скопировать ссылку')}</button></div>`;}
 function deliveryMarkup(){const result=deliveryState;if(!result)return '';return '<p>'+t(result.configured?'Configured source: ':'Source not connected. ',result.configured?'Настроенный источник: ':'Источник не подключён. ')+esc(result.source||'')+'</p>'+result.events.map(r=>'<p><strong>'+esc(r.external_id)+'</strong> · '+esc(r.status)+' · '+date(r.received_at)+' · '+t('Attempts: ','Попыток: ')+r.attempts+(r.error_code?' · '+t('Error ','Ошибка ')+r.error_code:'')+'</p>').join('');}
 function links(){let rows='';const partners=[{label:t('Manager link','Ссылка менеджера'),ref:data.me.invite},...data.affiliates];for(const aff of partners){let group='';for(const topic of ['charge','solar','mining']){const u=new URL('participate/'+topic+'/',data.websiteBase);u.searchParams.set('journey','fast');u.searchParams.set('topic',topic);u.searchParams.set('lang','en');u.searchParams.set('utm_source',aff.code?'affiliate':'manager');if(aff.code){u.searchParams.set('aff',aff.code);u.searchParams.set('partner_id',aff.code);}if(aff.ref)u.searchParams.set('ref',aff.ref);group+=linkRow('EcoGrid '+topic[0].toUpperCase()+topic.slice(1),u.href);}rows+='<details class="journey-partner-links"><summary>'+esc(aff.label)+'</summary>'+group+'</details>';}return `<div class="central-title"><div><h1>${t('Two routes. One client history.','Два маршрута. Одна история клиента.')}</h1><p>${t('Project traffic goes to a presentation request. Community traffic goes to the Club or Academy.','Запрос на презентацию ведёт на страницу проекта. Знакомство с сообществом — в Club или Академию.')}</p></div>${data.me.role==='admin'?`<button class="crm-button primary" data-affiliate>${t('Add buyer','Добавить баера')}</button>`:''}</div>${EcoJourneyUI.links(data.websiteBase,data.affiliates)}<section class="crm-panel"><p class="central-note">${t('Buyer → application → assigned manager → client account. Buyer attribution and client ownership are stored separately.','Баер → заявка → ответственный менеджер → клиентский аккаунт. Источник трафика и владелец клиента хранятся отдельно.')}</p>${rows}</section><section class="crm-panel"><h2>${t("External lead deliveries","Внешние заявки")}</h2><p>${t("A source must be connected and verified before traffic is sent.","Источник нужно подключить и проверить перед передачей трафика.")}</p>${button(t("Delivery journal","Журнал доставки"),"data-delivery-journal")}<div id="delivery-journal" role="status">${deliveryMarkup()}</div></section>`;}
 function balance(kind,requestId,corrects){const correction=account.state.adjustments.find(x=>x.operationId===corrects),r=account.state.requests.find(r=>r.id===requestId);operation={id:'OP-'+crypto.randomUUID(),kind,expectedBalance:account.state.balance,version:account.version,requestId:requestId||null,corrects:corrects||null,clientId:selected};dialog(kind==='credit'?t('Credit client balance','Пополнение баланса'):t('Debit client balance','Списание с баланса'),`<form id="central-balance" class="central-form"><label>${t('Amount (USD)','Сумма (USD)')}<input name="amount" type="number" inputmode="decimal" min="0.01" max="10000000" step="0.01" required value="${r?.amount||correction?.amount||''}" ${r||correction?'readonly':''}></label><label>${t('Reason / payment reference','Причина / номер платежа')}<input name="reason" required minlength="3" maxlength="250" value="${esc(r?.id||(corrects?t('Correction: ','Корректировка: ')+corrects:''))}"></label><p class="central-readonly">${t('Sample funds only. This does not charge a card or send a transfer.','Модельный баланс. Карта не списывается, перевод не отправляется.')}</p><button type="submit" class="crm-button primary">${t('Review change','Проверить изменение')}</button></form>`);}
 function profile(){profileVersion=account.version;dialog(t('Edit client details','Данные клиента'),`<form id="central-profile" class="central-form"><label>${t('Client name','Имя клиента')}<input name="name" required minlength="2" maxlength="100" value="${esc(account.client.name)}"></label><label>Email<input name="email" type="email" maxlength="160" value="${esc(account.client.email)}"></label><label>${t('Phone','Телефон')}<input name="phone" type="tel" maxlength="40" value="${esc(account.client.phone)}"></label><label>${t('Staff note','Заметка сотрудника')}<textarea name="note" maxlength="2000">${esc(account.state.client.note)}</textarea></label><button type="submit" class="crm-button primary">${t('Save details','Сохранить данные')}</button></form>`);}
})();
