'use strict';
window.createFinanceUI=function({getAccount,getClient,dialog,close,refresh,notice,button}){
 const {t,esc,money,api}=EcoCentral,$=s=>document.querySelector(s);
 let options,edit,operation,saving=false;
 const date=s=>new Date(s).toLocaleString(window.EcoLocale?.locale||'en-US',{dateStyle:'short',timeStyle:'short'});
 const tierName=name=>window.EcoLocale?.t(name)||name;
 const names=()=>({club_reward:t('Club bonus · preview','Бонус Club · модель'),club_reverse:t('Club bonus reversal','Отмена бонуса Club'),plan:t('Plan changed','Изменение плана'),weekly:t('Sample weekly credit','Модельное начисление'),credit:t('Manual credit','Ручное зачисление'),debit:t('Manual debit','Ручное списание'),topup_approve:t('Sample payment approved','Тестовое пополнение подтверждено'),topup_reject:t('Payment declined','Пополнение отклонено'),withdraw_approve:t('Sample withdrawal approved','Тестовый вывод подтверждён'),withdraw_reject:t('Withdrawal declined','Вывод отклонён')});
 const row=(label,value)=>`<div><dt>${label}</dt><dd translate="no">${value}</dd></div>`;
 function financePanel(a){const s=EcoFinance.summary(a),week=getAccount().nextWeek;return `<section class="crm-panel finance-panel"><div class="wf-card-head"><h3>${t('Plan & funds','План и средства')}</h3><div class="wf-actions">${button(t('Prepare plan','Подготовить план'),'data-finance-draft',true)}${button(t('Change active plan','Изменить активный план'),'data-finance-plan')}</div></div><dl class="wf-facts">${row(t('In active plan','В активном плане'),money(s.capital))}${row(t('Recorded credits','Записанные начисления'),money(s.recorded))}${row(t('Station group','Группа станций'),s.active?esc(tierName(s.active.name))+' · '+s.active.stationIds.length:'—')}${row(t('Weekly model','Модель за неделю'),s.active?money(s.weekly)+' · '+s.active.rate+'% / '+t('calendar month','календарный месяц'):'—')}</dl>${s.draft?`<p>${t('Saved draft','Сохранённый черновик')}: ${money(s.draft.capital)} · ${esc(tierName(s.draft.name))} · ${money(EcoFinance.planWeekly(s.draft))} / ${t('week · model','неделю · модель')}</p>`:''}${getAccount().planDraftNote?`<div class="wf-contact-summary"><span>${t('Last internal plan comment','Последний внутренний комментарий к плану')} · ${date(getAccount().planDraftNote.date)}</span><p translate="no">${esc(getAccount().planDraftNote.comment)}</p></div>`:''}${week?`<p>${t('Next weekly period ends','Следующий недельный период заканчивается')}: ${date(week.periodEnd)}</p>${button(t('Record sample week','Записать модельную неделю'),'data-finance-week '+(Date.parse(week.periodEnd)>Date.now()?'disabled':''))}`:''}<p class="central-readonly">${t('Manual entries and sample payment reviews are not verified payments.','Ручные проводки и тестовые подтверждения не являются проверенными платежами.')}</p></section>`;}
 function financeHistory(a){return `<section class="crm-panel wf-history"><h3>${t('Financial history','Финансовая история')}</h3>${a.adjustments.length?a.adjustments.slice(0,50).map(r=>`<article><div><b>${names()[r.kind]||t('Account adjustment','Корректировка счёта')}</b><time>${date(r.date)}</time></div><small translate="no">${esc(r.actor)} · ${esc(r.operationId||'')}</small><p translate="no">${esc(r.reason)}</p><dl class="wf-facts">${row(t('Balance','Остаток'),money(r.before.balance)+' → '+money(r.after.balance))}${row(t('Active plan','Активный план'),money(r.before.capital)+' → '+money(r.after.capital))}</dl>${r.corrects?`<small translate="no">${t('Corrects','Корректирует')}: ${esc(r.corrects)}</small>`:''}${['credit','debit'].includes(r.kind)&&!r.requestId&&!a.miningPositions?.some(p=>p.status==='active'&&p.id===r.operationId)&&!a.adjustments.some(x=>x.corrects===r.operationId)?button(t('Correct entry','Скорректировать'),'data-correct-entry="'+esc(r.operationId)+'"'):''}${r.periodEnd?`<small>${date(r.periodStart)} — ${date(r.periodEnd)}</small>`:''}</article>`).join(''):`<p>${t('No financial entries yet.','Финансовых записей пока нет.')}</p>`}</section>`;}
 async function editFinancialPlan(mode='active'){
  options??=await api('staff/finance-options');const a=getAccount(),p=mode==='draft'?(a.state.planDraft||a.state.plan):(a.state.plan||a.state.planDraft);
  edit={mode,clientId:getClient(),version:a.version,tier:p?.tierId||'single',ids:new Set(p?.stationIds||[])};
  dialog(mode==='draft'?t('Prepare a discussed plan','Подготовить обсуждённый план'):t('Change client plan','Изменение плана клиента'),`<form id="central-finance-plan" class="central-form"><label>${t('Plan amount (USD)','Сумма в плане (USD)')}<input name="capital" inputmode="decimal" required value="${p?.capital||(mode==='draft'&&a.crm?.callData?.amount>=250?a.crm.callData.amount:250)}" maxlength="20"></label><label>${t('Station group','Группа станций')}<select name="financeTier">${options.tiers.map(v=>`<option value="${v.id}" ${v.id===edit.tier?'selected':''}>${esc(tierName(v.name))} · ${v.count} · ${v.rate}% / ${t('calendar month','календарный месяц')} · ${t('from','от')} ${money(v.minimum)}</option>`).join('')}</select></label><label>${t('Find a station','Найти станцию')}<input type="search" id="finance-search" placeholder="${t('City, name, or ID','Город, название или ID')}"></label><div id="finance-selected" role="status"></div><div id="finance-stations" class="finance-stations"></div><label>${mode==='draft'?t('Internal comment','Внутренний комментарий'):t('Reason for change','Причина изменения')}<textarea name="reason" required minlength="3" maxlength="250" rows="2"></textarea></label><p>${mode==='draft'?t('The client can review and edit this selection. Saving does not activate a plan or move funds.','Клиент сможет посмотреть и изменить подборку. Сохранение не активирует план и не перемещает средства.'):t('Funds move between the balance and the active plan. Previous credits keep their recorded terms.','Средства переносятся между остатком и активным планом. Прошлые начисления сохраняют свои условия.')}</p><button class="crm-button primary" type="submit">${t('Review changes','Проверить изменения')}</button></form>`);
  paintFinanceStations('');
 }
 function setPlanStationCount(){edit.tier=$('[name=financeTier]').value;paintFinanceStations($('#finance-search').value);}
 function paintFinanceStations(query){if(!edit||!$('#finance-stations'))return;const q=query.toLowerCase().trim(),tier=options.tiers.find(t=>t.id===edit.tier);
  const chosen=options.stations.filter(s=>edit.ids.has(s.id)),rest=options.stations.filter(s=>!edit.ids.has(s.id)&&(!q||[s.name,s.city,s.state,s.id,s.country==='CA'?'Canada Канада':'United States США'].join(' ').toLowerCase().includes(q))).slice(0,30);
  $('#finance-selected').textContent=t('Selected: ','Выбрано: ')+edit.ids.size+' / '+tier.count;
  $('#finance-stations').innerHTML=[...chosen,...rest].map(s=>`<label><input type="checkbox" data-finance-station="${s.id}" ${edit.ids.has(s.id)?'checked':''} ${!EcoFinance.stationSelectable(s,getAccount().state.plan)?'disabled':''}><span translate="no">${esc(s.name)}${s.selectionClosed?'<small style="color:#ffb2ab" translate="no">'+t('Enrollment closed','Набор закрыт')+'</small>':''}<small>${esc(s.city)}, ${esc(s.state)} · ${s.id}</small></span></label>`).join('');
 }
 document.addEventListener('change',e=>{if(e.target.dataset.financeStation){const id=Number(e.target.dataset.financeStation);if(e.target.checked)edit.ids.add(id);else edit.ids.delete(id);paintFinanceStations($('#finance-search').value);}});
 function begin(kind,extra={}){operation={id:'FIN-'+crypto.randomUUID(),kind,clientId:getClient(),version:getAccount().version,...extra};}
 function reviewFinancialPlan(v){const capital=EcoFinance.parseAmount(v.capital),tier=options.tiers.find(t=>t.id===v.financeTier),s=EcoFinance.summary(getAccount().state);
  if(!EcoFinance.valid(capital)||!EcoFinance.eligible(capital,tier.id))throw Error(t('Check the tier minimum: $250 / $500 / $800 / from $1,000; maximum $10,000,000.','Проверьте минимум тарифа: $250 / $500 / $800 / от $1 000; максимум $10 000 000.'));
  if(edit.ids.size!==tier.count)throw Error(t('Select exactly ','Выберите ровно ')+tier.count+t(' stations.',' станций.'));
  if(edit.mode==='draft'){
   begin('draft',{clientId:edit.clientId,version:edit.version,plan:{tierId:tier.id,capital,stationIds:[...edit.ids]},reason:v.reason});
   confirm(row(t('Plan amount','Сумма плана'),money(capital))+row(t('Station group','Группа станций'),esc(tierName(tier.name))+' · '+tier.count)+row(t('Weekly model','Модель за неделю'),money(EcoFinance.weekly(capital,tier.rate)))+row(t('Available balance · unchanged','Свободный остаток · без изменений'),money(s.available)));return;
  }
  const next=EcoFinance.round(s.balance+s.capital-capital);if(next<s.reserved)throw Error(t('Not enough available funds for this plan.','Для этого плана недостаточно свободных средств.'));
  begin('plan',{clientId:edit.clientId,version:edit.version,plan:{tierId:tier.id,capital,stationIds:[...edit.ids]},reason:v.reason});
  confirm(`${row(t('Balance','Остаток'),money(s.balance)+' → '+money(next))}${row(t('Active plan','Активный план'),money(s.capital)+' → '+money(capital))}${row(t('Weekly model','Модель за неделю'),money(EcoFinance.weekly(capital,tier.rate)))}${row(t('Station group','Группа станций'),esc(tierName(tier.name))+' · '+tier.count)}`);
 }
 function reasonForm(title,description){dialog(title,`<form id="central-finance-reason" class="central-form">${description}<label>${t('Reason','Основание')}<textarea name="reason" required minlength="3" maxlength="250" rows="3"></textarea></label><button class="crm-button primary" type="submit">${t('Review change','Проверить изменение')}</button></form>`);}
 function reviewWeek(){const w=getAccount().nextWeek;if(!w)return;begin('weekly',{periodStart:w.periodStart});reasonForm(t('Record sample week','Записать модельную неделю'),`<p>${date(w.periodStart)} — ${date(w.periodEnd)}</p><p translate="no">${money(w.capital)} · ${w.rate}% / ${w.ratePeriod===EcoFinance.ratePeriod?t('calendar month · prorated for this period','календарный месяц · по дням периода'):t('week','неделю')} → ${money(w.payout)}</p>`);}
 function reviewRequest(id,decision){const r=getAccount().state.requests.find(v=>v.id===id&&v.status==='Pending');if(!r)return;begin('review',{requestId:id,decision});reasonForm(decision==='approve'?t('Review operation','Проверка операции'):t('Decline request','Отклонить заявку'),`<p>${r.type==='topup'?t('Funding','Пополнение'):t('Withdrawal','Вывод')}: <b>${money(r.amount)}</b></p><p translate="no">${esc(r.id)} · ${esc(r.payment?.method==='crypto'?r.payment.asset+' / '+r.payment.network:r.payment?.method||'—')}</p>${r.type==='topup'&&decision==='approve'?`<p>${t('Check the receiving account before approving. Approval adds this amount to the client balance once.','Проверьте поступление на принимающий счёт. Подтверждение один раз зачислит эту сумму клиенту.')}</p><label class="central-check"><input type="checkbox" name="receiptChecked" required>${t('I checked the receipt for this request.','Я проверил поступление по этой заявке.')}</label>`:''}<p>${t('Model review: no live account or payment provider is connected.','Проверка модели: реальный счёт и платёжный провайдер не подключены.')}</p>`);}
 function reviewFinanceReason(v){operation.reason=v.reason;operation.receiptChecked=v.receiptChecked==='on';const a=getAccount(),s=EcoFinance.summary(a.state),r=a.state.requests.find(v=>v.id===operation.requestId);const delta=operation.kind==='weekly'?a.nextWeek.payout:operation.decision==='reject'?0:r.type==='topup'?r.amount:-r.amount;
  confirm(row(t('Balance','Остаток'),money(s.balance)+' → '+money(EcoFinance.round(s.balance+delta)))+row(t('Active plan · unchanged','Активный план · без изменений'),money(s.capital)));
 }
 function confirm(rows){if(operation.kind==='plan'&&getAccount().state.plan?.status==='active')rows+='<p class="central-readonly">'+t('Changing the active plan closes completed weeks and starts a new seven-day period. Unconfirmed accrual from the unfinished week is not credited.','Изменение активного плана закрывает завершённые недели и запускает новый период на 7 дней. Предварительное начисление незавершённой недели не зачисляется.')+'</p>';dialog(operation.kind==='draft'?t('Save this selection for the client?','Сохранить подборку для клиента?'):t('Confirm financial operation','Подтверждение операции'),`<dl class="crm-review">${rows}</dl><p translate="no">${esc(operation.reason)}</p><button class="crm-button primary" id="central-finance-confirm">${operation.kind==='draft'?t('Save draft','Сохранить черновик'):t('Confirm','Подтвердить')}</button>`);}
 async function saveFinance(b){if(saving||!operation)return;saving=true;b.disabled=true;try{const isDraft=operation.kind==='draft';await api('staff/clients/'+operation.clientId+(isDraft?'/plan-draft':'/finance'),'POST',operation);operation=null;close();await refresh();notice(isDraft?t('Draft saved to the client account.','Черновик сохранён в кабинете клиента.'):t('Financial operation saved.','Финансовая операция сохранена.'));}finally{saving=false;if(b.isConnected)b.disabled=false;}}
 return {financePanel,financeHistory,editFinancialPlan,setPlanStationCount,paintFinanceStations,reviewFinancialPlan,reviewFinanceReason,reviewWeek,reviewRequest,saveFinance};
};
