'use strict';
// The queue is derived from saved requests. There is no second payment state or
// notification ledger; approval by either authorized reviewer removes the item.
window.createFundingInbox=function({onChange,onError,kind='topup'}){
 const {t,esc,money,api}=EcoCentral;let rows=[],loaded=false,busy=false,stopped=false;
 const withdrawal=kind==='withdraw',tab=withdrawal?'withdrawals':'funding',endpoint=withdrawal?'staff/withdrawal-requests':'staff/funding-requests';
 const key=r=>r.clientId+':'+r.id;
 const forClient=id=>rows.find(r=>r.clientId===id);
 const withdrawalText=r=>r?t('Withdrawal requested','Запросил вывод')+' · '+money(r.amount):'';
 function marker(clientId){if(!withdrawal||!clientId)return '';const r=forClient(clientId);return `<small class="wf-withdrawal-label" data-withdrawal-client="${esc(clientId)}" ${r?'':'hidden'}>${esc(withdrawalText(r))}</small>`;}
 function paintRows(root=document){if(!withdrawal)return;root.querySelectorAll('[data-withdrawal-client]').forEach(node=>{const r=forClient(node.dataset.withdrawalClient),text=withdrawalText(r);node.hidden=!r;if(node.textContent!==text)node.textContent=text;node.closest('.wf-list-row')?.classList.toggle('wf-withdrawal-pending',!!r);});}
 const label=r=>r.method==='crypto'?r.asset+' · '+r.network:r.method==='card'?t('Card','Карта'):t('Funding request','Пополнение');
 function banner(){return rows.length?`<div class="funding-alert" role="status"><div><strong>${t('Funding awaiting review','Пополнения ждут проверки')}: ${rows.length}</strong><span>${t('Clients reported sending funds. Check receipt before crediting.','Клиенты сообщили об отправке. Проверьте поступления перед зачислением.')}</span></div><button class="crm-button primary" data-tab="funding">${t('Open requests','Открыть заявки')}</button></div>`:'';}
 function page(){return `<div class="central-title"><div><h1>${t('Funding review','Проверка пополнений')}</h1><p>${t('Client reports are not confirmed receipts. Approve only after checking the receiving account.','Сообщение клиента ещё не подтверждает поступление. Подтверждайте после проверки принимающего счёта.')}</p></div></div><section class="crm-panel funding-queue">${rows.length?rows.map(r=>`<article><div><span class="wf-kicker">${t('CLIENT REPORTED PAYMENT','КЛИЕНТ СООБЩИЛ ОБ ОТПРАВКЕ')}</span><h2 translate="no">${esc(r.clientName)}</h2><p><strong>${money(r.amount)}</strong> · ${esc(label(r))}</p><small translate="no">${new Date(r.date).toLocaleString(window.EcoLocale?.locale||'en-US',{dateStyle:'short',timeStyle:'short'})} · ${esc(r.id)}</small></div><div class="wf-actions"><button class="crm-button primary" data-funding-request="${esc(r.id)}" data-funding-client="${esc(r.clientId)}">${t('Check receipt','Проверить поступление')}</button><button class="crm-button outline" data-client="${esc(r.clientId)}">${t('Client profile','Карточка клиента')}</button></div></article>`).join(''):`<p>${t('No funding requests awaiting review.','Пополнений на проверке нет.')}</p>`}</section>`;}
 const fundingBanner=banner,fundingPage=page;
 function requestBanner(){return withdrawal?(rows.length?`<div class="funding-alert" role="status"><div><strong>${t('Withdrawals awaiting review','Выводы ждут проверки')}: ${rows.length}</strong><span>${t('Requested funds are reserved until approval or rejection.','Суммы заявок зарезервированы до подтверждения или отклонения.')}</span></div><button class="crm-button primary" data-tab="${tab}">${t('Review withdrawals','Проверить выводы')}</button></div>`:''):fundingBanner();}
 function requestPage(){return withdrawal?`<div class="central-title"><div><h1>${t('Withdrawal review','Проверка выводов')}</h1><p>${t('Review the saved requests. Approval records a model withdrawal; no real transfer is sent.','Проверьте сохранённые заявки. Подтверждение записывает модельный вывод; реальный перевод не отправляется.')}</p></div></div><section class="crm-panel funding-queue">${rows.length?rows.map(r=>`<article><div><span class="wf-kicker">${t('FUNDS RESERVED','СРЕДСТВА В РЕЗЕРВЕ')}</span><h2 translate="no">${esc(r.clientName)}</h2><p><strong>${money(r.amount)}</strong></p><small translate="no">${new Date(r.date).toLocaleString(window.EcoLocale?.locale||'en-US',{dateStyle:'short',timeStyle:'short'})} · ${esc(r.id)}</small></div><div class="wf-actions"><button class="crm-button primary" data-funding-request="${esc(r.id)}" data-funding-client="${esc(r.clientId)}">${t('Review withdrawal','Проверить вывод')}</button><button class="crm-button outline" data-client="${esc(r.clientId)}">${t('Client profile','Карточка клиента')}</button></div></article>`).join(''):`<p>${t('No withdrawals awaiting review.','Выводов на проверке нет.')}</p>`}</section>`:fundingPage();}
 async function refresh(){if(busy||stopped||document.hidden)return;busy=true;try{const value=await api(endpoint);if(stopped)return;const old=new Set(rows.map(key)),next=value.requests||[],newCount=loaded?next.filter(r=>!old.has(key(r))).length:0;rows=next;loaded=true;onChange({newCount,count:rows.length});}catch(e){if(!stopped)onError(e);}finally{busy=false;}}
 const timer=setInterval(refresh,5000),visible=()=>{if(!document.hidden)refresh();};document.addEventListener('visibilitychange',visible);
 function stop(){stopped=true;clearInterval(timer);document.removeEventListener('visibilitychange',visible);}
 window.addEventListener('pagehide',stop,{once:true});
 return {refresh,banner:requestBanner,page:requestPage,marker,paintRows,stop,count:()=>rows.length};
};
