'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EcoFunnel=api;})(typeof window==='object'?window:globalThis,()=>{
 const reasons={no_budget:['No available funds','Нет свободных денег'],no_trust:['Needs more trust / evidence','Не доверяет'],unreachable:['Could not reach','Недозвон'],not_fit:['Not a fit','Не целевой'],thinking:['Needs time to consider','Подумает'],do_not_contact:['Asked not to be contacted','Просит не связываться'],other:['Other · explain in comment','Другое · уточнить в комментарии']};
 const outcomes={note:['Note only · no call','Только заметка · без звонка'],no_answer:['Called · no answer','Позвонили · не ответил'],connected:['Called · conversation held','Позвонили · разговор состоялся'],wrong_number:['Called · wrong number','Позвонили · неверный номер']};
 const consentVersion='followup-v1';
 const consentText={sms:'I agree to receive automated follow-up texts from EcoGrid at the number provided about my registration request. Up to 2 messages in the first 24 hours. Message and data rates may apply. Reply STOP to opt out or HELP for help. Consent is optional and is not a condition of purchase.',email:'I agree to receive follow-up emails from EcoGrid about this registration request. This is optional; I can unsubscribe at any time.'};
 const consentTextRu={sms:'Я согласен получать от EcoGrid автоматические SMS по указанному номеру по моей заявке: до 2 сообщений в первые 24 часа. Оператор может взимать плату за сообщения и трафик. Для отказа — ответ STOP, для помощи — HELP. Согласие необязательно и не является условием покупки.',email:'Я согласен получать от EcoGrid письма по этой заявке. Это необязательно; я могу отказаться от таких писем в любое время.'};
 function sla(record,time=Date.now()){const journey=record.context?.journey||record.journey;if(journey?.route==='nurture')return {waiting:false,ageMs:null,minutes:null,overdue:false,fast:false};const start=Date.parse(journey?.consultationAt||record.created),attempt=Date.parse(record.funnel?.firstAttemptAt),ageMs=Number.isFinite(start)?Math.max(0,(Number.isFinite(attempt)?attempt:time)-start):null,waiting=!Number.isFinite(attempt)&&!['not_qualified','do_not_contact'].includes(record.crm?.status)&&!record.duplicateOf&&!record.needsReview;return {waiting,ageMs,minutes:ageMs===null?null:Math.floor(ageMs/60000),overdue:waiting&&ageMs>=900000,fast:Number.isFinite(attempt)&&ageMs<=300000};}
 function queue(rows,time=Date.now()){return rows.map(r=>({...r,sla:sla(r,time)})).filter(r=>r.sla.waiting).sort((a,b)=>(b.sla.ageMs||0)-(a.sla.ageMs||0)||a.id.localeCompare(b.id));}
 function firstWithdrawal(state,time=Date.now()){return (state?.requests||[]).filter(r=>r.type==='withdraw'&&r.status==='Approved'&&r.amount>0&&Number.isFinite(Date.parse(r.reviewedAt))&&Date.parse(r.reviewedAt)<=time).sort((a,b)=>a.reviewedAt.localeCompare(b.reviewedAt)||String(a.id).localeCompare(String(b.id)))[0]||null;}
 const stages=['leads','accounts','connected','qualified','plan_saved','ftd','activated','repeat_deposit','club_invited'];
 function aggregate(rows,group){const result=new Map();for(const r of rows){const key=group==='caller'?r.callerId||'unassigned':group==='landing_caller'?(r.landing||'unknown')+'|'+(r.callerId||'unassigned'):r.landing||'unknown';let g=result.get(key);if(!g){g={key,landing:r.landing||'unknown',callerId:r.callerId||null,...Object.fromEntries(stages.map(k=>[k,0])),ftdCents:0,fundingCents:0,attempted:0,within5:0,totalWaitMs:0,reasons:{}};result.set(key,g);}for(const stage of stages)if(r.stages[stage])g[stage]++;g.ftdCents+=r.ftdCents||0;g.fundingCents+=r.fundingCents||0;if(r.firstAttemptMs!==null&&r.firstAttemptMs!==undefined){g.attempted++;g.within5+=r.firstAttemptMs<=300000?1:0;g.totalWaitMs+=r.firstAttemptMs;}if(r.closeReason)g.reasons[r.closeReason]=(g.reasons[r.closeReason]||0)+1;}
 return [...result.values()].map(g=>({...g,ftdRate:g.leads?g.ftd/g.leads:0,averageFirstCallMinutes:g.attempted?g.totalWaitMs/g.attempted/60000:null})).sort((a,b)=>b.ftd-a.ftd||b.leads-a.leads||a.key.localeCompare(b.key));}
 return {reasons,outcomes,consentVersion,consentText,consentTextRu,sla,queue,firstWithdrawal,stages,aggregate};
});
