'use strict';
window.EcoKnowledge=(()=>{
 const {t,esc:E,api}=EcoCentral;
 const categories={start:['Getting started','Начало работы'],company:['Company & evidence','Компания и источники'],walkthrough:['Account walkthrough','Презентация ЛК'],plans:['Plans & amounts','Планы и суммы'],questions:['Questions & answers','Вопросы и ответы'],payments:['Payments & withdrawals','Платежи и вывод'],handoff:['Client handoff','Передача клиента']};
 const states={draft:['Draft','Черновик'],published:['Published','Опубликовано'],withdrawn:['Withdrawn','Отозвано'],needs_review:['Review terms','Проверить условия']};
 const screens={dashboard:['Overview','Обзор'],map:['Stations','Станции'],tariffs:['My plan','План'],money:['Money','Деньги'],documents:['Documents','Документы'],help:['Help','Помощь'],profile:['Profile','Профиль']};
 let root,actor,rows=[],article=null,query='',category='',status='',editing=null,suggestion='',notice='',busy=false,sequence=0,listSequence=0,language,lastRefresh=0,timer,poller;
 const admin=()=>actor?.role==='admin',L=v=>t(...v),title=a=>t(a.titleEn,a.titleRu),date=v=>v?new Date(v).toLocaleString(window.EcoLocale?.locale||'en-US'):'—';
 const button=(text,attrs='',primary=false)=>`<button type="button" class="crm-button ${primary?'primary':'outline'}" ${attrs}>${text}</button>`;
 const badge=a=>`<span class="kb-badge" data-state="${a.status}">${L(states[a.status])} · v${a.version}</span>`;
 const options=(values,value,all=false)=>`${all?`<option value="">${t('All','Все')}</option>`:''}${Object.entries(values).map(([id,label])=>`<option value="${id}" ${id===value?'selected':''}>${L(label)}</option>`).join('')}`;
 const formFields=[['titleEn','Title · EN-US','Заголовок · EN-US',160],['titleRu','Title · RU','Заголовок · RU',160],['questionEn','Client question · EN-US','Вопрос клиента · EN-US',500],['questionRu','Client question · RU','Вопрос клиента · RU',500],['promptEn','Clarifying question · EN-US','Уточняющий вопрос · EN-US',500],['promptRu','Clarifying question · RU','Уточняющий вопрос · RU',500],['answerEn','Short answer · EN-US','Короткий ответ · EN-US',6000],['explanationRu','Manager notes · RU','Пояснение менеджеру · RU',6000],['nextEn','Next step · EN-US','Следующий шаг · EN-US',1000],['nextRu','Next step · RU','Следующий шаг · RU',1000],['sourceTitle','Source title','Название источника',250],['sourceRef','Source URL or document reference','URL или ссылка на документ',800]];
 function error(e){const labels={
  'Another article is already published for this conversation step.':['Another article is already published for this step. Withdraw it first.','Для этого шага уже опубликована статья. Сначала отзовите её.'],
  'Choose a valid conversation step.':['Choose a valid conversation step.','Выберите допустимый шаг презентации.'],
  'Administrator access required.':['Administrator access required.','Действие доступно только администратору.'],
  'Complete both language versions and the source.':['Complete both language versions and the source.','Заполните обе языковые версии и источник.'],
  'This article changed. Reload it before saving.':['This article changed. Reload it before saving.','Статья уже изменена. Обновите её перед сохранением.'],
  'This article is not currently published. Refresh the knowledge base.':['This article is no longer available. Choose another published answer.','Статья больше недоступна. Выберите другой опубликованный ответ.'],
  'Financial terms changed. Review and save a new draft before publishing.':['Financial terms changed. Review and save a new draft before publishing.','Условия изменились. Проверьте материал и сохраните новый черновик перед публикацией.'],
  'Review the source and both language versions before publishing.':['Review the source and both language versions before publishing.','Проверьте источник и обе языковые версии перед публикацией.'],
  'Use an HTTPS source or an internal document reference.':['Use an HTTPS source or an internal document reference.','Укажите HTTPS-ссылку или название внутреннего документа.'],
  'Enter a withdrawal reason.':['Enter a withdrawal reason.','Укажите причину отзыва.'],
  'Enter a correction between 3 and 2,000 characters.':['Enter a correction between 3 and 2,000 characters.','Укажите предложение от 3 до 2 000 символов.']};
  return labels[e.message]?L(labels[e.message]):e.status===401?t('Session ended. Sign in again.','Сессия завершена. Войдите снова.'):t('Unable to complete the request. Try again.','Не удалось выполнить запрос. Повторите попытку.');
 }
 function header(){return `<div class="kb-heading"><div><span class="kb-eyebrow">EcoGrid / ${t('CALLER DESK','РАБОЧЕЕ МЕСТО КОЛЛЕРА')}</span><h1>${t('Knowledge base','База знаний')}</h1><p>${t('Find the answer. Check the source. Continue the conversation.','Найдите ответ, проверьте источник и продолжите разговор.')}</p></div><div class="kb-admin-actions">${button(t('Guided conversation','Презентация'),'data-tab="guide"')}${admin()?button(t('New article','Новая статья'),'data-kb="new"',true):''}</div></div>`;}
 function shell(){root.innerHTML=`${header()}<div data-kb-helper></div><div class="kb-notice" role="status">${E(notice)}</div><div class="kb-filters"><label>${t('Search RU / EN','Поиск RU / EN')}<input id="kb-search" type="search" maxlength="200" value="${E(query)}" placeholder="${t('A question, amount or screen…','Вопрос, сумма или экран…')}"></label><label>${t('Category','Раздел')}<select id="kb-category">${options(categories,category,true)}</select></label>${admin()?`<label>${t('Status','Статус')}<select id="kb-status">${options(states,status,true)}</select></label>`:''}</div><div class="kb-layout"><nav id="kb-list" aria-label="${t('Knowledge articles','Материалы базы знаний')}"></nav><section id="kb-detail" aria-label="${t('Article details','Содержание статьи')}"></section></div>`;window.EcoKnowledgeHelper?.mount(root.querySelector('[data-kb-helper]'));paintList();paintDetail();}
 function paintList(){if(!root?.isConnected)return;root.querySelector('#kb-list').innerHTML=`<span class="kb-count">${t('Results','Материалов')}: ${rows.length}</span>${rows.length?rows.map(a=>`<button class="kb-row" data-kb-id="${a.id}" aria-pressed="${article?.id===a.id}"><small>${L(categories[a.category])}</small><strong>${E(title(a))}</strong><span>${E(t(a.questionEn,a.questionRu))}</span>${badge(a)}${admin()&&a.hasDraft&&a.status==='published'?`<small>${t('New draft available','Есть новая редакция')}</small>`:''}</button>`).join(''):`<div class="kb-empty"><h2>${t('No matching articles','Материалы не найдены')}</h2><p>${admin()?t('Change the filters or create an article.','Измените фильтры или создайте статью.'):t('Try a different search. Your administrator publishes the materials available here.','Измените запрос. Здесь появятся материалы, опубликованные администратором.')}</p></div>`}`;}
 function source(a){const link=a.sourceRef.startsWith('https://')?`<a href="${E(a.sourceRef)}" target="_blank" rel="noopener noreferrer">${E(a.sourceRef)} ↗</a>`:E(a.sourceRef);return `<section class="kb-source"><h3>${t('Source','Источник')}</h3><strong>${E(a.sourceTitle)}</strong><p>${link}</p><small>${t('Reviewed','Проверено')}: ${date(a.reviewedAt)} · ${E(a.author)} · v${a.version}</small></section>`;}
 function editForm(){return `<form id="kb-edit" class="kb-editor"><div class="kb-detail-top"><h2>${editing.id?t('Edit draft','Редактировать черновик'):t('New article','Новая статья')}</h2>${button(t('Cancel','Отмена'),'data-kb="cancel"')}</div><div class="kb-form-grid"><label>${t('Category','Раздел')}<select name="category">${options(categories,editing.content.category)}</select></label><label>${t('Account screen','Экран ЛК')}<select name="screen">${options(screens,editing.content.screen)}</select></label><label>${t('Scope','Область применения')}<select name="scope"><option value="demo" ${editing.content.scope==='demo'?'selected':''}>${t('Calculation model','Расчётная модель')}</option><option value="product" ${editing.content.scope==='product'?'selected':''}>${t('Product','Продукт')}</option></select></label><label class="kb-check"><input type="checkbox" name="dependsOnTerms" ${editing.content.dependsOnTerms?'checked':''}>${t('Depends on financial terms','Зависит от финансовых условий')}</label><label>${t('Conversation step','Шаг презентации')}<select name="journeyStep"><option value="">${t('Not part of the guide','Вне сценария')}</option>${Object.entries({entry_new:['First visit','Первый вход'],entry_draft:['Saved option','Обсуждённый вариант'],stations:['Station','Станция'],compare:['Comparison','Сравнение'],terms:['Conditions','Условия'],funding:['Funding','Пополнение'],activation:['Activation','Активация'],next_contact:['Next contact','Следующий контакт']}).map(([key,label])=>`<option value="${key}" ${editing.content.journeyStep===key?'selected':''}>${L(label)}</option>`).join('')}</select></label>${formFields.map(([key,en,ru,max])=>`<label class="${max>500?'kb-wide':''}">${t(en,ru)}${max>500?`<textarea name="${key}" required maxlength="${max}" rows="${max>1000?5:3}">${E(editing.content[key]||'')}</textarea>`:`<input name="${key}" required maxlength="${max}" value="${E(editing.content[key]||'')}">`}</label>`).join('')}</div><div class="kb-form-actions"><button type="submit" class="crm-button primary" ${busy?'disabled':''}>${t('Save draft','Сохранить черновик')}</button><span>${t('Publishing is a separate step.','Публикация — отдельное действие.')}</span></div></form>`;}
 function paintDetail(){if(!root?.isConnected)return;const host=root.querySelector('#kb-detail');if(editing){host.innerHTML=editForm();return;}const a=article;
  if(!a?.titleEn){host.innerHTML=`<div class="kb-empty kb-welcome"><span>↗</span><h2>${t('One answer, with its source.','Ответ вместе с источником.')}</h2><p>${t('Choose an article to see the wording, account screen and next step.','Выберите материал: реплика, экран кабинета и следующий шаг.')}</p></div>`;return;}
  const params=EcoNavigation.context('client',new URLSearchParams({tab:a.screen}),window.EcoLocale?.language);if(window.EcoSandbox?.clientId)params.set('client',window.EcoSandbox.clientId);
  const route=window.EcoSandbox?new URL('client/?'+params,document.baseURI).href:EcoNavigation.destination('client',params,window.EcoLocale?.language);
  host.innerHTML=`<article class="kb-article"><div class="kb-detail-top">${badge(a)}<small>${L(categories[a.category])}</small></div><h2>${E(title(a))}</h2>${admin()&&a.hasDraft&&a.publishedVersion?`<p class="kb-warning">${t('You are reading the draft. Managers see published version','Вы читаете черновик. Менеджеры видят опубликованную версию')} ${a.publishedVersion}.</p>`:''}${a.status==='needs_review'?`<p class="kb-warning">${t('Financial terms changed. This answer is hidden from managers until reviewed and republished.','Финансовые условия изменились. Ответ скрыт от менеджеров до проверки и повторной публикации.')}</p>`:''}<p class="kb-question">${E(t(a.questionEn,a.questionRu))}</p><section class="kb-prompt"><h3>${t('Ask first','Сначала уточните')}</h3><p>${E(t(a.promptEn,a.promptRu))}</p></section><section class="kb-answer"><div><h3>${t('Say · EN-US','Реплика · EN-US')}</h3>${button(t('Copy answer','Копировать ответ'),'data-kb="copy"')}</div><p lang="en-US">${E(a.answerEn)}</p></section><details ${window.EcoLocale?.allowRussian===false?'hidden':''} class="kb-explanation" ${window.EcoLocale?.language==='ru'?'open':''}><summary>${t('Manager notes · RU','Пояснение менеджеру · RU')}</summary><p lang="ru">${E(a.explanationRu)}</p></details><section class="kb-next"><h3>${t('Next step','Следующий шаг')}</h3><p>${E(t(a.nextEn,a.nextRu))}</p><a class="crm-button outline" href="${E(route)}" target="_blank" rel="noopener">${t('Account screen','Экран ЛК')}: ${L(screens[a.screen])} ↗</a><small>${t('Opens the signed-in client account or the sign-in screen.','Откроется текущий клиентский аккаунт или страница входа.')}</small></section>${source(a)}<p class="kb-scope">${t('Scope','Область применения')}: ${a.scope==='demo'?t('Calculation model','Расчётная модель'):t('Product','Продукт')}</p>${admin()?adminTools(a):`<form id="kb-suggest"><label>${t('Suggest a correction','Предложить исправление')}<textarea name="text" required minlength="3" maxlength="2000" rows="3">${E(suggestion)}</textarea></label><button class="crm-button outline" type="submit">${t('Send to administrator','Передать администратору')}</button></form>`}</article>`;
 }
 function adminTools(a){return `<div class="kb-admin-actions">${button(t('Edit draft','Редактировать черновик'),'data-kb="edit"')}${button(t('Review & publish','Проверить и опубликовать'),'data-kb="review"',true)}${['published','needs_review'].includes(a.status)?button(t('Withdraw article','Отозвать статью'),'data-kb="withdraw"'):''}</div><div id="kb-action"></div><details class="kb-history"><summary>${t('Version history','История версий')} · ${a.history.length}</summary>${a.history.map(v=>`<button type="button" data-kb-version="${v.version}">v${v.version} · ${E(v.author)} · ${date(v.created)} ↗</button>`).join('')}<div id="kb-history-content"></div></details><section class="kb-suggestions"><h3>${t('Suggested corrections','Предложения исправлений')} · ${a.suggestions.length}</h3>${a.suggestions.map(s=>`<article><small>${E(s.author)} · v${s.version} · ${date(s.created)}</small><p>${E(s.text)}</p></article>`).join('')||`<p>${t('No suggestions yet.','Предложений пока нет.')}</p>`}</section>`;}
 function setNotice(value){notice=value;const el=root?.querySelector('.kb-notice');if(el)el.textContent=value;}
 async function loadList(){const key=++listSequence;try{const data=await api('staff/knowledge?'+new URLSearchParams({q:query,category,status}));if(key!==listSequence||!root?.isConnected)return;rows=data.articles.sort((a,b)=>{const rank=x=>Number(x.titleRu?.match(/^\d{2}/)?.[0])||100;return rank(a)-rank(b)||title(a).localeCompare(title(b));});lastRefresh=Date.now();paintList();}catch(e){if(key===listSequence)setNotice(error(e));}}
 async function select(id){const key=++sequence;editing=null;article=null;suggestion='';paintDetail();try{const result=await api('staff/knowledge/'+id);if(key!==sequence||!root?.isConnected)return;article=result;paintList();paintDetail();if(innerWidth<850)root.querySelector('#kb-detail').scrollIntoView({behavior:'instant',block:'start'});}catch(e){if(key===sequence){setNotice(error(e));paintDetail();await loadList();}}}
 async function refreshArticle(){if(!article||editing)return;const id=article.id,key=++sequence;try{const result=await api('staff/knowledge/'+id);if(key!==sequence||!root?.isConnected)return;if(result.revision!==article.revision||result.status!==article.status||JSON.stringify(result.suggestions)!==JSON.stringify(article.suggestions)){article=result;paintDetail();}}catch(e){if(key!==sequence)return;if([403,404,410].includes(e.status)){article=null;paintDetail();}setNotice(error(e));}}
 async function click(e){const b=e.target.closest('button');if(!b||busy)return;const action=b.dataset.kb;
  if(b.dataset.kbId){await select(b.dataset.kbId);return;}
  try{
   if(action==='new'){++sequence;editing={content:{category:'start',screen:'dashboard',scope:'demo',dependsOnTerms:false}};paintDetail();root.querySelector('#kb-detail').scrollIntoView({behavior:'instant'});}
   if(action==='edit'){editing={id:article.id,revision:article.revision,content:{...article}};paintDetail();}
   if(action==='cancel'){editing=null;paintDetail();}
   if(action==='copy'){const current=await api('staff/knowledge/'+article.id);if(current.version!==article.version||current.status==='needs_review'||!admin()&&current.status!=='published'){article=current;paintDetail();throw Error('This article changed. Reload it before saving.');}await navigator.clipboard.writeText(current.answerEn);setNotice(t('Answer copied.','Ответ скопирован.'));}
   if(action==='review')root.querySelector('#kb-action').innerHTML=`<form id="kb-publish"><p>${t('Publish draft version','Опубликовать черновик версии')} ${article.version}?</p><label class="kb-check"><input type="checkbox" name="reviewed" required>${t('I checked the source, terms and both language versions.','Источник, условия и обе языковые версии проверены.')}</label><button type="submit" class="crm-button primary">${t('Publish this version','Опубликовать эту версию')}</button></form>`;
   if(action==='withdraw')root.querySelector('#kb-action').innerHTML=`<form id="kb-withdraw"><label>${t('Reason for withdrawal','Причина отзыва')}<textarea name="reason" required minlength="3" maxlength="1000" rows="3"></textarea></label><button type="submit" class="crm-button outline">${t('Confirm withdrawal','Подтвердить отзыв')}</button></form>`;
   if(b.dataset.kbVersion){const v=await api('staff/knowledge/'+article.id+'/versions/'+b.dataset.kbVersion);root.querySelector('#kb-history-content').innerHTML=`<h3>${t('Archived version','Архивная версия')} ${v.version}</h3><p>${E(v.content.answerEn)}</p><p>${E(v.content.explanationRu)}</p><small>${E(v.content.sourceTitle)} · ${E(v.content.sourceRef)}</small>`;}
  }catch(e){if(e.status===410){article=null;paintDetail();await loadList();}setNotice(error(e));}
 }
 async function submit(e){if(!e.target.id.startsWith('kb-'))return;e.preventDefault();if(busy)return;busy=true;const form=e.target,values=Object.fromEntries(new FormData(form)),submit=form.querySelector('[type=submit]');submit.disabled=true;
  try{
   if(form.id==='kb-edit'){article=await api('staff/knowledge'+(editing.id?'/'+editing.id:''),editing.id?'PUT':'POST',{revision:editing.revision,content:editing.content});editing=null;setNotice(t('Draft saved.','Черновик сохранён.'));}
   if(form.id==='kb-publish'){article=await api('staff/knowledge/'+article.id+'/publish','POST',{revision:article.revision,reviewed:values.reviewed==='on'});setNotice(t('Version published. Managers can now read it.','Версия опубликована и доступна менеджерам.'));}
   if(form.id==='kb-withdraw'){article=await api('staff/knowledge/'+article.id+'/withdraw','POST',{revision:article.revision,reason:values.reason});setNotice(t('Article withdrawn from manager access.','Статья отозвана из доступа менеджеров.'));}
   if(form.id==='kb-suggest'){await api('staff/knowledge/'+article.id+'/suggest','POST',{version:article.version,text:values.text});suggestion='';setNotice(t('Correction sent to the administrator.','Предложение передано администратору.'));}
   paintDetail();await loadList();
  }catch(e){if(e.status===410){article=null;paintDetail();await loadList();}setNotice(error(e));}finally{busy=false;if(submit.isConnected)submit.disabled=false;}
 }
 function input(e){const el=e.target;if(el.id==='kb-search'){query=el.value;clearTimeout(timer);timer=setTimeout(loadList,200);}if(editing&&el.form?.id==='kb-edit')editing.content[el.name]=el.type==='checkbox'?el.checked:el.value;if(el.form?.id==='kb-suggest')suggestion=el.value;}
 function change(e){input(e);if(e.target.id==='kb-category'){category=e.target.value;loadList();}if(e.target.id==='kb-status'){status=e.target.value;loadList();}}
 return {
  open(id){article={id};editing=null;},
  mount(host,user){actor=user;const lang=window.EcoLocale?.language;
   if(!root||!root.isConnected||root.parentElement!==host){host.innerHTML='<div id="kb-root" translate="no"></div>';root=host.firstElementChild;root.addEventListener('click',click);root.addEventListener('submit',submit);root.addEventListener('input',input);root.addEventListener('change',change);language=lang;shell();loadList();if(article)refreshArticle();clearInterval(poller);poller=setInterval(()=>{if(document.hidden||editing||busy||!root?.isConnected||root.querySelector('#kb-action form'))return;refreshArticle();if(!document.activeElement?.matches('#kb-root input,#kb-root textarea,#kb-root select'))loadList();},5000);}
   else if(language!==lang){language=lang;notice='';shell();}

  },
  unmount(){if(root){++sequence;++listSequence;clearTimeout(timer);clearInterval(poller);root=null;}}
 };
})();
