'use strict';
window.EcoKnowledgeHelper=(()=>{
 const {t,esc:E,api}=EcoCentral;
 let host,busy=false,generation=0,sources=[],poller;
 function mount(root){const token=++generation;host=root;sources=[];clearInterval(poller);poller=setInterval(async()=>{if(!host?.isConnected){clearInterval(poller);return;}if(document.hidden||busy||!sources.length)return;const checked=await Promise.all(sources.map(async a=>{try{const v=await api('staff/knowledge/'+a.id);return v.status==='published'&&v.version===a.version;}catch{return false;}}));if(generation!==token)return;if(checked.some(valid=>!valid)){sources=[];host.querySelector('.kb-helper-result').textContent=t('Sources changed or could not be verified. Search again.','Источники изменились или недоступны. Повторите поиск.');}},5000);host.innerHTML=`<details class="kb-helper"><summary>${t('Find an answer with its source','Найти ответ с источником')}</summary><p>${t('Published knowledge only. External AI is not connected. Ask a general product question without client details.','Только опубликованная база. Внешний AI не подключён. Задайте общий вопрос о продукте без данных клиента.')}</p><form><label>${t('Product question','Вопрос о продукте')}<input name="query" minlength="3" maxlength="300" required autocomplete="off"></label><button class="crm-button outline" type="submit">${t('Find sources','Найти источники')}</button></form><div class="kb-helper-result" role="status"></div></details>`;
 host.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;const button=e.target.querySelector('button'),result=host.querySelector('.kb-helper-result');button.disabled=true;result.textContent=t('Checking published sources…','Проверяем опубликованные материалы…');try{const data=await api('staff/knowledge-helper','POST',{query:e.target.elements.query.value,language:window.EcoLocale?.language||'en'});if(generation!==token||!host.isConnected)return;sources=data.sources;result.innerHTML=data.sources.length?data.sources.map(a=>`<article><strong>${E(a.title)} · v${a.version}</strong><p>${E(a.answer)}</p><small>${E(a.sourceTitle)} · ${E(a.sourceRef)}</small><button type="button" class="crm-button outline" data-knowledge-article="${E(a.id)}">${t('Open published article','Открыть опубликованную статью')}</button></article>`).join(''):`<p>${t('No published answer found. Ask the administrator to review the topic.','Опубликованный ответ не найден. Передайте тему администратору на проверку.')}</p>`;if(data.unavailable)result.insertAdjacentHTML('afterbegin',`<p>${t('AI unavailable. Showing published sources.','AI недоступен. Показаны опубликованные источники.')}</p>`);}catch(err){result.textContent=err.status===429?t('Question limit reached. Retry in a minute.','Лимит вопросов. Повторите через минуту.'):err.status===400?t('Use a general question without personal details.','Задайте общий вопрос без персональных данных.'):t('Could not load sources. Your question is kept; try again.','Не удалось загрузить источники. Вопрос сохранён; повторите попытку.');}finally{busy=false;if(button.isConnected)button.disabled=false;}});
 }
 return {mount};
})();
