'use strict';
(()=>{
 const t=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en;
 const items=window.ECOGRID_AVATARS||[],key=()=> 'ecogrid-avatar-v1:'+(window.ECO_PLATFORM_CONFIG?.clientPreview?'preview':window.ECO_SHARED_CONTEXT?.client?.id||'local');
 const english=['Spark','Volt','Helio','Byte','Orbit','Leaf','Fox','Cat','Panda','Owl','Raccoon','Red panda','Penguin','Bear','Tiger','Koala','Nova','Alex','Maya','Kai','Luna','Leo','Ada','Max'];
 let draft=null,category='all',generation=0;
 const valid=v=>v&&((items.some(x=>x.id===v.id))||(v.id==='custom'&&typeof v.src==='string'&&/^data:image\/jpeg;base64,[A-Za-z0-9+/]+={0,2}$/.test(v.src)&&v.src.length<700000));
 function saved(){try{const v=JSON.parse(localStorage.getItem(key())||'null');if(valid(v))return v;}catch{}return {id:'01-spark'};}
 const source=v=>v.id==='custom'?v.src:(items.find(i=>i.id===v.id)||items[0]).large;
 const image=()=>'<img data-profile-avatar src="'+source(saved())+'" width="56" height="56" alt="'+t('Profile avatar','Аватар профиля')+'">';
 const control=()=>'<button class="eg-avatar eg-avatar-edit" data-avatar-open aria-label="'+t('Choose profile image','Выбрать изображение профиля')+'">'+image()+'<span aria-hidden="true">'+window.EcoBrandIcons.nav('profile')+'</span></button>';
 function paint(){const root=document.querySelector('[data-avatar-picker]');if(!root)return;root.querySelector('[data-avatar-preview]').src=source(draft);root.querySelector('[data-avatar-grid]').innerHTML=items.map((item,index)=>({item,index})).filter(({item})=>category==='all'||item.group===category).map(({item,index})=>'<button type="button" class="eg-avatar-option" data-avatar-id="'+item.id+'" aria-pressed="'+(draft.id===item.id)+'"><img src="'+item.file+'" width="64" height="64" alt="" loading="lazy"><span>'+t(english[index],item.name)+'</span></button>').join('');root.querySelectorAll('[data-avatar-category]').forEach(b=>b.setAttribute('aria-pressed',String(category===b.dataset.avatarCategory)));}
 function open(){draft=saved();category='all';generation++;openModal('<section data-avatar-picker><div class="eg-avatar-intro"><img data-avatar-preview src="'+source(draft)+'" width="80" height="80" alt=""><div><h2>'+t('Make it yours','Ваш образ')+'</h2><p>'+t('Choose a character or add your photo.','Выберите персонажа или добавьте своё фото.')+'</p></div></div><div class="eg-avatar-tools"><label class="eco-button secondary" for="eg-avatar-upload">'+t('Upload photo','Загрузить фото')+'</label><input id="eg-avatar-upload" type="file" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG, WebP · '+t('up to 5 MB','до 5 МБ')+'</small></div><nav class="eg-avatar-categories" aria-label="'+t('Avatar categories','Категории аватаров')+'">'+[['all','All','Все'],['Роботы','Robots','Роботы'],['Звери','Animals','Звери'],['Люди','People','Люди']].map(([id,en,ru])=>'<button type="button" data-avatar-category="'+id+'">'+t(en,ru)+'</button>').join('')+'</nav><div data-avatar-grid class="eg-avatar-grid"></div><p class="eg-avatar-error" role="status" aria-live="polite"></p><div class="eg-avatar-footer"><small>'+t('Saved on this device.','Сохраняется на этом устройстве.')+'</small><button type="button" class="eco-button" data-avatar-save>'+t('Save avatar','Сохранить аватар')+'</button></div></section>');paint();}
 function feedback(message){const el=document.querySelector('.eg-avatar-error');if(el)el.textContent=message;}
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-avatar-open'))open();if(b.dataset.avatarCategory){category=b.dataset.avatarCategory;paint();}if(b.dataset.avatarId){generation++;feedback('');draft={id:b.dataset.avatarId};paint();}if(b.hasAttribute('data-avatar-save')){try{localStorage.setItem(key(),JSON.stringify(draft));document.querySelector('#modal').close();document.querySelectorAll('[data-profile-avatar]').forEach(img=>img.src=source(draft));toast(t('Avatar saved','Аватар сохранён'));}catch{feedback(t('Could not save. Try a smaller image or allow browser storage.','Не удалось сохранить. Попробуйте фото меньшего размера или разрешите хранение данных в браузере.'));}}});
 document.addEventListener('change',e=>{if(e.target.id!=='eg-avatar-upload')return;const file=e.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){feedback(t('Use a JPG, PNG or WebP image under 5 MB.','Выберите JPG, PNG или WebP размером до 5 МБ.'));e.target.value='';return;}const token=++generation,reader=new FileReader();feedback(t('Preparing photo…','Готовим фото…'));reader.onerror=()=>feedback(t('Could not read this photo. Try another file.','Не удалось прочитать фото. Выберите другой файл.'));reader.onload=()=>{const img=new Image();img.onerror=()=>feedback(t('Could not open this image. Try another photo.','Не удалось открыть изображение. Выберите другое фото.'));img.onload=()=>{if(token!==generation||!document.querySelector('[data-avatar-picker]'))return;const canvas=document.createElement('canvas');canvas.width=canvas.height=320;const context=canvas.getContext('2d'),side=Math.min(img.naturalWidth,img.naturalHeight);context.fillStyle='#eceee8';context.fillRect(0,0,320,320);context.drawImage(img,(img.naturalWidth-side)/2,(img.naturalHeight-side)/2,side,side,0,0,320,320);draft={id:'custom',src:canvas.toDataURL('image/jpeg',.85)};paint();feedback(t('Photo is ready. Save to apply it.','Фото готово. Сохраните, чтобы применить.'));};img.src=reader.result;};reader.readAsDataURL(file);});
 window.EcoProfileAvatar={image,control};
})();
