'use strict';
// Shared-account withdrawal presentation. All reservations and decisions stay server-owned.
if(window.ECO_SHARED_CONTEXT)window.EcoWithdrawalUI=(()=>{
 const t=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en,E=escapeHtml;
 const money=n=>new Intl.NumberFormat(window.EcoLocale?.locale||'en-US',{style:'currency',currency:'USD'}).format(n);
 const $=s=>document.querySelector(s),now=()=>window.EcoClientAccount?.now()??Date.now();
 let draft=null,busy=false,timer=null;
 const selectedZone=()=>window.EcoProfileModel?.selectedZone(demo.ecosystem?.timezone)||'';
 function zone(){return selectedZone()||'UTC';}
 function zoneLabel(){const id=selectedZone(),z=window.EcoProfileModel?.timeZones.find(x=>x.id===id);return z?E(t(z.en,z.ru)):'<button type="button" class="eco-text" data-withdraw-zone>'+t('Choose a US or Canadian time zone','Выбрать часовой пояс США или Канады')+'</button>';}
 function date(v){if(!selectedZone())return t('Choose your time zone in Profile to see the local time.','Выберите часовой пояс в профиле, чтобы увидеть местное время.');const d=new Date(v);if(!Number.isFinite(d.getTime()))return t('Not scheduled','Дата не задана');return new Intl.DateTimeFormat(window.EcoLocale?.locale||'en-US',{month:'short',day:'numeric',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:zone(),timeZoneName:'short'}).format(d);}
 const state=()=>EcoWithdrawals.state(demo,now());
 const pending=()=>demo.requests.find(r=>r.type==='withdraw'&&r.status==='Pending');
 function message(s){return ({activate:t('Your first request becomes available 4 days after plan activation.','Первую заявку можно подать через 4 суток после активации плана.'),pending:t('Your request is under review. The amount stays reserved until a decision.','Заявка на проверке. Сумма остаётся в резерве до решения.'),waiting:t('Your next request opens at the time shown below.','Следующую заявку можно отправить в указанное ниже время.'),balance:t('The waiting period has ended. At least $1 of available balance is required.','Срок ожидания завершён. Для заявки нужен свободный остаток от 1 USD.'),ready:t('You can request an amount from your available balance.','Можно отправить заявку в пределах свободного остатка.')})[s.reason];}
 function timing(s){return s.reason==='waiting'?`<time datetime="${new Date(s.eligibleAt).toISOString()}">${E(date(s.eligibleAt))}</time>`:'';}
 function calendarBody(){const s=state(),week=window.ECO_SHARED_CONTEXT.nextWeek,r=pending();const ended=week&&Date.parse(week.periodEnd)<=now();
  return `<div class="eco-section-title"><div><span class="eco-kicker">${t('ACCOUNT CALENDAR','КАЛЕНДАРЬ СЧЁТА')}</span><h2>${t('Two separate schedules.','Два отдельных расписания.')}</h2></div><span class="cashflow-zone">${zoneLabel()}</span></div><div class="cashflow-events"><article><span class="cashflow-type">${t('Weekly model credit · every 7 days','Модельное начисление · каждые 7 суток')}</span><strong>${week?money(week.payout):'—'}</strong><p>${week?(ended?t('Period ended · awaiting recorded credit','Период завершён · ожидаем записи начисления'):t('Current period ends','Текущий период заканчивается')):t('The first period starts when a plan is activated.','Первый период начинается при активации плана.')}</p>${week?`<time datetime="${E(week.periodEnd)}">${E(date(week.periodEnd))}</time>`:''}<small>${t('Only a recorded credit becomes part of your available balance.','В свободный остаток входит только записанное начисление.')}</small></article><article data-withdrawal-reason="${s.reason}"><span class="cashflow-type">${t('Withdrawal request · 4-day interval','Заявка на вывод · интервал 4 суток')}</span><strong>${s.reason==='pending'?t('Under review','На проверке'):s.canRequest?t('Available now','Доступна сейчас'):s.reason==='waiting'?t('Opens next','Следующая дата'):s.reason==='activate'?t('After activation','После активации'):t('Balance required','Нужен остаток')}</strong><p>${message(s)}</p>${timing(s)}${r?`<small>${t('Reserved','В резерве')}: ${money(r.amount)}</small>`:''}<button type="button" class="eco-text" data-action="withdraw">${r?t('View request','Открыть заявку'):s.canRequest?t('Request withdrawal','Запросить вывод'):t('View details','Посмотреть условия')} →</button></article></div>`;
 }
 function calendar(){return `<section class="eco-card cashflow-calendar" data-cashflow-calendar translate="no">${calendarBody()}</section>`;}
 const isOpen=()=>!!($('#modal')?.open&&$('#withdrawal-request-form'));
 function open(){if(busy)return;const r=pending();if(r){showPaymentReceipt(r.id);return;}const s=state();if(!draft||demo.requests.some(r=>r.id===draft.id))draft={id:'WDR-'+crypto.randomUUID(),raw:s.available>=1?String(Math.min(250,s.available)):''};
  openModal(`<section class="withdrawal-checkout" translate="no"><h2>${t('Request a withdrawal','Заявка на вывод')}</h2><div class="withdrawal-funds"><span>${t('Available balance','Свободный остаток')}</span><strong data-withdraw-available>${money(s.available)}</strong><dl><div><dt>${t('In active plan','В активном плане')}</dt><dd data-withdraw-capital>${money(EcoFinance.summary(demo).capital)}</dd></div><div><dt>${t('Already reserved','Уже в резерве')}</dt><dd data-withdraw-reserved>${money(s.reserved)}</dd></div></dl><small>${t('Plan capital and the open model period are not included.','Капитал плана и незавершённый модельный период сюда не входят.')}</small></div><div class="withdrawal-window" data-withdraw-window role="status"></div><button type="button" class="text-button" data-withdraw-current hidden>${t('Open the pending request','Открыть заявку на проверке')} →</button><form id="withdrawal-request-form" novalidate><label for="withdrawal-amount">${t('Amount, USD','Сумма, USD')}</label><div class="withdrawal-input"><input id="withdrawal-amount" type="text" inputmode="decimal" autocomplete="off" maxlength="20" value="${E(draft.raw)}" aria-describedby="withdrawal-limits withdrawal-error"><button type="button" data-withdraw-max>${t('Maximum','Максимум')}</button></div><small id="withdrawal-limits">${t('Minimum $1 · maximum $100,000 per request.','От 1 до 100 000 USD за одну заявку.')}</small><div class="withdrawal-preview"><span>${t('Available after reservation','Свободно после резервирования')}</span><b data-withdraw-after>—</b></div><p id="withdrawal-error" class="form-error" role="alert"></p><button type="submit" class="button primary" data-withdraw-submit>${t('Send request','Отправить заявку')}</button></form><div class="withdrawal-rules"><h3>${t('When you can request a withdrawal','Когда можно подать заявку')}</h3><ul><li>${t('First request: 4 days after your plan is activated.','Первая заявка — через 4 суток после активации плана.')}</li><li>${t('Next request: 4 days after your previous request is approved.','Следующая заявка — через 4 суток после одобрения предыдущей.')}</li><li>${t('If a request is declined, its amount becomes available again. The 4-day wait does not restart.','Если заявку отклонили, её сумма снова доступна. Отсчитывать 4 суток заново не нужно.')}</li></ul><small>${t('Your request is saved for review. Real transfers are not connected yet.','Заявка сохраняется для проверки. Реальные переводы пока не подключены.')}</small></div></section>`);refresh();$('#withdrawal-amount')?.focus();
 }
 function refresh(){stop();const calendars=[...document.querySelectorAll('[data-cashflow-calendar]')].filter(el=>!el.closest?.('[hidden]'));for(const el of calendars){const html=calendarBody();if(el._cashflowMarkup!==html){el.innerHTML=html;el._cashflowMarkup=html;}}
  if(isOpen()){const s=state(),input=$('#withdrawal-amount'),amount=EcoFinance.parseAmount(input.value),max=Math.min(EcoFinance.paymentMaximum,s.available),valid=Number.isFinite(amount)&&amount>=EcoFinance.paymentMinimum&&amount<=max;
   $('[data-withdraw-available]').textContent=money(s.available);$('[data-withdraw-reserved]').textContent=money(s.reserved);$('[data-withdraw-capital]').textContent=money(EcoFinance.summary(demo).capital);$('[data-withdraw-window]').innerHTML=`<strong>${message(s)}</strong>${timing(s)}<small>${zoneLabel()}</small>`;
   $('[data-withdraw-current]').hidden=!s.pending;input.disabled=busy||!!s.pending;input.setAttribute('aria-invalid',String(!!input.value&&!valid));$('[data-withdraw-max]').disabled=busy||!!s.pending||max<1;
   $('#withdrawal-error').textContent=input.value&&!valid?(Number.isFinite(amount)&&amount>max?t('Enter no more than ','Введите не больше ')+money(max)+'.':t('Enter at least $1, with up to two decimal places.','Введите от 1 USD, не более двух знаков после запятой.')):'';
   $('[data-withdraw-after]').textContent=valid?money(EcoFinance.round(s.available-amount)):'—';$('[data-withdraw-submit]').disabled=busy||!s.canRequest||!valid;$('[data-withdraw-submit]').textContent=busy?t('Saving request…','Сохраняем заявку…'):t('Send request','Отправить заявку');
  }
  if(document.hidden)return;const at=state().eligibleAt;if((isOpen()||calendars.length)&&at!==null&&at>now())timer=setTimeout(refresh,Math.min(60000,Math.max(50,at-now()+30)));
 }
 function stop(){clearTimeout(timer);timer=null;}
 async function submit(e){if(e.target.id!=='withdrawal-request-form')return;e.preventDefault();if(busy)return;const s=state(),amount=EcoFinance.parseAmount($('#withdrawal-amount').value);if(!s.canRequest||!Number.isFinite(amount)||amount<1||amount>Math.min(EcoFinance.paymentMaximum,s.available)){$('#withdrawal-error').textContent=!s.canRequest?message(s):t('Enter an amount within your available balance, with up to two decimal places.','Введите сумму в пределах свободного остатка, не более двух знаков после запятой.');refresh();return;}
  const form=e.target,id=draft.id;draft.raw=$('#withdrawal-amount').value;busy=true;$('#withdrawal-error').textContent='';refresh();try{const saved=await window.EcoClientAccount.requestWithdrawal({id,amount});if(saved?.state.requests?.some(r=>r.id===id&&r.type==='withdraw')){draft=null;if(form.isConnected&&$('#modal')?.open)showPaymentReceipt(id);else toast(t('Withdrawal request saved.','Заявка на вывод сохранена.'));}}catch{if(form.isConnected)$('#withdrawal-error').textContent=t('Could not save. Refresh the account before trying again.','Не удалось сохранить. Обновите счёт перед повторной попыткой.');}finally{busy=false;refresh();}
 }
 const previous=paymentModal;paymentModal=function(type){return type==='withdraw'?open():previous(type);};
 document.addEventListener('submit',submit);document.addEventListener('input',e=>{if(e.target.id==='withdrawal-amount'){draft.raw=e.target.value;$('#withdrawal-error').textContent='';refresh();}});
 document.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.hasAttribute('data-withdraw-zone')){$('#modal')?.close();tab='profile';renderClientTab();document.querySelector('#care-profile [name=timezone]')?.focus();return;}if(button.hasAttribute('data-withdraw-max')&&!busy){$('#withdrawal-amount').value=String(Math.min(EcoFinance.paymentMaximum,state().available));draft.raw=$('#withdrawal-amount').value;$('#withdrawal-error').textContent='';refresh();}if(button.hasAttribute('data-withdraw-current')){const r=pending();if(r)showPaymentReceipt(r.id);}});
 document.addEventListener('visibilitychange',()=>document.hidden?stop():refresh());document.addEventListener('ecocharge:locale',()=>{if(isOpen()&&!busy)open();else refresh();});window.addEventListener('pagehide',stop);
 return {calendar,refresh,stop,isOpen,open,date};
})();
