'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EcoAcademy=api;})(typeof globalThis!=='undefined'?globalThis:this,()=>{
 const lessons=['ai','coin','community'];
 const scenarios={
  business:{en:{label:'Tell people about my work',example:'I make handmade candles. Customers can choose a scent and order a gift set.',instruction:'Help me write a short introduction to my work for a Facebook post. Use the details below. Keep it warm and clear, under 80 words. End with one simple question for interested customers. Do not invent prices, materials or delivery terms.',check:'Check that the description matches what you actually offer. Add your own voice before sharing.'},ru:{label:'Рассказать о своём деле',example:'Я делаю свечи вручную. Покупатели могут выбрать аромат и заказать подарочный набор.',instruction:'Помоги написать короткий пост для Facebook о моём деле. Используй детали ниже. Напиши понятно и тепло, до 80 слов. Закончи одним простым вопросом для заинтересованных покупателей. Не придумывай цены, материалы или условия доставки.',check:'Проверьте, что описание соответствует вашему предложению. Добавьте свои слова перед публикацией.'}},
  everyday:{en:{label:'Make a practical plan',example:'I want to organize my family photos. I have 20 minutes each evening and photos on two phones.',instruction:'Help me turn this task into a manageable plan for the next three days. Use the time and resources I describe. Give me one small first step I can take today. Ask about any important missing details instead of guessing.',check:'Check whether the steps fit your time and circumstances. Adjust the plan before following it.'},ru:{label:'Составить понятный план',example:'Хочу разобрать семейные фотографии. У меня есть 20 минут по вечерам, фотографии лежат на двух телефонах.',instruction:'Помоги разбить эту задачу на посильный план на ближайшие три дня. Учти время и ресурсы, которые я описываю. Предложи один небольшой первый шаг на сегодня. Если не хватает важных деталей, задай вопрос вместо догадок.',check:'Проверьте, подходят ли шаги под ваше время и обстоятельства. Скорректируйте план перед выполнением.'}},
  learning:{en:{label:'Understand something new',example:'I want to understand how a home battery works with solar panels.',instruction:'Explain this topic in plain English for someone new to it. Start with a familiar example, explain any technical terms, and give me three questions to check my understanding. Distinguish established facts from things I should verify with a reliable source.',check:'Verify important facts against reliable sources. A confident answer can still contain mistakes.'},ru:{label:'Разобраться в новой теме',example:'Хочу понять, как домашний накопитель работает вместе с солнечными панелями.',instruction:'Объясни эту тему простыми словами для человека без подготовки. Начни со знакомого примера, поясни специальные термины и предложи три вопроса для самопроверки. Отдели известные факты от того, что нужно уточнить в надёжном источнике.',check:'Проверьте важные факты по надёжным источникам. Даже уверенный ответ может содержать ошибки.'}}
 };
 function scenario(id,lang){return (scenarios[id]||scenarios.business)[lang==='ru'?'ru':'en'];}
 function prompt(id,details,lang){const s=scenario(id,lang),text=String(details||'').trim().slice(0,700);return s.instruction+'\n\n'+(lang==='ru'?'Моя задача: ':'My task: ')+(text||s.example);}
 function progress(value){return lessons.filter(id=>Array.isArray(value)&&value.includes(id));}
 function toggle(value,id){const current=progress(value);if(!lessons.includes(id))return current;return current.includes(id)?current.filter(item=>item!==id):progress([...current,id]);}
 return {lessons,scenarios,scenario,prompt,progress,toggle};
});
