'use strict';
(()=>{
 const root=document.querySelector('[data-academy-player]'),L=window.EcoLessons,M=window.EcoAcademy;if(!root||!L||!M)return;
 const key='ecogrid-academy-skills-v2',lang=()=>window.EcoLocale?.language==='ru'?'ru':'en',t=(en,ru)=>lang()==='ru'?ru:en,txt=x=>L.text(x,lang()),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const track=(name,details={})=>window.EcoChargeFunnel?.track(name,{page:document.documentElement.dataset.page,...details});
 let complete=[];try{complete=L.cleanProgress(JSON.parse(localStorage.getItem(key)||'[]'));}catch{}
 let current=null,index=0,passed=new Set(),draft='',finished=false,feedback='';
 const map=root.querySelector('[data-course-map]'),game=root.querySelector('[data-course-game]'),content=root.querySelector('[data-course-content]'),next=root.querySelector('[data-course-next]'),message=root.querySelector('[data-course-feedback]');
 const inApp=document.documentElement.dataset.page==='app';
 const url=(kind)=>inApp?(kind==='gift'?'app/#club':'app/#ai'):(kind==='gift'?'club/#request-access':'app/#ai');
 function renderMap(){root.querySelector('[data-course-progress]').textContent=t('Skills completed: ','Освоено навыков: ')+complete.length+'/'+L.ids.length;map.innerHTML=L.ids.map((id,i)=>`<button type="button" class="academy-course" data-course="${id}" aria-pressed="${current===id}"><span class="academy-course-symbol" aria-hidden="true">${['✦','↗','◇'][i]}</span><span><strong>${escape(txt(L.courses[id].title))}</strong><small>${escape(txt(L.courses[id].description))}</small></span><span class="academy-course-state">${complete.includes(id)?'✓':t('Start','Начать')+' →'}</span></button>`).join('');}
 function render(focus=false){renderMap();game.hidden=!current;if(!current)return;const course=L.courses[current],step=course.steps[index];root.querySelector('[data-course-guide]').textContent=finished?t('You have a new skill to try. Come back whenever you need a refresher.','Теперь у вас есть навык для практики. Возвращайтесь, когда понадобится подсказка.'):t('Let’s try one small step together. Take your time.','Попробуем один небольшой шаг вместе. Спешить не нужно.');root.querySelector('[data-course-step]').textContent=finished?txt(course.title):(index+1)+' / '+course.steps.length;root.querySelector('[data-course-meter]').max=course.steps.length;root.querySelector('[data-course-meter]').value=finished?course.steps.length:index;root.querySelector('[data-course-back]').hidden=index===0||finished;message.textContent=feedback;message.dataset.correct=String(passed.has(index));
  if(finished){content.innerHTML=`<div class="academy-success"><span aria-hidden="true">✓</span><h3>${t('Lesson complete','Урок пройден')}</h3><p>${t('Try your new skill in EcoGrid AI or continue with another lesson.','Попробуйте новый навык в EcoGrid AI или продолжите другим уроком.')}</p><a class="ec-button ec-button-outline" href="${url(current==='coin'?'gift':'ai')}">${current==='coin'?t('Explore my welcome gift','Перейти к приветственному подарку'):t('Open EcoGrid AI','Открыть EcoGrid AI')} →</a></div>`;next.textContent=t('Choose another skill','Выбрать другой навык');next.disabled=false;
  }else{content.innerHTML=`<h3>${escape(txt(step.title))}</h3><p>${escape(txt(step.body))}</p>`;
   if(step.type==='quiz'){content.innerHTML+='<div class="academy-choices">'+step.options.map((option,i)=>`<button type="button" data-course-answer="${i}" ${passed.has(index)?'disabled':''} ${passed.has(index)&&i===step.answer?'class="is-correct"':''}>${escape(txt(option))}</button>`).join('')+'</div>';}
   if(step.type==='practice'){content.innerHTML+=`<label for="lesson-details">${t('Add your task or use the example','Добавьте свою задачу или используйте пример')}</label><textarea id="lesson-details" maxlength="700" rows="3" placeholder="${escape(M.scenario(step.scenario,lang()).example)}">${escape(draft)}</textarea><label for="lesson-result">${t('Your prompt','Ваш запрос')}</label><textarea id="lesson-result" readonly rows="5"></textarea><button type="button" class="ec-button ec-button-outline" data-copy-lesson>${t('Copy my prompt','Скопировать запрос')}</button><button type="button" class="academy-manual-copy" data-saved-lesson hidden>${t('I saved the selected text','Я сохранил выделенный текст')}</button>`;content.querySelector('#lesson-result').value=M.prompt(step.scenario,draft,lang());}
   if(step.type==='guide')content.innerHTML+=`<a class="ec-text-link" href="${url(step.link)}">${escape(txt(step.label))} →</a>`;
   next.textContent=index===course.steps.length-1?t('Finish lesson','Завершить урок'):t('Continue','Продолжить');next.disabled=step.type!=='guide'&&!passed.has(index);
  }if(focus)root.querySelector('.academy-stage').focus({preventScroll:true});
 }
 function start(id){current=L.resolve(id);index=0;finished=false;passed=new Set();draft='';feedback='';render(true);game.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});track('academy_lesson_opened',{lesson:current});}
 root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
  if(b.dataset.course){start(b.dataset.course);return;}
  if(b.hasAttribute('data-course-close')){current=null;render();root.querySelector('[data-course]').focus();return;}
  if(b.hasAttribute('data-course-back')){index=Math.max(0,index-1);feedback='';render(true);return;}
  if(b.hasAttribute('data-course-answer')){const ok=L.correct(current,index,Number(b.dataset.courseAnswer));if(ok){passed.add(index);feedback=txt(L.courses[current].steps[index].feedback);track('academy_answer_checked',{lesson:current,complete:true});}else{feedback=t('Try again. Look for the choice that gives you useful information and keeps you in control.','Попробуйте ещё раз. Выберите действие, которое даёт полезную информацию и оставляет контроль у вас.');track('academy_answer_checked',{lesson:current,complete:false});}render();return;}
  if(b.hasAttribute('data-copy-lesson')){const field=content.querySelector('#lesson-result');try{if(!navigator.clipboard?.writeText)throw Error('copy');await navigator.clipboard.writeText(field.value);passed.add(index);message.textContent=t('Copied. Your prompt is ready to use.','Скопировано. Запрос готов к использованию.');next.disabled=false;track('academy_example_copied',{lesson:current});}catch{field.focus();field.select();content.querySelector('[data-saved-lesson]').hidden=false;message.textContent=t('Copy the selected text using your device, then confirm below.','Скопируйте выделенный текст средствами устройства и подтвердите ниже.');}return;}
  if(b.hasAttribute('data-saved-lesson')){passed.add(index);next.disabled=false;message.textContent=t('Ready for the next step.','Можно переходить дальше.');return;}
  if(b.hasAttribute('data-course-next')){if(finished){current=null;render();root.querySelector('[data-course]').focus();return;}const step=L.courses[current].steps[index];if(step.type!=='guide'&&!passed.has(index))return;if(index===L.courses[current].steps.length-1){finished=true;complete=L.cleanProgress([...complete,current]);try{localStorage.setItem(key,JSON.stringify(complete));}catch{feedback=t('Progress is kept only while this page stays open.','Прогресс сохранится только до закрытия страницы.');}track('academy_lesson_completed',{lesson:current,complete:true});}else{index++;feedback='';}render(true);}
 });
 root.addEventListener('input',e=>{if(e.target.id==='lesson-details'){draft=e.target.value;passed.delete(index);next.disabled=true;content.querySelector('#lesson-result').value=M.prompt(L.courses[current].steps[index].scenario,draft,lang());message.textContent='';}});
 function route(){const u=new URL(location.href),id=u.searchParams.get('lesson')||u.hash.match(/^#lesson-(.+)$/)?.[1];if(id)start(id);}
 document.addEventListener('ecocharge:locale',()=>{feedback='';render();});document.addEventListener('ecogrid:course',e=>start(e.detail));window.addEventListener('hashchange',route);renderMap();route();
})();
