'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EcoLessons=api;})(typeof globalThis!=='undefined'?globalThis:this,()=>{
 const pair=(en,ru)=>({en,ru});
 const courses={
 ai:{title:pair('AI for everyday life','AI для повседневной жизни'),description:pair('Plans, ideas and your own work.','Планы, идеи и своё дело.'),icon:'ai',steps:[
  {type:'quiz',title:pair('Give AI a clear task','Дайте AI понятную задачу'),body:pair('Tell EcoGrid AI what you need, what matters and how you want the answer. Which request will be more useful?','Объясните EcoGrid AI задачу, важные детали и формат ответа. Какой запрос будет полезнее?'),options:[pair('Write something about my business.','Напиши что-нибудь о моём деле.'),pair('Write a short post about my handmade candles for first-time customers. Ask me about details you need.','Напиши короткий пост о моих свечах ручной работы для новых покупателей. Уточни недостающие детали.')],answer:1,feedback:pair('A specific task gives the assistant a useful starting point.','Конкретная задача помогает помощнику подготовить полезный ответ.')},
  {type:'practice',scenario:'business',title:pair('Now try your own task','Теперь попробуйте свою задачу'),body:pair('Add a few details. EcoGrid AI’s prompt builder turns them into a clear request you can save.','Добавьте несколько деталей. Конструктор EcoGrid AI соберёт понятный запрос, который можно сохранить.')},
  {type:'quiz',title:pair('Keep the final decision yours','Решение остаётся за вами'),body:pair('AI has written a confident answer. What should you do before using it?','AI подготовил уверенный ответ. Что сделать перед использованием?'),options:[pair('Use it without checking.','Использовать без проверки.'),pair('Check facts and details, then adapt it to my situation.','Проверить факты и детали, затем адаптировать под свою ситуацию.')],answer:1,feedback:pair('AI helps you prepare. Your judgment and reliable sources still matter.','AI помогает подготовиться. Важны ваша оценка и надёжные источники.')}
 ]},
 invest:{title:pair('AI for investment research','AI для разбора инвестиций'),description:pair('Compare terms, costs and questions.','Сравнивайте условия, расходы и риски.'),icon:'invest',steps:[
  {type:'quiz',title:pair('Start with the right question','Начните с правильного вопроса'),body:pair('You are reviewing a project. Which task is a useful way to involve AI?','Вы изучаете проект. Какую задачу полезно поставить AI?'),options:[pair('Tell me which project guarantees a profit.','Скажи, какой проект гарантирует прибыль.'),pair('Compare documented terms, identify costs and list missing information.','Сравни условия из документов, выдели расходы и недостающие сведения.')],answer:1,feedback:pair('AI can organize information. It cannot guarantee returns or verify claims without evidence.','AI может упорядочить информацию. Он не гарантирует доход и не подтверждает заявления без доказательств.')},
  {type:'practice',scenario:'investment',title:pair('Prepare questions before a decision','Подготовьте вопросы до решения'),body:pair('Use public project information. Leave out account numbers and private financial documents.','Используйте публичные сведения о проекте. Не добавляйте номера счетов и личные финансовые документы.')},
  {type:'quiz',title:pair('Look beyond the headline','Смотрите шире обещаний'),body:pair('A technology project calls itself green. What information helps you assess that claim?','Технологический проект называет себя экологичным. Что поможет оценить это заявление?'),options:[pair('A green logo and a confident presentation.','Зелёный логотип и уверенная презентация.'),pair('Energy sources, equipment life, waste handling and evidence for the claims.','Источники энергии, срок службы техники, обращение с отходами и подтверждения заявлений.')],answer:1,feedback:pair('Climate and resource claims need evidence, just like financial claims.','Экологические заявления требуют подтверждений, как и финансовые.')}
 ]},
 coin:{title:pair('EcoCoin and digital products','EcoCoin и цифровые продукты'),description:pair('Your gift, wallet and first steps.','Подарок, кошелёк и первые действия.'),icon:'coin',steps:[
  {type:'quiz',title:pair('Understand what the gift unlocks','Разберитесь, что даёт подарок'),body:pair('EcoCoin is designed for Club rewards: digital kits and workshops. What should you check first?','EcoCoin предназначен для клубных наград: цифровых наборов и практикумов. Что проверить сначала?'),options:[pair('Which reward I need and its terms.','Какая награда мне полезна и каковы её условия.'),pair('How much the token is guaranteed to grow.','Насколько гарантированно вырастет токен.')],answer:0,feedback:pair('Start with a useful reward. A gift is not a promise of investment returns.','Начните с полезной награды. Подарок не означает обещание инвестиционного дохода.')},
  {type:'quiz',title:pair('Keep access to your wallet private','Сохраните доступ к кошельку только у себя'),body:pair('To receive a gift, you are asked for wallet details. What can you share after checking the network?','Для получения подарка нужны данные кошелька. Что можно передать после проверки сети?'),options:[pair('My recovery words or private key.','Слова восстановления или приватный ключ.'),pair('Only my public receiving address.','Только публичный адрес получения.')],answer:1,feedback:pair('Never share recovery words or private keys, including with support.','Никому не передавайте слова восстановления и приватные ключи, в том числе поддержке.')},
  {type:'guide',title:pair('Your next step: the welcome gift','Следующий шаг — приветственный подарок'),body:pair('Ask the Club team for the EcoCoin network and a compatible wallet. Install the wallet from its official source, secure your access and check the receiving address. Review any fee before confirming an action.','Уточните у команды клуба сеть EcoCoin и совместимый кошелёк. Установите его из официального источника, сохраните доступ и проверьте адрес получения. Перед подтверждением действия проверьте комиссию.'),link:'gift',label:pair('Get my gift and wallet guide','Получить подарок и инструкцию')}
 ]}
 };
 const ids=Object.keys(courses),text=(value,lang)=>value[lang==='ru'?'ru':'en'];
 function cleanProgress(value){return ids.filter(id=>Array.isArray(value)&&value.includes(id));}
 function correct(course,index,choice){if(!ids.includes(course)||!Number.isInteger(index)||index<0)return false;const step=courses[course].steps[index];return !!step&&step.type==='quiz'&&Number.isInteger(choice)&&choice===step.answer;}
 function resolve(value){if(value==='life')return 'ai';if(value==='digital'||value==='community')return 'coin';return ids.includes(value)?value:'ai';}
 return {courses,ids,text,cleanProgress,correct,resolve};
});
