'use strict';
(()=>{
 const M=window.EcoAcademy,root=document.querySelector('.academy');if(!M||!root)return;
 const key='ecogrid-academy-progress-v1',language=()=>window.EcoLocale?.language==='ru'?'ru':'en',t=(en,ru)=>language()==='ru'?ru:en;
 const track=(event,details={})=>window.EcoChargeFunnel?.track(event,{page:'academy',...details});
 let completed=[];try{completed=M.progress(JSON.parse(localStorage.getItem(key)||'[]'));}catch{}
 const task=document.getElementById('academy-task'),details=document.getElementById('academy-details'),output=document.getElementById('academy-prompt');
 function renderPrompt(){const s=M.scenario(task.value,language());details.placeholder=s.example;output.value=M.prompt(task.value,details.value,language());document.getElementById('academy-check').textContent=s.check;document.getElementById('academy-copy-status').textContent='';}
 function renderProgress(){const box=root.querySelector('[data-academy-progress]');box.hidden=false;box.querySelector('progress').value=completed.length;box.querySelector('[data-academy-progress-label]').textContent=t('Lessons completed: ','Пройдено уроков: ')+completed.length+t(' of 3',' из 3');root.querySelectorAll('[data-academy-complete]').forEach(b=>{const done=completed.includes(b.dataset.academyComplete);b.setAttribute('aria-pressed',String(done));b.querySelector('[data-complete-label]').textContent=done?t('Lesson complete · undo','Урок пройден · отменить'):t('Mark lesson complete','Отметить урок пройденным');});}
 function openLesson(id,focus=false){if(!M.lessons.includes(id))return;const lesson=document.getElementById('lesson-'+id);lesson.open=true;if(focus)lesson.querySelector('summary').focus({preventScroll:true});}
 function fromLocation(){const id=location.hash.replace('#lesson-','');if(M.lessons.includes(id))openLesson(id);else if(!location.hash){const requested=new URL(location.href).searchParams.get('lesson');if(M.lessons.includes(requested)){openLesson(requested);document.getElementById('lesson-'+requested).scrollIntoView({block:'start'});}}}
 task.addEventListener('change',()=>{renderPrompt();track('academy_task_selected',{scenario:task.value});});details.addEventListener('input',renderPrompt);
 root.querySelectorAll('[data-academy-open]').forEach(link=>link.addEventListener('click',()=>openLesson(link.dataset.academyOpen,true)));
 root.querySelectorAll('[data-academy-lesson]').forEach(lesson=>lesson.addEventListener('toggle',()=>{if(lesson.open)track('academy_lesson_opened',{lesson:lesson.dataset.academyLesson});}));
 root.querySelectorAll('[data-academy-complete]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.academyComplete;completed=M.toggle(completed,id);try{localStorage.setItem(key,JSON.stringify(completed));}catch{root.querySelector('[data-academy-storage-status]').textContent=t('Your checkmarks will last until you close this page. Browser storage is unavailable.','Отметки останутся до закрытия страницы. Сохранение в браузере недоступно.');}renderProgress();track('academy_lesson_marked',{lesson:id,complete:completed.includes(id)});}));
 root.querySelectorAll('[data-academy-copy]').forEach(button=>button.addEventListener('click',async()=>{const isPrompt=button.dataset.academyCopy==='prompt',source=isPrompt?output:document.getElementById('academy-comment-text'),text=isPrompt?source.value:source.textContent,status=document.getElementById(isPrompt?'academy-copy-status':'academy-comment-status');try{if(!navigator.clipboard?.writeText)throw Error('clipboard');await navigator.clipboard.writeText(text);status.textContent=t('Copied. Adapt it, then try it.','Скопировано. Адаптируйте под себя и попробуйте.');track('academy_example_copied',{lesson:isPrompt?'ai':'community'});}catch{if(isPrompt){output.focus();output.select();}else{const selection=window.getSelection(),range=document.createRange();range.selectNodeContents(source);selection.removeAllRanges();selection.addRange(range);}status.textContent=t('Copy is unavailable. The text is selected — use your device’s Copy command.','Копирование недоступно. Текст выделен — воспользуйтесь командой «Копировать» на устройстве.');}}));
 root.querySelectorAll('[data-academy-next]').forEach(link=>link.addEventListener('click',()=>track('academy_next_clicked',{destination:link.dataset.academyNext})));
 document.addEventListener('ecocharge:locale',()=>{renderPrompt();renderProgress();root.querySelectorAll('.academy-feedback').forEach(el=>el.textContent='');});window.addEventListener('hashchange',fromLocation);
 window.addEventListener('storage',e=>{if(e.key===key){try{completed=M.progress(JSON.parse(e.newValue||'[]'));}catch{completed=[];}renderProgress();}});
 renderPrompt();renderProgress();fromLocation();
})();
