'use strict';
(()=>{
 const root=document.documentElement;if(root.dataset.page!=='app')return;
 const lang=()=>window.EcoLocale?.language==='ru'?'ru':'en',t=(en,ru)=>lang()==='ru'?ru:en;
 function activeSection(){return 'academy';}
 const clubEntry=new URLSearchParams(location.search).get('entry')==='club';
 function entryCopy(){if(!clubEntry)return;const panel=document.querySelector('[data-app-panel="academy"]');
  const set=(selector,en,ru)=>{const e=panel.querySelector(selector);if(e)e.textContent=t(en,ru);};
  set('h1','Join the Club. The Academy will guide you.','Вступайте в Клуб. Академия поможет начать.');
  set('.app-intro','Get help with registration, join the community and learn to use your account. The Academy explains the 500 EcoCoin welcome gift and shows the projects when you want to explore them.','Поможем зарегистрироваться, присоединиться к сообществу и освоить кабинет. Академия объяснит подарок 500 EcoCoin и покажет проекты, когда захотите с ними познакомиться.');
  const cta=panel.querySelector('.app-telegram');if(cta){const svg=cta.querySelector('svg');cta.replaceChildren(document.createTextNode(t('Join the Club through Telegram','Вступить в Клуб через Telegram')+' '));if(svg)cta.append(svg);}
  set('.app-next-hint','Registration and community access come first. Investing is a separate decision.','Сначала — регистрация и доступ к сообществу. Инвестиции — отдельное решение.');
  const benefits=[['One EcoGrid account and help signing in.','Один аккаунт EcoGrid и помощь со входом.'],['Community conversations and product guidance.','Общение в сообществе и помощь с продуктами.'],['Wallet setup and the EcoCoin welcome program.','Настройка кошелька и приветственная программа EcoCoin.']];panel.querySelectorAll('.app-benefits li span').forEach((e,i)=>{if(benefits[i])e.textContent=t(...benefits[i]);});
  set('.app-preview h2','From joining to feeling at home.','От регистрации до участия в сообществе.');
  const steps=panel.querySelectorAll('.app-message-example');if(steps[0]){steps[0].querySelector('strong').textContent=t('01 · Registration and sign-in','01 · Регистрация и вход');steps[0].querySelector('p').textContent=t('The Academy helps you create one account and open your personal workspace.','Академия помогает создать один аккаунт и открыть личный кабинет.');}if(steps[1]){steps[1].querySelector('strong').textContent=t('02 · Join the community','02 · Вступление в сообщество');steps[1].querySelector('p').textContent=t('Join the groups, meet other members and ask questions. Explore the projects if you are interested.','Подпишитесь на группы, знакомьтесь с участниками и задавайте вопросы. Изучайте проекты, если они вам интересны.');}
 }
 let trackedSection='';
 function showPanel(){if(location.hash==='#club'){const u=new URL('club/',document.baseURI);u.search=location.search;location.replace(u.href);return;}if(location.hash==='#ai')history.replaceState(null,'',location.pathname+location.search+'#academy');const hash=location.hash.slice(1),id=activeSection();if(id!==trackedSection){window.EcoChargeFunnel?.track('app_section_viewed',{page:'app',destination:id});trackedSection=id;}document.querySelectorAll('[data-app-panel]').forEach(p=>p.hidden=p.dataset.appPanel!==id);document.querySelectorAll('[data-app-tab]').forEach(a=>{if(a.dataset.appTab===id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const brand=document.querySelector('.eco-app-header .charge-brand'),name=id==='club'?'Club':'Academy';brand.querySelector('.charge-project-name').textContent=name;brand.setAttribute('aria-label','EcoGrid '+name);if(hash==='install'){location.replace(document.querySelector('[data-workspace-entry]').href);}}
 function offline(){document.querySelector('[data-app-offline]').hidden=navigator.onLine;}
 function guide(){const id=activeSection(),copy={academy:['Explore projects and see the account with the Academy. If you choose to participate, get help with registration, your wallet, EcoCoin and project tools.','Академия покажет проекты и кабинет. Если решите участвовать — поможет с регистрацией, кошельком, EcoCoin и инструментами проекта.'],club:['Introduce yourself or join a conversation that interests you. The welcome program explains the 500 EcoCoin gift and planned project AI mode.','Представьтесь или подключитесь к интересному обсуждению. В приветственной программе — 500 EcoCoin и объяснение планируемого AI-режима проектов.'],ai:['Describe what you want to do, add a few details and say what kind of answer you need. Continue in the AI chat.','Опишите задачу, добавьте важные детали и скажите, какой результат нужен. Продолжайте в AI-чате.']};document.querySelector('#eco-guide-title').textContent=t('I’ll help you get started.','Помогу с первым шагом.');document.querySelector('[data-app-guide-copy]').textContent=(clubEntry?t('The Academy helps you register, join the community and understand the EcoCoin gift. Explore investment projects when you choose.','Академия поможет зарегистрироваться, вступить в сообщество и разобраться с подарком EcoCoin. Проекты можно изучить по желанию.'):t(...copy[id]));const nav=document.querySelector('#eco-guide-dialog nav');nav.replaceChildren(document.querySelector('[data-app-panel="'+id+'"] .app-telegram').cloneNode(true));}
 document.addEventListener('ecocharge:locale',()=>{entryCopy();guide();});window.addEventListener('hashchange',()=>{showPanel();entryCopy();guide();window.scrollTo({top:0,behavior:'instant'});});window.addEventListener('online',offline);window.addEventListener('offline',offline);showPanel();entryCopy();offline();guide();
 if('serviceWorker' in navigator)navigator.serviceWorker.getRegistration(new URL('app/',document.baseURI)).then(r=>{if(r&&r.scope===new URL('app/',document.baseURI).href)return r.update();}).catch(()=>{});
})();
