'use strict';
(()=>{
 const root=document.documentElement;if(root.dataset.page!=='app')return;
 const lang=()=>window.EcoLocale?.language==='ru'?'ru':'en',t=(en,ru)=>lang()==='ru'?ru:en;
 function activeSection(){return 'academy';}
 let trackedSection='';
 function showPanel(){if(location.hash==='#club'){const u=new URL('club/',document.baseURI);u.search=location.search;location.replace(u.href);return;}if(location.hash==='#ai')history.replaceState(null,'',location.pathname+location.search+'#academy');const hash=location.hash.slice(1),id=activeSection();if(id!==trackedSection){window.EcoChargeFunnel?.track('app_section_viewed',{page:'app',destination:id});trackedSection=id;}document.querySelectorAll('[data-app-panel]').forEach(p=>p.hidden=p.dataset.appPanel!==id);document.querySelectorAll('[data-app-tab]').forEach(a=>{if(a.dataset.appTab===id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const brand=document.querySelector('.eco-app-header .charge-brand'),name=id==='club'?'Club':'Academy';brand.querySelector('.charge-project-name').textContent=name;brand.setAttribute('aria-label','EcoGrid '+name);if(hash==='install'){const target=document.querySelector('.eco-account-install');location.replace(target.href);}}
 function offline(){document.querySelector('[data-app-offline]').hidden=navigator.onLine;}
 function guide(){const id=activeSection(),copy={academy:['The Academy helps you register, join the Club and learn to use your account, wallet and EcoCoin.','Академия поможет зарегистрироваться, вступить в клуб и освоить кабинет, кошелёк и EcoCoin.'],club:['Introduce yourself or join a conversation that interests you. The welcome post explains how to use EcoCoin for your first-post kit.','Представьтесь или подключитесь к интересному обсуждению. В приветственном посте — как открыть набор для первого поста за EcoCoin.'],ai:['Describe what you want to do, add a few details and say what kind of answer you need. Continue in the AI chat.','Опишите задачу, добавьте важные детали и скажите, какой результат нужен. Продолжайте в AI-чате.']};document.querySelector('#eco-guide-title').textContent=t('I’ll help you get started.','Помогу с первым шагом.');document.querySelector('[data-app-guide-copy]').textContent=t(...copy[id]);const nav=document.querySelector('#eco-guide-dialog nav');nav.replaceChildren(document.querySelector('[data-app-panel="'+id+'"] .app-telegram').cloneNode(true));}
 document.addEventListener('ecocharge:locale',()=>{guide();});window.addEventListener('hashchange',()=>{showPanel();guide();window.scrollTo({top:0,behavior:'instant'});});window.addEventListener('online',offline);window.addEventListener('offline',offline);showPanel();offline();guide();
 if('serviceWorker' in navigator)navigator.serviceWorker.getRegistration(new URL('app/',document.baseURI)).then(r=>{if(r&&r.scope===new URL('app/',document.baseURI).href)return r.update();}).catch(()=>{});
})();
