'use strict';
(()=>{
 const root=document.documentElement;if(root.dataset.page!=='app')return;
 const lang=()=>window.EcoLocale?.language==='ru'?'ru':'en',t=(en,ru)=>lang()==='ru'?ru:en;
 const appRoot=new URL('app/',document.baseURI),dialog=document.querySelector('#app-install-dialog');let pendingInstall=null,returnFocus=null;
 const installed=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
 function activeSection(){const h=location.hash.slice(1);return ['academy','club'].includes(h)?h:(document.querySelector('[data-app-tab][aria-current=page]')?.dataset.appTab||'academy');}
 let trackedSection='';
 function showPanel(){if(location.hash==='#ai')history.replaceState(null,'',location.pathname+location.search+'#academy');const hash=location.hash.slice(1),id=activeSection();if(id!==trackedSection){window.EcoChargeFunnel?.track('app_section_viewed',{page:'app',destination:id});trackedSection=id;}document.querySelectorAll('[data-app-panel]').forEach(p=>p.hidden=p.dataset.appPanel!==id);document.querySelectorAll('[data-app-tab]').forEach(a=>{if(a.dataset.appTab===id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(hash==='install')openInstall();}
 function help(){const host=document.querySelector('[data-app-install-help]');document.querySelector('[data-app-native-install]').hidden=!pendingInstall||installed();if(installed()){host.textContent=t('EcoGrid is open as an app. You can return using its icon on this device.','EcoGrid уже открыт как приложение. Возвращайтесь через его значок на этом устройстве.');return;}host.innerHTML=pendingInstall?'<p>'+t('Use the button below and confirm in your browser.','Нажмите кнопку ниже и подтвердите установку в браузере.')+'</p>':'<p>'+t('Open this page in your regular browser, then:','Откройте эту страницу в обычном браузере, затем:')+'</p><ul><li>'+t('iPhone or iPad: Share → Add to Home Screen.','iPhone или iPad: «Поделиться» → «На экран Домой».')+'</li><li>'+t('Android: browser menu → Install app or Add to Home screen.','Android: меню браузера → «Установить приложение» или «Добавить на главный экран».')+'</li><li>'+t('Computer: use the install icon in Chrome or Edge. In Safari, choose File → Add to Dock.','Компьютер: значок установки в Chrome или Edge. В Safari — «Файл» → «Добавить в Dock».')+'</li></ul>';
 }
 function openInstall(){help();if(!dialog.open){returnFocus=document.activeElement;dialog.showModal();}}
 document.querySelectorAll('[data-app-install]').forEach(b=>b.addEventListener('click',openInstall));document.querySelector('[data-app-install-close]').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{if(location.hash==='#install')history.replaceState(null,'',location.pathname+location.search+'#'+activeSection());returnFocus?.focus();});
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();pendingInstall=e;help();});window.addEventListener('appinstalled',()=>{pendingInstall=null;document.querySelector('[data-app-install-status]').textContent=t('EcoGrid was installed on this device.','EcoGrid установлен на этом устройстве.');help();});
 document.querySelector('[data-app-native-install]').addEventListener('click',async()=>{const prompt=pendingInstall;if(!prompt)return;pendingInstall=null;try{await prompt.prompt();const result=await prompt.userChoice;document.querySelector('[data-app-install-status]').textContent=result.outcome==='accepted'?t('Installation requested. Follow your browser’s instructions.','Установка запрошена. Следуйте подсказкам браузера.'):t('You can keep using EcoGrid in your browser.','Можно продолжить пользоваться EcoGrid в браузере.');}catch{document.querySelector('[data-app-install-status]').textContent=t('Use your browser’s installation menu.','Используйте меню установки в браузере.');}help();});

 function offline(){document.querySelector('[data-app-offline]').hidden=navigator.onLine;}
 function guide(){const id=activeSection(),copy={academy:['Start with a practical lesson about your wallet, EcoCoin or account. Find the pinned getting-started post in the Academy.','Начните с практического урока о кошельке, EcoCoin или кабинете. Найдите закреплённый вводный пост в Академии.'],club:['Introduce yourself or join a conversation that interests you. The welcome post explains how to use EcoCoin for your first-post kit.','Представьтесь или подключитесь к интересному обсуждению. В приветственном посте — как открыть набор для первого поста за EcoCoin.'],ai:['Describe what you want to do, add a few details and say what kind of answer you need. Continue in the AI chat.','Опишите задачу, добавьте важные детали и скажите, какой результат нужен. Продолжайте в AI-чате.']};document.querySelector('#eco-guide-title').textContent=t('I’ll help you get started.','Помогу с первым шагом.');document.querySelector('[data-app-guide-copy]').textContent=t(...copy[id]);const nav=document.querySelector('#eco-guide-dialog nav');nav.replaceChildren(document.querySelector('[data-app-panel="'+id+'"] .app-telegram').cloneNode(true));}
 document.addEventListener('ecocharge:locale',()=>{help();guide();});window.addEventListener('hashchange',()=>{showPanel();guide();window.scrollTo({top:0,behavior:'instant'});});window.addEventListener('online',offline);window.addEventListener('offline',offline);showPanel();offline();guide();
 if('serviceWorker' in navigator&&(location.protocol==='https:'||['localhost','127.0.0.1'].includes(location.hostname)))navigator.serviceWorker.register(new URL('sw.js',appRoot),{scope:appRoot.pathname}).catch(()=>{});
})();
