'use strict';
(()=>{
 const M=window.EcoJourney,t=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en,params=new URL(location).searchParams,key='ecogrid-learning-v1';let read=[];
 try{const v=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(v))read=v.filter(x=>Object.hasOwn(M.topics,x));}catch{}
 function consultLink(){const f=document.querySelector('[data-journey-form]'),topic=f?.elements.journeyTopic.value||params.get('topic')||'energy',country=f?.elements.journeyCountry.value||'US';document.querySelectorAll('[data-journey-consult]').forEach(a=>{const p=['charge','solar','mining'].includes(topic)?'participate/'+topic+'/':'./';a.href=new URL(p+'?journey=fast&topic='+topic+'&country='+country+'&lang='+(window.EcoLocale?.language||'en')+'#request-access',document.baseURI).href;});}
 function progress(){document.querySelectorAll('[data-guide-read]').forEach(b=>{const done=read.includes(b.dataset.guideRead);b.setAttribute('aria-pressed',String(done));b.textContent=done?t('Read · undo','Прочитано · отменить'):t('Mark as read','Отметить прочитанным');});const n=document.querySelector('[data-journey-progress]');if(n)n.textContent=t('Read: ','Прочитано: ')+read.length+' / '+Object.keys(M.topics).length;}
 function track(event,details){window.EcoChargeFunnel?.track(event,details);}
 document.querySelectorAll('[data-journey-form]').forEach(form=>{
  const nurture=form.hasAttribute('data-journey-nurture'),fixed=form.hasAttribute('data-journey-fast'),routes=[...form.querySelectorAll('[name=journeyRoute]')],topic=form.elements.journeyTopic;
  if(!fixed&&Object.hasOwn(M.topics,params.get('topic')))topic.value=params.get('topic');
  if(['US','CA'].includes(params.get('country')))form.elements.journeyCountry.value=params.get('country');
  if(!fixed&&Object.hasOwn(M.purposes,params.get('purpose'))&&params.get('purpose')!=='updates')form.elements.journeyPurpose.value=params.get('purpose');
  const initial=nurture?'nurture':fixed?'fast':['fast','nurture'].includes(params.get('journey'))?params.get('journey'):document.documentElement.dataset.page==='learn'?'nurture':'fast';routes.forEach(r=>r.checked=r.value===initial);
  function sync(){const slow=form.elements.journeyRoute.value==='nurture';form.dataset.journey=slow?'nurture':'fast';const purpose=form.querySelector('[data-journey-purpose]');if(purpose)purpose.hidden=slow;form.elements.journeyPurpose.disabled=slow;form.querySelector('[data-journey-phone]').hidden=slow;form.elements.phone.disabled=slow;form.elements.email.required=slow;form.elements.marketingConsent.required=slow;form.querySelector('[data-journey-contact]').textContent=slow?t('I agree to save my interest and email preferences.','Согласен сохранить мой интерес и настройки email.'):t('I agree to be contacted about this request.','Согласен на связь по этой заявке.');form.querySelector('[data-journey-hint]').textContent=slow?t('Read the guides now. A consultation is requested separately.','Материалы доступны сразу. Консультацию можно запросить отдельно.'):t('Leave a phone number or email. The team will contact you about your chosen topic.','Оставьте телефон или email. Команда свяжется по выбранной теме.');form.querySelector('[type=submit]').textContent=slow?t('Save my interest','Сохранить мой интерес'):fixed?t('Request participation details','Получить условия участия'):t('Request a consultation','Запросить консультацию');const preferences=form.querySelector('.lead-preferences');preferences.hidden=slow;preferences.querySelectorAll('input,select').forEach(n=>n.disabled=slow);}
  form.addEventListener('change',e=>{if(e.target.name==='journeyRoute'){sync();track('journey_selected',{journey:form.elements.journeyRoute.value,topic:topic.value});}});
  document.addEventListener('ecocharge:locale',sync);document.querySelectorAll('[data-journey-choose]').forEach(a=>a.addEventListener('click',()=>{routes.forEach(r=>r.checked=r.value===a.dataset.journeyChoose);sync();}));sync();
 });
 document.addEventListener('click',e=>{const b=e.target.closest('[data-guide-read]');if(!b)return;const topic=b.dataset.guideRead;read=read.includes(topic)?read.filter(x=>x!==topic):[...read,topic];try{localStorage.setItem(key,JSON.stringify(read));}catch{}progress();track('guide_read',{topic,complete:read.includes(topic)});});
 document.querySelectorAll('[data-guide-topic]').forEach(a=>a.addEventListener('click',()=>{const f=document.querySelector('[data-journey-form]');if(f)f.elements.journeyTopic.value=a.dataset.guideTopic;consultLink();track('topic_selected',{topic:a.dataset.guideTopic});}));
 document.addEventListener('change',consultLink);document.addEventListener('ecocharge:locale',consultLink);document.addEventListener('ecocharge:locale',progress);progress();consultLink();
 if(document.documentElement.dataset.page==='learn'&&Object.hasOwn(M.topics,params.get('topic'))&&!location.hash)document.getElementById('guide-'+params.get('topic'))?.scrollIntoView({block:'start'});
})();
