'use strict';
(()=>{
 const M=window.EcoJourney,t=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en,params=new URL(location).searchParams;
 function consultLink(){const f=document.querySelector('[data-journey-form]'),topic=f?.elements.journeyTopic.value||params.get('topic')||'energy',country=f?.elements.journeyCountry.value||'US';document.querySelectorAll('[data-journey-consult]').forEach(a=>{const p=['charge','solar','mining'].includes(topic)?'participate/'+topic+'/':'./';a.href=new URL(p+'?journey=fast&topic='+topic+'&country='+country+'&lang='+(window.EcoLocale?.language||'en')+'#request-access',document.baseURI).href;});}
 function track(event,details){window.EcoChargeFunnel?.track(event,details);}
 document.querySelectorAll('[data-journey-form]').forEach(form=>{
  const nurture=form.hasAttribute('data-journey-nurture'),fixed=form.hasAttribute('data-journey-fast'),routes=[...form.querySelectorAll('[name=journeyRoute]')],topic=form.elements.journeyTopic;
  if(!nurture&&!fixed&&Object.hasOwn(M.projectTopics,params.get('topic')))topic.value=params.get('topic');
  if(['US','CA'].includes(params.get('country')))form.elements.journeyCountry.value=params.get('country');
  if(!fixed&&Object.hasOwn(M.purposes,params.get('purpose'))&&params.get('purpose')!=='updates')form.elements.journeyPurpose.value=params.get('purpose');
  const initial=nurture?'nurture':fixed?'fast':['fast','nurture'].includes(params.get('journey'))?params.get('journey'):document.documentElement.dataset.page==='learn'?'nurture':'fast';routes.forEach(r=>r.checked=r.value===initial);
  function sync(){const slow=form.elements.journeyRoute.value==='nurture';form.dataset.journey=slow?'nurture':'fast';const purpose=form.querySelector('[data-journey-purpose]');if(purpose)purpose.hidden=slow;form.elements.journeyPurpose.disabled=slow;form.querySelector('[data-journey-phone]').hidden=slow;form.elements.phone.disabled=slow;form.elements.email.required=slow;form.elements.marketingConsent.required=slow&&topic.value!=='club';form.querySelector('[data-journey-contact]').textContent=slow?t('I agree to save my interest and email preferences.','Согласен сохранить мой интерес и настройки email.'):t('I agree to be contacted about this request.','Согласен на связь по этой заявке.');form.querySelector('[data-journey-hint]').textContent=slow?(nurture?t('The team will explain how to register your wallet and receive welcome EcoCoin.','Команда объяснит, как зарегистрировать кошелёк и получить приветственные EcoCoin.'):t('Read the guides now. A consultation is requested separately.','Материалы доступны сразу. Консультацию можно запросить отдельно.')):t('Leave a phone number or email. The team will contact you about your chosen topic.','Оставьте телефон или email. Команда свяжется по выбранной теме.');form.querySelector('[type=submit]').textContent=slow?(nurture?t('Request my welcome EcoCoin','Получить приветственный EcoCoin'):t('Save my interest','Сохранить мой интерес')):fixed?t('Request participation details','Получить условия участия'):t('Request a consultation','Запросить консультацию');const preferences=form.querySelector('.lead-preferences');preferences.hidden=slow;preferences.querySelectorAll('input,select').forEach(n=>n.disabled=slow);}
  form.addEventListener('change',e=>{if(e.target.name==='journeyRoute'){sync();track('journey_selected',{journey:form.elements.journeyRoute.value,topic:topic.value});}});
  document.addEventListener('ecocharge:locale',sync);document.querySelectorAll('[data-journey-choose]').forEach(a=>a.addEventListener('click',()=>{routes.forEach(r=>r.checked=r.value===a.dataset.journeyChoose);sync();}));sync();
 });
 document.querySelectorAll('[data-guide-topic]').forEach(a=>a.addEventListener('click',()=>{const f=document.querySelector('[data-journey-form]');if(f)f.elements.journeyTopic.value=a.dataset.guideTopic;consultLink();track('topic_selected',{topic:a.dataset.guideTopic});}));
 document.addEventListener('change',consultLink);document.addEventListener('ecocharge:locale',consultLink);consultLink();
 if(params.get('topic')==='ai')document.getElementById('guide-energy')?.scrollIntoView({block:'start'});
 if(document.documentElement.dataset.page==='learn'&&Object.hasOwn(M.topics,params.get('topic'))&&!location.hash)document.getElementById('guide-'+params.get('topic'))?.scrollIntoView({block:'start'});
})();
