'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EcoLeadForm=api;})(typeof window==='object'?window:globalThis,()=>{
 function validate(v){if((v.name||'').trim().length<2)return 'Enter your name.';const phone=(v.phone||'').trim(),email=(v.email||'').trim();if(!phone&&!email)return 'Enter a phone number or email.';if(phone&&!/^\+?[\d\s().-]{7,40}$/.test(phone)||phone&&(phone.replace(/\D/g,'').length<7||phone.replace(/\D/g,'').length>15))return 'Enter a valid phone number.';if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return 'Enter a valid email address.';if(v.consent!=='on')return 'Please allow the team to contact you about this request.';if(v.smsConsent==='on'&&!phone)return 'Enter a phone number to allow follow-up texts.';if(v.emailConsent==='on'&&!email)return 'Enter an email address to allow follow-up emails.';return '';}
 function confirmation(receipt,time=Date.now()){
  if(receipt.local)return 'Preview only. No request was sent.';
  if(receipt.duplicate)return 'Your request is already with the team. We will contact you about the same request.';
  if(!receipt.phone)return 'Thank you. Your manager will reply by email during working hours.';
  const zone=receipt.context?.contactTimezone;let outOfHours=false;
  try{if(zone){const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:zone,hour:'numeric',hourCycle:'h23'}).format(new Date(time)));outOfHours=hour<9||hour>=20;}}catch{}
  return outOfHours?'Thank you. Your manager will call within the first 15 minutes of the next working window (9 AM–8 PM, your local time).':'Thank you. Your manager will call within 15 minutes during working hours (9 AM–8 PM, your local time).';
 }
 return {validate,confirmation};
});
if(typeof window==='object')(()=>{const t=s=>window.EcoLocale?.t(s)||s;document.querySelectorAll('[data-lead-form]').forEach(form=>{let pending=false,receipt=null;const result=form.querySelector('[data-lead-result]'),inputs=form.querySelector('[data-lead-fields]'),followup=form.querySelector('[data-lead-followup]'),button=form.querySelector('[type=submit]');
 function showReceipt(){if(!receipt)return;result.dataset.error='false';result.dataset.success='true';result.replaceChildren();const title=document.createElement('strong');title.textContent=t(EcoLeadForm.confirmation(receipt));const contact=document.createElement('p');contact.setAttribute('translate','no');contact.textContent=[receipt.name,receipt.phone,receipt.email].filter(Boolean).join(' · ');result.append(title,contact);inputs.hidden=true;followup.hidden=receipt.local;if(receipt.local){const note=document.createElement('p');note.textContent=t('No team was notified. Open the shared project to submit a request.');result.append(note);}result.focus();}
 form.querySelector('[data-lead-again]')?.addEventListener('click',()=>{receipt=null;inputs.hidden=false;followup.hidden=true;result.textContent='';delete result.dataset.success;form.querySelector('[name=name]').focus();});
 document.addEventListener('ecocharge:locale',showReceipt);
 form.addEventListener('submit',async e=>{e.preventDefault();if(pending||receipt)return;const fields=Object.fromEntries(new FormData(form)),error=EcoLeadForm.validate(fields)||(fields.miningInquiry?window.EcoMiningUI.validate():'')||((fields.solarRequestType||fields.solarSystem)?window.EcoSolar.validate(fields):'');delete result.dataset.success;if(error){result.dataset.error='true';result.textContent=t(error);result.focus();return;}pending=true;button.disabled=true;result.textContent=t('Sending your request…');result.dataset.error='false';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);
 try{const payload={name:fields.name.trim(),phone:fields.phone.trim(),email:fields.email.trim(),website:fields.website,consent:fields.consent==='on',smsConsent:fields.smsConsent==='on',emailConsent:fields.emailConsent==='on',consentVersion:fields.consentVersion,consentLanguage:window.EcoLocale?.language==='ru'?'ru':'en',attribution:window.EcoPlatform?.attribution()||{},context:typeof location==='object'?{contactTimezone:fields.contactTimezone||'',tierId:new URL(location.href).searchParams.get('tier'),tab:new URL(location.href).searchParams.get('tab')||new URL(location.href).searchParams.get('next')}:{}};if((fields.solarRequestType||fields.solarSystem)){payload.context.intent='solar_purchase';payload.context.solar={requestType:fields.solarRequestType,country:fields.solarCountry,chargerId:fields.solarCharger,vehicle:fields.solarVehicle,systemId:fields.solarSystem,zip:fields.solarZip,property:fields.solarProperty,billMonthly:fields.solarBill,battery:fields.solarBattery,panelId:fields.solarPanel,batteryModelId:fields.solarBatteryModel};}if(fields.miningInquiry){payload.context.intent='mining';payload.context.mining=window.EcoMiningUI.input();}const base=window.ECO_PLATFORM_CONFIG?.apiBase;
  if(!base){receipt={...payload,local:true};}
  else{const r=await fetch(new URL('api/leads',base),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});const data=await r.json();if(!r.ok||!data.accepted||!data.id)throw Error('not accepted');receipt={...payload,id:data.id,duplicate:!!data.duplicate};window.EcoChargeFunnel?.track(fields.miningInquiry?'mining_inquiry_requested':(fields.solarRequestType||fields.solarSystem)?'solar_quote_requested':'registration_request_sent',{miningRoute:fields.miningRoute,solarSystem:fields.solarSystem,page:fields.miningInquiry?'mining':(fields.solarRequestType||fields.solarSystem)?'solar':undefined,landing:payload.attribution.landing_id||'main',duplicate:!!data.duplicate,mode:window.ECO_PLATFORM_CONFIG?.mode||'shared-demo'});}
  showReceipt();
 }catch{result.dataset.error='true';result.textContent=t('Your request was not sent. Your details are kept. Check the connection and try again.');result.focus();}finally{clearTimeout(timer);pending=false;button.disabled=false;}});
 });})();
