'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EcoLeadForm=api;})(typeof window==='object'?window:globalThis,()=>{
 function validate(v){
  const phone=(v.phone||'').trim(),email=(v.email||'').trim();
  if((v.name||'').trim().length<2)return 'Enter your name.';
  if(v.journeyRoute==='nurture'&&!email)return v.journeyTopic==='club'?'Enter your email address for the Club welcome steps.':'Enter an email address for project updates.';
  if(v.marketingConsent==='on'&&!email)return 'Enter an email address for project updates.';
  if(!phone&&!email)return 'Enter a phone number or email.';
  if(phone&&(!/^\+?[\d\s().-]{7,40}$/.test(phone)||phone.replace(/\D/g,'').length<7||phone.replace(/\D/g,'').length>15))return 'Enter a valid phone number.';
  if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return 'Enter a valid email address.';
  if(v.journeyRoute==='nurture'&&v.journeyTopic!=='club'&&v.marketingConsent!=='on')return 'Choose email updates or request a consultation instead.';
  if(v.consent!=='on')return 'Please allow the team to contact you about this request.';
  if(v.smsConsent==='on'&&!phone)return 'Enter a phone number to allow follow-up texts.';
  if(v.emailConsent==='on'&&!email)return 'Enter an email address to allow follow-up emails.';
  return '';
 }
 function invalidField(error){if(error==='Enter your name.')return 'name';if(error.startsWith('Please allow'))return 'consent';if(error.startsWith('Choose email updates'))return 'marketingConsent';if(error==='Enter a phone number or email.'||error.toLowerCase().includes('email address'))return 'email';if(error.includes('phone number'))return 'phone';return 'request';}
 function confirmation(receipt,time=Date.now()){
  if(receipt.context?.journey?.topic==='club'&&!receipt.local)return 'Your Club request is saved. Next, the team will guide you through wallet setup and your welcome EcoCoin.';
  if(receipt.context?.journey?.route==='nurture'&&!receipt.local)return 'Your interest is saved. Explore the guides now and request a conversation when you are ready.';
  if(receipt.local)return 'Preview only. No request was sent.';
  if(receipt.duplicate)return 'Your request is already with the team. We will contact you about the same request.';
  if(!receipt.phone)return 'Thank you. Your manager will reply by email during working hours.';
  const zone=receipt.context?.contactTimezone;let outOfHours=false;
  try{if(zone){const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:zone,hour:'numeric',hourCycle:'h23'}).format(new Date(time)));outOfHours=hour<9||hour>=20;}}catch{}
  return outOfHours?'Thank you. Your manager will call within the first 15 minutes of the next working window (9 AM–8 PM, your local time).':'Thank you. Your manager will call within 15 minutes during working hours (9 AM–8 PM, your local time).';
 }
 return {validate,invalidField,confirmation};
});
if(typeof window==='object')(()=>{const t=s=>window.EcoLocale?.t(s)||s;document.querySelectorAll('[data-lead-form]').forEach(form=>{let pending=false,receipt=null,started=false,invalid=null;const result=form.querySelector('[data-lead-result]'),inputs=form.querySelector('[data-lead-fields]'),followup=form.querySelector('[data-lead-followup]'),button=form.querySelector('[type=submit]');
 function context(){return {page:document.documentElement?.dataset.page,topic:form.elements?.journeyTopic?.value,journey:form.elements?.journeyRoute?.value};}
 function track(name,extra={}){window.EcoChargeFunnel?.track(name,{...context(),...extra});}
 function clearError(){if(invalid){invalid.field.removeAttribute('aria-invalid');if(invalid.description)invalid.field.setAttribute('aria-describedby',invalid.description);else invalid.field.removeAttribute('aria-describedby');invalid.note.remove();invalid=null;}result.textContent='';delete result.dataset.error;}
 form.addEventListener('input',()=>{if(!started){started=true;track('lead_form_started');}if(invalid)clearError();});
 function showError(error){clearError();result.dataset.error='true';result.textContent=t(error);const name=EcoLeadForm.invalidField(error),field=form.elements?.namedItem(name);track('lead_validation_failed',{field:name});if(field&&typeof field.focus==='function'){const note=document.createElement('span');note.className='lead-field-error';note.id=(field.id||'lead-'+name)+'-error';note.textContent=t(error);const description=field.getAttribute('aria-describedby')||'';field.setAttribute('aria-invalid','true');field.setAttribute('aria-describedby',[description,note.id].filter(Boolean).join(' '));(field.closest('.lead-consent')||field).insertAdjacentElement('afterend',note);invalid={field,note,description};field.focus();}else result.focus();}
 function showReceipt(){if(!receipt)return;result.dataset.error='false';result.dataset.success='true';result.replaceChildren();const title=document.createElement('strong');title.textContent=t(EcoLeadForm.confirmation(receipt));const contact=document.createElement('p');contact.setAttribute('translate','no');contact.textContent=[receipt.name,receipt.phone,receipt.email].filter(Boolean).join(' · ');result.append(title,contact);if(receipt.sandbox){title.textContent=window.EcoLocale?.language==='ru'?'Заявка сохранена только в этом браузере. Отправка команде пока не подключена.':'Request saved in this browser only. Delivery to the team is not connected yet.';}const guide=followup.querySelector?.('a[href]');if(guide&&receipt.context?.journey){guide.href=new URL(receipt.context.journey.topic==='club'?'club/#club-wallet':'learn/?topic='+receipt.context.journey.topic+'&journey=nurture',document.baseURI);guide.textContent=t(receipt.context.journey.topic==='club'?'Review the wallet setup steps →':'Continue exploring EcoGrid →');}const projectTopic=receipt.context?.journey?.topic;const projectNames={charge:'EcoGrid Charge',solar:'EcoGrid Solar',mining:'EcoGrid Mining'};if(projectNames[projectTopic]&&receipt.context?.journey?.route==='fast'){
 const ru=window.EcoLocale?.language==='ru',project=projectNames[projectTopic];
 if(guide){guide.href=new URL('participate/'+projectTopic+'/?lang='+(ru?'ru':'en')+'#project-business',document.baseURI);guide.textContent=ru?'Материалы '+project+' перед обсуждением →':project+' materials before our conversation →';}
 const next=followup.querySelector?.('p');if(next)next.textContent=ru?'Следующий шаг — обсуждение '+project+'. Разберём площадку, выручку, расходы и условия участия. Согласуем время связи в вашем часовом поясе.':'Next: a conversation about '+project+'. We will review the site, revenue, costs and participation terms, and agree a time in your time zone.';
 const topic=document.createElement('p');topic.textContent=(ru?'Выбранный проект: ':'Selected project: ')+project;result.append(topic);
 }inputs.hidden=true;followup.hidden=receipt.local;if(receipt.local){const note=document.createElement('p');note.textContent=t('No team was notified. Open the shared project to submit a request.');result.append(note);}result.focus();}
 form.querySelector('[data-lead-again]')?.addEventListener('click',()=>{receipt=null;inputs.hidden=false;followup.hidden=true;result.textContent='';delete result.dataset.success;form.querySelector('[name=name]').focus();});
 document.addEventListener('ecocharge:locale',showReceipt);
 form.addEventListener('submit',async e=>{e.preventDefault();if(pending||receipt)return;const fields=Object.fromEntries(new FormData(form)),error=EcoLeadForm.validate(fields)||(fields.miningInquiry?window.EcoMiningUI.validate():'')||((fields.solarRequestType||fields.solarSystem)?window.EcoSolar.validate(fields):'');delete result.dataset.success;if(error){showError(error);return;}clearError();pending=true;button.disabled=true;result.textContent=t('Sending your request…');result.dataset.error='false';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);
 try{const payload={name:fields.name.trim(),phone:(fields.phone||'').trim(),email:(fields.email||'').trim(),website:fields.website,consent:fields.consent==='on',smsConsent:fields.smsConsent==='on',emailConsent:fields.emailConsent==='on',consentVersion:fields.consentVersion,consentLanguage:window.EcoLocale?.language==='ru'?'ru':'en',marketingConsent:fields.marketingConsent==='on',marketingConsentVersion:fields.marketingConsentVersion,attribution:window.EcoPlatform?.currentAttribution?.()||window.EcoPlatform?.attribution()||{},context:typeof location==='object'?{contactTimezone:fields.contactTimezone||'',tierId:new URL(location.href).searchParams.get('tier'),tab:new URL(location.href).searchParams.get('tab')||new URL(location.href).searchParams.get('next')}:{}};if((fields.solarRequestType||fields.solarSystem)){payload.context.intent='solar_purchase';payload.context.solar={requestType:fields.solarRequestType,country:fields.solarCountry,chargerId:fields.solarCharger,vehicle:fields.solarVehicle,systemId:fields.solarSystem,zip:fields.solarZip,property:fields.solarProperty,billMonthly:fields.solarBill,battery:fields.solarBattery,panelId:fields.solarPanel,batteryModelId:fields.solarBatteryModel};}if(fields.miningInquiry){payload.context.intent='mining';payload.context.mining=window.EcoMiningUI.input();}const topic=fields.journeyTopic||(fields.miningInquiry?'mining':fields.solarRequestType==='charging'?'charge':fields.solarRequestType||fields.solarSystem?'solar':(typeof location==='object'?new URL(location.href).searchParams.get('topic'):null)||'energy');payload.context.journey={route:fields.journeyRoute||'fast',topic,purpose:fields.journeyRoute==='nurture'?'updates':fields.journeyPurpose||(fields.solarRequestType||fields.solarSystem?'equipment':fields.miningRoute==='purchase'?'equipment':'participation'),country:fields.journeyCountry||fields.solarCountry||fields.miningCountry||'US'};if(topic==='charge'&&window.EcoPublicPlanUI?.context()){payload.context.projectCalculation=window.EcoPublicPlanUI.context();payload.context.tierId=payload.context.projectCalculation.tierId;}const base=window.ECO_PLATFORM_CONFIG?.apiBase;
  if(window.EcoSandbox){const data=await window.EcoSandbox.request('public/leads','POST',payload);receipt={...payload,id:data.id,duplicate:!!data.duplicate,sandbox:true};}
  else if(!base){receipt={...payload,local:true};}
  else{const r=await fetch(new URL('api/leads',base),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});const data=await r.json();if(!r.ok||!data.accepted||!data.id)throw Error('not accepted');receipt={...payload,id:data.id,duplicate:!!data.duplicate};}
  if(!receipt.local)window.EcoChargeFunnel?.track(fields.miningInquiry?'mining_inquiry_requested':(fields.solarRequestType||fields.solarSystem)?'solar_quote_requested':payload.context.journey.topic==='club'?'club_request_saved':payload.context.journey.route==='nurture'?'project_interest_saved':'consultation_requested',{journey:payload.context.journey.route,topic:payload.context.journey.topic,purpose:payload.context.journey.purpose,country:payload.context.journey.country,duplicate:!!receipt.duplicate,deliveryMode:receipt.sandbox?'sandbox':receipt.local?'local':'server'});
  showReceipt();
 }catch{track('lead_request_failed');result.dataset.error='true';result.textContent=t('Your request was not sent. Your details are kept. Check the connection and try again.');result.focus();}finally{clearTimeout(timer);pending=false;button.disabled=false;}});
 });})();
