'use strict';
(()=>{const form=document.querySelector('[data-mining-form]');if(!form)return;
 const M=window.EcoMining,t=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en,T=s=>window.EcoLocale?.t(s)||s,calc=document.querySelector('[data-mining-calculator]'),field=n=>form.elements.namedItem(n),fmt=n=>new Intl.NumberFormat(window.EcoLocale?.language==='ru'?'ru-RU':'en-US',{style:'currency',currency:'USD'}).format(n);
 let attached=null,expanded=false;
 const raw=()=>Object.fromEntries(new FormData(calc));
 function input(){return {route:field('miningRoute').value,country:field('miningCountry').value,minerId:field('miningMiner').value,coinId:field('miningCoin').value,budgetUsd:field('miningBudget').value,units:field('miningUnits').value,note:field('miningNote').value,...(attached?{calculation:attached}:{})};}
 function paint(){const units=['purchase','hosted'].includes(field('miningRoute').value);field('miningUnits').disabled=!units;document.querySelector('[data-mining-units]').hidden=!units;document.querySelector('[data-mining-attached]').hidden=!attached;document.querySelector('[data-mining-attached]').textContent=t('Your scenario inputs will be sent with this request. They are not a price or return promise.','Допущения расчёта будут переданы с заявкой. Это не обещание цены или дохода.');}
 function recalc(){const water=document.querySelector('[data-mining-waterfall]'),cards=document.querySelector('[data-mining-scenarios]');try{const v=raw();updateLabels();const a=M.calculate(v),series=M.scenarios(v),items=[[t('Gross revenue','Валовая выручка'),a.gross],[t('Electricity','Электроэнергия'),-a.energy],[t('Pool fee','Комиссия пула'),-a.fee],[t('Other operating costs','Другие расходы'),-a.maintenance],[t('Operating result','Операционный результат'),a.net]];water.replaceChildren();items.forEach(([label,value],i)=>{const row=document.createElement('div');row.className='mining-water-row'+(i===4?' total':'');const name=document.createElement('span'),amount=document.createElement('strong');name.textContent=label;amount.textContent=fmt(value);amount.setAttribute('translate','no');row.append(name,amount);water.append(row);});cards.replaceChildren();series.forEach((s,i)=>{const card=document.createElement('article'),h=document.createElement('h3'),total=document.createElement('strong'),period=document.createElement('p'),share=document.createElement('p');h.textContent=[t('Conservative · −25% revenue','Консервативный · −25% выручки'),t('Base · your assumptions','Базовый · ваши допущения'),t('Strong · +25% revenue','Сильный · +25% выручки')][i];total.textContent=fmt(s.net);total.dataset.loss=String(s.net<0);total.setAttribute('translate','no');period.textContent=t('Project operating result / day','Операционный результат проекта / сутки');share.textContent=t('Illustrative share: ','Доля в примере: ')+v.share+'% → '+fmt(s.shareNet)+t(' / day',' / сутки');share.setAttribute('translate','no');card.append(h,total,period,share);cards.append(card);});scaleResults(v);if(attached){attached={...v};field('miningCoin').value=v.coinId;filterRequestModels();field('miningMiner').value=v.minerId;document.querySelector('[data-mining-calculation-status]').textContent=t('The updated assumptions are attached to your request.','Обновлённые допущения прикреплены к заявке.');}}catch(e){water.textContent=T(e.message);cards.replaceChildren();document.querySelector('[data-mining-scale-results]').replaceChildren();attached=null;document.querySelector('[data-mining-calculation-status]').textContent='';paint();}}
 function focusRequest(){document.getElementById('mining-request').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});field('miningRoute').focus({preventScroll:true});}
 document.querySelectorAll('[data-mining-route]').forEach(b=>b.addEventListener('click',()=>{field('miningRoute').value=b.dataset.miningRoute;paint();focusRequest();}));
 document.querySelectorAll('[data-mining-pick]').forEach(b=>b.addEventListener('click',()=>{selectCalc(b.dataset.miningPick);field('miningCoin').value=M.find(b.dataset.miningPick).coinId;filterRequestModels();field('miningMiner').value=b.dataset.miningPick;recalc();document.getElementById('mining-economics').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});calc.elements.minerId.focus({preventScroll:true});}));
 document.querySelector('[data-mining-attach]').addEventListener('click',()=>{try{M.scenarios(raw());attached={...raw()};field('miningCoin').value=attached.coinId;filterRequestModels();field('miningMiner').value=attached.minerId;paint();document.querySelector('[data-mining-calculation-status]').textContent=t('Scenario attached to your request.','Расчёт прикреплён к заявке.');focusRequest();}catch(e){document.querySelector('[data-mining-calculation-status]').textContent=T(e.message);}});
 calc.addEventListener('input',e=>{if(e.target.tagName!=='SELECT')recalc();});calc.addEventListener('change',e=>{if(e.target.name==='coinId')selectCalc(M.miners.find(m=>m.coinId===e.target.value).id);else if(e.target.name==='minerId')selectCalc(e.target.value);recalc();});calc.addEventListener('submit',e=>e.preventDefault());field('miningRoute').addEventListener('change',paint);document.addEventListener('ecocharge:locale',()=>{paint();recalc();catalog();});
 window.EcoMiningUI={input,validate(){try{M.inquiry(input());return '';}catch(e){return e.message;}}};
 function selectCalc(id){const m=M.find(id),changed=calc.elements.coinId.value!==m.coinId;calc.elements.coinId.value=m.coinId;for(const o of calc.elements.minerId.options){o.hidden=M.find(o.value).coinId!==m.coinId;o.disabled=o.hidden;}calc.elements.minerId.value=id;if(changed)calc.elements.hashprice.value=M.coins[m.coinId].exampleHashprice;}
function updateLabels(){const coin=M.coins[calc.elements.coinId.value];document.querySelector('[data-mining-hash-label]').textContent=t('Gross revenue','Валовая выручка')+' · USD / '+coin.revenueUnit+t(' / day',' / сутки');document.querySelector('[data-mining-coin-note]').textContent=coin.ticker+' · '+coin.algorithm+'. '+(calc.elements.coinId.value==='ltc-doge'?t('Enter the combined LTC + DOGE gross revenue once.','Укажите суммарную выручку LTC + DOGE один раз.'):t('The preset is an example, not a current market quote.','Начальное значение — пример, а не текущая рыночная котировка.'));document.querySelectorAll('[data-mining-scale]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.miningScale===calc.elements.units.value)));}
function scaleResults(v){const box=document.querySelector('[data-mining-scale-results]');box.replaceChildren();const title=document.createElement('p');title.textContent=t('Same miner and assumptions · operating result per day','Один майнер и те же допущения · результат за сутки');box.append(title);for(const units of [1,10,100]){const a=M.calculate({...v,units}),row=document.createElement('div'),label=document.createElement('span'),value=document.createElement('strong');label.textContent=units+' ASIC · '+(M.find(v.minerId).powerW*units/1000).toLocaleString(window.EcoLocale?.language==='ru'?'ru-RU':'en-US')+' kW';value.textContent=fmt(a.net);value.dataset.loss=a.net<0;row.append(label,value);box.append(row);}}
function filterRequestModels(){const c=field('miningCoin').value;for(const o of field('miningMiner').options){o.hidden=!!(o.value&&c&&M.find(o.value).coinId!==c);o.disabled=o.hidden;}if(field('miningMiner').value&&c&&M.find(field('miningMiner').value).coinId!==c)field('miningMiner').value='';}
function detach(){attached=null;document.querySelector('[data-mining-calculation-status]').textContent=t('Selection changed. Attach a new calculation if needed.','Выбор изменён. При необходимости прикрепите новый расчёт.');paint();}
field('miningCoin').addEventListener('change',()=>{filterRequestModels();detach();});
field('miningMiner').addEventListener('change',()=>{if(field('miningMiner').value){field('miningCoin').value=M.find(field('miningMiner').value).coinId;filterRequestModels();}detach();});
function catalog(){const coin=document.querySelector('[data-mining-filter]').value,cards=[...document.querySelectorAll('[data-mining-card]')],matches=cards.filter(c=>coin==='all'||c.dataset.miningCard===coin);cards.forEach(c=>c.hidden=!matches.includes(c)||(!expanded&&matches.indexOf(c)>=6));document.querySelector('[data-mining-more]').hidden=expanded||matches.length<=6;document.querySelector('[data-mining-count]').textContent=t('Shown ','Показано ')+Math.min(expanded?matches.length:6,matches.length)+t(' of ',' из ')+matches.length;}
document.querySelector('[data-mining-filter]').addEventListener('change',()=>{expanded=false;catalog();});document.querySelector('[data-mining-more]').addEventListener('click',()=>{expanded=true;catalog();});document.querySelectorAll('[data-mining-scale]').forEach(b=>b.addEventListener('click',()=>{calc.elements.units.value=b.dataset.miningScale;recalc();}));
calc.elements.coinId.value='btc';selectCalc('s21-pro');filterRequestModels();catalog();paint();recalc();

})();

