'use strict';
(()=>{
 const section=document.querySelector('#project-calculator');if(!section)return;
 const form=section.querySelector('[data-public-plan-form]'),M=window.EcoPublicPlan,F=window.EcoFinance,params=new URL(location).searchParams;
 const t=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en,locale=()=>window.EcoLocale?.language==='ru'?'ru-RU':'en-US',money=n=>new Intl.NumberFormat(locale(),{style:'currency',currency:'USD'}).format(n),q=s=>section.querySelector(s);
 let current=null,edited=false;
 const tier=F.tiers.find(v=>v.id===params.get('tier'))||F.tiers[0];form.elements.tierId.value=tier.id;form.elements.capital.value=params.get('amount')||tier.minimum;form.elements.start.value=params.get('start')||new Date().toISOString().slice(0,10);
 function track(name){window.EcoChargeFunnel?.track(name,{page:document.documentElement.dataset.page,topic:'charge',tier:form.elements.tierId.value});}
 function render(){
  const selected=F.tiers.find(v=>v.id===form.elements.tierId.value);q('[data-public-plan-limits]').textContent=t('Minimum: ','Минимум: ')+money(selected.minimum)+t(' · All amounts in USD',' · Все суммы в USD');
  for(const el of [form.elements.capital,form.elements.start])el.removeAttribute('aria-invalid');
  try{current=M.calculate(Object.fromEntries(new FormData(form)));q('[data-public-plan-error]').textContent='';q('[data-public-plan-week]').textContent=money(current.weekly);q('[data-public-plan-rate]').textContent=current.rate.toLocaleString(locale())+'%';q('[data-public-plan-month]').textContent=money(current.monthly);const date=s=>new Intl.DateTimeFormat(locale(),{dateStyle:'medium',timeZone:'UTC'}).format(new Date(s+'T00:00:00Z'));q('[data-public-plan-period]').textContent=date(current.start)+' → '+date(current.end);}
  catch(e){current=null;const amount=e.message.includes('amount');(amount?form.elements.capital:form.elements.start).setAttribute('aria-invalid','true');q('[data-public-plan-error]').textContent=amount?t('Enter at least '+money(selected.minimum)+' and no more than '+money(F.maximum)+'.','Введите сумму от '+money(selected.minimum)+' до '+money(F.maximum)+'.'):t('Choose a valid calculation start date.','Укажите корректную дату начала расчёта.');for(const key of ['week','rate','month','period'])q('[data-public-plan-'+key+']').textContent='—';}
  q('[data-public-plan-download]').disabled=!current;
  const link=q('[data-public-plan-details]');link.setAttribute('aria-disabled',String(!current));const same=document.documentElement.dataset.page==='participate/charge';const url=new URL('participate/charge/',document.baseURI);url.searchParams.set('lang',window.EcoLocale?.language||'en');if(current){url.searchParams.set('tier',current.tierId);url.searchParams.set('amount',current.capital);url.searchParams.set('start',current.start);}url.hash='request-access';link.href=same?'#request-access':url.href;
  const note=document.querySelector('[data-public-plan-attached]');if(note)note.textContent=current?t('Your request will include: ','В заявку попадёт: ')+form.elements.tierId.selectedOptions[0].textContent+' · '+money(current.capital)+' · '+current.start:'';
 }
 function change(e){if(e.target.name==='tierId'){const next=F.tiers.find(v=>v.id===e.target.value);if(!F.eligible(F.parseAmount(form.elements.capital.value),next.id))form.elements.capital.value=next.minimum;}render();q('[data-public-plan-status]').textContent='';if(!edited){track('project_calculation_started');edited=true;}}
 form.addEventListener('input',e=>{if(e.target.tagName!=='SELECT')change(e);});form.addEventListener('change',change);form.addEventListener('submit',e=>e.preventDefault());document.addEventListener('ecocharge:locale',render);
 q('[data-public-plan-details]').addEventListener('click',e=>{if(!current){e.preventDefault();form.querySelector('[aria-invalid=true]')?.focus();return;}track('project_details_requested');});
 q('[data-public-plan-download]').addEventListener('click',()=>{if(!current)return;const text=['EcoGrid Charge',t('Plan calculation','Расчёт плана'),form.elements.tierId.selectedOptions[0].textContent,t('Capital: ','Капитал: ')+money(current.capital),t('Start date (UTC): ','Дата начала (UTC): ')+current.start,t('Monthly plan rate: ','Месячная ставка плана: ')+current.rate+'%',t('Next 7 days: ','Ближайшие 7 дней: ')+money(current.weekly),t('Full calendar month: ','Полный календарный месяц: ')+money(current.monthly),t('Calculated using the calendar-month plan model, without compounding. This is not a forecast of station revenue or a guarantee. Review project costs and exit terms separately.','Расчёт по календарной модели плана без капитализации. Это не прогноз выручки станции и не гарантия. Расходы и условия выхода изучаются отдельно.'),new URL('terms/',document.baseURI).href].join('\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='EcoGrid-Charge-'+current.start+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);q('[data-public-plan-status]').textContent=t('Your calculation is ready to download.','Расчёт подготовлен к скачиванию.');track('project_calculation_downloaded');});
 window.EcoPublicPlanUI={context:()=>current?M.normalize(current):null};render();
})();
