'use strict';
window.EcoArcade=(()=>{
 const M=window.EcoArcadeModel,t=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en;
 const key=()=>`eco-energy-run-v1:${window.ECO_SHARED_CONTEXT?.client.id||'guest'}`;
 let root,canvas,ctx,frame=0,last=0,run=null,saved=M.records(),track='city',observer,language,completed=false,storageAvailable=true;
 const reduce=matchMedia('(prefers-reduced-motion: reduce)'),names=()=>({city:t('Solar district','Солнечный квартал'),highway:t('Storage highway','Энергетическая магистраль'),coast:t('Pacific coast','Тихоокеанское побережье')});
 function load(){storageAvailable=true;try{saved=M.records(JSON.parse(localStorage.getItem(key())||'{}'));}catch{saved=M.records();storageAvailable=false;}}
 function sidebar(){return `<section class="eco-card"><h2>${t('Personal best','Личный рекорд')}</h2><b class="arcade-record">${saved.best}</b><small>${t('Points · saved on this device','Очки · сохранены на этом устройстве')}</small><p class="arcade-note">${t('Completed runs','Завершено заездов')}: ${saved.runs} · ${t('Cells','Капсулы')}: ${saved.cells}</p></section><section class="eco-card"><h2>${t('Choose your route','Выберите маршрут')}</h2>${M.tracks.map(v=>`<button type="button" class="arcade-track" data-track="${v.id}" aria-pressed="${track===v.id}" ${saved.runs<v.runs||run?.status==='playing'?'disabled':''}><span>${names()[v.id]}${saved.runs<v.runs?`<small>${t('Complete','Завершите')} ${v.runs} ${t(v.runs===1?'run to unlock':'runs to unlock',v.runs===1?'заезд для открытия':'заезда для открытия')}</small>`:''}</span><i aria-hidden="true"></i></button>`).join('')}</section><section class="eco-card"><h2>${t('Achievements','Достижения')}</h2>${[[saved.runs>0,t('First finish','Первый финиш'),t('Complete one run','Завершите один заезд')],[saved.collector,t('Energy collector','Коллекционер энергии'),t('Collect 15 cells in one run','Соберите 15 капсул за заезд')],[saved.clean,t('Clean drive','Чистый маршрут'),t('Finish without hitting an obstacle','Финишируйте без столкновений')]].map(([yes,title,copy])=>`<div class="arcade-achievement" data-earned="${yes}"><b>${yes?'✓ ':''}${title}</b><small>${copy}</small></div>`).join('')}</section>`;}
 function mount(host){unmount();if(!window.ECO_SHARED_CONTEXT?.client)return;root=host;language=window.EcoLocale?.language;load();root.innerHTML=`<div id="energy-run"><div class="arcade-head"><div><span class="arcade-free">${t('ARCADE / FREE TO PLAY','ПЕРЕРЫВ / БЕСПЛАТНО')}</span><h1>Energy Run</h1><p>${t('Drive from the solar district to the charging hub. Collect consecutive cells to build your score streak.','Пройдите маршрут от солнечного квартала до зарядного хаба. Собирайте капсулы подряд — серия увеличивает очки.')}</p></div><button class="eco-text" data-eco-route="dashboard">${t('Back to overview','К обзору')} ↗</button></div><div class="arcade-layout"><div><div class="arcade-route-banner"><span data-route-name>${names()[track]}</span><span>${t('45 sec · 3 lanes','45 сек · 3 полосы')}</span></div><div class="arcade-board"><div class="arcade-hud" aria-hidden="true"><span>${t('Time left','Осталось')}<b data-time>45</b></span><span>${t('Points','Очки')}<b data-score>0</b></span><span>${t('Cells','Капсулы')}<b data-cells>0</b></span><span>${t('Streak','Серия')}<b data-streak>0</b></span></div><div class="arcade-route-progress" role="progressbar" aria-label="${t('Route completed','Маршрут пройден')}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i data-run-progress></i></div><canvas tabindex="0" aria-label="${t('Energy Run. Steer with left and right arrows, mouse or touch. Escape pauses.','Energy Run. Управляйте стрелками, мышью или пальцем. Escape — пауза.')}"></canvas><div class="arcade-overlay"><div><strong data-run-title></strong><p data-run-message></p><button type="button" class="eco-button" data-arcade-overlay-play></button></div></div><div class="arcade-controls"><button class="steer" data-steer="-1" aria-label="${t('Steer left','Налево')}">←</button><button class="eco-button" data-arcade-play></button><button class="steer" data-steer="1" aria-label="${t('Steer right','Направо')}">→</button><button class="eco-button secondary" data-arcade-pause>${t('Pause','Пауза')}</button></div></div><div class="arcade-route-steps" aria-hidden="true"><span data-run-leg="0">${t('Solar district','Солнечный квартал')}</span><span data-run-leg="1">${t('Battery storage','Накопители')}</span><span data-run-leg="2">${t('Charging hub','Зарядный хаб')}</span></div><p class="arcade-status" role="status" aria-live="polite"></p><p class="arcade-note">${t('Free after registration. Points have no monetary value and do not affect your balance, plan or accrual. Records stay on this browser and device.','Бесплатно после регистрации. Очки не имеют денежной стоимости и не влияют на баланс, план или начисления. Рекорд хранится в этом браузере на этом устройстве.')}</p><p class="arcade-note">${t('Mouse / drag to steer · ← → keys · Escape to pause. The run pauses when you leave the tab.','Мышь / движение пальцем · клавиши ← → · Escape — пауза. При уходе из вкладки игра останавливается.')}</p></div><aside class="arcade-side">${sidebar()}</aside></div></div>`;
  canvas=root.querySelector('canvas');ctx=canvas.getContext('2d');if(!ctx){root.querySelector('.arcade-status').textContent=t('Canvas is unavailable in this browser.','Canvas недоступен в этом браузере.');return;}
  if(!run)run=M.create({track});canvas.addEventListener('pointerdown',pointer);canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||e.buttons)pointer(e)});canvas.addEventListener('pointercancel',pause);root.querySelector('#energy-run').addEventListener('click',click);observer=new ResizeObserver(resize);observer.observe(canvas);document.addEventListener('keydown',keyboard);document.addEventListener('visibilitychange',visibility);window.addEventListener('blur',pause);resize();paintUI();
 }
 function resize(){if(!canvas||!ctx)return;const box=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(box.width*dpr);canvas.height=Math.round(box.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
 function pointer(e){if(run?.status!=='playing')return;const rect=canvas.getBoundingClientRect();M.move(run,(e.clientX-rect.left)/rect.width);if(e.type==='pointerdown'){canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);}if(e.cancelable)e.preventDefault();}
 function steer(delta){M.move(run,run.target+delta/3);}
 function keyboard(e){if(!root?.isConnected||e.target.matches('input,textarea,select'))return;if(e.key==='Escape'){pause();return;}if(e.code==='Space'&&e.target===canvas){e.preventDefault();if(run?.status==='playing')pause();else play();return;}if(run?.status==='playing'&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();steer(e.key==='ArrowLeft'?-1:1);}}
 function click(e){const b=e.target.closest('button');if(!b)return;if((b.hasAttribute('data-arcade-play')||b.hasAttribute('data-arcade-overlay-play')))play();if(b.hasAttribute('data-arcade-pause'))pause();if(b.dataset.steer&&run)steer(Number(b.dataset.steer));if(b.dataset.track&&M.available(saved).includes(b.dataset.track)&&run?.status!=='playing'){track=b.dataset.track;run=M.create({track});completed=false;paintUI();draw();}}
 function play(){if(!ctx||run?.status==='playing')return;if(!run||run.status==='ready'||run.status==='finished'){run=M.create({seed:crypto.getRandomValues(new Uint32Array(1))[0],track});completed=false;}run.status='playing';last=0;paintUI();canvas.scrollIntoView({block:'center',behavior:'instant'});canvas.focus({preventScroll:true});cancelAnimationFrame(frame);frame=requestAnimationFrame(tick);}
 function pause(){if(run?.status!=='playing')return;run.status='paused';cancelAnimationFrame(frame);frame=0;paintUI();draw();}
 function visibility(){if(document.hidden)pause();}
 function tick(time){if(!root?.isConnected||run.status!=='playing')return;const delta=last?(time-last)/1000:0;last=time;M.step(run,delta);draw();hud();if(run.status==='finished'){if(!completed){saved=M.complete(saved,run);completed=true;try{localStorage.setItem(key(),JSON.stringify(saved));}catch{storageAvailable=false;}}paintUI();return;}frame=requestAnimationFrame(tick);}
 function hud(){root.querySelector('[data-time]').textContent=Math.ceil(M.duration-run.time);root.querySelector('[data-score]').textContent=run.score;root.querySelector('[data-cells]').textContent=run.energy;root.querySelector('[data-streak]').textContent=run.streak;root.querySelector('[data-run-progress]').style.width=(run.time/M.duration*100)+'%';root.querySelector('.arcade-route-progress').setAttribute('aria-valuenow',Math.round(run.time/M.duration*100));root.querySelectorAll('[data-run-leg]').forEach(el=>el.dataset.reached=String(run.time>=Number(el.dataset.runLeg)*15));root.querySelector('[data-route-name]').textContent=names()[track];}
 function paintUI(){if(!root?.isConnected||!run)return;const playing=run.status==='playing',finished=run.status==='finished';root.querySelector('.arcade-board').classList.toggle('is-playing',playing);root.querySelector('.arcade-overlay').hidden=playing;root.querySelector('[data-run-title]').textContent=finished?t('Finish. '+run.score+' points','Финиш. '+run.score+' очков'):run.status==='paused'?t('Your run is paused','Заезд на паузе'):t('Power the journey.','Зарядите маршрут.');root.querySelector('[data-run-message]').textContent=finished?t(`${run.energy}/15 cells · best streak ${run.bestStreak} · ${run.hits} hits.`,`${run.energy}/15 капсул · лучшая серия ${run.bestStreak} · столкновений: ${run.hits}.`):t('Collect 15 energy cells before the finish. Every 5 in a row unlocks a points bonus. Avoid the orange barriers.','Соберите 15 капсул до финиша. Каждые 5 подряд добавляют бонус к очкам. Обходите оранжевые барьеры.');root.querySelector('[data-arcade-play]').textContent=playing?t('Driving…','Заезд…'):run.status==='paused'?t('Resume run','Продолжить'):finished?t('Drive again','Ещё заезд'):t('Start 45-second run','Старт · 45 секунд');root.querySelector('[data-arcade-play]').disabled=playing;root.querySelector('[data-arcade-overlay-play]').textContent=root.querySelector('[data-arcade-play]').textContent;root.querySelector('[data-arcade-pause]').disabled=!playing;root.querySelector('.arcade-side').innerHTML=sidebar();root.querySelector('.arcade-status').textContent=!storageAvailable?t('Storage unavailable. This record cannot be saved on this device.','Хранилище недоступно. Рекорд на этом устройстве не сохранится.'):finished?t('Run complete. Your record and unlocked routes are saved.','Заезд завершён. Рекорд и открытые маршруты сохранены.'):run.status==='paused'?t('Paused. Resume whenever you are ready.','Пауза. Продолжите, когда будете готовы.'):'';hud();}
 function draw(){if(!ctx||!canvas||!run)return;const w=canvas.clientWidth,h=canvas.clientHeight,c=ctx,colors=track==='coast'?['#193e50','#bd917b','#102b38']:track==='highway'?['#081326','#457a9d','#112739']:['#0a2430','#779c82','#122b35'];c.clearRect(0,0,w,h);const sky=c.createLinearGradient(0,0,0,h);sky.addColorStop(0,colors[0]);sky.addColorStop(.5,colors[1]);sky.addColorStop(1,colors[2]);c.fillStyle=sky;c.fillRect(0,0,w,h);const horizon=h*.24;
  c.fillStyle=track==='coast'?'#d9b791':'#b5d4ab';c.beginPath();c.arc(w*.73,h*.19,track==='coast'?22:12,0,Math.PI*2);c.fill();c.fillStyle='#102e39';for(let i=0;i<14;i++){const x=i*w/13,bh=18+(i*29%65);c.fillRect(x,horizon-bh,w/18,bh);if(track==='city'){c.fillStyle='#abc77d55';for(let y=horizon-bh+7;y<horizon-5;y+=10)c.fillRect(x+5,y,3,3);c.fillStyle='#102e39';}}
  const road=y=>w*(.055+.92*y*y),py=y=>horizon+(h-horizon)*y,px=(x,y)=>w/2+(x-.5)*road(y);
  // Roadside solar fields, storage cabinets and charging pylons belong to the same route.
  const phase=reduce.matches?0:(run.time*.15)%1;
  for(let i=0;i<10;i++){
   const z=((i+phase)/10),scale=.12+z*z,yy=py(z),side=i%2?1:-1,xx=w/2+side*(road(z)*.63+25*scale);
   if(track==='coast'){
    c.fillStyle='#1b687279';c.fillRect(0,py(z),Math.max(0,px(0,z)-6),Math.max(1,3*scale));
   }
   if(i%3===0){
    const ww=46*scale,hh=25*scale;c.fillStyle='#25616d';c.strokeStyle='#7ba8a87a';c.lineWidth=1;c.beginPath();c.moveTo(xx-ww,yy-hh);c.lineTo(xx+ww*.7,yy-hh);c.lineTo(xx+ww,yy);c.lineTo(xx-ww*.7,yy);c.closePath();c.fill();c.stroke();for(let col=1;col<4;col++){c.beginPath();c.moveTo(xx-ww+col*ww*.425,yy-hh);c.lineTo(xx-ww*.7+col*ww*.425,yy);c.stroke();}c.fillStyle='#486670';c.fillRect(xx-ww*.45,yy,3*scale,13*scale);c.fillRect(xx+ww*.5,yy,3*scale,13*scale);
   }else if(i%3===1){
    const ww=18*scale,hh=44*scale;c.fillStyle='#537876';c.fillRect(xx-ww/2,yy-hh,ww,hh);c.fillStyle='#1d3d47';c.fillRect(xx-ww*.3,yy-hh*.85,ww*.6,hh*.3);c.fillStyle='#c8f276';c.fillRect(xx-ww*.25,yy-hh*.45,ww*.5,2*scale);
   }else{
    c.strokeStyle='#5b7c84';c.lineWidth=2*scale;c.beginPath();c.moveTo(xx,yy);c.lineTo(xx,yy-55*scale);c.lineTo(xx-side*20*scale,yy-62*scale);c.stroke();c.fillStyle='#d4edc8';c.fillRect(xx-side*20*scale-5*scale,yy-63*scale,10*scale,3*scale);
   }
  }
  c.fillStyle='#10232c';c.beginPath();c.moveTo(px(0,0),horizon);c.lineTo(px(1,0),horizon);c.lineTo(px(1,1),h);c.lineTo(px(0,1),h);c.closePath();c.fill();c.lineWidth=2;c.strokeStyle='#94c4b55e';for(const side of [0,1]){c.beginPath();for(let y=0;y<=1.01;y+=.025)c.lineTo(px(side,y),py(y));c.stroke();}
  const flow=reduce.matches?0:(run.time*.45)%1;c.strokeStyle='#a7c8c450';for(const lane of [1/3,2/3])for(let i=0;i<12;i++){const y=((i+flow)/12),z=Math.min(1,y+.027);c.lineWidth=1+y*2;c.beginPath();c.moveTo(px(lane,y),py(y));c.lineTo(px(lane,z),py(z));c.stroke();}
  for(const item of [...run.items].sort((a,b)=>a.y-b.y)){const y=Math.min(1,item.y),x=px(item.x,y),cy=py(y),r=6+18*y*y;if(item.kind==='energy'){c.fillStyle='#d5f98a';c.beginPath();c.moveTo(x,cy-r);c.lineTo(x+r*.65,cy);c.lineTo(x,cy+r);c.lineTo(x-r*.65,cy);c.closePath();c.fill();c.fillStyle='#276749';c.fillRect(x-2,cy-r*.4,4,r*.8);}else{c.fillStyle='#c18b68';c.fillRect(x-r,cy-r*.6,r*2,r*.8);c.fillStyle='#202d30';c.fillRect(x-r*.8,cy+r*.2,4,r*.4);c.fillRect(x+r*.6,cy+r*.2,4,r*.4);c.strokeStyle='#f8d6a9';c.lineWidth=2;c.beginPath();c.moveTo(x-r*.8,cy-r*.45);c.lineTo(x-r*.1,cy);c.moveTo(x+r*.1,cy-r*.45);c.lineTo(x+r*.8,cy);c.stroke();}}
  const x=px(run.x,.8),y=py(.8),carW=Math.min(48,w*.105),carH=carW*1.7;c.save();c.translate(x,y);c.fillStyle='#0005';c.beginPath();c.ellipse(0,carH*.2,carW*.8,carH*.6,0,0,Math.PI*2);c.fill();c.fillStyle=run.cooldown>0?'#dcc39c':'#dcece3';c.beginPath();c.moveTo(-carW*.32,-carH*.55);c.quadraticCurveTo(0,-carH*.7,carW*.32,-carH*.55);c.lineTo(carW*.5,carH*.42);c.quadraticCurveTo(0,carH*.55,-carW*.5,carH*.42);c.closePath();c.fill();c.fillStyle='#1b3c48';c.beginPath();c.moveTo(-carW*.26,-carH*.31);c.lineTo(carW*.26,-carH*.31);c.lineTo(carW*.34,-carH*.04);c.lineTo(-carW*.34,-carH*.04);c.fill();c.fillRect(-carW*.3,carH*.22,carW*.6,carH*.12);c.fillStyle='#dafb91';c.fillRect(-carW*.42,-carH*.42,carW*.18,3);c.fillRect(carW*.24,-carH*.42,carW*.18,3);c.fillStyle='#bf7b67';c.fillRect(-carW*.41,carH*.38,carW*.2,3);c.fillRect(carW*.21,carH*.38,carW*.2,3);c.restore();
  if(run.feedbackFor>0){c.save();c.globalAlpha=Math.min(1,run.feedbackFor*2);c.font='700 22px sans-serif';c.textAlign='center';c.fillStyle=run.feedback.startsWith('+')?'#dbff9c':'#ffc1a9';c.fillText(run.feedback,x,y-carH*.8-(.8-run.feedbackFor)*25);c.restore();}
  if(run.status==='playing'&&!reduce.matches){c.strokeStyle='#a4ebe01a';c.lineWidth=1;for(let j=0;j<4;j++){const yy=horizon+(h-horizon)*((run.time*.8+j*.23)%1);c.beginPath();c.moveTo(12,yy);c.lineTo(12,yy+17);c.moveTo(w-12,yy);c.lineTo(w-12,yy+17);c.stroke();}}
 }
 function unmount(){pause();cancelAnimationFrame(frame);frame=0;observer?.disconnect();document.removeEventListener('keydown',keyboard);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('blur',pause);root=null;canvas=null;ctx=null;}
 window.addEventListener('beforeunload',unmount);return {mount,unmount,get language(){return language}};
})();
