'use strict';
window.EcoClubUI=(()=>{
 const t=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en,E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),M=c=>(c/100).toLocaleString(window.EcoLocale?.locale||'en-US',{style:'currency',currency:'USD'}),D=d=>new Date(d).toLocaleDateString(window.EcoLocale?.locale||'en-US');
 const names=()=>({pending:t('Awaiting program / budget','Ожидает запуска / бюджета'),credited:t('Credited · model','Зачислено · модель'),held:t('Under review','На проверке'),ineligible:t('First funding below minimum','Первое пополнение ниже минимума'),rejected:t('Declined','Отклонено'),reversed:t('Reversed','Отменено')});
 let host=null,data=null,invite=null,busy=false,month='';
 async function api(path,body){const response=await fetch(new URL('api/'+path,document.baseURI),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),r=await response.json();if(!response.ok)throw Error(r.error||'Unable to load Club');return r;}
 const level=l=>t(l.en,l.ru);
 function markup(d,i){const link=new URL('register/',document.baseURI);link.searchParams.set('ref',i.code);link.searchParams.set('lang',window.EcoLocale?.language||'en');const r=d.rank,n=r.next,earned=d.rewards.filter(v=>v.status==='credited').reduce((s,v)=>s+v.amountCents,0);
 return `<div class="club" translate="no"><section class="club-pass"><div class="club-pass-main"><span class="club-eyebrow">EcoGrid · CLUB</span><h2>${t('Share EcoGrid with people you know.','Рекомендуйте EcoGrid знакомым.')}</h2><p>${t('Invite people you know. Share your personal link. One direct invitation, one reward.','Приглашайте знакомых. Отправьте личную ссылку. Одно личное приглашение — один бонус.')}</p><div class="club-rank"><span class="club-rank-dot" aria-hidden="true"></span><strong>${t('Member','Участник')}</strong><span>${r.days} ${t('days in the club','дней в клубе')}</span></div></div><aside class="club-offer"><span>${t('For a personal invitation','За личное приглашение')}</span><strong>${M(d.rules.referrerCents*(d.rules.campaign?.multiplier||1))}</strong><p>${t('Once, after your friend’s first confirmed funding of','Разово, после первого подтверждённого пополнения друга от')} ${M(d.rules.minimumCents)}.</p><span class="club-status">${d.rules.enabled?(d.rules.budgetAvailable?t('Reward program enabled','Программа включена'):t('Monthly budget used · rewards queue','Бюджет месяца исчерпан · бонусы в очереди')):t('Rewards await program activation','Бонусы ожидают запуска программы')}</span><small>${t('Subject to the acquisition budget.','В пределах бюджета привлечения.')}</small>${d.rules.welcomeCents?`<small>${t('Your friend’s welcome bonus: ','Приветственный бонус другу: ')+M(d.rules.welcomeCents)}</small>`:''}</aside></section>
 <section class="club-panel" data-club-ai translate="no"><div class="club-heading"><h3>EcoGrid AI</h3><span>${t('Included with Club','Входит в Club')}</span></div><p>${t('Every EcoGrid Club member can use our EcoGrid AI for free.','Каждый участник EcoGrid Club может бесплатно пользоваться нашим EcoGrid AI.')}</p><p>${t('Understand project data, compare energy-use scenarios and get clear explanations.','Разбирайтесь в данных проектов, сравнивайте сценарии использования энергии и получайте понятные объяснения.')}</p></section>
 <section class="club-share"><div><h3>${t('Your invitation','Ваше приглашение')}</h3><p>${t('Access starts with a request. The administrator assigns a manager.','Доступ начинается с заявки. Менеджера назначает администратор.')}</p></div><div><label class="club-sr" for="club-link">${t('Invitation link','Ссылка приглашения')}</label><div class="club-copy"><input id="club-link" readonly value="${E(link.href)}"><button type="button" class="eco-button" data-club-copy>${t('Copy link','Скопировать')}</button></div><small>${t('Share the link yourself. We do not message your contacts.','Отправьте ссылку сами. Клуб не рассылает сообщения вашим контактам.')}</small></div></section>
 <div class="club-metrics">${[[i.requests,t('Requests','Заявки')],[d.counts.registered,t('Personal accounts','Личные приглашения')],[d.counts.active,t('Active personal clients','Активные лично приглашённые')],[M(earned),t('Club credits · model','Бонусы Club · модель')]].map(([v,k])=>`<div><strong>${v}</strong><span>${k}</span></div>`).join('')}</div>
 <section class="club-panel"><div class="club-heading"><h3>${t('Club journal','Жизнь клуба')}</h3><span>${t('Published by your team','Публикации команды')}</span></div>${d.rules.campaign?`<article class="club-season"><span>${t('Seasonal invitation program','Сезонная программа приглашений')}</span><h4>${E(d.rules.campaign.title)}</h4><p>${d.rules.campaign.multiplier}× · ${D(d.rules.campaign.start)} — ${D(d.rules.campaign.end)} · ${t('Within the campaign and monthly budgets.','В пределах бюджета акции и месяца.')}</p></article>`:''}<div class="club-posts">${d.posts.map(p=>`<article><small>${E(p.author)} · ${D(p.date)}</small><h4>${E(p.title)}</h4><p>${E(p.text)}</p></article>`).join('')||`<p class="club-empty">${t('Read project updates and join the conversation in the Club feed.','Читайте новости проектов и участвуйте в обсуждении в ленте клуба.')}</p>`}</div><button class="eco-text" data-eco-route="feed">${t('Open the Club feed →','Открыть ленту клуба →')}</button></section>
 <details class="club-panel"><summary>${t('Reward history and rules','История бонусов и правила')}</summary><p>${t('Rewards come from a capped acquisition budget, never from a transfer out of a friend’s account. Further funding and second-generation invitations do not earn commissions.','Бонусы выделяются из ограниченного бюджета привлечения, без списания со счёта друга. Повторные пополнения и второй круг не дают комиссий.')}</p><p>${t('Only the first confirmed funding counts; smaller deposits are not combined. A pending reward is not part of your available balance. This build uses model credits; live payments remain disabled.','Учитывается только первое подтверждённое пополнение; небольшие платежи не суммируются. Ожидающий бонус не входит в доступный баланс. В этой сборке зачисления модельные, реальные платежи отключены.')}</p><p>${t('Plan rates and withdrawal terms stay the same.','Ставки плана и условия вывода не меняются.')}</p><div class="club-rewards">${d.rewards.map(r=>`<div><span>${D(r.date)} · ${r.side==='welcome'?t('Welcome','Приветственный'):t('Personal invitation','Личное приглашение')}</span><strong>${M(r.amountCents)}</strong><span>${names()[r.status]||E(r.status)}</span></div>`).join('')||`<p>${t('No reward records yet.','Записей о бонусах пока нет.')}</p>`}</div></details><p id="club-notice" role="status"></p></div>`;
 }
 async function load(){const h=host;if(!h?.isConnected)return;const [d,i]=await Promise.all([api('client/club'+(month?'?month='+encodeURIComponent(month):'')),api('client/invitations')]);if(host!==h||!h.isConnected)return;data=d;invite=i;h.classList.remove('eco-card');h.innerHTML=markup(d,i);}
 async function mount(h){if(!h)return;host=h;try{await load();}catch(e){if(h.isConnected)h.textContent=EcoClubModel.message(e.message,window.EcoLocale?.language);}}
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-club-copy]');if(!b)return;try{await navigator.clipboard.writeText(host.querySelector('#club-link').value);b.textContent=t('Copied','Скопировано');}catch{host.querySelector('#club-link').select();host.querySelector('#club-notice').textContent=t('Select and copy the link.','Выделите и скопируйте ссылку.');}});
 document.addEventListener('change',async e=>{if(!e.target.matches('[data-club-month]'))return;month=e.target.value;try{await load();}catch(err){host.querySelector('#club-notice').textContent=EcoClubModel.message(err.message,window.EcoLocale?.language);}});
 document.addEventListener('submit',async e=>{if(!e.target.matches('[data-club-preferences]'))return;e.preventDefault();if(busy)return;busy=true;const f=e.target,b=f.querySelector('button');b.disabled=true;try{await api('client/club/preferences',{clientId:window.ECO_SHARED_CONTEXT.client.id,alias:f.elements.alias.value,listed:f.elements.listed.checked});await load();host.querySelector('#club-notice').textContent=t('Visibility saved.','Видимость сохранена.');}catch(err){host.querySelector('#club-notice').textContent=EcoClubModel.message(err.message,window.EcoLocale?.language);}finally{busy=false;b.disabled=false;}});
 return {mount,markup};
})();
