'use strict';
(()=>{
 const t=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en,E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let posts=[],filter='all',loading=false,error='',editor=null,staffRoot=null,canPublish=false,busy=false,request=0;
 const preview=()=>window.ECO_PLATFORM_CONFIG?.clientPreview===true;
 const labels=()=>({all:t('All','Все'),news:t('News','Новости'),projects:t('Projects','Проекты'),offers:t('Offers','Акции'),guides:t('Guides','Полезное')});
 const text=(p,k)=>p[k+(window.EcoLocale?.language==='ru'?'Ru':'En')];
 const action=()=>({projects:t('Explore projects','Посмотреть проекты'),tariffs:t('Calculate a plan','Рассчитать план'),equipment:t('Choose equipment','Выбрать оборудование'),documents:t('Read the terms','Изучить условия'),help:t('Contact support','Открыть поддержку')});
 const reactionLabels=()=>({like:t('Like','Нравится'),useful:t('Useful','Полезно'),interested:t('Interested','Интересно')});
 const reactionIcon={like:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 5.8a5.4 5.4 0 0 0-7.6 0L12 7l-1.2-1.2a5.4 5.4 0 0 0-7.6 7.6L12 22l8.8-8.6a5.4 5.4 0 0 0 0-7.6Z" transform="translate(1 0) scale(.92)"/></svg>',useful:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-3H4ZM13 7a3 3 0 0 1 3-3h5v14h-4a4 4 0 0 0-4 3"/></svg>',interested:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 18h6m-5 3h4M8 14a7 7 0 1 1 8 0c-1 1-1 2-1 4H9c0-2 0-3-1-4Z"/></svg>'};
 async function api(route,method='GET',body){const res=await fetch(new URL('api/'+route,document.baseURI),{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await res.json();if(!res.ok)throw Error(data.error||t('Unable to load the feed.','Не удалось загрузить ленту.'));return data;}
 function local(){let chosen={};try{chosen=JSON.parse(localStorage.getItem('ecogrid-feed-reactions-v1')||'{}');}catch{}return EcoCommunityModel.seeds.map(p=>({...p,status:'published',myReaction:EcoCommunityModel.reactions.includes(chosen[p.id])?chosen[p.id]:'',reactions:Object.fromEntries(EcoCommunityModel.reactions.map(r=>[r,chosen[p.id]===r?1:0]))}));}
 function card(p,staff=false,compact=false){const expired=p.endsAt&&Date.parse(p.endsAt)<Date.now(),date=p.createdAt?new Intl.DateTimeFormat(window.EcoLocale?.locale||'en-US',{day:'numeric',month:'short'}).format(new Date(p.createdAt)):'';return `<article class="eg-post" data-post="${E(p.id)}"><header><span class="eg-post-brand"><img src="assets/ecocharge-mark.svg" width="28" height="28" alt=""></span><span><strong>EcoGrid</strong><small>${E(labels()[p.category])}${date?' · '+date:''}${p.pinned?' · '+t('Pinned','Закреплено'):''}</small></span>${staff?`<span class="eg-post-status">${E({draft:t('Draft','Черновик'),published:t('Published','Опубликовано'),archived:t('Archived','В архиве')}[p.status])}</span>`:''}</header><h2>${E(text(p,'title'))}</h2><p class="eg-post-body ${compact?'compact':''}">${E(text(p,'body'))}</p>${p.category==='offers'?`<div class="eg-post-terms"><b>${expired?t('Offer ended','Акция завершена'):t('Until ','До ')+E(new Date(p.endsAt).toLocaleDateString(window.EcoLocale?.locale||'en-US'))}</b><p>${E(text(p,'terms'))}</p></div>`:''}${!staff&&p.cta&&!expired?`<button class="eco-text" data-eco-route="${E(p.cta)}">${action()[p.cta]} →</button>`:''}<footer>${EcoCommunityModel.reactions.map(r=>`<button class="eg-reaction" ${staff?'disabled':''} data-community-reaction="${r}" data-post-id="${E(p.id)}" aria-label="${E(reactionLabels()[r])}" aria-pressed="${p.myReaction===r}"><span aria-hidden="true">${reactionIcon[r]}</span> ${reactionLabels()[r]} <b>${p.reactions?.[r]||0}</b></button>`).join('')}${staff&&canPublish?`<button class="eco-text" data-community-edit="${E(p.id)}">${t('Edit','Редактировать')}</button>`:''}</footer></article>`;}
 function accountUpdates(){
  if(typeof demo==='undefined')return '';
  const recent=(demo.sessions||[]).slice().sort((a,b)=>Date.parse(b.date)-Date.parse(a.date))[0],positions=window.EcoMiningPortfolio?.positions(demo)||[];
  if(!recent&&!positions.length)return '';
  const money=n=>new Intl.NumberFormat(window.EcoLocale?.locale||'en-US',{style:'currency',currency:'USD'}).format(n),stamp=d=>new Intl.DateTimeFormat(window.EcoLocale?.locale||'en-US',{day:'numeric',month:'long'}).format(new Date(d));
  return `<section class="eco-card eg-feed-account"><div class="eco-section-title"><h2>${t('Your project updates','Обновления ваших проектов')}</h2></div>${recent?`<button class="eg-feed-update" data-eco-event="credit:${E(recent.id)}"><span><strong>EcoGrid Charge · +${money(recent.payout)}</strong><small>${t('Weekly credit recorded','Недельное начисление учтено')} · ${stamp(recent.date)}</small></span><span aria-hidden="true">›</span></button>`:''}${positions.length?`<button class="eg-feed-update" data-action="eco-mining-details"><span><strong>EcoGrid Mining</strong><small>${positions.some(p=>(p.payouts||[]).length)?t('View recorded payouts and participation details','Посмотрите учтённые выплаты и параметры участия'):t('No payouts recorded yet. View participation details.','Выплаты пока не учтены. Откройте параметры участия.')}</small></span><span aria-hidden="true">›</span></button>`:''}</section>`;
 }
 function filters(staff=false){return `<nav class="eg-feed-filters" aria-label="${t('Feed categories','Категории ленты')}">${Object.entries(labels()).filter(([id])=>staff||id==='all'||posts.some(p=>p.category===id)).map(([id,name])=>`<button data-community-filter="${id}" aria-pressed="${filter===id}">${name}</button>`).join('')}</nav>`;}
 function message(){return error?`<p role="alert">${E(error)}</p><button class="eco-button secondary" data-community-refresh>${t('Try again','Повторить')}</button>`:loading?`<p role="status">${t('Loading feed…','Загружаем ленту…')}</p>`:'';}
 function content(staff=false){const rows=posts.filter(p=>filter==='all'||p.category===filter);return filters(staff)+message()+rows.map(p=>card(p,staff)).join('')+(!loading&&!error&&!rows.length?`<p class="eco-empty">${t('No posts in this category. Choose another category to continue reading.','В этой категории пока нет публикаций. Выберите другую, чтобы продолжить чтение.')}</p>`:'');}
 function paint(){const feed=document.querySelector('[data-community-feed]');if(feed)feed.innerHTML=content();const home=document.querySelector('[data-community-preview]');if(home)home.innerHTML=`<div class="eco-section-title"><h2>${t('EcoGrid feed','Лента EcoGrid')}</h2><button class="eco-text" data-eco-route="feed">${t('All posts →','Все публикации →')}</button></div>${message()}${[...posts].sort((a,b)=>Date.parse(b.updatedAt||b.createdAt||0)-Date.parse(a.updatedAt||a.createdAt||0)).slice(0,1).map(p=>card(p,false,true)).join('')}`;if(staffRoot?.isConnected&&!editor)staffRoot.innerHTML=`<section class="eg-community-staff"><div class="eco-section-title"><h1>${t('Client feed','Лента клиентов')}</h1>${canPublish?`<button class="eco-button" data-community-new>${t('Create post','Создать публикацию')}</button>`:''}</div><p>${canPublish?t('Published posts are visible to every client. Reactions are counted once per client.','Опубликованные записи видны всем клиентам. На каждый пост учитывается одна реакция клиента.'):t('This is what clients see. Only an administrator can publish or change posts.','Так публикации видят клиенты. Создавать и изменять записи может администратор.')}</p>${content(true)}</section>`;}
 async function load(staff=false){if(loading)return;loading=true;error='';paint();const token=++request;try{const result=preview()?{posts:local(),canPublish:false}:await api(staff?'staff/community':'client/community');if(token!==request)return;posts=result.posts;canPublish=result.canPublish;}catch(e){error=t('The feed could not load. Please retry.','Не удалось загрузить ленту. Попробуйте ещё раз.');}finally{loading=false;paint();}}
 function editorMarkup(){const p=editor;return `<section class="eg-community-staff"><h1>${p.id?t('Edit post','Редактировать публикацию'):t('New post','Новая публикация')}</h1><form id="community-editor"><div class="eg-editor-columns">${['Ru','En'].map(l=>`<fieldset><legend>${l==='Ru'?'Русский':'English'}</legend><label>${t('Title','Заголовок')}<input name="title${l}" maxlength="160" required value="${E(p['title'+l])}"></label><label>${t('Post text','Текст публикации')}<textarea name="body${l}" maxlength="6000" rows="7" required>${E(p['body'+l])}</textarea></label><label>${t('Offer conditions','Условия акции')}<textarea name="terms${l}" rows="3" maxlength="6000">${E(p['terms'+l])}</textarea></label></fieldset>`).join('')}</div><div class="eg-editor-columns"><label>${t('Category','Категория')}<select name="category">${EcoCommunityModel.categories.map(k=>`<option value="${k}" ${p.category===k?'selected':''}>${labels()[k]}</option>`).join('')}</select></label><label>${t('Button destination','Куда ведёт кнопка')}<select name="cta"><option value="">${t('No button','Без кнопки')}</option>${Object.entries(action()).map(([k,n])=>`<option value="${k}" ${p.cta===k?'selected':''}>${n}</option>`).join('')}</select></label><label>${t('Offer ends (UTC)','Конец акции (UTC)')}<input type="datetime-local" name="endsAt" value="${E(p.endsAt?.slice(0,16)||'')}"></label><label>${t('Status','Статус')}<select name="status">${['draft','published','archived'].map(k=>`<option value="${k}" ${p.status===k?'selected':''}>${{draft:t('Draft','Черновик'),published:t('Published','Опубликовано'),archived:t('Archived','В архиве')}[k]}</option>`).join('')}</select></label></div><label class="eg-pin"><input type="checkbox" name="pinned" ${p.pinned?'checked':''}>${t('Pin at top','Закрепить вверху')}</label><p>${t('Offers require an end date and conditions in both languages.','Для акции обязательны срок и условия на обоих языках.')}</p><p role="alert" id="community-feedback"></p><div class="eco-actions"><button class="eco-button" type="submit">${t('Save post','Сохранить публикацию')}</button><button class="eco-button secondary" type="button" data-community-cancel>${t('Cancel','Отмена')}</button></div></form></section>`;}
 document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-community-filter')){filter=b.dataset.communityFilter;paint();}if(b.hasAttribute('data-community-refresh'))load(!!staffRoot?.isConnected);if(b.hasAttribute('data-community-new')){editor={category:'news',status:'draft',cta:'',pinned:false};staffRoot.innerHTML=editorMarkup();}if(b.hasAttribute('data-community-edit')){editor=structuredClone(posts.find(p=>p.id===b.dataset.communityEdit));staffRoot.innerHTML=editorMarkup();}if(b.hasAttribute('data-community-cancel')){editor=null;paint();}
  if(b.hasAttribute('data-community-reaction')){if(busy)return;const p=posts.find(p=>p.id===b.dataset.postId);if(!p)return;const reaction=p.myReaction===b.dataset.communityReaction?'':b.dataset.communityReaction;busy=true;b.disabled=true;error='';try{if(preview()){const choices=Object.fromEntries(posts.map(x=>[x.id,x.myReaction]));choices[p.id]=reaction;localStorage.setItem('ecogrid-feed-reactions-v1',JSON.stringify(choices));posts=local();}else{const updated=await api('client/community/reaction','POST',{postId:p.id,reaction});posts=posts.map(x=>x.id===p.id?updated:x);}}catch{error=t('Reaction was not saved. Try again.','Реакция не сохранена. Попробуйте ещё раз.');}finally{busy=false;paint();document.querySelector(`[data-post-id="${p.id}"][data-community-reaction="${b.dataset.communityReaction}"]`)?.focus({preventScroll:true});}}
 });
 document.addEventListener('submit',async event=>{if(event.target.id!=='community-editor')return;event.preventDefault();if(busy)return;const form=event.target,values=Object.fromEntries(new FormData(form)),input={...editor,...values,pinned:values.pinned==='on',endsAt:values.endsAt?new Date(values.endsAt+'Z').toISOString():''};if(input.category==='offers'&&(!input.endsAt||!input.termsRu.trim()||!input.termsEn.trim())){form.querySelector('[role="alert"]').textContent=t('Enter the offer end date and conditions in both languages.','Укажите срок и условия акции на обоих языках.');return;}busy=true;form.querySelector('[type="submit"]').disabled=true;try{await api('staff/community','POST',input);editor=null;await load(true);}catch(e){form.querySelector('[role="alert"]').textContent=e.message;}finally{busy=false;form.querySelector('[type="submit"]')?.removeAttribute('disabled');}});
 window.EcoCommunityUI={page:()=>`<header class="eg-page-heading eg-editorial-heading"><span class="eco-kicker">ECOGRID</span><h1>${t('Stay connected','Будьте в курсе')}</h1><p>${t('News, project updates and useful guides from the team.','Новости, обновления проектов и полезные материалы команды.')}</p>${preview()?`<p class="eg-preview-reactions">${t('Reactions in this preview are saved on this device.','В этом просмотре реакции сохраняются на вашем устройстве.')}</p>`:''}</header>${accountUpdates()}<div data-community-feed></div>`,mount(){staffRoot=null;editor=null;paint();load();},staff(root){if(staffRoot===root&&root.querySelector('.eg-community-staff'))return;staffRoot=root;editor=null;paint();load(true);},unmount(){staffRoot=null;editor=null;}};
})();
