'use strict';
if(window.ECO_SHARED_CONTEXT)(()=>{
 const t=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en,E=escapeHtml,M=n=>new Intl.NumberFormat(window.EcoLocale?.locale||'en-US',{style:'currency',currency:'USD'}).format(n);
 const $=s=>document.querySelector(s),ui=()=>demo.ecosystem??={read:[],scenarios:[],timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'};
 const stationCount=n=>n+' '+t(n===1?'station':'stations',n%100>=11&&n%100<=14?'станций':n%10===1?'станция':n%10>=2&&n%10<=4?'станции':'станций');
 const date=v=>new Date(v).toLocaleString(window.EcoLocale?.locale||'en-US',{dateStyle:'short',timeStyle:'short',timeZone:ui().timezone||'UTC'});
 const calendarDate=v=>Number.isFinite(Date.parse(v))?new Intl.DateTimeFormat(window.EcoLocale?.locale||'en-US',{day:'numeric',month:'long',timeZone:ui().timezone||'UTC'}).format(new Date(v)):'—';
 const themeKey='ecogrid-theme',themeNow=()=>document.documentElement?.dataset.ecoTheme==='dark'?'dark':'light';
 const themeGlyph=theme=>theme==='dark'?'<svg class="eg-theme-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.93 4.93l1.42 1.42m11.3 11.3 1.42 1.42M2 12h2m16 0h2M4.93 19.07l1.42-1.42m11.3-11.3 1.42-1.42"/></svg>':'<svg class="eg-theme-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 14.2A8.4 8.4 0 0 1 9.8 3.5 8.5 8.5 0 1 0 20.5 14.2Z"/></svg>';
 function themeButton(){const dark=themeNow()==='dark',label=dark?t('Use light theme','Включить светлую тему'):t('Use dark theme','Включить тёмную тему');return `<button class="eco-icon eco-theme-toggle" type="button" data-eco-theme-toggle aria-pressed="${dark}" aria-label="${label}" title="${label}">${themeGlyph(dark?'dark':'light')}</button>`;}
 function applyTheme(theme){if(theme!=='light'&&theme!=='dark')return;document.documentElement.dataset.ecoTheme=theme;document.documentElement.style.colorScheme=theme;try{localStorage.setItem(themeKey,theme)}catch{}document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#191d20':'#f5f8f6');}
 let moneyFilter='all',days=30,helpQuery='',context='',contextData=null,lastBalance,identityMount;
 const button=(label,action,secondary=false)=>`<button class="eco-button ${secondary?'secondary':''}" data-action="${action}">${label}</button>`;
 const routeButton=(label,target,cls='eco-text')=>`<button class="${cls}" data-eco-route="${target}">${label}</button>`;
 const statuses=()=>({Pending:t('Pending review','На проверке'),Approved:t('Approved','Подтверждено'),Rejected:t('Declined','Отклонено')});
 function events(){const rows=[];
  for(const a of demo.adjustments||[])if(['club_reward','club_reverse'].includes(a.kind))rows.push({id:'adjustment:'+a.operationId,title:a.kind==='club_reward'?t('Club bonus · model','Бонус Club · модель'):t('Club bonus reversed','Бонус Club отменён'),detail:M(a.amount),date:a.date,type:'adjustment',amount:a.kind==='club_reward'?a.amount:-a.amount,operationId:a.operationId});
  for(const brief of demo.energyBriefs||[])rows.push({id:'brief:'+brief.id,title:window.EcoEnergyJournal?.titles()[brief.kind]||'Energy Lab',detail:brief.authorName+' · '+brief.text.slice(0,100),date:brief.createdAt,type:'brief',brief});
  if(demo.plan?.status==='active'&&window.EcoEnergyJournalModel){const report=EcoEnergyJournalModel.report(demo,window.EcoClientAccount.now());if(report.end>=Date.parse(demo.planHistory?.[0]?.date||demo.plan.appliedAt))rows.push({id:report.id,title:t('Monday report available','Отчёт понедельника доступен'),detail:t('Confirmed model credits','Подтверждённые модельные начисления')+' · '+M(report.cents/100),date:new Date(report.end).toISOString(),type:'report'});}
  for(const r of demo.requests)rows.push({id:'request:'+r.id+':'+r.status,title:(r.type==='topup'?t('Funding','Пополнение'):t('Withdrawal','Вывод'))+' · '+(statuses()[r.status]||r.status),detail:M(r.amount),date:r.reviewedAt||r.date,type:r.type,amount:r.amount,request:r});
  for(const a of demo.adjustments||[])if(['credit','debit'].includes(a.kind)&&!a.requestId){const mining=a.kind==='debit'&&(demo.miningPositions||[]).some(p=>p.id===a.operationId&&p.capital===a.amount);rows.push({id:'adjustment:'+a.operationId,title:mining?t('Capital allocated · EcoMiner','Средства направлены в EcoMiner'):a.kind==='credit'?t('Balance adjustment · credit','Корректировка · зачисление'):t('Balance adjustment · debit','Корректировка · списание'),detail:M(a.amount),date:a.date,type:'adjustment',amount:a.kind==='credit'?a.amount:-a.amount,operationId:a.operationId,position:mining?(demo.miningPositions||[]).find(p=>p.id===a.operationId):null});}
  for(const s of demo.sessions||[])rows.push({id:'credit:'+s.id,title:t('Weekly credit recorded','Недельное начисление записано'),detail:M(s.payout),date:s.date,type:'credit',amount:s.payout,session:s,operationId:s.id});
  for(const r of demo.tickets||[])if(r.reply)rows.push({id:'reply:'+r.id+':'+r.reply,title:t('Your manager replied','Менеджер ответил'),detail:r.subject||r.message,date:r.repliedAt||r.date,type:'reply',ticket:r});
  if(demo.plan)rows.push({id:'plan:'+demo.plan.appliedAt,title:t('Plan activated','План активирован'),detail:(window.EcoLocale?.t(demo.plan.name)||demo.plan.name)+' · '+M(demo.plan.capital),date:demo.plan.appliedAt,type:'plan'});
  if(demo.identityEvent?.updated&&demo.identityEvent.status!=='draft')rows.push({id:'identity:'+demo.identityEvent.updated,title:({submitted:t('Details sent to your manager','Анкета отправлена менеджеру'),reviewed:t('Your manager reviewed your documents','Менеджер просмотрел документы'),changes_requested:t('Your manager requested a clarification','Менеджер запросил уточнение')})[demo.identityEvent.status],detail:t('Documents & details','Документы и данные'),date:demo.identityEvent.updated,type:'identity'});
  return rows.sort((a,b)=>Date.parse(b.date)-Date.parse(a.date));
 }
 function operationDetails(v){
  const session=v.session,position=v.position,field=(label,value)=>`<div><dt>${label}</dt><dd>${E(value)}</dd></div>`;
  const project=session?'EcoGrid Charge':position?'EcoGrid Mining':t('Account balance','Баланс счёта');
  const amount=(v.amount>0?'+':v.amount<0?'−':'')+M(Math.abs(v.amount||0));
  return `<section class="eg-operation-details" translate="no"><span class="eg-status">${t('Recorded','Учтено')}</span><h2>${E(v.title)}</h2><strong class="eg-operation-amount">${amount}</strong><dl>${field(t('Project','Проект'),project)}${session?.planName?field(t('Plan at the time of credit','План на момент начисления'),window.EcoLocale?.t(session.planName)||session.planName):''}${session?.periodStart&&session?.periodEnd?field(t('Accrual period','Период начисления'),date(session.periodStart)+' — '+date(session.periodEnd)):''}${session&&Number.isFinite(session.capital)?field(t('Capital for this period','Сумма участия в этом периоде'),M(session.capital)):''}${position?field(t('Mining participation','Участие в майнинге'),M(position.capital)):''}${field(t('Recorded at','Дата операции'),date(v.date))}${field(t('Operation ID','Номер операции'),v.operationId||v.id)}</dl>${session?`<p>${t('This weekly model credit is included in your balance. It is separate from the current preliminary estimate.','Это недельное модельное начисление учтено в балансе. Текущий предварительный расчёт показан отдельно.')}</p>`:''}${button(t('Ask about this operation','Вопрос по этой операции'),'eco-message')}</section>`;
 }
 const unread=()=>events().filter(e=>!ui().read?.includes(e.id));
 const vDirection=e=>e.amount===undefined?'is-info':e.amount<0?'is-outgoing':'is-incoming';
 function rows(items){return items.length?items.map(e=>`<button class="eco-event" data-eco-event="${E(e.id)}"><span class="eco-event-dot ${vDirection(e)} ${ui().read?.includes(e.id)?'read':''}"></span><span><strong>${E(e.title)}</strong><small>${E(e.detail)}</small></span><time>${date(e.date)}</time><span>↗</span></button>`).join(''):`<p class="eco-empty">${t('New account activity will appear here.','Здесь появятся новые события по вашему счёту.')}</p>`;}
 function header(){if(!$('#eco-top')){const el=document.createElement('div');el.id='eco-top';el.setAttribute('translate','no');$('.main-nav').before(el);}const value=EcoFinance.summary(demo).available;$('#eco-top').innerHTML=`${window.EcoInstallApp?.header()||''}${window.ECO_SHARED_CONTEXT?`<button class="eco-icon eco-mobile-chat" data-open-live-chat aria-label="${t('Live chat','Чат с менеджером')}" aria-haspopup="dialog" aria-controls="ec-live-chat">${icon('chat')}<b class="eco-badge" data-chat-count hidden></b></button>`:''}<button data-live-wallet class="eco-wallet ${lastBalance!==undefined&&lastBalance!==value?'changed':''}" data-eco-route="money"><small>${t('Available','Доступно')}</small><b>${M(value)}</b></button><button class="eco-icon" aria-label="${t('Notifications','Уведомления')}" data-eco-route="notifications">${icon('bell')}<span class="eco-badge">${unread().length||''}</span></button><button class="eco-icon" aria-label="${t('Profile','Профиль')}" data-eco-route="profile">${icon('users')}</button>`;const languageSwitch=document.querySelector('[data-locale-switch]');document.querySelectorAll('[data-locale-switch]').forEach(el=>{if(el!==languageSwitch)el.remove();});if(languageSwitch)$('#eco-top').before(languageSwitch);document.querySelector('.eco-theme-toggle')?.remove();$('.topbar').insertAdjacentHTML('beforeend',themeButton());lastBalance=value;}
 const liveController=window.ecoLiveAccrualController=new LiveAccrualController({document,media:matchMedia('(prefers-reduced-motion: reduce)'),format:M,dayLabel:(day,active)=>active?t('Day '+day+' of 7','День '+day+' из 7'):t('Not active','Не активен'),labels:key=>key==='inactive'?t('Available after plan activation','После активации плана'):key==='closing'?t('Period ended · confirming model credit','Период завершён · зачисляем модельный расчёт'):t('Preliminary model accrual · daily demand rhythm (UTC)','Предварительный расчёт · суточный ритм спроса (UTC)'),onPeriodClose:start=>window.EcoClientAccrual.closePeriod(start),onTick:(payload,now)=>{window.EcoEnergyUI?.updateAccount(payload,now);window.EcoEnergyJournal?.tick(demo,payload,now);},onResume:()=>window.EcoClientAccrual.refresh()});liveController.update(window.ECO_SHARED_CONTEXT.liveAccrual);
 const energyActive=()=>EcoWorkspace.energyState(demo,window.ECO_SHARED_CONTEXT.liveAccrual).active;
 const weekRing=()=>energyActive()?(window.EcoEnergyUI?.weekRing()||''):'';
 function liveCard(){return `<section class="eco-live-card" translate="no"><div><span class="eco-kicker">${t('CURRENT WEEK ESTIMATE','РАСЧЁТ ТЕКУЩЕЙ НЕДЕЛИ')}</span><div class="energy-period-value"><strong data-live-accrual>${M(0)}</strong>${weekRing()}</div><small data-live-status></small></div><div><span>${t('In charging projects','В проектах зарядок')}</span><b data-live-capital>${M(demo.plan?.capital||0)}</b><span>${t('Recorded charging credits','Учтённые начисления по зарядкам')}</span><b data-live-confirmed>${M(EcoFinance.summary(demo).recorded)}</b></div></section>`;}
 let upgradeTier,upgradeAmount,upgradePlanKey;
 function upgradeCard(){const p=EcoFinance.summary(demo).active;if(!p)return '';if(window.EcoParticipation?.issue(demo))return `<section class="eco-card"><h2>${t('Keep your open request in view','Ваш открытый вопрос')}</h2><p>${t('Review the outstanding conversation or withdrawal before considering a plan change.','Проверьте текущую переписку или заявку на вывод перед изменением плана.')}</p><button class="eco-text" data-eco-route="help">${t('Contact my manager →','Написать менеджеру →')}</button><button class="eco-text" data-eco-route="money">${t('Account activity →','Операции по счёту →')}</button></section>`;const tiers=EcoFinance.tiers;
  if(upgradePlanKey!==p.appliedAt){upgradePlanKey=p.appliedAt;upgradeTier=undefined;upgradeAmount=undefined;}
  upgradeTier??=tiers[Math.min(tiers.findIndex(v=>v.id===p.tierId)+1,tiers.length-1)].id;upgradeAmount??=String(p.capital);
  return `<section class="eco-upgrade" translate="no"><div><span class="eco-kicker">${t('YOUR NEXT SCENARIO','СЛЕДУЮЩИЙ СЦЕНАРИЙ')}</span><h2>${t('Explore a higher weekly amount.','Увеличить недельное начисление.')}</h2><p>${t('Compare plans with your own amount.','Сравните тарифы на своей сумме.')}</p><label for="eco-upgrade-tier">${t('Plan','Тариф')}</label><select id="eco-upgrade-tier">${tiers.map(v=>`<option value="${v.id}" ${v.id===upgradeTier?'selected':''}>${E(window.EcoLocale?.t(v.name)||v.name)} · ${v.rate}% / ${t('calendar month','календарный месяц')}</option>`).join('')}</select><label for="eco-upgrade-amount">${t('Your total plan amount, USD','Ваша полная сумма в плане, USD')}</label><input id="eco-upgrade-amount" inputmode="decimal" maxlength="20" value="${E(upgradeAmount)}" aria-describedby="eco-upgrade-result"></div><div class="eco-upgrade-output"><div id="eco-upgrade-result" role="status" aria-live="polite">${upgradeResult()}</div><button class="eco-button" data-eco-upgrade ${validDemoInvestment(EcoFinance.parseAmount(upgradeAmount))?'':'disabled'}>${t('Choose stations & review →','Выбрать станции и проверить →')}</button><small>${t('Model calculation · 7-day period','Модельный расчёт · период 7 дней')}</small></div></section>`;
 }
 function upgradeResult(){const p=EcoFinance.summary(demo).active,tier=EcoFinance.tiers.find(v=>v.id===upgradeTier),amount=EcoFinance.parseAmount(upgradeAmount),valid=validDemoInvestment(amount);if(!valid)return `<p>${t('Enter $250–$10,000,000, with up to two decimal places.','Введите от 250 до 10 000 000 $, не более двух знаков после запятой.')}</p>`;
  const before=EcoFinance.planWeekly(p),after=EcoFinance.weekly(amount,tier.rate),diff=EcoFinance.round(after-before),gap=Math.max(0,amount-p.capital-EcoFinance.summary(demo).available);
  return `<small>${t('Weekly model with your selection','За неделю с вашим выбором')}</small><strong>${M(after)}</strong><span class="eco-upgrade-delta">${diff>0?'+':''}${M(diff)} ${t('vs. current plan','к текущему плану')}</span><dl><div><dt>${t('Current weekly model','Сейчас за неделю')}</dt><dd>${M(before)}</dd></div><div><dt>${t('Additional funding needed','Нужно добавить')}</dt><dd>${M(gap)}</dd></div></dl>`;
 }
 function refreshUpgrade(){const result=$('#eco-upgrade-result');if(!result)return;result.innerHTML=upgradeResult();const valid=validDemoInvestment(EcoFinance.parseAmount(upgradeAmount));$('#eco-upgrade-amount').setAttribute('aria-invalid',String(!valid));$('[data-eco-upgrade]').disabled=!valid;}
 const navigation=[['dashboard','home','Home','Главная'],['projects','zap','Projects','Проекты'],['money','wallet','Wallet','Кошелёк'],['services','grid','Services','Сервисы'],['profile','users','Profile','Профиль']];
 const activeNav=()=>['map','tariffs','assets','saved'].includes(tab)?'projects':['equipment','help','documents','arcade','invite','feed'].includes(tab)?'services':['results'].includes(tab)?'money':['identity','notifications'].includes(tab)?'profile':tab;
 const navIcon=g=>window.EcoBrandIcons.nav(({home:'home',zap:'projects',wallet:'wallet',grid:'services',users:'profile',bell:'feed',file:'feed',chat:'profile',map:'projects'})[g]||'services');
 const oldNav=renderNav;renderNav=function(){oldNav();if(workspaceRole!=='client')return;$('.main-nav').setAttribute('translate','no');$('.main-nav').setAttribute('aria-label',t('Main navigation','Основная навигация'));$('.main-nav').innerHTML=navigation.map(([id,g,en,ru])=>`<button class="nav-item ${activeNav()===id?'active':''}" data-tab="${id}" ${activeNav()===id?'aria-current="page"':''}>${window.EcoBrandIcons.nav(({dashboard:"home",projects:"projects",money:"wallet",services:"services",profile:"profile"})[id])}<span>${t(en,ru)}</span></button>`).join('');header();};
 function stationCard(id){const s=journeyStation(id);if(!s)return '';const p=journeyPhoto(s);return `<button class="eco-station" data-journey-open="${s.id}"><img src="${E(p.path)}" alt="${E(p.alt)}" loading="lazy"><span><strong translate="no">${E(journeyLabel(s))}</strong><small>${s.ports} ${t('charging ports','разъёмов')} · ${p.kind==='illustration'?t('Illustration','Иллюстрация'):t('Location photo','Фото локации')}</small></span><b>↗</b></button>`;}

 function accountUpdates(){return '<section class="eco-card eco-account-updates"><div class="eco-section-title"><h2>'+t('Recent activity','Последние события')+'</h2>'+routeButton(t('All activity →','Все события →'),'notifications')+'</div>'+rows(events().slice(0,3))+'</section>';}
 function recentOperations(){const items=events().filter(e=>['topup','withdraw','credit','adjustment'].includes(e.type)).slice(0,3);if(!items.length)return '';return `<section class="eco-card eg-recent-operations"><div class="eco-section-title"><h2>${t('Recent transactions','Последние операции')}</h2>${routeButton(t('View all →','Все →'),'money')}</div>${rows(items)}</section>`;}
 function accountOverview(v){const p=v.active,next=window.ECO_SHARED_CONTEXT.nextWeek,loc=p&&journeyStation(p.stationIds[0]),photo=loc&&journeyPhoto(loc);
  const pending=v.pendingFunding[0];
  return '<div class="eco-account-top" data-account-overview>'+`<section class="eco-account-balance" data-energy-money aria-label="${t('Account summary','Финансовая сводка')}">
   <span class="eco-kicker">${t('AVAILABLE BALANCE','ДОСТУПНЫЙ БАЛАНС')}</span><strong class="eco-account-available">${M(v.available)}</strong>
   <div class="eco-account-actions">${button(t('Add funds','Пополнить'),'topup')}${button(t('Withdraw','Вывести'),'withdraw',true)}${routeButton(t('History','История'),'money')}</div>
   <dl class="eco-account-totals"><div><dt>${t('In active plan','В активном плане')}</dt><dd>${M(v.capital)}</dd></div>${energyActive()?`<div><dt>${t('Earned this period','Начислено за период')}</dt><dd class="eco-account-live energy-period-value"><span data-live-accrual>${M(0)}</span>${weekRing()}</dd></div>`:''}</dl>
   ${energyActive()?'<small class="eco-account-model" data-live-status></small>':''}${window.EcoEnergyUI?.lockedStrip(energyActive())||''}
   ${v.reserved>0?`<p class="eco-account-reserved">${t('Reserved for withdrawal','В резерве на вывод')}: <b>${M(v.reserved)}</b></p>`:''}
   <div class="eco-account-recorded"><span>${t('Recorded model credits','Учтённые модельные начисления')}</span><b>${M(v.recorded)}</b></div>
  </section><section class="eco-account-plan" aria-label="${t('Current plan','Текущий план')}">
   ${p?`<div class="eco-account-plan-title"><div><span class="eco-kicker">${t('ACTIVE PLAN','АКТИВНЫЙ ПЛАН')}</span><h2>${E(window.EcoLocale?.t(p.name)||p.name)}</h2><small>${stationCount(p.stationIds.length)} · ${p.rate}% ${p.ratePeriod===EcoFinance.ratePeriod?t('per calendar month · model, not a guarantee','за календарный месяц · модель, не гарантия'):t('per week','в неделю')}</small></div>${photo?`<button class="eco-account-photo" data-journey-open="${loc.id}" aria-label="${E(t('View station','Открыть станцию')+' '+journeyLabel(loc))}"><img src="${E(photo.path)}" alt="${E(photo.alt)}"></button>`:''}</div><p class="eco-account-cadence">${EcoBusiness.cadence(window.EcoLocale?.language)}</p><dl class="eco-account-schedule"><div><dt>${t('Estimated weekly accrual','Расчёт начисления за неделю')}</dt><dd>${M(v.activeWeekly)}</dd></div>${next?`<div><dt>${t('Next weekly credit','Следующее начисление')}</dt><dd><time datetime="${E(next.periodEnd)}">${date(next.periodEnd)}</time></dd></div>`:''}</dl>${button(t('My plan','Мой план'),'eco-active-plan',true)}`:
   `<span class="eco-kicker">${t('PLAN NOT ACTIVE','ПЛАН НЕ АКТИВЕН')}</span><h2>${v.stage==='ready'?t('Your selection is ready.','Выбор готов к активации.'):v.stage==='pending'?t('Waiting for funding review.','Ожидаем проверки пополнения.'):t('Choose where to start.','Выберите свой план.')}</h2><p>${v.plan?E(window.EcoLocale?.t(v.plan.name)||v.plan.name)+' · '+M(v.plan.capital):t('Choose an amount and review the plan before activation.','Выберите сумму и проверьте условия перед активацией.')}</p>${v.plan?`<dl class="eco-account-schedule"><div><dt>${t('Weekly model after activation','Модель за неделю после активации')}</dt><dd>${M(v.weekly)}</dd></div></dl>`:''}${pending?`<small>${t('Under review','На проверке')}: ${M(pending.amount)} · ${t('not yet credited','ещё не зачислено')}</small>`:''}${button(v.stage==='pending'?t('View request status','Статус заявки'):v.stage==='ready'?t('Activate selected plan','Активировать выбранный план'):v.plan?t('Review selection','Проверить подборку'):t('Choose a plan','Выбрать план'),v.action)}`}
  </section></div>
  ${pending&&p?`<section class="eco-account-notice"><div><strong>${t('Funding under review','Пополнение на проверке')} · ${M(pending.amount)}</strong><span>${t('Not included in your available balance.','Не включено в доступный баланс.')}</span></div>${button(t('View status','Посмотреть статус'),'payment-pending-status',true)}</section>`:''}
  ${p&&demo.planDraft?`<section class="eco-account-notice"><div><strong>${t('Saved selection','Сохранённый выбор')} · ${E(window.EcoLocale?.t(demo.planDraft.name)||demo.planDraft.name)} · ${M(demo.planDraft.capital)}</strong><span>${t('Your active plan stays in effect until you confirm a change.','Текущий план действует до подтверждения изменения.')}</span></div>${button(v.stage==='ready'?t('Review & activate','Проверить и активировать'):t('Review selection','Проверить подборку'),v.stage==='ready'?'activate-draft':'journey-my-plan',true)}</section>`:''}
  <div class="eco-account-followup">${accountUpdates()}${conversationCard(v)}</div>`;
 }
 function legacyHome(){const activation=EcoFunding.activation(demo),funding=EcoFunding.intent(demo),v=EcoWorkspace.overview(demo),p=v.plan,research=explorationState(),station=p?.stationIds[0]||research.saved[0]||research.recent[0]||stations[0]?.id,loc=journeyStation(station),photo=loc&&journeyPhoto(loc);
  const stateCopy={new:t('NO PLAN SELECTED','ПЛАН ЕЩЁ НЕ ВЫБРАН'),funded:t('FUNDS AVAILABLE · CHOOSE A PLAN','СРЕДСТВА ДОСТУПНЫ · ВЫБЕРИТЕ ПЛАН'),pending:t('FUNDING REQUEST UNDER REVIEW','ПОПОЛНЕНИЕ НА ПРОВЕРКЕ'),ready:t('FUNDS AVAILABLE · ACTIVATE PLAN','СРЕДСТВА ДОСТУПНЫ · АКТИВИРУЙТЕ ПЛАН'),draft:p?.savedBy==='manager'?t('DRAFT FROM YOUR MANAGER','ЧЕРНОВИК ОТ МЕНЕДЖЕРА'):t('SAVED DRAFT','СОХРАНЁННЫЙ ЧЕРНОВИК'),active:t('ACTIVE PLAN','АКТИВНЫЙ ПЛАН')};
  const labels={new:t('Build my plan','Собрать мой план'),funded:t('Choose a plan','Выбрать план'),draft:t('Review selection','Проверить подборку'),ready:t('Activate selected plan','Активировать выбранный план'),pending:t('View request status','Статус заявки'),active:t('Open my plan','Открыть мой план')};
  return `<header class="eco-overview-heading"><h1>${v.accountMode?t('Your account','Ваш счёт'):t('Your charging workspace','Станции и ваш план')}</h1></header>
   ${activation.visible?EcoFundingUI.activationHero(demo,window.EcoLocale?.language):funding.visible?EcoFundingUI.hero(demo,window.EcoLocale?.language):''}
   ${activation.visible?`<div class="eco-account-followup">${accountUpdates()}${conversationCard(v)}</div>`:funding.visible?'':v.accountMode?accountOverview(v):`<div class="eco-overview-top"><section class="eco-selection" data-energy-money data-overview-stage="${v.stage}">
    <div class="eco-selection-title"><div><span class="eco-kicker">${stateCopy[v.stage]}</span><h2>${p?E(window.EcoLocale?.t(p.name)||p.name):t('Start with your selection.','Начните со своего выбора.')}</h2></div>${photo?`<button class="eco-selection-photo" data-journey-open="${station}" aria-label="${E(t('View station','Открыть станцию')+' '+journeyLabel(loc))}"><img src="${E(photo.path)}" alt="${E(photo.alt)}"></button>`:''}</div>
    ${p?`<dl class="eco-selection-values"><div><dt>${t('Plan amount','Сумма плана')}</dt><dd>${M(p.capital)}</dd></div><div><dt>${t('Estimated weekly accrual','Расчёт начисления за неделю')}</dt><dd>${M(v.weekly)}</dd></div></dl><p class="eco-selection-meta">${stationCount(p.stationIds.length)} · ${p.rate}% ${t('per calendar month · sample calculation','за календарный месяц · модельный расчёт')}</p>`: `<p>${t('Explore stations, compare your amount and keep a selection to discuss.','Изучите станции, сравните расчёты и сохраните выбор для обсуждения.')}</p>`}
    ${v.stage==='pending'?`<p class="eco-selection-status">${t('Request registered. Funds are not yet credited.','Заявка зарегистрирована. Средства ещё не зачислены.')}</p>`:''}
    ${v.active&&demo.planDraft?`<p class="eco-selection-status">${t('Active plan','Активный план')}: ${E(window.EcoLocale?.t(v.active.name)||v.active.name)} · ${M(v.active.capital)}</p>`:''}
    <div class="eco-selection-actions">${button(labels[v.stage],v.action)}<button class="eco-text" data-eco-question="plan">${t('Discuss selection','Обсудить выбор')} →</button></div>
   ${window.EcoEnergyUI?.lockedStrip(energyActive())||''}</section>${conversationCard(v)}</div>`}
   ${window.EcoMiningPortfolio?.render(demo,window.EcoLocale?.language,true)||''}
   ${v.clubVisible?clubEntry():''}
   ${v.active?calendar():''}
   ${window.EcoEquipmentUI?.entry()||''}
   ${v.active?'':window.EcoEnergyUI?.teaser(false)||''}
   ${v.collapseLab?`<details class="eco-fund-lab" data-funding-lab><summary>${t('Energy flow model','Модель энергопотока')} <span>${t('Solar, storage and three energy outlets','Солнце, накопители и три направления')}</span></summary>${window.EcoEnergyUI?.markup()||''}</details>`:window.EcoEnergyUI?.markup()||''}
   <details class="eco-secondary-details"><summary>${t('Your journal & weekly reports','Ваш журнал и недельные отчёты')}</summary>${window.EcoEnergyJournal?.markup(demo,window.ECO_SHARED_CONTEXT.liveAccrual,window.EcoClientAccount.now())||''}</details>
   ${v.active?'<details class="eco-secondary-details"><summary>'+t('Stations, comparisons & other tools','Станции, сравнения и другие инструменты')+'</summary>':''}
   <nav class="eco-explore-links ${energyActive()||funding.visible?'eco-explore-secondary':''}" aria-label="${t('Explore your account','Изучить кабинет')}">
    <button data-action="journey-saved"><span><strong>${t('Saved stations','Избранные станции')}</strong><small>${research.saved.length?stationCount(research.saved.length):t('Choose from the directory','Выбрать в каталоге')}</small></span>↗</button>
    <button data-eco-route="saved"><span><strong>${t('Compare scenarios','Сравнить расчёты')}</strong><small>${ui().scenarios.length?ui().scenarios.length+' '+t('saved','сохранено'):t('Your amount and station group','Ваша сумма и группа станций')}</small></span>↗</button>
    <button data-action="eco-session-lesson"><span><strong>${t('Inside a charging session','Разобрать зарядную сессию')}</strong><small>${t('Payment, electricity, costs','Оплата, электричество, расходы')}</small></span>↗</button>
    <button data-eco-route="arcade"><span><strong>${t("Energy Run · Arcade","Energy Run · Перерыв")}</strong><small>${t("A free 45-second drive","Бесплатный заезд на 45 секунд")}</small></span>↗</button><button data-eco-route="documents"><span><strong>${t('Documents & terms','Документы и условия')}</strong><small>${t('Access to funds and agreement','Доступ к средствам и договор')}</small></span>↗</button>
   </nav>
   <div class="eco-grid"><section class="eco-card"><div class="eco-section-title"><h2>${t('Your shortlist','Ваш выбор станций')}</h2>${button(t('Compare stations','Сравнить станции'),'journey-compare',true)}</div>${(research.saved.length?research.saved:p?.stationIds||[station]).slice(0,3).map(stationCard).join('')}${routeButton(t('Open directory →','Открыть каталог →'),'map')}</section><section class="eco-card"><div class="eco-section-title"><h2>${t('Your scenarios','Ваши расчёты')}</h2>${routeButton(t('View all →','Все варианты →'),'saved')}</div>${scenarioCards(true)}</section></div>
   ${v.active?upgradeCard():''}${v.accountMode?'':`<div class="eco-grid">${accountUpdates()}${`<section class="eco-card"><h2>${t('Questions before deciding','Вопросы перед решением')}</h2><div class="eco-question-topics"><button data-eco-question="documents">${t('Which documents should I review?','Какие документы изучить?')} →</button><button data-eco-question="account">${t('How will I access my funds?','Как получить доступ к средствам?')} →</button></div></section>`}</div>`}${v.active?'</details>':''}`;
 }
 function shortcut(target,g,en,ru){return `<button data-eco-route="${target}"><span class="eg-shortcut-icon">${window.EcoBrandIcons.art(({projects:"portfolio",map:"station",equipment:"equipment",help:"support",saved:"portfolio",documents:"document"})[target])}</span><span>${t(en,ru)}</span></button>`;}
 function projectRows(){const v=EcoWorkspace.overview(demo),p=v.active,mining=window.EcoMiningPortfolio?.positions(demo)||[];
  return `<div class="eg-project-list">${p?`<button class="eg-project-row" data-action="eco-active-plan"><span class="eg-project-symbol">${window.EcoBrandIcons.art("station")}</span><span class="eg-project-copy"><strong>EcoGrid Charge</strong><small>${E(window.EcoLocale?.t(p.name)||p.name)} · ${stationCount(p.stationIds.length)}</small></span><span class="eg-project-amount"><strong>${M(p.capital)}</strong><small>${M(v.activeWeekly)} / ${t('7 days · model','7 дней · модель')}</small></span><span class="eg-status is-active"><i></i>${t('Active','Активен')}</span><span class="eg-row-arrow" aria-hidden="true">›</span></button>`:''}${mining.map(position=>{const m=EcoMining.find(position.minerId),hasPayout=(position.payouts||[]).length>0;return `<button class="eg-project-row" data-action="eco-mining-details"><span class="eg-project-symbol">${window.EcoBrandIcons.art("miner")}</span><span class="eg-project-copy"><strong translate="no">${E(m.model)}</strong><small>${E(EcoMining.coins[m.coinId].ticker)} · ${position.country==='CA'?t('Canada','Канада'):t('United States','США')}</small></span><span class="eg-project-amount"><strong>${M(position.capital)}</strong><small>${t('Project participation','Участие в проекте')}</small></span><span class="eg-status ${hasPayout?'is-active':'is-muted'}"><i></i>${hasPayout?t('Accruals recorded','Есть начисления'):t('No accruals yet','Начислений пока нет')}</span><span class="eg-row-arrow" aria-hidden="true">›</span></button>`;}).join('')}${!p&&!mining.length?`<div class="eg-empty-state"><p>${t('No active projects yet. Compare the available terms before choosing.','Активных проектов пока нет. Сначала сравните доступные условия.')}</p>${routeButton(t('Open project catalogue','Открыть каталог проектов'),'projects','eco-button')}</div>`:''}</div>`;
 }
 function serviceTile(target,g,name,copy){return `<button class="eg-service" data-eco-route="${target}"><span class="eg-service-icon">${window.EcoBrandIcons.art(({tariffs:"station","equipment-mining":"miner",equipment:"equipment",feed:"news",help:"support",documents:"document",invite:"club",arcade:"run"})[target]||"portfolio")}</span><strong>${name}</strong><small>${copy}</small><span class="eg-service-arrow" aria-hidden="true">↗</span></button>`;}
 function nextEventCard(v){const next=window.ECO_SHARED_CONTEXT.nextWeek,p=v.active;return p&&next?`<section class="eco-card eg-next-event"><span class="eg-card-icon">${window.EcoBrandIcons.art('document')}</span><div><span class="eco-kicker">${t('NEXT CHARGING CREDIT','СЛЕДУЮЩЕЕ НАЧИСЛЕНИЕ · ЗАРЯДКИ')}</span><h2>${calendarDate(next.periodEnd)}</h2><small>${t('According to your plan schedule','По графику вашего плана')}</small></div>${routeButton(t('Calendar →','Календарь →'),'money')}</section>`:'';}
 function homeSupport(){return `<section class="eco-card eg-support-card"><span class="eg-card-icon">${window.EcoBrandIcons.art('support')}</span><h2>${t('Need help?','Нужна помощь?')}</h2><p>${t('Questions about projects, wallet or calculations.','Вопросы по проектам, кошельку или расчётам.')}</p>${routeButton(t('Open support','Открыть поддержку'),'help','eco-button secondary')}</section>`;}
 function home(){const v=EcoWorkspace.overview(demo),mining=window.EcoMiningPortfolio?.positions(demo)||[],capital=v.capital+mining.reduce((s,p)=>s+p.capital,0),activation=EcoFunding.activation(demo),funding=EcoFunding.intent(demo),projectCount=(v.active?1:0)+mining.length;
  return `<header class="eg-page-heading eg-dashboard-heading"><div><h1>${t('Your portfolio','Ваш портфель')}</h1><p>${t('Money, projects and recent events','Деньги, проекты и последние события')}</p></div><button class="eg-avatar" data-eco-route="profile" aria-label="${t('Open profile','Открыть профиль')}">${window.EcoProfileAvatar.image()}</button></header>
   ${activation.visible?EcoFundingUI.activationHero(demo,window.EcoLocale?.language):funding.visible?EcoFundingUI.hero(demo,window.EcoLocale?.language):''}
   ${!activation.visible&&!funding.visible?`<section class="eg-summary-grid" aria-label="${t('Portfolio summary','Сводка портфеля')}"><article class="eg-balance" data-account-overview data-energy-money><span class="eg-balance-label">${t('Available','Доступно')}</span><strong class="eg-balance-number">${M(v.available)}</strong><span class="eg-balance-note">${t('Available balance','Свободный остаток')}</span><div class="eg-money-actions">${routeButton(t('Open wallet','Открыть кошелёк'),'money','eco-button')}${routeButton(t('History','История'),'money','eco-button secondary')}</div></article><article class="eco-card eg-summary-card"><span>${t('In projects','В проектах')}</span><strong>${M(capital)}</strong><small>${projectCount} ${t(projectCount===1?'active project':'active projects',projectCount===1?'активный проект':projectCount>=2&&projectCount<=4?'активных проекта':'активных проектов')}</small><span class="eg-summary-glyph">${window.EcoBrandIcons.art('portfolio')}</span></article><article class="eco-card eg-summary-card"><span>${t('Charging · 7 days','Зарядки · за 7 дней')}</span><strong>${v.active?M(v.activeWeekly||0):'—'}</strong><small>${t('Model · excluding mining','Модель · без майнинга')}</small><span class="eg-summary-glyph">${window.EcoBrandIcons.art('document')}</span></article></section>`:''}
   <div class="eg-dashboard-grid">
    <section class="eco-card eg-projects-card" data-home-projects><div class="eco-section-title"><h2>${t('My projects','Мои проекты')}</h2>${routeButton(t('View all →','Все проекты →'),'projects')}</div>${projectRows()}</section>
    ${nextEventCard(v)}
    ${recentOperations()}
    
    
    ${homeSupport()}
   </div><div data-community-preview></div>`;
 }
 function projectGuide(){return `<section class="eg-guide"><h2>${t('Make an informed choice','Разберитесь перед выбором')}</h2><ol><li><button data-eco-route="documents"><b>1</b><span><strong>${t('Understand the terms','Изучите условия')}</strong><small>${t('How participation and access to funds work.','Как устроены участие и доступ к средствам.')}</small></span></button></li><li><button data-eco-route="tariffs"><b>2</b><span><strong>${t('Compare your options','Сравните варианты')}</strong><small>${t('Your amount, model estimate and selected stations.','Ваша сумма, модельный расчёт и выбранные станции.')}</small></span></button></li><li><button data-eco-route="help"><b>3</b><span><strong>${t('Get answers','Разберите вопросы')}</strong><small>${t('Review funding, withdrawals and support.','Пополнение, вывод и связь с командой.')}</small></span></button></li></ol></section>`;}
 function projects(){const v=EcoWorkspace.overview(demo);return `<header class="eg-page-heading eg-editorial-heading"><span class="eco-kicker">ECOGRID · ${t('PARTICIPATION','УЧАСТИЕ')}</span><h1>${t('Your projects','Ваши проекты')}</h1><p>${t('Active projects and available directions use separate terms and calculations.','Действующие проекты и доступные направления используют отдельные условия и расчёты.')}</p></header><section class="eco-card eg-projects-card"><div class="eco-section-title"><h2>${t('Active projects','Действующие проекты')}</h2><span class="eg-section-note">${t('Your recorded participation','Ваше учтённое участие')}</span></div>${projectRows()}</section><section class="eg-section"><div class="eco-section-title"><h2>${t('Project catalogue','Каталог проектов')}</h2><span class="eg-section-note">${t('Compare before choosing','Сравните до выбора')}</span></div><div class="eg-service-grid eg-project-options">${serviceTile('tariffs','zap','EcoGrid Charge',t('Select your amount and see a 7-day estimate.','Выберите сумму и посмотрите расчёт за 7 дней.'))}${serviceTile('equipment-mining','grid','EcoMiner',t('Compare configurations and discuss project participation.','Сравните модели и обсудите участие в проекте.'))}</div></section>${v.active?`<details class="eco-secondary-details"><summary>${t('Charging plan details','Подробности плана зарядок')}</summary>${accountOverview(v)}</details>`:''}${window.EcoMiningPortfolio?.render(demo,window.EcoLocale?.language,true)||''}${projectGuide()}<div class="eg-shortcuts">${shortcut('map','map','Station map','Карта станций')}${shortcut('saved','file','Comparisons','Расчёты')}${shortcut('documents','file','Terms','Условия')}${shortcut('help','chat','Questions','Вопросы')}</div>`;}
 function services(){return `<header class="eg-page-heading eg-editorial-heading"><span class="eco-kicker">ECOGRID</span><h1>${t('Services for you','Сервисы для вас')}</h1><p>${t('Equipment, useful tools and support in one place.','Оборудование, полезные инструменты и поддержка в одном месте.')}</p></header><div class="eg-service-grid">${serviceTile('equipment','zap',t('Equipment','Оборудование'),t('Solar, storage, charging and EcoMiner.','Панели, накопители, зарядки и EcoMiner.'))}${serviceTile('feed','bell',t('EcoGrid feed','Лента EcoGrid'),t('News, project updates and offers.','Новости, обновления проектов и акции.'))}${serviceTile('help','chat',t('Support','Поддержка'),t('Answers and contact with your manager.','Ответы на вопросы и связь с менеджером.'))}${serviceTile('documents','file',t('Documents','Документы'),t('Plan terms and account documents.','Условия плана и документы по счёту.'))}${serviceTile('invite','users','EcoGrid Club',t('Personal invitations and program terms.','Личные приглашения и условия программы.'))}${serviceTile('arcade','map','Energy Run',t('A short break. Points have no cash value.','Короткий перерыв. Очки не имеют денежной стоимости.'))}</div><details class="eco-secondary-details" data-account-journal><summary>${t('Your journal & weekly reports','Ваш журнал и недельные отчёты')}</summary>${window.EcoEnergyJournal?.markup(demo,window.ECO_SHARED_CONTEXT.liveAccrual,window.EcoClientAccount.now())||''}</details><details class="eco-fund-lab" data-funding-lab><summary>${t('How energy flows','Как распределяется энергия')}<span>Energy Lab</span></summary>${window.EcoEnergyUI?.markup()||''}</details>`;}

 function clubEntry(){return `<section class="eco-club-entry" data-club-entry><div><span class="eco-kicker">EcoGrid CLUB</span><h2>${t('Your invitations & club activity','Ваши приглашения и участие в Club')}</h2><p>${t('Your link, invitation history and current program terms.','Ваша ссылка, история приглашений и текущие условия программы.')}</p></div>${routeButton(t('Open Club →','Открыть Club →'),'invite','eco-button secondary')}</section>`;}
 function conversationCard(v){const last=v.latest;return `<aside class="eco-conversation"><span class="eco-kicker">${t('YOUR MANAGER','ВАШ МЕНЕДЖЕР')}</span><h2 translate="no">${E(demo.manager.name)}</h2>${last?`<div class="eco-last-message"><span>${last.reply?t('Latest manager reply','Последний ответ менеджера'):t('Your question · awaiting reply','Ваш вопрос · ожидает ответа')}</span><p translate="no">${E(last.reply||last.message)}</p><small>${date(last.repliedAt||last.date)}</small></div><button class="eco-text" data-thread="${E(last.id)}">${last.reply&&last.readReply!==last.reply?t('Read reply','Прочитать ответ'):t('Open conversation','Открыть переписку')} →</button>`:`<p>${v.active?t('Ask about your plan or account activity. Your current plan is attached to the question.','Задайте вопрос о плане или операциях. Текущий план приложится к сообщению.'):t('Send your selection with a question. The amount and stations stay attached to the conversation.','Отправьте свой выбор с вопросом. Сумма и станции сохранятся в переписке.')}</p><button class="eco-text" ${v.active?'data-eco-active-question':'data-eco-question="plan"'}>${v.active?t('Ask about my plan','Вопрос по моему плану'):t('Ask about my selection','Вопрос по моему выбору')} →</button>`}</aside>`;}
 function calendar(){return window.EcoWithdrawalUI?.calendar()||'';}
 function moneyPage(){const s=EcoFinance.summary(demo),miningCapital=(window.EcoMiningPortfolio?.positions(demo)||[]).reduce((sum,p)=>sum+p.capital,0),activation=EcoFunding.activation(demo),funding=EcoFunding.intent(demo);return `<header class="eg-page-heading"><div><h1>${t('Wallet','Кошелёк')}</h1><p>${t('Available, allocated and reserved funds','Доступные, размещённые и зарезервированные средства')}</p></div>${routeButton(t('Report →','Отчёт →'),'results')}</header>${activation.visible?EcoFundingUI.activationHero(demo,window.EcoLocale?.language):funding.visible?EcoFundingUI.hero(demo,window.EcoLocale?.language):`<section class="eco-money-card eg-wallet-summary"><article class="eg-balance"><span class="eg-balance-label">${t('Available','Доступно')}</span><strong class="eg-balance-number">${M(s.available)}</strong><span class="eg-balance-note">${t('Available balance','Свободный остаток')}</span><div class="eg-money-actions">${button(t('Add funds','Пополнить'),'topup')}${button(t('Withdraw','Вывести'),'withdraw',true)}</div></article><dl class="eco-card eg-wallet-totals"><div><dt>${t('In charging projects','В проектах зарядок')}</dt><dd>${M(s.capital)}</dd></div>${miningCapital?`<div><dt>${t('In mining projects','В проектах майнинга')}</dt><dd>${M(miningCapital)}</dd></div>`:''}<div><dt>${t('Reserved for withdrawal','В резерве на вывод')}</dt><dd>${M(s.reserved)}</dd></div><div><dt>${t('Recorded credits','Учтённые начисления')}</dt><dd>${M(s.recorded)}</dd></div></dl></section>${liveCard()}${calendar()}`}<section class="eg-transactions"><div class="eco-section-title"><h2>${t('Transaction history','История операций')}</h2><span class="eg-section-note">${t('Select an operation to view details','Нажмите на операцию, чтобы открыть подробности')}</span></div><div class="eco-filters" aria-label="${t('Transaction filters','Фильтры операций')}">${[['all','All','Все'],['topup','Funding','Пополнения'],['credit','Credits','Начисления'],['withdraw','Withdrawals','Выводы']].map(([id,en,ru])=>`<button data-eco-filter="${id}" aria-pressed="${moneyFilter===id}">${t(en,ru)}</button>`).join('')}</div><section class="eco-card">${rows(events().filter(e=>['topup','withdraw','credit','adjustment'].includes(e.type)&&(moneyFilter==='all'||e.type===moneyFilter)))}</section></section>`;}
 function scenarioCards(compact=false){const saved=ui().scenarios||[];return saved.length?saved.slice(0,compact?2:6).map(p=>`<article class="eco-scenario"><div><strong>${E(window.EcoLocale?.t(p.label||p.name)||p.name)}</strong><small>${stationCount(p.stationIds.length)} · ${p.rate}% / ${p.ratePeriod===EcoFinance.ratePeriod?t('calendar month','календарный месяц'):t('week','неделю')}</small></div><b>${M(p.capital)}</b><small>${t('Weekly model','Расчёт за неделю')}: ${M(EcoFinance.planWeekly(p))}</small><div class="eco-actions"><button class="eco-text" data-eco-load="${E(p.id)}">${t('Continue','Продолжить')} →</button><button class="eco-text" data-eco-discuss="${E(p.id)}">${t('Discuss','Обсудить')}</button>${compact?'':`<button class="eco-text" data-eco-delete="${E(p.id)}">${t('Remove','Убрать')}</button>`}</div></article>`).join(''):`<p class="eco-empty">${t('Keep up to six scenarios to compare at your own pace.','Сохраните до шести вариантов и сравните их в удобное время.')}</p>${routeButton(t('Build a scenario →','Собрать расчёт →'),'tariffs','eco-button secondary')}`;}
 const faq=()=>[[t('How does mining participation work?','Как устроено участие в майнинге?'),t('EcoMiner participation is shown separately from charging projects. Compare the participation amount, project share and recorded payouts in Projects. Energy, service costs and mining revenue affect the result; the charging plan rate does not apply.','Участие EcoMiner показано отдельно от проектов зарядок. В разделе «Проекты» доступны сумма участия, доля в проекте и учтённые выплаты. Результат зависит от выручки майнинга, стоимости энергии и обслуживания; ставка плана зарядок здесь не применяется.')],[t('Where can I find my account results?','Где посмотреть результат по счёту?'),t('Wallet shows the available balance, participation by direction and recorded transactions. The current week estimate is separate and is not available for withdrawal until recorded.','В кошельке показаны доступный остаток, участие по направлениям и записанные операции. Расчёт текущей недели указан отдельно: до записи начисления он не входит в доступный остаток.')],[t('Where does the money go?','Куда направляется сумма?'),t('Funding adds to your available balance. Activating a plan moves the chosen amount into that plan. These are separate steps.','Пополнение увеличивает свободный остаток. При активации выбранная сумма переводится в план. Это отдельные действия.')],[t('Can I choose my own amount?','Можно указать свою сумму?'),t('Yes. Single: 13% from $250; Network: 14% from $500; Portfolio: 15% from $800; Custom: 16% from $1,000. Rates are per calendar month; credits are recorded weekly.','Да. Single: 13% от $250; Network: 14% от $500; Portfolio: 15% от $800; Своя сумма: 16% при сумме от $1 000. Ставки за календарный месяц; начисления записываются раз в неделю.')],[t('When can I request a withdrawal?','Когда доступен вывод?'),t('The first request opens 4 days after activation. A completed withdrawal starts the next 4-day period. The available balance and pending requests matter too.','Первая заявка доступна через 4 дня после активации. После выполненного вывода начинается следующий четырёхдневный период. Учитываются свободный остаток и заявки на проверке.')],[t('Do I have to upload documents?','Обязательно загружать документы?'),t('No. You can skip this optional step in this project. Uploaded details need your review before they are submitted.','Нет. В этом проекте шаг необязателен. Перед отправкой распознанные данные нужно проверить.')]];
 function help(){return `<h1>${t('How can we help?','Чем помочь?')}</h1><div class="eco-grid"><section class="eco-card"><span class="eco-kicker">${t('YOUR MANAGER','ВАШ МЕНЕДЖЕР')}</span><h2 translate="no">${E(demo.manager.name)}</h2>${button(t('Write a message','Написать сообщение'),'eco-help-message')}${button(t('Request a call','Запросить звонок'),'call',true)}${button(t('My conversations','Моя переписка'),'conversations',true)}</section><section class="eco-card"><label for="eco-help-search">${t('Search answers','Поиск по ответам')}</label><input id="eco-help-search" type="search" value="${E(helpQuery)}" placeholder="${t('Amount, payment, withdrawal…','Сумма, оплата, вывод…')}"><div id="eco-answers">${answers()}</div></section></div>`;}
 const answers=()=>faq().filter(x=>x.join(' ').toLowerCase().includes(helpQuery.toLowerCase())).map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')||`<p role="status">${t('No answer found. Try another word, for example “mining” or “withdrawal”.','Ответ не найден. Попробуйте другое слово, например «майнинг» или «вывод».')}</p><button class="eco-text" data-eco-clear-help>${t('Show all answers','Показать все ответы')}</button>`;
 function profile(){if(window.EcoClientCare)return window.EcoClientCare.profile();return `<h1>${t('Your profile','Ваш профиль')}</h1><div class="eco-grid"><section class="eco-card"><h2 translate="no">${E(demo.client?.name)}</h2><p translate="no">${E(demo.client.email)}</p>${demo.acquisition?.phone?`<p translate="no">${E(demo.acquisition.phone)}</p>`:''}${routeButton(t('Documents & personal details','Документы и личные данные'),'identity','eco-button')}<p>${t('Optional · reviewed before sending','Необязательно · проверка перед отправкой')}</p>${routeButton(t('Plan documents →','Документы плана →'),'documents')}<br>${routeButton(t('EcoGrid Club →','EcoGrid Club →'),'invite')}</section><section class="eco-card"><form id="eco-preferences"><label>${t('Time zone','Часовой пояс')}<select name="timezone">${[...new Set([ui().timezone||'UTC','UTC','America/New_York','America/Chicago','America/Denver','America/Los_Angeles','Asia/Tbilisi','Europe/Moscow'])].map(z=>`<option ${z===ui().timezone?'selected':''}>${z}</option>`).join('')}</select></label><button class="eco-button" type="submit">${t('Save preferences','Сохранить настройки')}</button></form><p>${t('Use EN / RU in the header to switch languages.','Язык можно переключить кнопками EN / RU в шапке.')}</p>${button(t('Sign out','Выйти'),'signout',true)}</section></div>`;}
 function results(){const cutoff=days?Date.now()-days*86400000:0,items=events().filter(e=>Date.parse(e.date)>=cutoff),approved=items.filter(e=>e.request?.status==='Approved'),credits=items.filter(e=>e.type==='credit'),sum=rows=>rows.reduce((s,r)=>s+r.amount,0);return `<div class="eco-section-title"><h1>${t('My account activity','Мой результат')}</h1><button class="eco-text" data-eco-export>${t('Download CSV','Скачать CSV')} ↓</button></div><div class="eco-filters">${[7,30,0].map(d=>`<button data-eco-days="${d}" aria-pressed="${days===d}">${d?d+' '+t('days','дней'):t('All time','Всё время')}</button>`).join('')}</div><div class="eco-stats">${[[t('Approved funding','Подтверждённые пополнения'),sum(approved.filter(e=>e.type==='topup'))],[t('Recorded credits','Записанные начисления'),sum(credits)],[t('Completed withdrawals','Выполненные выводы'),sum(approved.filter(e=>e.type==='withdraw'))]].map(([label,n])=>`<section class="eco-card"><small>${label}</small><h2>${M(n)}</h2></section>`).join('')}</div><section class="eco-card"><h2>${t('Recorded weekly credits','История начислений')}</h2>${rows(credits)}</section><p class="eco-muted">${t('Only recorded account entries are included. Funding is not profit.','Показаны записанные операции счёта. Пополнение не является прибылью.')}</p>`;}
 actions['eco-mining-details']=()=>openModal(window.EcoMiningPortfolio.render(demo,window.EcoLocale?.language,true));
 function go(target){if(target==='equipment-mining'){window.EcoEquipmentUI?.prepare?.('mining');target='equipment';}$('#modal')?.close();tab=target;renderClientTab();window.scrollTo({top:0,behavior:'instant'});}
 document.addEventListener('click',e=>{if(e.target.closest('[data-energy-open]')){const details=$('[data-funding-lab]');if(details)details.open=true;}},true);
 let beatUntil=0,beatTimer;
 function energyBeat(){if(Date.now()<beatUntil)return;beatUntil=Date.now()+2000;const money=document.querySelectorAll('[data-energy-money], [data-live-wallet]'),caption=$('[data-energy-caption]');if(caption)caption.textContent=energyActive()?t('Explore dispatch alongside your active plan. Model demand does not change your accrual.','Изучайте распределение энергии рядом со своим планом. Спрос в модели не меняет начисление.'):t('Activate a plan to start your model accrual. This dispatch model is free to explore.','Активируйте план, чтобы запустить модельное начисление. Модель распределения можно изучать бесплатно.');for(const el of money)el.classList.add('energy-money-beat');clearTimeout(beatTimer);beatTimer=setTimeout(()=>money.forEach(el=>el.classList.remove('energy-money-beat')),1600);}
 const oldRender=renderClientTab;renderClientTab=function(){if(tab==='arcade'&&$('#energy-run')&&window.EcoArcade?.language===window.EcoLocale?.language){header();return;}window.EcoArcade?.unmount();window.EcoWithdrawalUI?.stop();clearTimeout(beatTimer);beatUntil=0;liveController.stop();window.EcoEnergyUI?.unmount();oldRender();if(workspaceRole!=='client')return;document.body.classList.add('eco-shell');header();let root=$('#eco-workspace');if(!root){root=document.createElement('div');root.id='eco-workspace';root.setAttribute('translate','no');$('#client-view').append(root);}const own=['dashboard','money','help','profile','identity','notifications','saved','results','invite','documents','arcade','equipment','projects','services','feed'].includes(tab);root.hidden=!own;
  if(own){for(const child of $('#client-view').children)if(child!==root)child.hidden=true;
   if(tab==='identity'){if(identityMount!==root||!$('#identity-form')){identityMount=root;EcoIdentityUI.client(root);}}
   else{identityMount=null;root.innerHTML=({feed:()=>window.EcoCommunityUI.page(),projects,services,equipment:()=>window.EcoEquipmentUI.render(),arcade:()=>'',dashboard:home,money:moneyPage,help,profile,results,documents:()=>window.EcoPlanUI?.documentsPage()||'',saved:()=>`<div class="eco-section-title"><h1>${t('Your scenarios','Ваши расчёты')}</h1>${routeButton(t('New scenario →','Новый расчёт →'),'tariffs')}</div><div class="eco-grid">${scenarioCards()}</div>`,notifications:()=>`<div class="eco-section-title"><h1>${t('Notifications','Уведомления')}</h1><button class="eco-text" data-eco-read-all>${t('Mark all as read','Прочитать все')}</button></div><section class="eco-card">${rows(events())}</section>`,invite:()=>`<h1 translate="no">EcoGrid Club</h1><section class="eco-card" id="eco-invitation">${t('Loading your link…','Загружаем ссылку…')}</section>`})[tab]();if(['dashboard','feed'].includes(tab))window.EcoCommunityUI?.mount();if(tab==='invite')invite();if(tab==='arcade')window.EcoArcade?.mount(root);}
   if(['dashboard','money','projects','services'].includes(tab))liveController.start();window.EcoWithdrawalUI?.refresh();if(['dashboard','services'].includes(tab))window.EcoEnergyUI?.mount($('.energy-lab'),{onBeat:energyBeat});
  }else{identityMount=null;if(tab==='tariffs'&&!$('#eco-save-scenario'))$('#tariffs-section').insertAdjacentHTML('beforeend',`<section id="eco-save-scenario" class="eco-card" translate="no"><h2>${t('Keep this scenario','Сохранить вариант')}</h2><p>${t('Compare it later or discuss it with your manager. This does not activate a plan.','Вернитесь к нему позже или обсудите с менеджером. Это не активирует план.')}</p><div class="eco-actions"><button class="eco-button" data-eco-save>${t('Save scenario','Сохранить расчёт')}</button>${routeButton(t('View saved scenarios','Открыть сравнение'),'saved')}</div></section>`);}
 };
 async function invite(){if(window.EcoClubUI)return window.EcoClubUI.mount($('#eco-invitation'));try{const r=await fetch(new URL('api/client/invitations',document.baseURI)),data=await r.json();if(!r.ok)throw Error(data.error);const box=$('#eco-invitation');if(!box)return;const link=new URL('register/',document.baseURI);link.searchParams.set('ref',data.code);link.searchParams.set('lang',window.EcoLocale?.language||'en');box.innerHTML=`<p>${t('Your friend can request account access. Their contact information and balance remain private.','Друг сможет оставить заявку на доступ. Его контакты и баланс останутся закрытыми.')}</p><label>${t('Your invitation link','Ваша ссылка')}<input readonly value="${E(link.href)}" id="eco-invite-link"></label><button class="eco-button" data-eco-copy>${t('Copy link','Скопировать ссылку')}</button><div class="eco-grid"><p>${t('Requests','Заявки')}<strong>${data.requests}</strong></p><p>${t('Accounts created','Созданные аккаунты')}<strong>${data.registered}</strong></p></div><small>${t('No monetary referral reward is enabled.','Денежное вознаграждение за приглашения пока не предусмотрено.')}</small>`;}catch(e){if($('#eco-invitation'))$('#eco-invitation').textContent=e.message;}}
 function inquirySnapshot(topic='plan',current=false){
  const p=current?demo.plan:tab==='tariffs'?{...EcoFinance.tiers.find(v=>v.id===chosenTier),tierId:chosenTier,capital:investmentDraft,stationIds:chosenStations}:demo.planDraft||demo.plan;
  const value={topic,...(['plan','account'].includes(topic)&&p?{tierId:p.tierId,capital:p.capital,stationIds:p.stationIds}:{}),...(topic==='station'&&selected?{stationId:selected.id,stationIds:[selected.id]}:{})};
  return EcoWorkspace.context(value,new Set(stations.map(s=>s.id)));
 }
 function questionWith(value){contextData=structuredClone(value);context='';actions['eco-message']();}
 function attachedContext(c){return c?`<section class="eco-inquiry-snapshot" translate="no"><strong>${t('Attached selection','Выбор к вопросу')}</strong><dl>${EcoWorkspace.rows(c,window.EcoLocale?.language).map(([key,value])=>`<div><dt>${E(key)}</dt><dd>${E(value)}</dd></div>`).join('')}</dl>${c.capturedAt?`<small>${date(c.capturedAt)}</small>`:''}</section>`:'';}
 contextMarkup=attachedContext;
 let lessonEnergy=30;
 function lessonResult(){const v=EcoWorkspace.session(lessonEnergy);return `<dl><div><dt>${t('Charging payment','Оплата зарядки')}</dt><dd>${M(v.receipts)}</dd></div><div><dt>${t('Solar + storage cost','Себестоимость солнца и накопителей')}</dt><dd>−${M(v.electricity)}</dd></div><div><dt>${t('Before other costs','До прочих расходов')}</dt><dd>${M(v.beforeOtherCosts)}</dd></div></dl><p>${t('Site costs, maintenance, tax and distribution rules still apply. This amount is not credited to your account.','Ещё учитываются аренда площадки, обслуживание, налоги и условия распределения. Эта сумма не зачисляется на ваш счёт.')}</p>`;}
 actions['eco-session-lesson']=()=>{const r=explorationState();if(!r.read.includes('session')){r.read.push('session');persist();}openModal(`<section class="eco-session-lesson" translate="no"><span class="eco-kicker">${t('CHARGING SESSION · EXAMPLE','ЗАРЯДНАЯ СЕССИЯ · ПРИМЕР')}</span><h2>${t('Follow one charging payment.','Из чего складывается оплата зарядки.')}</h2><label for="eco-session-energy">${t('Energy','Энергия')} · <output id="eco-session-kwh">${lessonEnergy} kWh</output></label><input id="eco-session-energy" type="range" min="10" max="80" step="1" value="${lessonEnergy}"><p>${t('Model assumptions per kWh: charging','Допущения модели за кВт·ч: зарядка')} ${M(EcoBusiness.config.chargingPrice)} · ${t('own solar + storage','своя генерация и накопители')} ${M(EcoBusiness.config.solarStorageCost)} · ${t('utility comparison','сравнение с энергокомпанией')} ${M(EcoBusiness.config.utilityPrice)}. ${t('These are illustrative prices, not actual contracts.','Это условные цены, а не фактические договоры.')}</p><div id="eco-session-result" aria-live="polite">${lessonResult()}</div><button class="eco-button" data-eco-lesson-question>${t('Ask about these costs','Задать вопрос о расходах')}</button></section>`);};
 actions['eco-message']=()=>{if(window.EcoClientCare)return window.EcoClientCare.compose(contextData?.topic||'general',contextData,context);openModal(`<div translate="no"><h2>${t('Message your manager','Сообщение менеджеру')}</h2>${context?`<p>${E(context)}</p>`:''}${attachedContext(contextData)}<form id="eco-question"><label>${t('Your question','Ваш вопрос')}<textarea name="message" required maxlength="1200" rows="5"></textarea></label><button type="submit" class="eco-button">${t('Send question','Отправить вопрос')}</button></form></div>`);};
 actions['eco-help-message']=()=>{context='';contextData=null;actions['eco-message']();};
 actions['eco-active-plan']=()=>{const s=EcoFinance.summary(demo),p=s.active,w=window.ECO_SHARED_CONTEXT.nextWeek;if(!p)return;
  openModal(`<section class="payment-result" translate="no"><span class="payment-preview-label">${t('ACTIVE PLAN','АКТИВНЫЙ ПЛАН')}</span><h2>${E(window.EcoLocale?.t(p.name)||p.name)}</h2><dl class="payment-result-details"><div><dt>${t('In plan','В плане')}</dt><dd>${M(s.capital)}</dd></div><div><dt>${t('Estimated weekly accrual','Расчёт начисления за неделю')}</dt><dd>${M(s.weekly)} · ${p.rate}% / ${t('calendar month','календарный месяц')}</dd></div>${w?`<div><dt>${t('Next weekly credit','Следующее начисление')}</dt><dd>${date(w.periodEnd)}</dd></div>`:''}</dl><h3>${t('Your stations','Ваши станции')} · ${p.stationIds.length}</h3>${p.stationIds.map(stationCard).join('')}${routeButton(t('Plan documents →','Документы плана →'),'documents','eco-button secondary')}</section>`);
 };
 actions.manager=()=>questionWith(inquirySnapshot(tab==='map'?'station':'plan'));actions.profile=()=>go('profile');
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-eco-theme-toggle')){applyTheme(themeNow()==='dark'?'light':'dark');header();document.querySelector('[data-eco-theme-toggle]')?.focus({preventScroll:true});return;}
  if(b.dataset.ecoQuestion)questionWith(inquirySnapshot(b.dataset.ecoQuestion));
  if(b.hasAttribute('data-eco-active-question'))questionWith(inquirySnapshot('plan',true));
  if(b.hasAttribute('data-eco-lesson-question'))questionWith({topic:'session',stationIds:[],lesson:EcoWorkspace.session(lessonEnergy)});
  if(b.hasAttribute('data-eco-upgrade')){const amount=EcoFinance.parseAmount(upgradeAmount);if(!validDemoInvestment(amount))return;const tier=EcoFinance.tiers.find(v=>v.id===upgradeTier);chosenTier=tier.id;investmentDraft=amount;chosenStations=EcoFinance.summary(demo).active.stationIds.slice(0,tier.count);go('tariffs');}
  if(b.dataset.ecoRoute){if(b.dataset.ecoRoute==='documents'&&!ui().read.includes('terms')){ui().read.push('terms');persist();}go(b.dataset.ecoRoute);}
  if(b.dataset.ecoFilter){moneyFilter=b.dataset.ecoFilter;renderClientTab();}if(b.hasAttribute('data-eco-days')){days=Number(b.dataset.ecoDays);renderClientTab();}
  if(b.hasAttribute('data-eco-read-all')){ui().read=[...new Set([...(ui().read||[]),...events().map(e=>e.id)])].slice(-100);persist();renderClientTab();}
  if(b.dataset.energyAsk){const p=demo.plan?.status==='active'?demo.plan:demo.planDraft;contextData={topic:'station',...(p?{tierId:p.tierId,capital:p.capital,stationIds:p.stationIds}:{}),energy:window.EcoEnergyUI.snapshot(b.dataset.energyAsk)};context=t('Energy Lab · energy channel','Energy Lab · направление энергии');actions['eco-message']();}
  if(b.dataset.energyBriefQuestion){const brief=demo.energyBriefs?.find(v=>v.id===b.dataset.energyBriefQuestion);if(brief)window.EcoClientCare.compose('general',null,(window.EcoEnergyJournal.titles()[brief.kind]||'Energy Lab')+' · '+brief.authorName+' · '+brief.id);}
  if(b.hasAttribute('data-energy-discuss')){contextData=null;context=window.EcoEnergyUI.context();actions['eco-message']();}
  if(b.dataset.ecoEvent){const v=events().find(v=>v.id===b.dataset.ecoEvent);if(!v)return;let readSave;if(!ui().read.includes(v.id)){ui().read=[...ui().read,v.id].slice(-100);readSave=persist();}if(v.type==='report'){if(readSave)await readSave;go('services');const journal=document.querySelector('[data-account-journal]');if(journal)journal.open=true;const report=document.querySelector('.energy-week-report');if(report){report.open=true;report.scrollIntoView({behavior:'instant',block:'center'});}return;}if(v.request){showPaymentReceipt(v.request.id);return;}contextData=null;context=v.title+' · '+v.detail;if(v.type==='credit'||v.type==='adjustment'){context+=' · '+(v.operationId||v.id);openModal(operationDetails(v));return;}openModal(`<div translate="no"><h2>${E(v.title)}</h2><p>${E(v.detail)}</p><p>${date(v.date)}</p>${v.operationId?`<p>ID: ${E(v.operationId)}</p>`:''}${v.request?`<dl><dt>ID</dt><dd>${E(v.request.id)}</dd><dt>${t('Payment method','Способ оплаты')}</dt><dd>${E(paymentLabel(v.request))}</dd></dl>`:''}${v.ticket?`<p>${E(v.ticket.reply)}</p>`:''}${v.type==='identity'?routeButton(t('Open documents →','Открыть анкету →'),'identity','eco-button'):''}${button(t('Ask about this','Задать вопрос'),'eco-message')}</div>`);}
  if(b.hasAttribute('data-eco-save')){const tier=EcoFinance.tiers.find(v=>v.id===chosenTier);if(!EcoFinance.valid(investmentDraft)||!EcoFinance.eligible(investmentDraft,tier.id)||chosenStations.length!==tier.count)return toast(t('Check the amount and station selection.','Проверьте сумму и выбранные станции.'));if(ui().scenarios.length>=6)return toast(t('Remove a scenario before saving another.','Удалите один вариант перед сохранением нового.'));ui().scenarios.push({id:crypto.randomUUID(),tierId:tier.id,name:tier.name,rate:tier.rate,ratePeriod:EcoFinance.ratePeriod,capital:investmentDraft,stationIds:[...chosenStations],label:tier.name});persist();toast(t('Scenario saved.','Расчёт сохранён.'));}
  if(b.dataset.ecoLoad){const p=ui().scenarios.find(p=>p.id===b.dataset.ecoLoad);if(p){chosenTier=p.tierId;investmentDraft=p.capital;chosenStations=p.stationIds.slice();go('tariffs');}}
  if(b.dataset.ecoDelete){ui().scenarios=ui().scenarios.filter(p=>p.id!==b.dataset.ecoDelete);persist();renderClientTab();}
  if(b.dataset.ecoDiscuss){const p=ui().scenarios.find(p=>p.id===b.dataset.ecoDiscuss);if(p)questionWith(EcoWorkspace.context({topic:'plan',tierId:p.tierId,capital:p.capital,stationIds:p.stationIds},new Set(stations.map(v=>v.id))));}
  if(b.hasAttribute('data-eco-copy')){try{await navigator.clipboard.writeText($('#eco-invite-link').value);toast(t('Link copied.','Ссылка скопирована.'));}catch{$('#eco-invite-link').select();}}
  if(b.hasAttribute('data-eco-export')){const cutoff=days?Date.now()-days*86400000:0,data=[['Date','Type','Amount USD','Status'],...events().filter(e=>e.amount!==undefined&&Date.parse(e.date)>=cutoff).map(e=>[e.date,e.type,e.amount,e.request?.status||'Recorded'])];const blob=new Blob(['\uFEFF'+data.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ecocharge-account.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 });
 document.addEventListener('click',e=>{if(e.target.closest('[data-eco-clear-help]')){helpQuery='';$('#eco-help-search').value='';$('#eco-answers').innerHTML=answers();$('#eco-help-search').focus();}});
 document.addEventListener('input',e=>{if(e.target.id==='eco-session-energy'){lessonEnergy=Number(e.target.value);$('#eco-session-kwh').textContent=lessonEnergy+' kWh';$('#eco-session-result').innerHTML=lessonResult();}if(e.target.id==='eco-help-search'){helpQuery=e.target.value;$('#eco-answers').innerHTML=answers();}if(e.target.id==='eco-upgrade-amount'){upgradeAmount=e.target.value;refreshUpgrade();}});
 document.addEventListener('change',e=>{if(e.target.id==='eco-upgrade-tier'){upgradeTier=e.target.value;refreshUpgrade();}});
 document.addEventListener('submit',async e=>{if(e.target.id==='eco-question'){e.preventDefault();const message=e.target.elements.message.value.trim();if(!message)return;demo.tickets.push({id:'MSG-'+crypto.randomUUID(),subject:context||t('Question for my manager','Вопрос менеджеру'),message,...(contextData?{context:structuredClone(contextData)}:{}),status:'Open',date:new Date().toISOString(),reply:''});const submit=e.target.querySelector('button[type=submit]');submit.disabled=true;const saved=await persist();if(saved){$('#modal').close();toast(t('Question sent with its context.','Вопрос отправлен вместе с контекстом.'));context='';contextData=null;}else if(submit.isConnected)submit.disabled=false;}
  if(e.target.id==='eco-preferences'){e.preventDefault();ui().timezone=e.target.elements.timezone.value;persist();toast(t('Preferences saved.','Настройки сохранены.'));}
 });
 document.addEventListener('ecocharge:locale',()=>{identityMount=null;renderClientTab();});
})();
