'use strict';
window.EcoEnergyJournal=(()=>{
 const business=window.EcoBusiness;
 const model=window.EcoEnergyJournalModel,t=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en;
 const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=c=>new Intl.NumberFormat(window.EcoLocale?.locale||'en-US',{style:'currency',currency:'USD'}).format(c/100);
 const date=n=>new Date(n).toLocaleDateString(window.EcoLocale?.locale||'en-US',{dateStyle:'medium',timeZone:'UTC'});
 const names=()=>({...business.labels(window.EcoLocale?.language),city:t('City · earlier model','Город · прежняя модель'),highway:t('Highway · earlier model','Трасса · прежняя модель'),retail:t('Retail · earlier model','ТЦ · прежняя модель')});
 const titles=()=>({weekly:t('Weekly review','Недельный отчёт'),recommendation:t('Manager’s scenario','Сценарий менеджера'),call:t('After our call','Итоги звонка'),event:t('Model network note','Заметка о модели сети')});
 let reportOpen=false;
 document.addEventListener?.('toggle',event=>{if(event.target.matches?.('.energy-week-report'))reportOpen=event.target.open;},true);
 function labMarkup(){return `<section class="energy-economics" aria-labelledby="energy-economics-title"><div class="energy-economics-head"><div><span class="energy-utility">${t('ONE MODEL · ONE WEEKLY TOTAL','ОДНА МОДЕЛЬ · ОДИН ИТОГ НЕДЕЛИ')}</span><h3 id="energy-economics-title">${t('From energy to your model share','От энергии к модельной доле')}</h3></div><span class="energy-model-badge">${t('Calculation model','Расчётная модель')}</span></div><p data-energy-rhythm></p><ol class="energy-chain">${[['energy',t('Energy equivalent','Эквивалент энергии')],['revenue',t('Receipts','Выручка')],['cost',t('Costs','Расходы')],['net',t('Net result','Чистый результат')],['share',t('Example share','Условная доля')],['today',t('Accrued today · UTC','Набежало сегодня · UTC')]].map(([key,label])=>`<li><small>${label}</small><strong data-energy-value="${key}">—</strong></li>`).join('')}</ol><div class="energy-economics-foot"><span>${t('Weekly reference','Эталон недели')} <b data-energy-weekly>—</b></span><span>${t('Today’s target within this period','Ориентир за сегодня в пределах периода')} <b data-energy-daily>—</b></span></div><details><summary>${t('Calculation assumptions','Допущения расчёта')}</summary><p>${t('Illustrative network figures are calculated backward from your plan’s model accrual: share 0.4%, costs 35% of receipts, blended energy price $0.25/kWh. These are not station measurements, verified energy sales or ownership rights. The energy figure below is an economic equivalent, not measured solar production or the integral of the dispatch sandbox.','Условные показатели сети рассчитаны обратно от начисления модели плана: доля 0,4%, расходы 35% выручки, средняя цена энергии 0,25 $/кВт·ч. Это не данные станций и не права владения. Энергия — экономический эквивалент, а не измеренная солнечная выработка или интеграл модельного потока.')}</p><p>${t('The fixed UTC demand curve changes the display pace only. Play, Peak and location allocation do not change the weekly total or available balance. Calendar-day amounts may differ by one cent due to rounding; partial first and last days are capped.','Фиксированный профиль спроса UTC меняет только темп отображения. Play, Peak и разбивка локаций не меняют итог недели или доступный баланс. Из-за округления суточные суммы могут отличаться на один цент; неполные первые и последние сутки ограничены периодом.')}</p></details><div class="energy-network-event"><span>${t('MODEL NETWORK / NOW','МОДЕЛЬ СЕТИ / СЕЙЧАС')}</span><p data-energy-model-event></p></div></section>`;}
 function paintLab(host,payload,now,hour,peak){if(!host?.isConnected)return;const v=model.view(payload,now,hour,peak),set=(selector,text)=>{const el=host.querySelector(selector);if(el&&el.textContent!==text)el.textContent=text;};
  const c=v.chain,values={energy:(c.kwh/1000).toFixed(3)+' MWh',revenue:money(c.revenueCents),cost:money(c.costCents),net:money(c.netCents),share:'0.4%',today:money(v.todayCents)};
  for(const [key,value]of Object.entries(values))set(`[data-energy-value="${key}"]`,v.active?value:'—');
  host.querySelector('[data-energy-chart-wall]')?.setAttribute?.('d',`M${((now-v.dayStart)/86400000*216).toFixed(1)} 6V80`);
  set('[data-energy-weekly]',v.active?money(Math.round(v.weeklyEarn*100)):'—');set('[data-energy-daily]',v.active?money(v.targetCents):'—');
  set('[data-energy-rhythm]',v.active?t('UTC daily rhythm · '+v.pace.toFixed(2)+'× the average pace. Preliminary display; one credit when the plan week closes.','Суточный ритм UTC · '+v.pace.toFixed(2)+'× среднего темпа. Предварительный расчёт; одно зачисление при закрытии недели плана.'):t('Activate a plan to see your model amounts. You can explore dispatch now.','Активируйте план, чтобы увидеть свой модельный расчёт. Распределение нагрузки доступно уже сейчас.'));
  for(const site of v.sites){set(`[data-energy-contribution="${site.id}"]`,v.active?money(site.cents):'—');set(`[data-energy-weight="${site.id}"]`,Math.round(site.weight*100)+'%');}
  const leader=v.sites.slice().sort((a,b)=>b.weight-a.weight)[0];set('[data-energy-model-event]',names()[leader.id]+' · '+Math.round(leader.weight*100)+'% '+t('of the illustrated energy flow at ','модельного энергопотока в ')+String(Math.floor(hour)).padStart(2,'0')+':'+String(Math.floor(hour%1*60)).padStart(2,'0')+(peak?t(' · Peak scenario',' · Пиковый сценарий'):'')+'. '+t('Move the time slider to compare.','Переместите время для сравнения.'));
 }
 function comparison(c){return `<dl class="energy-comparison"><div><dt>${t('Energy channel','Направление энергии')}</dt><dd>${names()[c.location]} · ${c.percent}%</dd></div><div><dt>${t('Illustrative week: before → after','Модельная неделя: было → стало')}</dt><dd>${money(c.beforeCents)} → ${money(c.afterCents)}</dd></div><div><dt>${t('Channel difference','Разница по направлению')}</dt><dd>${c.deltaCents>=0?'+':''}${money(c.deltaCents)}</dd></div><div><dt>${t('Total weekly difference','Изменение итога недели')}</dt><dd>${money(0)}</dd></div></dl><p class="energy-journal-note">${t('Comparison against the regular 18:00 model. This does not change your plan, rights or weekly amount.','Сравнение с обычным сценарием 18:00. План, права и недельная сумма остаются прежними.')}</p>`;}
 function briefMarkup(b,account){const stale=b.kind==='recommendation'&&b.plan?.appliedAt!==account.plan?.appliedAt;return `<article class="energy-brief" data-energy-brief="${E(b.id)}"><header><span>${titles()[b.kind]||titles().event}</span><time>${date(b.createdAt)}</time></header><p class="energy-author">${E(b.authorName)} · ${t('Published for you','Опубликовано для вас')}</p><p class="energy-brief-text">${E(b.text)}</p>${b.report?`<p>${t('Closed credits in report','Закрытые начисления в отчёте')}: <b>${money(b.report.cents)}</b> · ${date(b.report.start)} – ${date(b.report.end-1)}</p>`:''}${b.comparison?comparison(b.comparison):''}${stale?`<p>${t('Saved for an earlier plan. Ask your manager to review it.','Сохранено для прежнего плана. Попросите менеджера обновить расчёт.')}</p>`:''}<button type="button" class="eco-text" data-energy-brief-question="${E(b.id)}">${t('Discuss with my manager','Обсудить с менеджером')} →</button></article>`;}
 function reportMarkup(report,comment){return `<div class="energy-report"><span class="eco-kicker">${t('MONDAY REVIEW · UTC','ОБЗОР ПО ПОНЕДЕЛЬНИКАМ · UTC')}</span><h3>${date(report.start)} — ${date(report.end-1)}</h3><strong>${money(report.cents)}</strong><p>${report.credits.length?t('Recorded model credits. Completed periods: '+report.credits.length+'.','Учтённые начисления по модели. Закрытых периодов: '+report.credits.length+'.'):t('No plan periods closed in this calendar week. Your current period continues.','За эту календарную неделю периоды плана не закрывались. Текущий период продолжается.')}</p><small>${t('This report does not create a new credit. Plan periods close 7 days after their own start.','Отчёт не создаёт нового зачисления. Периоды плана закрываются через 7 дней от своего начала.')}</small>${comment?`<blockquote><p>${E(comment.text)}</p><cite>${E(comment.authorName)}</cite></blockquote>`:`<p class="energy-journal-note">${t('Your manager has not added a comment yet.','Менеджер пока не добавил комментарий.')}</p>`}</div>`;}
 function markup(account,payload,now=Date.now()){
  const yesterday=model.daily(account,payload,now-86400000),winner=yesterday.sites.slice().sort((a,b)=>b.cents-a.cents)[0],report=model.report(account,now),briefs=(account.energyBriefs||[]).slice().reverse(),comment=briefs.find(b=>b.kind==='weekly'&&b.report?.id===report.id),pinned=briefs.find(b=>b.kind==='recommendation'),other=briefs.filter(b=>b.id!==pinned?.id).slice(0,4);
  const milestoneNames={dollar:t('First model dollar','Первый модельный доллар'),week:t('First closed week','Первая закрытая неделя'),withdrawal:t('First approved withdrawal · model','Первый подтверждённый вывод · модель'),month:t('30 days since activation','30 дней от активации')};
  return `<section class="energy-journal" data-energy-journal data-journal-day="${Math.floor(now/86400000)}" translate="no"><div class="eco-section-title"><div><span class="eco-kicker">${t('YOUR NETWORK JOURNAL','ВАШ ЖУРНАЛ СЕТИ')}</span><h2>${t('Accruals & reports','Начисления и отчёты')}</h2></div><button class="eco-text" data-action="call">${t('Request the next call','Запросить следующий звонок')} ↗</button></div><div class="energy-journal-grid"><div class="energy-yesterday"><span>${t('Yesterday · UTC · model','Вчера · UTC · модель')}</span><strong>${money(yesterday.cents)}</strong><p>${yesterday.cents?t('Largest illustrated contribution: ','Наибольший модельный вклад: ')+names()[winner.id]+' · '+money(winner.cents):t('No model accrual for yesterday.','Вчера модельных начислений не было.')}</p><small>${t('Reconstructed from period data and the fixed demand profile. Channel attribution is illustrative; it does not report actual energy sales.','Расчёт по данным периодов и фиксированному профилю спроса. Распределение по направлениям условное; это не фактические продажи энергии.')}</small></div><details class="energy-week-report" ${reportOpen?'open':''}><summary>${t('Weekly report available','Недельный отчёт доступен')} · ${date(report.end)}</summary>${reportMarkup(report,comment)}</details></div><div class="energy-milestones" aria-label="${t('Your milestones','Ваши вехи')}">${model.milestones(account,payload,now).map(m=>`<div data-energy-milestone="${m.id}" data-done="${m.done}"><span class="energy-milestone-mark" aria-hidden="true">${m.done?'✓':'○'}</span><span>${milestoneNames[m.id]}<small data-milestone-status>${m.done?t('Reached','Достигнуто'):t('Ahead','Впереди')}</small></span></div>`).join('')}</div>${pinned?`<div class="energy-pinned"><span class="eco-kicker">${t('PINNED SCENARIO','ЗАКРЕПЛЁННЫЙ СЦЕНАРИЙ')}</span>${briefMarkup(pinned,account)}</div>`:''}<div class="energy-briefs"><h3>${t('From your manager','От вашего менеджера')}</h3>${other.length?other.map(b=>briefMarkup(b,account)).join(''):`<p class="energy-journal-note">${t('Published call notes, weekly comments and model network updates appear here.','Здесь появятся опубликованные итоги звонков, комментарии к неделе и заметки о модели сети.')}</p>`}</div></section>`;
 }
 function tick(account,payload,now){const root=document.querySelector('[data-energy-journal]');if(!root)return;if(root.dataset.journalDay!==String(Math.floor(now/86400000))){root.outerHTML=markup(account,payload,now);return;}for(const m of model.milestones(account,payload,now)){const node=root.querySelector(`[data-energy-milestone="${m.id}"]`);if(node&&node.dataset.done!==String(m.done)){node.dataset.done=String(m.done);node.querySelector('.energy-milestone-mark').textContent=m.done?'✓':'○';node.querySelector('[data-milestone-status]').textContent=m.done?t('Reached','Достигнуто'):t('Ahead','Впереди');}}}
 return {labMarkup,paintLab,markup,tick,briefMarkup,comparison,titles,names};
})();
