(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('../funding-policy.js'),require('../account-finance.js'));else root.EcoFundingUI=factory(root.EcoFunding,root.EcoFinance);})(typeof window==='undefined'?globalThis:window,function(funding,finance){
 'use strict';
 const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function hero(account,lang='en'){
  const v=funding.intent(account);if(!v.visible)return '';
  const ru=lang==='ru',t=(en,russian)=>ru?russian:en,money=n=>new Intl.NumberFormat(ru?'ru-RU':'en-US',{style:'currency',currency:'USD'}).format(n),p=v.draft;
  const manager=escape(account.manager?.name||t('your manager','ваш менеджер'));
  return `<section class="eco-fund-hero" data-funding-hero data-energy-money translate="no" aria-label="${t('Fund your plan','Пополнение для плана')}">
   <div class="eco-fund-main"><span class="eco-kicker">${v.managerDraft?t('YOUR MANAGER’S SELECTION','ВЫБОР ВАШЕГО МЕНЕДЖЕРА'):p?t('YOUR SAVED SELECTION','ВАШ СОХРАНЁННЫЙ ВЫБОР'):t('YOUR FIRST STEP','ПЕРВЫЙ ШАГ')}</span>
   <h2>${p?t('Fund your selected plan.','Пополните счёт для выбранного плана.'):t('Start with your balance.','Начните с пополнения счёта.')}</h2>
   <p class="eco-fund-context">${p?escape(p.name)+' · '+money(p.capital):t('Add funds from $250. Choose your station group before activating a plan.','Пополнение от 250 $. Выберите группу станций перед активацией плана.')}</p>
   ${v.managerDraft?`<p class="eco-post-call" data-post-call>${t('Plan prepared by','План подготовил(а)')} <strong>${manager}</strong>. ${t('Fund','Пополните на')} <strong>${money(v.required)}</strong>${t(', then activate your selection.',', затем активируйте выбранный план.')}</p>`:''}
   <div class="eco-fund-actions"><button class="eco-button" data-action="fund-overview">${t('Fund','Пополнить на')} ${money(v.amount)} <span aria-hidden="true">→</span></button><button class="eco-text" data-action="${p?'journey-my-plan':'journey-resume'}">${p?t('Review plan','Проверить план'):t('Build my plan','Собрать мой план')}</button></div>
   <p class="eco-fund-preview">${funding.previewNotice(lang)}</p>${v.remaining?`<small>${t('Up to $100,000 per request. Remaining funding after this amount:','До 100 000 $ на заявку. После этой суммы останется пополнить:')} ${money(v.remaining)}</small>`:''}</div>
   <dl class="eco-fund-summary"><div><dt>${t('Available balance','Доступный баланс')}</dt><dd>${money(v.available)}</dd></div>${p?`<div><dt>${t('Still needed for this plan','Осталось для этого плана')}</dt><dd>${money(v.required)}</dd></div><div><dt>${t('Weekly model after activation','Модель за неделю после активации')}</dt><dd>${money(finance.planWeekly(p))}</dd></div>`:`<div><dt>${t('Plan status','Статус плана')}</dt><dd class="eco-fund-status">${t('Not activated','Не активирован')}</dd></div>`}<div class="eco-fund-next"><dt>${t('After funding is approved','После подтверждения пополнения')}</dt><dd>${t('Review & activate your plan','Проверьте и активируйте план')}</dd></div></dl>
  </section>`;
 }
 function activationHero(account,lang='en'){
  const v=funding.activation(account);if(!v.visible)return '';
  const t=(en,ru)=>lang==='ru'?ru:en,money=n=>new Intl.NumberFormat(lang==='ru'?'ru-RU':'en-US',{style:'currency',currency:'USD'}).format(n),p=v.draft;
  return `<section class="eco-fund-hero eco-activation-hero" data-activation-hero data-energy-money translate="no" aria-label="${t('Activate your plan','Активация плана')}"><div class="eco-fund-main"><span class="eco-kicker">${t('FUNDS AVAILABLE · YOUR NEXT STEP','СРЕДСТВА ДОСТУПНЫ · СЛЕДУЮЩИЙ ШАГ')}</span><h2>${t('Your funds are ready. Activate your plan.','Средства доступны. Активируйте план.')}</h2><p class="eco-fund-context">${escape(p.name)} · ${money(p.capital)} · ${t('Stations','Станций')}: ${p.stationIds.length}</p><div class="eco-fund-actions"><button class="eco-button" data-action="activate-draft">${t('Activate plan','Активировать план')} <span aria-hidden="true">→</span></button><button class="eco-text" data-action="journey-my-plan">${t('Review plan','Проверить план')}</button></div><p class="eco-activation-note">${t('Activation moves the selected amount into your plan and starts its model period. Confirm the details in the next step.','Активация переводит выбранную сумму в план и запускает модельный период. Подтвердите детали на следующем шаге.')}</p><button class="eco-text eco-activation-topup" data-action="topup">${t('Add more funds','Пополнить ещё')}</button></div><dl class="eco-fund-summary"><div><dt>${t('Available balance','Доступный баланс')}</dt><dd>${money(v.available)}</dd></div><div><dt>${t('Weekly model after activation','Модель за неделю после активации')}</dt><dd>${money(finance.planWeekly(p))}</dd></div><div><dt>${t('Balance after activation','Остаток после активации')}</dt><dd>${money(v.after)}</dd></div>${v.reserved?`<div><dt>${t('Withdrawal reserve unchanged','Резерв вывода сохраняется')}</dt><dd>${money(v.reserved)}</dd></div>`:''}</dl></section>`;
 }
 return {hero,activationHero};
});
