'use strict';
window.EcoIdentityUI=(()=>{
 const t=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const labels=()=>({firstName:t('First name','Имя'),lastName:t('Last name','Фамилия'),birthDate:t('Date of birth','Дата рождения'),country:t('Country','Страна'),city:t('City','Город'),address:t('Address','Адрес'),postalCode:t('ZIP / postal code','Почтовый индекс')});
 const statuses=()=>({draft:t('Not submitted','Не отправлено'),submitted:t('Sent to your manager','Отправлено менеджеру'),reviewed:t('Reviewed by your manager','Просмотрено менеджером'),changes_requested:t('Changes requested','Нужны уточнения')});
 let state,clientRoot,files={},busy=false;
 async function api(route,method='GET',body){const r=await fetch(new URL('api/'+route,document.baseURI),{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(route.startsWith('client/')?{...body,clientId:window.ECO_SHARED_CONTEXT.client.id}:body)}:{})});const data=await r.json();if(!r.ok){const errors={'Confirm that you want to send these details.':'Подтвердите отправку данных.','Enter your first and last name.':'Укажите имя и фамилию.','Document details changed. Refresh and try again.':'Анкета изменилась. Обновите страницу и повторите.','Check the date of birth.':'Проверьте дату рождения.','Choose a review result and add a comment.':'Укажите результат и комментарий проверки.','Your signed-in account changed. Sign in again.':'Аккаунт изменился. Войдите заново.'};throw Error(t(data.error,errors[data.error]||data.error));}return data;}
 function values(){return Object.fromEntries([...document.querySelectorAll('#identity-form [data-identity-field]')].map(el=>[el.name,el.value]));}
 function error(e){const box=document.querySelector('#identity-error');if(box)box.textContent=t('Could not save. ','Не удалось сохранить. ')+(window.EcoLocale?.t(e.message)||e.message);}
 function inputFields(value){return Object.entries(labels()).map(([key,label])=>`<label>${label}<input data-identity-field name="${key}" type="${key==='birthDate'?'date':'text'}" maxlength="${key==='address'?250:100}" value="${esc(value[key])}" ${['firstName','lastName'].includes(key)?'required':''} autocomplete="${({firstName:'given-name',lastName:'family-name',birthDate:'bday',country:'country-name',city:'address-level2',address:'street-address',postalCode:'postal-code'})[key]}"></label>`).join('');}
 function paint(value=state.fields){if(!clientRoot?.isConnected)return;clientRoot.innerHTML=`<div class="eco-section-title"><div><span class="eco-kicker">${t('YOUR PROFILE','ВАША АНКЕТА')}</span><h1>${t('Documents & details','Документы и данные')}</h1></div><span class="eco-tag">${t('Optional','Необязательно')}</span></div><p>${t('Add a photo to fill in recognized fields. Check the details before sending them to your manager. You can keep using your account without this step.','Добавьте фото, чтобы заполнить распознанные поля. Проверьте данные перед отправкой менеджеру. Эту процедуру можно пропустить и пользоваться кабинетом.')}</p><p class="eco-status">${statuses()[state.status]}${state.reviewNote?' · '+esc(state.reviewNote):''}</p><div class="identity-slots">${['front','back'].map(slot=>{const saved=state.files.find(f=>f.slot===slot);return `<section class="eco-card"><h3>${slot==='front'?t('Front / photo page','Лицевая сторона / разворот с фото'):t('Back · if needed','Обратная сторона · при необходимости')}</h3>${saved?`<img class="identity-preview" src="api/client/identity/file/${saved.id}" alt="${t('Attached document','Прикреплённый документ')}"><button type="button" class="eco-text" data-identity-remove="${saved.id}">${t('Remove image','Удалить фото')}</button>`:`<div class="identity-empty">${t('JPG or PNG · up to 6 MB','JPG или PNG · до 6 МБ')}</div>`}<label class="eco-button" tabindex="0" role="button">${t('Take a photo','Снять камерой')}<input type="file" data-identity-pick="${slot}" accept="image/jpeg,image/png" capture="environment" hidden></label><label class="eco-button secondary" tabindex="0" role="button">${t('Choose a file','Выбрать файл')}<input type="file" data-identity-pick="${slot}" accept="image/jpeg,image/png" hidden></label><div data-identity-preview="${slot}"></div></section>`;}).join('')}</div><p class="eco-muted">${t('Images are stored privately on this project server and are available to you, your assigned manager and the administrator. Recognition runs locally; no external AI receives the image.','Изображения хранятся в закрытой базе проекта и доступны вам, ответственному менеджеру и администратору. Распознавание выполняется локально; внешний AI не получает фото.')}</p><form id="identity-form"><div class="identity-fields">${inputFields(value)}</div><label class="identity-consent"><input type="checkbox" name="consent" required> ${t('I checked these details and want to add them to my profile and share them with my manager.','Я проверил данные и хочу добавить их в анкету и передать моему менеджеру.')}</label><button class="eco-button" type="submit">${t('Save & send details','Сохранить и отправить данные')}</button></form><p id="identity-error" role="alert"></p><p id="identity-feedback" role="status"></p>`;}
 async function client(root){clientRoot=root;root.innerHTML=`<p>${t('Loading your details…','Загружаем анкету…')}</p>`;try{state=await api('client/identity');paint();}catch(e){root.textContent=e.message;}}
 async function normalize(file){if(file.size>6*1024*1024||!['image/jpeg','image/png'].includes(file.type))throw Error(t('Choose JPG or PNG up to 6 MB.','Выберите JPG или PNG до 6 МБ.'));const bitmap=await createImageBitmap(file),scale=Math.min(1,2200/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.9);}
 document.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.matches('label[role=button]')&&e.target.querySelector('[data-identity-pick]')){e.preventDefault();e.target.querySelector('input').click();}});
 document.addEventListener('change',async e=>{const slot=e.target.dataset.identityPick;if(!slot||!e.target.files?.[0])return;try{const data=await normalize(e.target.files[0]);files[slot]=data;const box=document.querySelector(`[data-identity-preview="${slot}"]`);box.innerHTML=`<img class="identity-preview" src="${data}" alt="${t('Photo preview','Предпросмотр фото')}"><button class="eco-button" data-identity-upload="${slot}">${t('Attach & read fields','Прикрепить и распознать')}</button><small>${t('The image will be sent to the project server.','Фото будет отправлено на сервер проекта.')}</small>`;}catch(err){error(err);}});
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;try{
  if(b.dataset.identityUpload){busy=true;b.disabled=true;b.textContent=t('Reading image…','Распознаём…');const slot=b.dataset.identityUpload,old=values();state=await api('client/identity/upload','POST',{slot,mime:'image/jpeg',base64:files[slot].split(',')[1],version:state.version});files={};paint({...state.fields,...state.suggested,...Object.fromEntries(Object.entries(old).filter(([,v])=>v))});document.querySelector('#identity-feedback').textContent=state.ocr==='suggested'?t('Suggested fields are ready. Check every field before sending.','Поля распознаны. Проверьте каждое поле перед отправкой.'):t('Image attached. Automatic reading could not fill the fields; enter them below.','Фото прикреплено. Автоматически заполнить поля не удалось — введите их ниже.');}
  if(b.dataset.identityRemove){const old=values();busy=true;state=await api('client/identity/remove','POST',{id:b.dataset.identityRemove,version:state.version});paint(old);}
  if(b.dataset.identityReview){const container=b.closest('[data-identity-client]'),uid=container.dataset.identityClient,note=container.querySelector('textarea').value;busy=true;await api('staff/clients/'+uid+'/identity/review','POST',{version:Number(container.dataset.version),status:b.dataset.identityReview,note});await staff(container,uid);}
 }catch(err){error(err);const box=b.closest('[data-identity-client]')?.querySelector('[role=alert]');if(box)box.textContent=err.message;}finally{busy=false;if(b.isConnected)b.disabled=false;}});
 document.addEventListener('submit',async e=>{if(e.target.id!=='identity-form')return;e.preventDefault();if(busy)return;busy=true;const b=e.target.querySelector('button');b.disabled=true;try{state=await api('client/identity/submit','POST',{fields:values(),version:state.version,consent:e.target.elements.consent.checked});paint();document.querySelector('#identity-feedback').textContent=t('Saved to your profile and sent to your manager.','Сохранено в анкете и передано менеджеру.');}catch(err){error(err);}finally{busy=false;if(b.isConnected)b.disabled=false;}});
 async function staff(root,uid){root.dataset.identityClient=uid;root.innerHTML='<p>'+t('Loading documents…','Загружаем документы…')+'</p>';try{const p=await api('staff/clients/'+uid+'/identity');if(!root.isConnected)return;root.dataset.version=p.version;root.innerHTML=`<h3>${t('Client documents','Документы клиента')}</h3><p>${statuses()[p.status]}</p><dl class="wf-facts">${Object.entries(labels()).map(([key,label])=>`<div><dt>${label}</dt><dd translate="no">${esc(p.fields[key]||'—')}</dd></div>`).join('')}</dl><div class="identity-slots">${p.files.map(f=>`<a href="api/staff/clients/${uid}/identity/file/${f.id}" target="_blank" rel="noopener">${f.slot==='front'?t('Front','Лицевая сторона'):t('Back','Обратная сторона')} · ${Math.round(f.size/1024)} KB ↗</a>`).join('')}</div>${p.status==='submitted'?`<label>${t('Review comment','Комментарий проверки')}<textarea maxlength="500" rows="2"></textarea></label><button class="crm-button" data-identity-review="reviewed">${t('Mark as reviewed','Отметить просмотренным')}</button><button class="crm-button outline" data-identity-review="changes_requested">${t('Request changes','Запросить уточнение')}</button>`:''}<p>${esc(p.reviewNote)}</p><small>${t('Document review does not certify identity or complete regulatory verification.','Просмотр документов не является удостоверением личности или завершённой регуляторной проверкой.')}</small><p role="alert"></p>`;}catch(e){root.textContent=e.message;}}
 return {client,staff};
})();
