(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EcoChargeModel=api;})(typeof window==='object'?window:globalThis,()=>{
 'use strict';
 const policy=Object.freeze({version:'charge-revenue-v1',participantShare:.58,companyShare:.42,minimumStations:3,minimumAmount:250,currency:'USD',baseAllocationIncluded:true,aiCost:472,aiDays:30,welcomeCoins:500,executionStatus:'not-connected'});
 const pairs={
  who:['EcoGrid is an energy and technology project. Charge focuses on EV charging infrastructure. The agreement must identify the full legal name and registration number of the contracting entity.','EcoGrid — проект в сфере энергетики и технологий. Charge связан с зарядной инфраструктурой для электромобилей. В договоре должны быть указаны полное юридическое название и регистрационный номер стороны договора.'],
  where:['Charge targets the United States. Before participation, review the company jurisdiction and address, each site address, its operator and evidence of the right to receive its revenue. These documents are not yet supplied here.','Целевой рынок Charge — США. До участия нужно проверить юрисдикцию и адрес компании, адрес каждого объекта, оператора и документы на право получать его выручку. Эти документы пока не предоставлены.'],
  work:['The proposed model covers financing and operation: site selection, equipment, connection, maintenance and driver payments. The proposal must specify the responsibilities of EcoGrid, the operator and contractors.','Предлагаемая модель объединяет финансирование и эксплуатацию: выбор площадки, оборудование, подключение, обслуживание и оплату водителями. Предложение должно определять обязанности EcoGrid, оператора и подрядчиков.'],
  source:['Drivers pay for EV charging. Received charging revenue funds participant distributions. A calculation or a station photograph does not confirm that revenue.','Водители оплачивают зарядку электромобилей. Источник выплат участникам — полученная выручка зарядок. Расчёт или фотография станции не подтверждают эту выручку.'],
  rights:['Your contractual right, share, reporting, payment schedule and exit conditions must be defined before funding. The site and complete funding budget must be known. Choosing a directory location does not create ownership or a right to revenue.','До внесения денег договор должен определить ваше право, долю, отчётность, порядок выплат и выход. Объект и полный бюджет финансирования должны быть известны. Выбор локации в справочнике не создаёт собственность или право на выручку.'],
  split:['Participants receive 58% of gross charging revenue in proportion to their agreed shares. The company receives 42% and pays ALL electricity, rent, maintenance, staff, acquisition and other operating costs from its portion. Its profit is the remainder after these costs.','Участникам распределяются 58% всей выручки зарядок пропорционально согласованным долям. Компания получает 42% и из них оплачивает ВСЕ расходы: электричество, аренду, обслуживание, персонал, привлечение клиентов и остальные операционные затраты. Прибыль компании — остаток после этих расходов.'],
  formula:['For each station: received revenue × 58% × your contractual share. Add the results across your stations. This is a revenue share, not a fixed monthly interest rate or a promise to return the original capital.','По каждой зарядке: полученная выручка × 58% × ваша договорная доля. Результаты по выбранным зарядкам складываются. Это доля выручки, а не фиксированный месячный процент или обещание возврата вложенного капитала.'],
  allocation:['Choose at least three eligible chargers. Basic allocation across them is included. Changes apply to future periods under the agreement; completed distributions are never moved between clients. More chargers diversify demand exposure but cannot guarantee a payout.','Выберите минимум три доступные для участия зарядки. Базовое распределение между ними включено. Изменения применяются к будущим периодам по договору; завершённые выплаты между клиентами не перераспределяются. Несколько зарядок распределяют риск загрузки, но не гарантируют выплату.'],
  ai:['Paid AI is an optional optimization service intended to increase income by improving future allocation among eligible chargers using demand and project constraints. Price: 472 EcoCoin for 30 days. A 500-coin gift covers one period and leaves 28. Basic allocation continues without this service.','Платный AI — дополнительная оптимизация для повышения дохода: улучшает планируемое распределение участия между доступными зарядками с учётом спроса и ограничений проекта. Цена — 472 EcoCoin за 30 дней. Подарка 500 хватит на один период, останется 28. Без услуги базовое распределение продолжается.'],
  aiEvidence:['The service is not connected to live allocation yet. Any income uplift is a projection until supported by measured results. AI cannot create a missing revenue balance or guarantee the projected payout.','Услуга пока не подключена к реальному распределению. Прибавка к доходу остаётся прогнозом до подтверждения измеренными результатами. AI не создаёт недостающую выручку и не гарантирует прогнозную выплату.'],
  costs:['Operating savings within the company’s 42% improve the company result. They do not automatically increase the participant’s 58% revenue share. The participant benefits only when eligible revenue or the contractual allocation improves.','Экономия расходов внутри 42% улучшает результат компании. Она не повышает автоматически выплату участнику из 58% выручки. Для участника важны рост учитываемой выручки или улучшение договорного распределения.'],
  proof:['Before activation: verified contracting entity, site and operator rights, total funding budget, your shares, revenue reporting, payout dates and exit terms. Until these are available, save a selection and discuss the documents with the Academy.','До активации: подтверждённая сторона договора, права на объекты и оператор, полный бюджет, ваши доли, отчётность по выручке, даты выплат и выход. Пока данных нет, сохраните подборку и обсудите документы с Академией.'],
  cadence:['Distributions follow verified revenue and contractual periods. The account separates a weekly planning estimate from verified revenue.','Выплаты зависят от подтверждённой выручки и периодов договора. Кабинет разделяет недельный расчётный ориентир и подтверждённую выручку.']
 };
 const weeklyReference=Object.freeze({capital:250,days:7,base:Object.freeze([7,8,9]),ai:Object.freeze([10,11,12]),kind:'user-provided-projection'});
 function weeklyOffer(capital=250){cents(capital);if(capital<250||capital>1e7)throw Error('Enter at least $250.');const factor=capital/weeklyReference.capital,scale=values=>values.map(v=>Math.round(v*factor*100)/100);return {capital,days:7,base:scale(weeklyReference.base),ai:scale(weeklyReference.ai),kind:weeklyReference.kind};}
 const questions=[['who','Who are you?','Кто вы?'],['where','Where are the company and chargers?','Где компания и зарядки?'],['work','What does EcoGrid do?','Что делает EcoGrid?'],['source','Where does my income come from?','Откуда мой заработок?'],['rights','What do I receive for my money?','Что я получаю за свои деньги?'],['split','How is revenue distributed?','Как распределяется выручка?'],['formula','How is my payment calculated?','Как рассчитывается моя выплата?'],['allocation','Why at least three chargers?','Зачем минимум три зарядки?'],['ai','What does paid AI add?','Что даёт платный AI?']];
 const copy=(key,lang='en')=>(pairs[key]||['',''])[lang==='ru'?1:0];
 const faq=(lang='en')=>questions.map(([id,en,ru])=>({id,question:lang==='ru'?ru:en,answer:copy(id,lang)+(id==='ai'?' '+copy('aiEvidence',lang):'')}));
 const cents=v=>{if(!Number.isFinite(v)||v<0||v>1e10||Math.abs(v*100-Math.round(v*100))>1e-4)throw Error('Invalid USD amount.');return Math.round(v*100);};
 function selection(input,allowed){
  const capital=Number(input?.capital),ids=input?.stationIds;
  cents(capital);if(capital<policy.minimumAmount||capital>1e7)throw Error('Enter at least $250.');
  if(!Array.isArray(ids)||ids.length<policy.minimumStations||ids.length>100||new Set(ids).size!==ids.length||ids.some(id=>!Number.isSafeInteger(id)||allowed&&!allowed.has(id)))throw Error('Select at least three different eligible chargers.');
  return {economyModel:policy.version,tierId:['single','network','portfolio','scale'].includes(input.tierId)?input.tierId:'single',name:'Charge',capital,stationIds:ids.slice(),rate:13,ratePeriod:'calendar-month',period:'week',settlementBasis:'projection',baseAllocationIncluded:true};
 }
 // A deterministic basic allocation proposal, never a claim of live AI execution.
 function allocate(capital,stationIds){selection({capital,stationIds});const total=cents(capital),base=Math.floor(total/stationIds.length),rest=total%stationIds.length;return stationIds.map((id,i)=>({id,capital:(base+(i<rest?1:0))/100}));}
 function settlement({revenue,share}){
  const gross=cents(revenue);if(!Number.isFinite(share)||share<0||share>1)throw Error('Invalid contractual share.');
  const pool=Math.floor(gross*58/100),company=gross-pool,payout=Math.floor(pool*share);
  return {revenue:gross/100,participantPool:pool/100,companyRevenue:company/100,payout:payout/100};
 }
 function portfolio(rows){
  if(!Array.isArray(rows)||rows.length<policy.minimumStations||new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('At least three different chargers are required.');
  const detail=rows.map(row=>({id:row.id,...settlement(row)}));return {stations:detail,payout:detail.reduce((n,r)=>n+Math.round(r.payout*100),0)/100};
 }
 // Illustrative hardware/installation assumptions, not actual object financials.
 const assumptions=Object.freeze({chargerCount:3,referenceHardware:36181,hardwareDiscount:.19,installationPerCharger:40000,pricePerKwh:.45,powerCost:.12,efficiency:.95,processingShare:.03,fixedMonthlyPerCharger:750,replacementMonths:120,kwhPerSession:30,days:30,source:'https://www.mbusassep.com/equipment/product/18149'});
 function scenarios(capital=250,count=3){
  const ids=Array.from({length:count},(_,i)=>i+1),allocations=allocate(capital,ids),a=assumptions,hardware=Math.round(a.referenceHardware*(1-a.hardwareDiscount)*100)/100,budget=hardware+a.installationPerCharger;
  if(capital>budget*count)throw Error('Amount exceeds the illustrative funding budget.');
  return {capital,count,budget:Math.round(budget*count*100)/100,assumptions:a,rows:[5,10,20].map((sessions,i)=>{const revenue=sessions*a.kwhPerSession*a.days*a.pricePerKwh;return {id:['conservative','base','strong'][i],sessionsPerDay:sessions,revenue:Math.round(revenue*count*100)/100,...portfolio(allocations.map(r=>({id:r.id,revenue:Math.round(revenue*100)/100,share:r.capital/budget})))}})};
 }
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function html(lang='en',{compact=false}={}){const ru=lang==='ru';return `<section class="charge-policy" data-charge-policy="${policy.version}" translate="no"><p class="charge-policy-label">EcoGrid Charge · ${ru?'МОДЕЛЬ УЧАСТИЯ':'PARTICIPATION MODEL'}</p><h2>${ru?'Минимум 3 зарядки. Доля фактической выручки.':'At least 3 chargers. A share of actual revenue.'}</h2><div class="charge-policy-split"><div><strong>58%</strong><span>${ru?'участникам по долям':'to participants by share'}</span></div><div><strong>42%</strong><span>${ru?'компании на все расходы':'to the company for all costs'}</span></div></div><p>${escape(copy('formula',lang))}</p><p>${escape(copy('allocation',lang))}</p>${compact?'':`<details><summary>${ru?'Ответы перед решением':'Answers before you decide'}</summary>${faq(lang).map(r=>`<h3>${escape(r.question)}</h3><p>${escape(r.answer)}</p>`).join('')}<p>${escape(copy('proof',lang))}</p></details>`}</section>`;}
 return Object.freeze({policy,weeklyReference,weeklyOffer,copy,faq,selection,allocate,settlement,portfolio,scenarios,assumptions,html});
});
