'use strict';
// One checkout surface. Preview destinations never accept real transfers.
const paymentNetworks=[{id:'usdt-trc20',asset:'USDT',network:'TRC20',name:'Tron'},{id:'usdt-erc20',asset:'USDT',network:'ERC20',name:'Ethereum'},{id:'usdc-base',asset:'USDC',network:'Base',name:'Base'},{id:'btc',asset:'BTC',network:'Bitcoin',name:'Bitcoin'}];
let paymentDraft=null,paymentSending=false,paymentReceiptId=null;
const paymentBeforeMethods=paymentModal;
const paymentCardIcon='<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><rect x="2" y="5" width="20" height="14" rx="3"/><path d="M2 10h20M6 15h4"/></svg>';
const paymentText=(en,ru)=>window.EcoLocale?.language==='ru'?ru:en;
const paymentMoney=n=>new Intl.NumberFormat(window.EcoLocale?.locale||'en-US',{style:'currency',currency:'USD'}).format(n);
const paymentNetwork=()=>paymentNetworks.find(n=>n.id===paymentDraft?.network)||paymentNetworks[0];
const paymentLabel=r=>r.payment?.method==='manual'?paymentText('Recorded by team','Записано сотрудником'):r.payment?.method==='card'?paymentText('Card','Карта'):r.payment?.method==='crypto'?`${r.payment.asset} · ${r.payment.network}`:paymentText('Funding request','Заявка на пополнение');
const paymentValid=n=>EcoFinance.valid(n)&&n>=EcoFinance.paymentMinimum&&n<=EcoFinance.paymentMaximum;
const paymentPlanKey=()=>JSON.stringify(demo.planDraft&&[demo.planDraft.tierId,demo.planDraft.capital,demo.planDraft.stationIds]);
function newPaymentDraft(amount,method='card',network='usdt-trc20'){return {id:'PAY-'+crypto.randomUUID(),amount,amountText:new Intl.NumberFormat(window.EcoLocale?.locale||'en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(amount),method,network,step:method,planKey:paymentPlanKey()};}
function paymentModalHeader(title){return `<div class="payment-header"><h2>${title}</h2><span class="payment-preview-label">${paymentText('Transfers not connected','Переводы не подключены')}</span></div>`;}
paymentModal=function(type){if(type!=='topup')return paymentBeforeMethods(type);const pending=EcoFunding.state(demo).pending[0];if(pending)return showPaymentReceipt(pending.id);if(!paymentDraft||paymentDraft.planKey!==paymentPlanKey()||demo.requests.some(r=>r.id===paymentDraft.id))paymentDraft=newPaymentDraft(draftFundingGap()||250);showPaymentMethods();};
// Explicit overview entry resets an old edited checkout to today's outstanding amount.
actions['fund-overview']=()=>{if(paymentSending)return;const pending=EcoFunding.state(demo).pending[0];if(pending)return showPaymentReceipt(pending.id);const intent=EcoFunding.intent(demo);if(!intent.visible){actions['journey-my-plan']();return;}openFundingAmount(intent.amount);};
function openFundingAmount(amount){if(paymentSending)return;const pending=EcoFunding.state(demo).pending[0];if(pending)return showPaymentReceipt(pending.id);if(!paymentValid(amount))return;paymentDraft=newPaymentDraft(amount);paymentModal('topup');}
function paymentAmountChips(){if(paymentDraft.starterId)return '';const intent=EcoFunding.intent(demo),anchor=demo.planDraft?intent.amount:paymentDraft.amount;return '<div class="payment-amount-chips" role="group" aria-label="'+paymentText('Quick amounts','Быстрый выбор суммы')+'">'+EcoFunding.amountChips(anchor).map(n=>'<button type="button" data-payment-amount="'+n+'" aria-pressed="'+(EcoFinance.parseAmount(paymentDraft.amountText)===n)+'">'+paymentMoney(n)+'</button>').join('')+'</div>';}
function refreshPaymentChips(){for(const b of document.querySelectorAll?.('[data-payment-amount]')||[])b.setAttribute('aria-pressed',String(Number(b.dataset.paymentAmount)===EcoFinance.parseAmount(paymentDraft.amountText)));}
function paymentCaptureAmount(report=false){if(!paymentDraft)return false;const field=$('#payment-amount');if(field)paymentDraft.amountText=field.value;const amount=EcoFinance.parseAmount(paymentDraft.amountText??String(paymentDraft.amount)),offer=EcoFunding.offer(paymentDraft.starterId);const valid=paymentValid(amount)&&(!paymentDraft.starterId||(offer&&amount===offer.total));if(valid)paymentDraft.amount=amount;if(report){const error=$('#funding-error');if(error)error.textContent=valid?'':paymentText('Enter $1–$100,000, with at most two decimal places.','Введите от 1 до 100 000 USD, не более двух знаков после запятой.');if(field)field.setAttribute('aria-invalid',String(!valid));}return valid;}
function paymentPlanContext(){const p=demo.planDraft;return `<details class="payment-terms"><summary>${paymentText('Plan & terms','План и условия')}</summary>${p?`<p>${escapeHtml(window.EcoLocale?.t(p.name)||p.name)} · ${paymentMoney(p.capital)} · ${paymentText('Stations','Станции')}: ${p.stationIds.length}</p>`:''}<p>${paymentText('Funding adds to your balance. Plan activation is a separate step.','Пополнение поступает на баланс. План активируется отдельно.')}</p><a href="terms/" target="_blank" rel="noopener">${paymentText('Fees, access & risks','Комиссии, доступ и риски')} ↗</a></details>`;}
function showPaymentMethods(){if(!paymentDraft||paymentSending)return;paymentReceiptId=null;paymentDraft.step=paymentDraft.method;paymentDraft.amountText??=String(paymentDraft.amount);const isCrypto=paymentDraft.method==='crypto';openModal(`<section class="payment-checkout" translate="no">${paymentModalHeader(paymentText('Add funds','Пополнение'))}<p class="payment-preview-note">${EcoFunding.previewNotice(window.EcoLocale?.language)}</p><form id="funding-method-form" novalidate><fieldset class="payment-controls"><legend class="sr-only">${paymentText('Payment details','Данные пополнения')}</legend><label class="payment-amount-label" for="payment-amount">${paymentText('Amount','Сумма')} <span>USD</span></label><input ${paymentDraft.starterId?'readonly':''} id="payment-amount" type="text" inputmode="decimal" maxlength="20" aria-describedby="funding-error" autocomplete="off" value="${escapeHtml(paymentDraft.amountText)}" required>${paymentAmountChips()}<div class="payment-switch" role="group" aria-label="${paymentText('Payment method','Способ оплаты')}"><button type="button" data-payment-method="card" aria-pressed="${!isCrypto}">${paymentText('Card','Карта')}</button><button type="button" data-payment-method="crypto" aria-pressed="${isCrypto}">${paymentText('Crypto','Криптовалюта')}</button></div>${isCrypto?paymentCryptoBody():paymentCardBody()}<div id="funding-error" class="form-error" role="alert"></div>${paymentPlanContext()}<div class="payment-submit"><button class="button primary" type="submit">${isCrypto?paymentText("I've sent it",'Я отправил'):paymentText('Report payment','Сообщить об оплате')} ${icon('arrow')}</button></div><div class="payment-links"><button type="button" class="text-button" data-action="payment-return-plan">${paymentText('Back to plan','Вернуться к плану')}</button><span>${paymentText('Balance updates after approval','Баланс обновится после подтверждения')}</span></div></fieldset></form></section>`);if(isCrypto)renderPaymentQr();}
function paymentCardBody(){return `<div class="payment-card-simple">${paymentCardIcon}<div><strong>${paymentText('Debit or credit card','Банковская карта')}</strong><p>${paymentText('Card checkout is not connected. No charge will be made.','Карточная оплата не подключена. Списания не будет.')}</p></div></div>`;}
function paymentCryptoBody(){const n=paymentNetwork();return `<label class="payment-network-label" for="checkout-network">${paymentText('Currency & network','Валюта и сеть')}</label><select id="checkout-network">${paymentNetworks.map(v=>`<option value="${v.id}" ${v.id===n.id?'selected':''}>${v.asset} · ${v.network} (${v.name})</option>`).join('')}</select><div class="payment-crypto"><div class="payment-wallet"><label for="payment-address">${paymentText('Address placeholder','Адрес не подключён')}</label><textarea id="payment-address" rows="2" readonly spellcheck="false" translate="no">${paymentPreviewAddress()}</textarea><button type="button" class="button secondary" data-action="copy-payment-address">${paymentText('Copy address','Копировать адрес')} ${icon('file')}</button><small>${paymentText('No live wallet. Do not send funds.','Кошелёк не подключён. Не отправляйте средства.')}</small><span id="payment-copy-status" role="status"></span></div><div class="payment-qr-wrap"><div id="payment-qr" aria-busy="true"><span>${paymentText('Preparing QR…','Готовим QR…')}</span></div><small>${paymentText('Preview QR · not for transfers','QR-пример · не для перевода')}</small></div></div>`;}
function paymentPricing(draft){const o=EcoFunding.offer(draft.starterId);if(!o)return '';return `<dl class="payment-pricing"><div><dt>Plan capital</dt><dd>${money(o.capital)}</dd></div><div><dt>Total due</dt><dd>${money(o.total)}</dd></div></dl><p class="payment-pricing-note">The full payment amount is credited to your balance after approval.</p>`;}
function appendPaymentBreakdowns(){if($('#payment-breakdowns'))return;const rows=demo.requests.filter(r=>r.payment?.starterId&&r.payment?.companyFeeUSD>0).slice().reverse();if(rows.length)$('#modal-content').insertAdjacentHTML('beforeend',`<section id="payment-breakdowns" class="payment-history"><h3>Starting payments & fees</h3>${rows.map(r=>{const p=EcoFunding.pricing(r);return `<article class="payment-pricing-history"><strong translate="no">${escapeHtml(r.id)}</strong><span>${escapeHtml(r.status)}</span><dl class="payment-pricing"><div><dt>Total payment</dt><dd>${money(p.total)}</dd></div><div><dt>Plan capital</dt><dd>${money(p.net)}</dd></div><div><dt>Company fee</dt><dd>${money(p.fee)}</dd></div></dl></article>`}).join('')}</section>`);}
function showCardCheckout(){if(paymentDraft&&!paymentSending){paymentDraft.method='card';showPaymentMethods();}}
function showCryptoCheckout(){if(paymentDraft&&!paymentSending){paymentDraft.method='crypto';showPaymentMethods();}}
function paymentPreviewAddress(){return 'PREVIEW-NO-LIVE-WALLET-'+paymentNetwork().id.toUpperCase();}
function paymentQrPayload(){return JSON.stringify({type:'ecocharge-payment-preview',id:paymentDraft.id,amountUSD:paymentDraft.amount,asset:paymentNetwork().asset,network:paymentNetwork().network,transferEnabled:false});}
async function renderPaymentQr(){const target=$('#payment-qr');if(!target||!paymentDraft)return;target.removeAttribute('data-payload');if(!paymentCaptureAmount()){target.innerHTML=`<span>${paymentText('Enter a valid amount','Укажите корректную сумму')}</span>`;target.setAttribute('aria-busy','false');return;}target.innerHTML=`<span>${paymentText('Preparing QR…','Готовим QR…')}</span>`;target.setAttribute('aria-busy','true');const expected=paymentQrPayload();try{await window.ecoLoadLibrary('qr');if(!target.isConnected||!paymentDraft||paymentDraft.method!=='crypto'||!paymentCaptureAmount()||expected!==paymentQrPayload())return;const qr=qrcode(0,'M');qr.addData(expected,'Byte');qr.make();target.innerHTML=qr.createSvgTag({cellSize:4,margin:16,scalable:true});target.dataset.payload=expected;const svg=target.querySelector('svg');svg.setAttribute('role','img');svg.setAttribute('aria-label',paymentText('Preview QR code, not for transfers','QR-пример, не для переводов'));}catch{if(target.isConnected)target.innerHTML=`<button type="button" class="text-button" data-action="payment-qr-retry">${paymentText('Retry QR','Загрузить QR повторно')}</button>`;}finally{if(target.isConnected)target.setAttribute('aria-busy','false');}}
function paymentDate(value){if(!value||!Number.isFinite(Date.parse(value)))return paymentText('Not recorded','Не записано');const options={year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short',timeZone:demo.ecosystem?.timezone||'UTC'};try{return new Intl.DateTimeFormat(window.EcoLocale?.locale||'en-US',options).format(new Date(value));}catch{return new Intl.DateTimeFormat('en-US',{...options,timeZone:'UTC'}).format(new Date(value));}}
function paymentStatus(r){return ({Pending:paymentText('Awaiting review','На проверке'),Approved:r.type==='withdraw'?paymentText('Model withdrawal approved','Модельный вывод подтверждён'):paymentText('Funding approved','Пополнение подтверждено'),Rejected:paymentText('Request declined','Заявка отклонена')})[r.status]||paymentText('Status unavailable','Статус недоступен');}
function paymentReceiptBody(id){
 const r=demo.requests.find(r=>r.id===id);if(!r)return `<h2>${paymentText('Operation unavailable','Операция недоступна')}</h2><p>${paymentText('This request is not in the current account. Open request history or refresh the status.','Этой заявки нет в текущем аккаунте. Откройте историю или обновите статус.')}</p>`;
 const pending=r.status==='Pending',approved=r.status==='Approved',rejected=r.status==='Rejected',withdraw=r.type==='withdraw';
 const copy=withdraw?(pending?paymentText('This amount is reserved until review. No transfer has been made.','Сумма в резерве до решения. Перевод не выполнен.'):approved?paymentText('Deducted from the model balance. This does not confirm a real transfer.','Списано с модельный баланса. Это не подтверждение реального перевода.'):rejected?paymentText('The reservation has been released. No funds were deducted.','Резерв снят. Средства не списаны.'):paymentText('Refresh to check the result.','Обновите статус, чтобы проверить результат.')):(pending?paymentText('Thank you! Please wait for your balance to be credited. Your manager and administrator have the request for review. Funds will be added after receipt is confirmed.','Спасибо! Ожидайте пополнения баланса. Заявка передана вашему менеджеру и администратору. Средства зачислят после проверки поступления.'):approved?paymentText('Added to your model balance. Plan activation is a separate step.','Средства зачислены на модельный баланс. План активируется отдельно.'):rejected?paymentText('No funds were added. Check the reason before trying again.','Средства не добавлены. Перед повтором проверьте причину.'):paymentText('Refresh to check the result.','Обновите статус, чтобы проверить результат.'));
 const funds=EcoFinance.summary(demo),ready=!!funds.draft&&funds.gap===0&&!funds.pending.length;
 const detail=(label,value)=>`<div><dt>${label}</dt><dd>${escapeHtml(value)}</dd></div>`,reason=r.reviewReason||r.reason;
 return `${paymentModalHeader(withdraw?paymentText('Withdrawal status','Статус вывода'):paymentText('Funding status','Статус пополнения'))}<span class="payment-result-status" data-status="${escapeHtml(r.status)}" role="status">${paymentStatus(r)}</span><strong class="payment-result-amount">${paymentMoney(r.amount)}</strong><p class="payment-result-copy">${copy}</p><dl class="payment-result-details">${detail(paymentText('Method','Способ'),r.payment?paymentLabel(r):paymentText('Not specified','Не указан'))}${detail(paymentText('Created','Создана'),paymentDate(r.date))}${r.reviewedAt?detail(paymentText('Reviewed','Решение'),paymentDate(r.reviewedAt)):''}${detail(paymentText('Request ID','Номер заявки'),r.id)}</dl>${reason?`<div class="payment-review-note"><strong>${paymentText('Review note','Комментарий к решению')}</strong><p>${escapeHtml(reason)}</p></div>`:''}${pending?`<p>${paymentText('You can close this window. The request will stay in your history.','Можно закрыть окно. Заявка останется в истории.')}</p>`:rejected&&withdraw?`<button class="button primary" data-action="withdraw">${paymentText('New withdrawal request','Новая заявка на вывод')}</button>`:rejected&&!withdraw?`<button class="button primary" data-payment-retry="${escapeHtml(r.id)}">${paymentText('Try again','Повторить')}</button>`:approved&&!withdraw?`<button class="button primary" data-action="${ready?'activate-draft':funds.active||funds.draft?'journey-my-plan':'journey-resume'}">${ready?paymentText('Activate selected plan','Активировать выбранный план'):funds.active?paymentText('Open my plan','Открыть мой план'):funds.draft?paymentText('Review my selection','Проверить подборку'):paymentText('Choose a plan','Выбрать план')}</button>`:''}`;
}
function paymentHistoryBody(){const rows=demo.requests.slice().reverse();return `${paymentModalHeader(paymentText('Request history','История заявок'))}<div class="payment-operation-list">${rows.length?rows.map(r=>`<button type="button" data-payment-view="${escapeHtml(r.id)}"><span><strong>${r.type==='withdraw'?paymentText('Withdrawal','Вывод'):paymentText('Funding','Пополнение')}</strong><small>${escapeHtml(paymentDate(r.date))}</small><small>${escapeHtml(r.id)}</small></span><span><strong>${paymentMoney(r.amount)}</strong><small>${paymentStatus(r)}</small></span></button>`).join(''):`<p>${paymentText('No requests yet.','Заявок пока нет.')}</p>`}</div>`;}
// Only these read-only surfaces allow background account updates through an open dialog.
function paymentOperationOpen(){return !!($('#modal')?.open&&$('[data-operation-dialog]'));}
function paymentOperationRefresh(){const root=$('[data-operation-dialog]');if(!paymentOperationOpen())return;const body=root.querySelector('.payment-operation-body'),markup=root.dataset.operationDialog==='history'?paymentHistoryBody():paymentReceiptBody(root.dataset.operationId);if(body&&body._operationMarkup!==markup){body.innerHTML=markup;body.querySelector('h2')?.setAttribute('id','dialog-title');$('#modal').setAttribute?.('aria-labelledby','dialog-title');body._operationMarkup=markup;}}
function paymentOperationConnection(ok){const node=$('[data-operation-sync]');if(node)node.textContent=ok?paymentText('Status updates automatically','Статус обновляется автоматически'):paymentText('Could not refresh. Showing the last saved status.','Не удалось обновить. Показан последний сохранённый статус.');}
function showPaymentOperation(kind,id=''){paymentReceiptId=kind==='receipt'?id:null;openModal(`<section class="payment-checkout payment-result" data-operation-dialog="${kind}" data-operation-id="${escapeHtml(id)}" translate="no"><div class="payment-operation-body"></div><div class="payment-operation-tools"><button type="button" class="text-button" data-action="payment-refresh-status">${paymentText('Refresh status','Обновить статус')}</button>${kind==='receipt'?`<button type="button" class="text-button" data-action="cab-request-history">${paymentText('Request history','История заявок')}</button>`:''}</div><small data-operation-sync role="status"></small><button class="text-button" data-action="back-overview">${paymentText('Back to overview','Вернуться к обзору')}</button></section>`);paymentOperationRefresh();paymentOperationConnection(true);}
function showPaymentReceipt(id){if(paymentSending&&paymentDraft?.id===id){toast(paymentText('Saving request…','Сохраняем заявку…'));return;}showPaymentOperation('receipt',id);}
window.EcoOperationDialog={isOpen:paymentOperationOpen,refresh:paymentOperationRefresh,connection:paymentOperationConnection};
actions['cab-request-history']=()=>showPaymentOperation('history');
actions['payment-pending-status']=()=>{const r=demo.requests.find(r=>r.type==='topup'&&r.status==='Pending');if(r)showPaymentReceipt(r.id);else actions['cab-request-history']();};
actions['payment-refresh-status']=async()=>{const button=$('[data-action="payment-refresh-status"]');if(button)button.disabled=true;try{if(window.EcoClientAccount)await window.EcoClientAccount.refresh();else paymentOperationRefresh();}finally{if(button?.isConnected)button.disabled=false;}};
async function submitPaymentRequest(method){if(paymentSending||!paymentDraft||paymentDraft.method!==method||!['card','crypto'].includes(method)||!paymentCaptureAmount(true))return;
 const previous=demo.requests.find(r=>r.id===paymentDraft.id)||EcoFunding.state(demo).pending[0];if(previous)return showPaymentReceipt(previous.id);
 const draft={...paymentDraft},n=paymentNetwork(),offer=EcoFunding.offer(draft.starterId);if(draft.starterId&&(!offer||draft.amount!==offer.total||EcoFunding.state(demo).hasFirstDeposit))return;
 const payment=method==='card'?{mode:'preview',method:'card',currency:'USD'}:{mode:'preview',method:'crypto',asset:n.asset,network:n.network,networkId:n.id};if(offer)Object.assign(payment,{starterId:offer.id,companyFeeUSD:offer.fee,totalUSD:offer.total,creditedUSD:offer.capital});
 paymentSending=true;const controls=$('.payment-controls'),surface=$('.payment-checkout');if(controls)controls.disabled=true;
 demo.requests.push({id:draft.id,type:'topup',amount:offer?offer.capital:Math.round(draft.amount*100)/100,status:'Pending',date:new Date().toISOString(),payment});
 try{const saved=await persist();if(window.ECO_SHARED_CONTEXT&&!saved){return;}paymentSending=false;paymentDraft=null;if(surface?.isConnected&&$('#modal').open)showPaymentReceipt(draft.id);else toast(paymentText('Funding request saved.','Заявка на пополнение сохранена.'));}
 catch{demo.requests=demo.requests.filter(r=>r.id!==draft.id);if($('#funding-error'))$('#funding-error').textContent=paymentText('Request not saved. Try again.','Заявка не сохранена. Повторите попытку.');}
 finally{paymentSending=false;if(controls?.isConnected)controls.disabled=false;}
}
actions['payment-back']=()=>{paymentCaptureAmount();showPaymentMethods();};
actions['payment-return-plan']=()=>{if(paymentSending)return;paymentCaptureAmount();actions['journey-my-plan']();};
actions['submit-card-payment']=()=>submitPaymentRequest('card');
actions['submit-crypto-payment']=()=>submitPaymentRequest('crypto');
actions['payment-qr-retry']=renderPaymentQr;
actions['copy-payment-address']=async()=>{const input=$('#payment-address'),status=$('#payment-copy-status');if(!input)return;try{await navigator.clipboard.writeText(input.value);if(status?.isConnected)status.textContent=paymentText('Address placeholder copied','Адрес не подключён скопирован');}catch{input.focus();input.select();if(status?.isConnected)status.textContent=paymentText('Select and copy the address.','Выделите и скопируйте адрес.');}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||paymentSending)return;if(b.dataset.paymentAmount&&paymentDraft&&!paymentDraft.starterId){const amount=Number(b.dataset.paymentAmount);if(!paymentValid(amount))return;paymentDraft.amount=amount;paymentDraft.amountText=new Intl.NumberFormat(window.EcoLocale?.locale||'en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(amount);showPaymentMethods();document.querySelector?.('[data-payment-amount="'+amount+'"]')?.focus();return;}if(b.dataset.paymentView){showPaymentReceipt(b.dataset.paymentView);return;}if(['crypto','card'].includes(b.dataset.paymentMethod)&&paymentDraft){paymentCaptureAmount();paymentDraft.method=b.dataset.paymentMethod;showPaymentMethods();$(`[data-payment-method="${paymentDraft.method}"]`)?.focus();}if(b.dataset.paymentRetry){const r=demo.requests.find(r=>r.id===b.dataset.paymentRetry&&r.type==='topup'&&r.status==='Rejected');if(r){paymentDraft=newPaymentDraft(r.amount,r.payment?.method==='crypto'?'crypto':'card',r.payment?.networkId||'usdt-trc20');showPaymentMethods();}}});
document.addEventListener('change',e=>{if(paymentSending||!paymentDraft)return;if(e.target.id==='checkout-network'&&paymentNetworks.some(n=>n.id===e.target.value)){paymentCaptureAmount();paymentDraft.network=e.target.value;showPaymentMethods();$('#checkout-network')?.focus();}});
document.addEventListener('input',e=>{if(e.target.id==='payment-amount'&&paymentDraft&&!paymentSending){paymentCaptureAmount(true);refreshPaymentChips();if(paymentDraft.method==='crypto')renderPaymentQr();}});
document.addEventListener('submit',e=>{if(e.target.id!=='funding-method-form')return;e.preventDefault();if(paymentDraft)submitPaymentRequest(paymentDraft.method);});
document.addEventListener('ecocharge:locale',()=>{if(paymentOperationOpen()){showPaymentOperation($('[data-operation-dialog]').dataset.operationDialog,paymentReceiptId||'');return;}if($('.payment-checkout')&&$('#modal').open){if(paymentReceiptId)showPaymentReceipt(paymentReceiptId);else{paymentCaptureAmount();showPaymentMethods();}}});

const historyBeforePayments=actions.history;
actions.history=()=>{historyBeforePayments();const rows=demo.requests.filter(r=>r.payment).slice().reverse().slice(0,8);if(rows.length)$('#modal-content').insertAdjacentHTML('beforeend',`<section class="payment-history"><h3>Payment methods & status</h3>${rows.map(r=>`<div><span><strong>${escapeHtml(paymentLabel(r))}</strong><small translate="no">${escapeHtml(r.id)}</small></span><span><strong>${money(r.amount)}</strong><small>${escapeHtml(r.status)}</small><button type="button" class="text-button" data-payment-view="${escapeHtml(r.id)}">${paymentText('Details','Подробнее')}</button></span></div>`).join('')}</section>`);};
const reviewBeforePayments=reviewRequest;
reviewRequest=function(id,decision){reviewBeforePayments(id,decision);const r=demo.requests.find(r=>r.id===id);if(r?.payment&&$('#review-form'))$('#review-form').insertAdjacentHTML('beforebegin',`<div class="payment-review"><span>Payment method</span><strong>${escapeHtml(paymentLabel(r))}</strong>${r.payment.starterId?paymentPricing({starterId:r.payment.starterId}):''}<p>Preview request. Approval changes the sample balance; it does not verify a card charge or a blockchain transfer.</p></div>`);};
const acquisitionRoutes=[['website','Website → account'],['lead-form','Lead form → caller → account']];
const acquisitionStages=[['new','New lead'],['contacted','Contacted by caller'],['qualified','Qualified'],['payment','Payment discussed']];
function acquisitionDetails(){const a=demo.acquisition||{},funded=demo.requests.some(r=>r.type==='topup'&&r.status==='Approved'),pending=demo.requests.some(r=>r.type==='topup'&&r.status==='Pending');return {route:acquisitionRoutes.find(r=>r[0]===(a.route||demo.attribution?.lead_route))?.[1]||'Not recorded',stage:funded?'First deposit recorded':pending?'Payment awaiting review':acquisitionStages.find(s=>s[0]===a.stage)?.[1]||'New lead'};}
const profileBeforePayments=cabProfile;
cabProfile=function(){const a=acquisitionDetails();return profileBeforePayments()+`<section class="cab-card-section"><div class="cab-section-heading"><h2>Acquisition & payment</h2><button class="button secondary" data-action="edit-acquisition">Edit lead details</button></div><dl class="cab-detail-list"><div><dt>Entry path</dt><dd>${a.route}</dd></div><div><dt>Lead stage</dt><dd>${a.stage}</dd></div><div><dt>Phone</dt><dd translate="no">${escapeHtml(demo.acquisition?.phone||'—')}</dd></div></dl><p class="cab-caption">Lead details are managed in this workspace. Meta lead forms and a shared CRM are not connected.</p></section>`;};
actions['edit-acquisition']=()=>{if(role!=='admin')return;const a=demo.acquisition||{};openModal(`<h2>Lead details</h2><form id="acquisition-form"><label for="acquisition-route">Entry path</label><select id="acquisition-route">${acquisitionRoutes.map(([id,label])=>`<option value="${id}" ${(a.route||demo.attribution?.lead_route)===id?'selected':''}>${label}</option>`).join('')}</select><label for="acquisition-stage">Lead stage</label><select id="acquisition-stage">${acquisitionStages.map(([id,label])=>`<option value="${id}" ${a.stage===id?'selected':''}>${label}</option>`).join('')}</select><label for="acquisition-phone">Phone</label><input id="acquisition-phone" type="tel" maxlength="40" autocomplete="off" value="${escapeHtml(a.phone||'')}" placeholder="+1 555 010 0000"><p class="form-hint">Payment status updates from funding requests. These fields do not send a message or place a call.</p><button class="button primary" type="submit">Save lead details</button></form>`);};
document.addEventListener('submit',e=>{if(e.target.id!=='acquisition-form')return;e.preventDefault();if(role!=='admin')return;const route=$('#acquisition-route').value,stage=$('#acquisition-stage').value;if(!acquisitionRoutes.some(r=>r[0]===route)||!acquisitionStages.some(s=>s[0]===stage))return;demo.acquisition={route,stage,phone:$('#acquisition-phone').value.trim(),updatedAt:new Date().toISOString()};activity('Manager updated lead details');persist();$('#modal').close();renderAdmin();toast('Lead details saved.');});

// Preserve an explicit lead-form route or first-touch campaign for direct account visits.
try{const params=new URL(location.href).searchParams,context=JSON.parse(sessionStorage.getItem('ecocharge-attribution')||'{}');for(const key of ['utm_source','utm_medium','utm_campaign','utm_content','utm_term','gclid','fbclid'])if(params.has(key)&&!context[key])context[key]=params.get(key).slice(0,300);if(['website','lead-form'].includes(params.get('lead_route')))context.lead_route=params.get('lead_route');if(Object.keys(context).length&&!demo.attribution){demo.attribution=context;persist();}}catch{}
