'use strict';
// Local presentation state. This module has no network or authentication capability.
window.createEcoSandbox=function(seed,domain,stations){
 const clone=v=>structuredClone(v),F=domain.finance,P=domain.policy,O=domain.operations,J=domain.journey;
 const ids=new Set(stations.map(s=>s.id));ids.closed=new Set(stations.filter(s=>s.selectionClosed).map(s=>s.id));
 const now=()=>new Date().toISOString(),id=p=>p+'-'+crypto.randomUUID(),fail=(m,status=400)=>{const e=Error(m);e.status=status;throw e;};
 const record=()=>({status:'new',comment:'',nextContact:null,version:1,history:[],funnel:{},consents:[],callData:{}});
 const version=(r,b)=>{if(b.version!==undefined&&Number(b.version)!==r.version)fail('Данные изменились. Обновите карточку и повторите действие.',409);};
 function snapshot(db,uid){const a=db.accounts[uid];if(!a)fail('Клиент удалён. Выберите другого клиента.',404);a.finance=F.summary(a.state);a.nextWeek=O.nextWeek(a.state);const w=a.nextWeek;a.liveAccrual={active:!!w,curve:'demand-v1',capital:w?.capital||0,weeklyRatePercent:w?.rate||0,monthlyRatePercent:w?.ratePeriod==='calendar-month'?w.rate:undefined,ratePeriod:w?.ratePeriod||'week',periodStartedAt:w?.periodStart||null,serverNow:now(),confirmedCredits:a.finance.recorded};a.state.client={...a.state.client,name:a.client.name,email:a.client.email};a.state.acquisition={...a.state.acquisition,phone:a.client.phone};const origin=Object.values(db.leads).find(l=>l.client_id===uid);if(origin?.context?.journey){a.state.journey=clone(origin.context.journey);a.state.subscription=clone(origin.context.subscription||null);}a.state.manager={...a.state.manager,name:db.overview.managers.find(m=>m.id===a.client.owner)?.name||'EcoGrid'};return a;}
 function history(r,action,details,actor){r.history??=[];r.history.unshift({id:id('AUD'),action,details:clone(details),actor:actor.name,created:now()});r.version++;}
 function membership(r,b,actor,registered){
  if(!['admin','ftd'].includes(actor.role))fail('Team access required.',403);
  if(r.version!==b.version)fail('Данные изменились. Обновите карточку и повторите действие.',409);
  if(typeof b.member!=='boolean')fail('Choose the Club membership status.');
  if(b.member&&!registered)fail('Create the client account before confirming Club membership.');
  const previous=r.clubMember===true;
  if(previous!==b.member){r.clubMember=b.member;history(r,'club_membership_updated',{from:previous,to:b.member},actor);}
  return r;
 }
 function overview(db,actor){return {...db.overview,me:actor,managers:db.overview.managers.map(m=>({...m,openLeads:Object.values(db.leads).filter(l=>l.owner===m.id&&!l.client_id).length})),leads:Object.values(db.leads).filter(l=>actor.role==='admin'||l.owner===actor.id).sort((a,b)=>b.created.localeCompare(a.created)).map(l=>({...l,funnel:l.crm.funnel||l.funnel||{}})),clients:Object.values(db.accounts).filter(a=>actor.role==='admin'||a.client.owner===actor.id).map(a=>({...a.client,created:a.created||db.generatedAt,balance:a.state.balance,version:a.version,journey:a.state.journey,crm:a.crm,funnel:a.crm.funnel||{},identityStatus:db.identities[a.client.id]?.status,firstWithdrawal:domain.funnel.firstWithdrawal(a.state)}))};}
 function contact(r,b,actor){version(r,b);if(!b.comment?.trim())fail('Добавьте результат контакта.');if(b.status==='callback'&&!b.nextContact)fail('Укажите время следующего контакта.');Object.assign(r,{status:b.status||r.status,comment:b.comment,nextContact:b.nextContact||null,callData:{...r.callData,...b.callData}});r.funnel??={};if(b.callOutcome&&b.callOutcome!=='note'){r.funnel.firstAttemptAt??=now();if(b.callOutcome==='connected'){r.funnel.connectedAt??=now();r.funnel.firstConnectedAt??=now();}}if(b.closeReason)r.funnel.closeReason=b.closeReason;history(r,'contact_saved',b,actor);return r;}
 function journeyCorrection(l,b,actor){if(!b.journey)return;let chosen;try{chosen=J.normalize(b.journey);}catch(e){fail(e.message);}if(!chosen)fail('Choose a client journey.');l.context??={};l.context.journey={...J.merge(l.context.journey,chosen,l.context.journey?.lastSource||l.attribution,now()),...chosen};if(b.marketingOptOut===true&&l.context.subscription)l.context.subscription={...l.context.subscription,granted:false,revokedAt:now()};}
 function createLead(db,b,actor){const name=b.name||[b.firstName,b.lastName].filter(Boolean).join(' ');if(name.trim().length<2)fail('Укажите имя клиента.');if(!b.email&&!b.phone)fail('Укажите телефон или почту.');const l={id:id('LEAD'),name:name.trim(),first_name:b.firstName||name.split(' ')[0],last_name:b.lastName||name.split(' ').slice(1).join(' '),email:b.email||'',phone:b.phone||'',owner:actor.role==='admin'?null:actor.id,affiliate:null,attribution:{landing_id:'main',utm_source:'manual'},context:{},status:'new',client_id:null,created:now(),consent_at:now(),crm:record(),conflicts:[],needsReview:false,duplicateOf:null};if(b.comment)contact(l.crm,b,actor);db.leads[l.id]=l;return l;}
 function createClient(db,b,actor){const l=db.leads[b.leadId];if(actor.role!=='admin'&&l?.owner!==actor.id)fail('Заявка другого менеджера.',403);if(!l?.owner)fail('Сначала назначьте менеджера заявке.');if(l.client_id)fail('У этой заявки уже есть кабинет.');if(b.crmVersion!==l.crm.version)fail('Заявка изменилась. Откройте её повторно.',409);if(!/^[a-z0-9][a-z0-9._-]{3,49}$/i.test(b.username||''))fail('Логин: от 4 до 50 латинских букв, цифр или ._-');if(Object.values(db.accounts).some(a=>a.client.username===b.username))fail('Этот логин уже используется.');if(!b.name||b.name.trim().length<2)fail('Укажите имя клиента.');const c={id:id('CL'),username:b.username,name:b.name,role:'client',email:b.email||'',phone:b.phone||'',owner:l.owner,invite:''},a={client:c,state:P.initial(c,db.overview.managers.find(m=>m.id===l.owner)),version:1,crm:clone(l.crm),created:now()};a.state.attribution=clone(l.attribution);a.state.journey=clone(l.context?.journey||null);a.state.subscription=clone(l.context?.subscription||null);l.client_id=c.id;l.status='registered';a.crm.leadId=l.id;a.crm.subject=l.id;a.crm.origin={original_owner:l.owner,basis:'account_created'};if(b.comment)contact(a.crm,{...b,version:a.crm.version},actor);l.crm=clone(a.crm);db.accounts[c.id]=a;db.identities[c.id]={version:1,status:'draft',fields:{},files:[],reviewNote:''};return snapshot(db,c.id);}
 function posts(db,uid,staff){return db.responses['staff/community'].posts.filter(p=>staff||p.status==='published').map(p=>{const choices=db.reactions[p.id]||{};return {...p,myReaction:choices[uid]||'',reactions:Object.fromEntries(['like','useful','interested'].map(r=>[r,(Number(seed.reactionBaselines?.[p.id]?.[r])||0)+Object.values(choices).filter(v=>v===r).length]))};});}
 function chat(db,uid,actor){const a=snapshot(db,uid),threads=a.state.tickets.map(t=>{const messages=(t.messages?.length?t.messages:[{from:'client',text:t.message,date:t.date}]).map((m,i)=>({...m,id:m.id||t.id+':'+(i+1),sequence:i+1})),cursor=db.chatReads?.[actor.id+':'+uid+':'+t.id]||0,awaitingReply=messages.at(-1)?.from==='client'&&t.status!=='Resolved';return {...t,clientId:uid,messages,unread:messages.filter(m=>m.sequence>cursor&&(actor.role==='client'?m.from!=='client':m.from==='client')).length,awaitingReply,awaitingSince:awaitingReply?messages.findLast(m=>m.from==='client')?.date:null};});return {client:a.client,manager:{id:a.client.owner,name:a.state.manager.name},threads};}
 function report(db,actor,query){const q=new URLSearchParams(query),v=overview(db,actor),rows=v.leads.filter(l=>(!q.get('from')||l.created.slice(0,10)>=q.get('from'))&&(!q.get('to')||l.created.slice(0,10)<=q.get('to'))&&(!q.get('landing')||l.attribution?.landing_id===q.get('landing'))&&(!q.get('caller')||l.owner===q.get('caller'))).map(l=>{const a=db.accounts[l.client_id],payments=a?.state.requests.filter(r=>r.type==='topup'&&r.status==='Approved'&&r.receiptChecked===true&&r.amount>0&&Number.isFinite(Date.parse(r.reviewedAt))).sort((a,b)=>a.reviewedAt.localeCompare(b.reviewedAt))||[];return {journey:l.context?.journey,source:l.attribution,created:l.created,qualified:l.crm.status==='qualified',account:!!a,connected:!!l.crm.funnel?.firstConnectedAt,paidAt:payments[0]?.reviewedAt||null,landing:l.attribution?.landing_id||'main',callerId:l.owner,firstAttemptMs:l.crm.funnel?.firstAttemptAt?Date.parse(l.crm.funnel.firstAttemptAt)-Date.parse(l.context?.journey?.consultationAt||l.created):null,closeReason:l.crm.funnel?.closeReason,ftdCents:Math.round((payments[0]?.amount||0)*100),stages:{leads:true,accounts:!!a,connected:!!l.crm.funnel?.connectedAt,qualified:l.crm.status==='qualified',plan_saved:!!a?.state.planDraft,ftd:!!payments.length,activated:a?.state.plan?.status==='active',repeat_deposit:payments.length>1,club_invited:!!l.crm.funnel?.clubInvitedAt}};});const total=domain.funnel.aggregate(rows.map(r=>({...r,landing:'all'})),'landing')[0]||{leads:0,ftd:0,ftdRate:0,averageFirstCallMinutes:null,reasons:{}};return {journeys:{byRoute:J.cohorts(rows),byTopic:J.cohorts(rows,'topic'),byPartner:J.cohorts(rows,'partner')},total,byLanding:domain.funnel.aggregate(rows,'landing'),byCaller:domain.funnel.aggregate(rows,'caller'),byLandingCaller:domain.funnel.aggregate(rows,'landing_caller'),callers:v.managers};}
 function route(db,path,method,b,ctx){
  const [url,query='']=path.split('?'),parts=url.split('/'),staff=parts[0]==='staff',actor=staff?(ctx.role==='ftd'?{...db.overview.managers[0],role:'ftd'}:db.overview.me):db.accounts[ctx.clientId]?.client;
  if(url==='public/leads'&&method==='POST'){
   if(b.website)fail('Проверьте поля заявки.');if(!b.consent)fail('Подтвердите согласие на обработку заявки.');
   if(b.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(b.email))fail('Проверьте адрес почты.');if(b.phone&&!/^\+?[\d\s().-]{7,24}$/.test(b.phone))fail('Проверьте номер телефона.');
   const duplicate=Object.values(db.leads).find(l=>(b.email&&l.email.toLowerCase()===b.email.trim().toLowerCase())||(b.phone&&l.phone.replace(/\D/g,'')===b.phone.replace(/\D/g,'')));
   let incoming;try{incoming=J.normalize(b.context?.journey);}catch(e){fail(e.message);}if(incoming?.route==='nurture'&&(!b.email||(!['club','academy'].includes(incoming.topic)&&(b.marketingConsent!==true||b.marketingConsentVersion!==J.version))))fail('Email and consent to project updates are required.');
   let calculation=null;if(incoming?.topic==='charge'&&b.context?.projectCalculation){try{calculation=domain.publicPlan.normalize(b.context.projectCalculation);}catch(e){fail(e.message);}}
   if(duplicate){if(calculation){duplicate.context??={};duplicate.context.projectCalculation=calculation;duplicate.context.tierId=calculation.tierId;}if(incoming){duplicate.context??={};duplicate.context.journey=J.merge(duplicate.context.journey,incoming,b.attribution,now());if(b.marketingConsent===true&&b.marketingConsentVersion===J.version)duplicate.context.subscription={granted:true,email:b.email,version:J.version,capturedAt:now(),language:b.consentLanguage||'en'};history(duplicate.crm,'journey_requested',{journey:duplicate.context.journey},{name:'EcoGrid website'});if(duplicate.client_id){db.accounts[duplicate.client_id].version++;snapshot(db,duplicate.client_id);}}return {accepted:true,id:duplicate.id,duplicate:true};}
   const l=createLead(db,b,{role:'admin',name:'Сайт EcoGrid'});l.attribution={landing_id:'main',lead_route:'website',...b.attribution};l.context=clone(b.context||{});delete l.context.projectCalculation;if(calculation){l.context.projectCalculation=calculation;l.context.tierId=calculation.tierId;}if(incoming)l.context.journey=J.merge(null,incoming,b.attribution,now());if(b.marketingConsent===true&&b.marketingConsentVersion===J.version)l.context.subscription={granted:true,email:b.email,version:J.version,capturedAt:now(),language:b.consentLanguage||'en'};l.consent_language=b.consentLanguage||'ru';l.consent_version=b.consentVersion||'website';l.crm.consents=[['sms',b.smsConsent],['email',b.emailConsent]].map(([channel,granted])=>({channel,granted:!!granted,created:now()}));
   history(l.crm,'website_request',{source:l.attribution,context:l.context},{name:'Сайт EcoGrid'});return {accepted:true,id:l.id,duplicate:false};
  }
  if(url==='logout')return {ok:true};
  if(!actor)fail('Выберите клиента.',404);
  const visible=uid=>{const a=snapshot(db,uid);if(staff&&actor.role!=='admin'&&a.client.owner!==actor.id)fail('Клиент закреплён за другим менеджером.',403);return a;};
  if(url==='staff/overview')return overview(db,actor);
  if(url==='staff/finance-options')return {tiers:F.tiers,stations};
  if(url==='staff/leads'&&method==='POST')return createLead(db,b,actor);
  if(url==='staff/clients'&&method==='POST')return createClient(db,b,actor);
  if(url==='staff/funnel')return report(db,actor,query);
  if(url==='staff/followups')return {items:[]};
  if(url==='staff/lead-deliveries')return {configured:false,source:'',events:[]};
  if(url==='staff/affiliates'){if(!/^[a-z0-9-]{3,50}$/.test(b.code))fail('Проверьте код баера.');if(db.overview.affiliates.some(a=>a.code===b.code))fail('Код уже существует.');db.overview.affiliates.push({code:b.code,label:b.label,owner:b.owner});return {ok:true};}
  if(url==='staff/assign'){
   if(actor.role!=='admin')fail('Назначение доступно администратору.',403);if(!db.overview.managers.some(m=>m.id===b.owner))fail('Выберите менеджера.');
   for(const item of b.items){const r=item.kind==='lead'?db.leads[item.id]:visible(item.id)?.client;if(!r)fail('Запись не найдена.',404);const crm=item.kind==='lead'?r.crm:db.accounts[item.id].crm;if(r.owner===b.owner)fail('Этот менеджер уже назначен.');if(item.kind==='client'){if(db.overview.handoffs.some(h=>h.client_id===item.id))fail('Передача уже ожидает принятия.');db.overview.handoffs.push({id:id('HANDOFF'),client_id:item.id,client_name:r.name,from_owner:r.owner,to_owner:b.owner,reason:b.reason,version:1});continue;}version(crm,{version:item.version});r.owner=b.owner;history(crm,'assigned',{owner:b.owner,reason:b.reason},actor);if(item.kind==='client')db.accounts[item.id].version++;}return {ok:true};
  }
  if(url==='staff/handoff'){const h=db.overview.handoffs.find(h=>h.id===b.id);if(!h)fail('Передача не найдена.');version(h,b);if(b.action==='accept'){if(actor.id!==h.to_owner)fail('Принять может только назначенный менеджер.',403);const account=snapshot(db,h.client_id);account.client.owner=h.to_owner;history(account.crm,'handoff_accepted',{from:h.from_owner,to:h.to_owner},actor);account.version++;}else if(actor.role!=='admin')fail('Отмена доступна администратору.',403);db.overview.handoffs=db.overview.handoffs.filter(h=>h.id!==b.id);return {ok:true};}
  if(url==='staff/funding-requests'||url==='staff/withdrawal-requests'){const type=url.includes('funding')?'topup':'withdraw';return {requests:overview(db,actor).clients.flatMap(c=>db.accounts[c.id].state.requests.filter(r=>r.type===type&&r.status==='Pending').map(r=>({...r,clientId:c.id,clientName:c.name,owner:c.owner,method:r.payment?.method||'model'})))};}
  if(url==='staff/chats')return {threads:overview(db,actor).clients.flatMap(c=>chat(db,c.id,actor).threads.map(t=>({...t,clientName:c.name,owner:c.owner,ownerName:db.accounts[c.id].state.manager.name,last:t.messages.at(-1)})))};
  if(url==='staff/community'||url==='client/community'){
   if(method==='GET')return {posts:posts(db,ctx.clientId,staff),canPublish:staff&&actor.role==='admin'};
   if(actor.role!=='admin')fail('Публикации изменяет администратор.',403);if(!b.titleRu?.trim()||!b.titleEn?.trim()||!b.bodyRu?.trim()||!b.bodyEn?.trim())fail('Заполните заголовок и текст на двух языках.');
   const list=db.responses['staff/community'].posts,old=list.find(p=>p.id===b.id),post={...b,id:old?.id||id('POST'),createdAt:old?.createdAt||now(),updatedAt:now(),version:(old?.version||0)+1,reactions:{like:0,useful:0,interested:0}};if(old)list.splice(list.indexOf(old),1,post);else list.unshift(post);return post;
  }
  if(url==='client/community/reaction'){const p=db.responses['staff/community'].posts.find(p=>p.id===b.postId&&p.status==='published');if(!p||!['','like','useful','interested'].includes(b.reaction))fail('Публикация или реакция недоступна.');db.reactions[p.id]??={};db.reactions[p.id][ctx.clientId]=b.reaction;return posts(db,ctx.clientId,false).find(v=>v.id===p.id);}
  if(url.startsWith('staff/knowledge')){
   if(url==='staff/knowledge-helper'){const words=String(b.query||'').toLowerCase().split(/\s+/).filter(w=>w.length>2),sources=Object.values(db.knowledge).filter(a=>a.status==='published').map(a=>({a,score:words.filter(w=>JSON.stringify(a).toLowerCase().includes(w)).length})).filter(v=>v.score).sort((a,b)=>b.score-a.score).slice(0,3).map(({a})=>({id:a.id,version:a.version,title:a.titleRu||a.titleEn||a.title,answer:b.language==='ru'?a.explanationRu:a.answerEn,sourceTitle:a.sourceTitle,sourceRef:a.sourceRef}));return {sources};}
   const key=parts[2],action=parts[3],a=db.knowledge[key];
   if(method==='GET'){if(key&&action==='versions')return {version:Number(parts[4]),content:a.versionsData?.[parts[4]]||a};if(key)return a||fail('Статья не найдена.',404);const q=new URLSearchParams(query);return {articles:Object.values(db.knowledge).filter(a=>(actor.role==='admin'||a.status==='published')&&(!q.get('q')||JSON.stringify(a).toLowerCase().includes(q.get('q').toLowerCase()))&&(!q.get('category')||a.category===q.get('category'))&&(!q.get('status')||a.status===q.get('status')))};}
   if(action==='suggest'){a.suggestions??=[];a.suggestions.push({id:id('SUG'),text:b.text,author:actor.name,date:now()});return a;}
   if(actor.role!=='admin')fail('Редактирование доступно администратору.',403);
   if(action==='publish'||action==='withdraw'){if(!a)fail('Статья не найдена.');a.status=action==='publish'?'published':'needs_review';a.version=(a.version||0)+1;a.revision++;return a;}
   const next={...a,...b.content,id:key||id('KB'),status:'draft',version:a?.version||1,revision:(a?.revision||0)+1,versions:a?.versions||[],suggestions:a?.suggestions||[]};db.knowledge[next.id]=next;return next;
  }
  if(url.startsWith('staff/club')){const d=db.responses['staff/club'];if(method==='GET')return d;if(actor.role!=='admin')fail('Нужны права администратора.',403);if(parts[2]==='config'){version(d.config,b);d.config={...d.config,...b,version:d.config.version+1};return d;}if(parts[2]==='post'){const p=d.posts.find(p=>p.id===b.id);if(b.archive&&p)p.archived=true;else d.posts.unshift({...b,author:actor.name,date:now(),archived:false});return d;}fail('Для проверки бонуса сначала создайте приглашение и пополнение.');}
  if(url==='client/club')return {...db.responses[url],rules:{...db.responses[url].rules,...db.responses['staff/club'].config},posts:db.responses['staff/club'].posts.filter(p=>!p.archived)};
  if(url==='client/invitations')return {...db.responses[url],code:'local-'+ctx.clientId,requests:0};
  if(url==='client/club/preferences'){const d=db.responses['client/club'];d.alias=b.alias;d.listed=b.listed;return d;}
  const uid=staff&&parts[1]==='clients'?parts[2]:ctx.clientId;
  if(staff&&parts[1]==='leads'){
   const l=db.leads[parts[2]];if(!l)fail('Заявка не найдена.',404);if(actor.role!=='admin'&&l.owner!==actor.id)fail('Заявка другого менеджера.',403);
   if(parts[3]==='club-membership'&&method==='POST'){const result=membership(l.crm,b,actor,!!l.client_id);if(l.client_id)db.accounts[l.client_id].crm=clone(result);return result;}
   if(parts[3]==='contact'){const result=contact(l.crm,b,actor);journeyCorrection(l,b,actor);if(l.client_id){db.accounts[l.client_id].version++;snapshot(db,l.client_id);}return result;}
   if(parts[3]==='profile'){version(l.crm,b);Object.assign(l,{first_name:b.firstName,last_name:b.lastName,name:[b.firstName,b.lastName].join(' '),phone:b.phone,email:b.email});contact(l.crm,b,actor);return l;}
   if(parts[3]==='resolve-match'){l.needsReview=false;l.conflicts=[];l.duplicateOf=b.originalId==='separate'?null:b.originalId;return l;}
   if(parts[3]==='call-context')return {kind:'lead',key:l.id,name:l.name,clientId:l.client_id,crm:l.crm,source:l.attribution,journey:l.context?.journey,mining:l.context?.mining,solar:l.context?.solar,state:null,rules:{},serverNow:now()};
   if(parts[3]==='followup-consent'){l.crm.consents=l.crm.consents.map(c=>c.channel===b.channel?{...c,granted:false}:c);return {ok:true};}return l;
  }
  const a=visible(uid),action=staff?parts.slice(3).join('/'):parts.slice(1).join('/');
  if(action==='club-membership'&&method==='POST'){if(!staff)fail('Team access required.',403);const result=membership(a.crm,b,actor,true),origin=Object.values(db.leads).find(l=>l.client_id===uid);if(origin)origin.crm=clone(result);return result;}
  if(action==='chat'||action==='chat/read'){
   if(method==='GET')return chat(db,uid,actor);if(action==='chat/read'){db.chatReads??={};db.chatReads[actor.id+':'+uid+':'+b.ticketId]=b.sequence;return chat(db,uid,actor);}
   if(!b.text?.trim())fail('Введите сообщение.');let thread=a.state.tickets.find(t=>t.id===b.ticketId);if(!thread){thread={id:id('CHAT'),subject:'Чат с командой',message:b.text,date:now(),channel:'live-chat',messages:[],status:'Open'};a.state.tickets.push(thread);}
   if(!thread.messages.some(m=>m.id===b.id)){const date=now();thread.messages.push({id:b.id||id('MSG'),from:staff?'manager':'client',text:b.text.trim(),date,authorName:actor.name,sequence:thread.messages.length+1});if(staff)Object.assign(thread,{reply:b.text.trim(),repliedAt:date,readReply:null,status:'Resolved'});else{thread.message=b.text.trim();thread.status='Open';thread.service={...thread.service,closed:false};}}a.version++;return {...chat(db,uid,actor),sentTicketId:thread.id};
  }
  if(action.startsWith('identity')){const d=db.identities[uid]||{version:1,status:'draft',fields:{},files:[],reviewNote:''};if(d.status==='empty')d.status='draft';if(method==='GET')return d;version(d,b);if(action.endsWith('submit')){if(!b.consent)fail('Подтвердите отправку анкеты.');d.fields=b.fields;d.status='submitted';}if(action.endsWith('review')){d.status=b.status;d.reviewNote=b.note;}if(action.endsWith('upload'))fail('Для проверки используйте текстовую анкету без настоящих документов.');if(action.endsWith('remove'))d.files=d.files.filter(f=>f.id!==b.id);d.version++;return d;}
  if(action==='journey'&&!staff){version(a,b);if(b.clientId!==uid)fail('Client access required.',403);let chosen;try{chosen=J.normalize(b.journey);}catch(e){fail(e.message);}if(!chosen)fail('Choose a topic.');if(b.marketingConsent===true&&!a.client.email)fail('Add an email in your profile first.');a.state.journey=J.merge(a.state.journey,chosen,a.state.journey?.lastSource||a.state.attribution,now());if(b.consultationRequested===true)J.requestConversation(a.state,chosen,b.language,id('JOURNEY'),now());a.state.subscription={granted:b.marketingConsent===true,email:a.client.email,version:J.version,capturedAt:now(),language:b.language||'en'};const origin=Object.values(db.leads).find(l=>l.client_id===uid);if(origin){origin.context={...origin.context,journey:clone(a.state.journey),subscription:clone(a.state.subscription)};history(origin.crm,'client_journey_updated',{journey:a.state.journey},actor);}a.version++;return snapshot(db,uid);}
  if(action==='call-context')return {kind:'client',key:uid,name:a.client.name,clientId:uid,crm:a.crm,source:a.state.attribution||{},journey:a.state.journey,state:a.state,rules:{},serverNow:now()};
  if(action==='plan-document')return domain.planDocument.snapshot(a,stations,new URLSearchParams(query).get('selection')||'auto');
  if(action==='accrual/close')return a;
  if(method==='GET'&&(action===''||action==='account'))return a;
  if(action==='delete'&&staff){if(actor.role!=='admin')fail('Удаление доступно администратору.',403);db.archive.push(clone(a));delete db.accounts[uid];delete db.identities[uid];for(const l of Object.values(db.leads))if(l.client_id===uid){l.client_id=null;l.status='new';}return {ok:true};}
  if(action==='contact'){const origin=Object.values(db.leads).find(l=>l.client_id===uid);if(origin){journeyCorrection(origin,b,actor);a.state.journey=clone(origin.context.journey);a.state.subscription=clone(origin.context.subscription||null);}else if(b.journey)a.state.journey={...J.merge(a.state.journey,b.journey,a.state.attribution,now()),...J.normalize(b.journey)};a.version++;const r=contact(a.crm,b,actor);if(db.leads[r.leadId])db.leads[r.leadId].crm=clone(r);return r;}
  version(a,b);
  if(action==='balance'){domain.crm.changeBalance(a.state,{...b,role:actor.role,actor:actor.name});}
  else if(action==='finance'){const op={...b,role:actor.role,actor:actor.name};if(b.kind==='plan')O.activate(a.state,b.plan,ids,op);else if(b.kind==='review')O.review(a.state,op);else if(b.kind==='weekly')O.creditWeek(a.state,op);else fail('Неизвестная операция.');}
  else if(action==='plan-draft'){a.state.planDraft=P.draft(b.plan,a.state.planDraft,ids,'manager',a.state.plan);a.planDraftNote={date:now(),comment:b.reason};}
  else if(action==='profile'){let v=b;if(!staff){if(b.clientId!==uid)fail('Client access required.',403);const checked=domain.profile.profile(b.profile||{});if(Object.keys(checked.errors).length)fail('Проверьте контактные данные и часовой пояс.');v=checked.value;}if(!v?.name||v.name.trim().length<2)fail('Укажите имя клиента.');Object.assign(a.client,{name:v.name.trim(),email:v.email||'',phone:v.phone||''});a.state.client.note=staff?b.note||'':a.state.client.note;a.state.preferences={...a.state.preferences,language:v.language||a.state.preferences?.language};if(!staff)a.state.ecosystem={...a.state.ecosystem,timezone:v.timezone};}
  else if(action==='reply'){const t=a.state.tickets.find(t=>t.id===b.ticketId);if(!t||!b.text?.trim())fail('Выберите обращение и введите ответ.');t.messages??=[];t.messages.push({id:id('MSG'),text:b.text,from:'manager',date:now(),authorName:actor.name});t.reply=b.text;t.repliedAt=now();t.status='Resolved';}
  else if(action==='account'){a.state=P.mergeClient(a.state,b.state,ids);}
  else if(action==='support'||action==='equipment'){if(b.kind==='read'){const t=a.state.tickets.find(t=>t.id===b.ticketId);if(t)t.readReply=t.reply;}else{let appointment=null;if(b.appointment){appointment=domain.profile.appointment(b.appointment,Date.parse(now()));if(!appointment)fail('Выберите будущее время в часовом поясе США или Канады.');}const text=(appointment?`Preferred callback: ${appointment.date} at ${appointment.time} (${appointment.timeZone}). Time to be confirmed.\n\n`:'')+(b.message||b.comment||b.notes||'Запрос по оборудованию');if(text.length<3)fail('Добавьте сообщение.');let t=a.state.tickets.find(t=>t.id===b.ticketId);if(!t){t={id:b.id||id('TICKET'),...(appointment?{appointment}:{}),subject:b.subject||'Подбор оборудования',message:text,date:now(),context:b.context||b.selection||null,status:'Open',messages:[]};a.state.tickets.push(t);}t.messages.push({id:id('MSG'),from:'client',text,date:now()});t.message=text;t.status='Open';t.service={...t.service,closed:false};}}
  else if(action==='energy-brief'){
   if(!['weekly','recommendation','call','event'].includes(b.kind)||!b.text?.trim()||b.text.trim().length<3)fail('Добавьте комментарий к публикации.');
   a.state.energyBriefs??=[];if(a.state.energyBriefs.some(v=>v.id===b.id))fail('Публикация уже сохранена.',409);
   const brief={id:b.id||id('BRIEF'),kind:b.kind,text:b.text.trim(),authorId:actor.id,authorName:actor.name,createdAt:now(),source:'model'};
   if(b.kind==='weekly')brief.report=domain.journal.report(a.state);
   if(b.kind==='recommendation'){if(!a.liveAccrual.active)fail('Сначала активируйте план.');brief.comparison=domain.journal.recommendation(a.liveAccrual,b.location,Number(b.percent));brief.plan={capital:a.liveAccrual.capital,rate:a.liveAccrual.weeklyRatePercent,appliedAt:a.state.plan.appliedAt};}
   a.state.energyBriefs.push(brief);
  }
  else if(action==='followup-consent'){a.crm.consents=a.crm.consents.map(c=>c.channel===b.channel?{...c,granted:false}:c);}
  else fail('Этот сценарий недоступен в локальном просмотре: '+url,400);
  a.version++;return snapshot(db,uid);
 }
 return {initial:()=>clone(seed),snapshot,overview,execute(db,path,method='GET',body={},context={}){const draft=clone(db),result=route(draft,path,method,body,context);return {db:draft,result:clone(result)};}};
};
