'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EcoSolarGuide=api;})(typeof window==='object'?window:globalThis,()=>{
 const business=typeof module==='object'&&module.exports?require('./business-model.js'):window.EcoBusiness;
 const checkedAt='2026-09-28';
 const sources=[{name:'SolarReviews · cash-system costs before incentives',url:'https://www.solarreviews.com/solar-panel-cost'},{name:'IRS · Residential Clean Energy Credit',url:'https://www.irs.gov/credits-deductions/residential-clean-energy-credit'}];
 function sections(language='en'){const t=(en,ru)=>language==='ru'?ru:en;return [
  {title:t('Opening','Открытие'),text:t('Hi [name], this is [manager] with EcoGrid. You asked about energy equipment or specialist advice. Is now a good time to understand the property and what you would like the system to do?','Здравствуйте, [имя], это [менеджер] из EcoGrid. Вы оставили заявку на энергетическое оборудование или помощь в подборе. Удобно сейчас уточнить данные объекта и задачи, которые должна решать система?')},
  {title:t('Qualify the home and the goal','Объект и задача'),text:t('Confirm country (United States or Canada), ZIP/postal code and service coverage, ownership, roof condition, shade, available space and the last 12 months of electricity use. Ask: is the main goal reducing purchased electricity, backup for essentials, or supporting larger loads? Which appliances need backup? Check the utility tariff and export rules before estimating savings.','Уточните страну (США или Канада), почтовый индекс и территорию обслуживания, владение домом, состояние крыши, тень, площадь и расход электричества за 12 месяцев. Главная задача — меньше покупать электричество, резерв для основных приборов или питание более крупных нагрузок? Какие приборы нужны при отключении? До расчёта экономии проверьте тариф и правила отдачи энергии в сеть.')},
  {title:t('EcoGrid AI · energy management','EcoGrid AI · управление энергией'),text:business.ai('solar',language).body+' '+business.ai('storage',language).body},
  {title:t('EcoGrid AI · EV charging','EcoGrid AI · зарядная инфраструктура'),text:business.ai('charge',language).body+' '+t('For equipment at your property, confirm compatible controls, metering and the service scope in the quote.','Для оборудования на вашем объекте совместимость управления, учёт энергии и состав сервиса согласовываются в предложении.')},
  {title:t('Explain the starting price','Объяснить ориентир цены'),text:t('Our U.S. starting planning estimates in USD, before incentives, are $16,800 for Home 5, $21,490 for Home 7 and $28,600 for Home 10. These are system-and-installation estimates, not the price of panels alone. The reference design uses Qcells 440 W modules. Roof work, electrical upgrades, battery storage, final equipment and local installation conditions can change the quote.','Ориентиры для США в USD до льгот: Home 5 — $16 800, Home 7 — $21 490, Home 10 — $28 600. Это система с установкой, а не цена только панелей. Базовый пример рассчитан на модули Qcells 440 W. Работы с крышей, модернизация электрики, накопитель, окончательное оборудование и местные условия могут изменить смету.')},
  {title:t('Panel and battery preference','Выбор панели и накопителя'),text:t('We can compare Qcells, REC, Canadian Solar, Silfab and Trina Solar modules, then discuss Enphase, Tesla, FranklinWH or sonnen storage as a separate quote. Availability and regional approvals must be checked. Panel watts describe rated generating power; battery kWh describe stored energy, while kW describes output power. Capacity alone does not tell us how long your whole home can run. The installer must confirm compatible inverter, controls, isolation and load requirements.','Сравним модули Qcells, REC, Canadian Solar, Silfab и Trina Solar, затем отдельно рассчитаем накопитель Enphase, Tesla, FranklinWH или sonnen. Наличие и региональные допуски нужно проверить. Ватты панели — номинальная мощность генерации; кВт·ч накопителя — запас энергии, а кВт — мощность отдачи. По одной ёмкости нельзя обещать часы работы всего дома. Инсталлятор должен проверить инвертор, управление, отключение от сети и нагрузку.')},
  {title:t('Incentives: no automatic 30% discount','Льготы: без автоматической скидки 30%'),text:t('For Canada, confirm local prices, currency and incentive rules separately; U.S. tax guidance does not apply. Our figures do not deduct incentives. IRS guidance excludes the residential clean energy credit for property placed in service after December 31, 2025. Any state or utility benefit needs an address-specific eligibility check. A lease or PPA is a separate ownership and payment arrangement, not an automatic discount or a program EcoGrid has confirmed offering.','Для Канады отдельно проверьте местную цену, валюту и программы; правила IRS к ней не относятся. В цене льготы не вычтены. По IRS домашний налоговый вычет недоступен для объектов, введённых после 31 декабря 2025 года. Местные программы проверяются по адресу и условиям клиента. Лизинг и PPA — отдельные договорные схемы, а не автоматическая скидка или уже подтверждённая программа EcoGrid.')},
  {title:t('If the client asks why a panel costs much less','Если клиент сравнивает с ценой одной панели'),text:t('A module price covers one component. A finished system also requires an inverter, mounting, wiring, design, labor and permitting. We compare itemized quotes with the same scope. Do not use wholesale module prices as an installed-system price or promise a fixed panel-only price without a supplier quote.','Цена модуля относится к одному компоненту. В готовой системе нужны инвертор, крепления, проводка, проектирование, работа и разрешения. Сравниваем подробные сметы с одинаковым составом. Нельзя выдавать оптовую цену модуля за стоимость установленной системы или обещать цену отдельной панели без предложения поставщика.')},
  {title:t('Close on a written quote','Закрытие на письменную смету'),text:t('I have your preferred system and equipment. Let’s confirm the roof and electricity use, then put the equipment, installation scope and price in writing. What time works for the follow-up? This request does not place an order or take payment.','Я сохранил выбранную систему и оборудование. Уточним крышу и расход электричества, затем зафиксируем комплектацию, работы и цену письменно. Когда удобно вернуться с расчётом? Эта заявка не оформляет заказ и не списывает деньги.')},
  {title:t('Manager checklist','Зафиксировать в CRM'),text:t('For EV charging, ask the make/model, connector, parking location, portable vs fixed preference and installation assessment; discuss Tesla, DEWALT or ChargePoint without promising stock. If unsure, keep the equipment undecided. Record property details, selected panel and battery, budget, service-area check, open technical questions and agreed callback. Honor no-contact requests. Do not promise stock, savings, financing, tax eligibility or installation dates without confirmation. Home solar sales do not activate a participation plan or create a Club funding bonus.','Для зарядки уточните модель автомобиля, разъём, место парковки, переносной или стационарный вариант и необходимость обследования электрики; обсудите Tesla, DEWALT или ChargePoint без обещания наличия. Если клиент не определился, оставьте подбор специалисту. Запишите данные объекта, панель и накопитель, бюджет, проверку территории обслуживания, технические вопросы и время контакта. Отказ от связи обязателен к исполнению. Не обещайте наличие, экономию, финансирование, льготы и дату монтажа без подтверждения. Покупка солнечной системы не активирует план участия и не создаёт бонус Club за пополнение.')}
 ];}
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function html(language='en'){return `<details class="crm-panel solar-sales-guide" translate="no" lang="${language==='ru'?'ru':'en'}"><summary>${language==='ru'?'Energy equipment · спич и цены':'Energy equipment · conversation and pricing'}</summary>${sections(language).map(s=>`<h3>${esc(s.title)}</h3><p>${esc(s.text)}</p>`).join('')}<small>${language==='ru'?'Проверено':'Checked'}: ${checkedAt}</small><p>${sources.map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${s.name} ↗</a>`).join(' · ')}</p></details>`;}
 return {checkedAt,sources,sections,html};
});
