'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.EcoSolar=api;})(typeof window==='object'?window:globalThis,()=>{
 const brandModels={"qcells-440":["EcoGrid Solar","ET153"],"rec-470":["EcoGrid Solar","ET Alpha mod 2.0"],"canadian-470":["EcoGrid Solar","ET-42 MAX"],"silfab-440":["EcoGrid Solar","ET Prime 440"],"silfab-420":["EcoGrid Solar","ET Elite 420"],"trina-450":["EcoGrid Solar","ET Vertex 450"],"enphase-5p":["EcoGrid Storage","ES5"],"tesla-3":["EcoGrid Storage","ES13.5"],"franklin-2":["EcoGrid Storage","ES15 MAX"],"enphase-10c":["EcoGrid Storage","ES10"],"sonnen-10":["EcoGrid Storage","ES10 Core"],"sonnen-20":["EcoGrid Storage","ES20 MAX"],"tesla-mobile":["EcoGrid Charge","ECH Mobile 32"],"dewalt-16":["EcoGrid Charge","ECH Portable 16"],"tesla-universal":["EcoGrid Charge","ECH Home 48"],"chargepoint-flex":["EcoGrid Charge","ECH Flex 50"],"chargepoint-cpf50":["EcoGrid Charge","ECH Pro 50"]};
 const brandName=p=>p?(p.brand&&p.brandModel?p.brand+' '+p.brandModel:p.manufacturer+' '+p.model):'';
 const version='energy-2026-09-v4';
 const moduleSpec=Object.freeze({manufacturer:'Qcells',model:'Q.TRON BLK M-G2+',powerW:440,efficiency:22.5,widthMm:1134,heightMm:1722,depthMm:30,weightKg:21.2,productYears:25,performanceYears:25,source:'https://us.qcells.com/q-tron-blk-m-g2/',datasheet:'https://media.qcells.com/v/1FhTENgd/'});
 const systems=Object.freeze([{id:'home-5',name:'EcoGrid Solar 5',nominalKw:5,estimateUsd:16800,panels:12},{id:'home-7',name:'EcoGrid Solar 7',nominalKw:7,estimateUsd:21490,panels:16},{id:'home-10',name:'EcoGrid Solar 10',nominalKw:10,estimateUsd:28600,panels:23}].map(s=>Object.freeze({...s,arrayKw:s.panels*moduleSpec.powerW/1000,pricePerNominalW:s.estimateUsd/(s.nominalKw*1000),panelAreaM2:Math.round(s.panels*moduleSpec.widthMm*moduleSpec.heightMm/100000)/10})));
 const find=id=>systems.find(s=>s.id===id);
 const panels=Object.freeze([
  {id:'qcells-440',...moduleSpec,image:'solar-qcells-440.jpg',technology:'N-type Q.ANTUM NEO',use:'The reference for Home 5 / 7 / 10',warranty:'25-year product and performance terms'},
  {id:'rec-470',manufacturer:'REC',model:'Alpha Pure-RX',powerW:470,efficiency:22.6,widthMm:1205,heightMm:1728,depthMm:30,technology:'Heterojunction (HJT)',image:'solar-rec-470.webp',use:'HJT technology in an all-black module',warranty:'20-year product / 25-year performance terms; ProTrust eligibility checked separately',source:'https://www.recgroup.com/en/rec-alpha-pure-rx',datasheet:'https://www.recgroup.com/sites/default/files/2025-04/Web_DS_REC%20Alpha%20Pure-RX_EN%20US_042025.pdf'},
  {id:'canadian-470',manufacturer:'Canadian Solar',model:'TOPHiKu6 · CS6.2-48TM-470H',powerW:470,efficiency:23.5,widthMm:1134,heightMm:1762,depthMm:35,technology:'N-type TOPCon',image:'solar-canadian-470.webp',use:'470 W in a 1,762 × 1,134 mm footprint',warranty:'25-year product coverage for eligible rooftop regions / 30-year performance terms',source:'https://www.csisolar.com/na/module/',datasheet:'https://static.csisolar.com/wp-content/uploads/sites/3/2025/05/09130713/CS-Datasheet-TOPHiKu6_All-Black_CS6.2-48TM-H_v1.0C25_F23_D1_NA-1.pdf'}
 ,{id:'silfab-440',manufacturer:'Silfab',model:'Prime · SIL-440 QD',powerW:440,efficiency:22.6,widthMm:1133,heightMm:1721,depthMm:35,technology:'N-type · 108 half cells',image:'solar-silfab-440.webp',use:'All-black N-type design',warranty:'12-year product warranty, extendable to 25 years with registration; 30-year performance terms',source:'https://silfabsolar.com/our-solar-panels/silfab-prime/sil-440-qd/',datasheet:'https://silfabsolar.com/wp-content/uploads/2026/09/Silfab-SIL-440-QD-Data-Generic-20260804-Final.pdf'},
  {id:'silfab-420',manufacturer:'Silfab',model:'Elite · SIL-420 BG',powerW:420,efficiency:21.9,widthMm:1029,heightMm:1864,depthMm:35,technology:'Back-contact · mono-PERC MWT',image:'solar-silfab-420.webp',photoDetail:true,use:'Back-contact design with a conductive backsheet',warranty:'12-year product warranty, extendable to 25 years with registration; 30-year performance terms',source:'https://silfabsolar.com/our-solar-panels/silfab-elite/sil-420-bg/',datasheet:'https://silfabsolar.com/wp-content/uploads/2025/12/Silfab-SIL-420-BG-Data-Final.pdf'},
  {id:'trina-450',manufacturer:'Trina Solar',model:'Vertex S+ · TSM-450 NEG9R.28',powerW:450,efficiency:22.5,widthMm:1134,heightMm:1762,depthMm:30,technology:'Dual glass · N-type i-TOPCon',image:'solar-trina-450.webp',use:'Dual-glass module for rooftop systems',warranty:'25-year product / 30-year power terms; regional availability and approval checked in the quote',source:'https://pages.trinasolar.com/NEG9R.28.html',datasheet:'https://static.trinasolar.com/sites/default/files/Datasheet_Vertex%20S%2B_NEG9R.28_EN_2024_A_S1_web.pdf'}
 ].map(p=>Object.freeze({...p,brand:brandModels[p.id][0],brandModel:brandModels[p.id][1]})));
 const batteries=Object.freeze([
  {id:'enphase-5p',manufacturer:'Enphase',model:'IQ Battery 5P',capacityKWh:5,continuousKW:3.84,image:'storage-enphase-5p.webp',use:'A modular starting point',architecture:'AC-coupled · LFP',warranty:'15-year limited warranty',source:'https://enphase.com/store/storage/gen3/iq-battery-5p'},
  {id:'tesla-3',manufacturer:'Tesla',model:'Powerwall 3',capacityKWh:13.5,continuousKW:11.5,image:'storage-tesla-3.webp',use:'Integrated solar inverter',architecture:'Integrated PV inverter · U.S. configuration',warranty:'10-year limited warranty',source:'https://energylibrary.tesla.com/docs/Public/EnergyStorage/Powerwall/3/Datasheet/en-us/Powerwall-3-Datasheet.pdf'},
  {id:'franklin-2',manufacturer:'FranklinWH',model:'aPower 2',capacityKWh:15,continuousKW:10,image:'storage-franklin-poster.webp',use:'Higher capacity per unit',architecture:'AC-coupled · LFP · aGate required',warranty:'15 years or 60 MWh throughput, subject to terms',source:'https://www.franklinwh.com/document/apower-2-datasheet'}
 ,{id:'enphase-10c',manufacturer:'Enphase',model:'IQ Battery 10C',capacityKWh:10,continuousKW:7.08,image:'storage-enphase-10c.webp',use:'10 kWh with a compact wall-mounted design',architecture:'AC-coupled · LFP · fourth-generation system',warranty:'15-year limited warranty, up to 6,000 cycles; manufacturer terms apply',source:'https://enphase.com/store/storage/gen4/iq-battery-10c'},
  {id:'sonnen-10',manufacturer:'sonnen',model:'sonnenCore+ · SCORE-P10',capacityKWh:10,continuousKW:4.8,image:'storage-sonnen-core.webp',photoDetail:true,photoCaption:'Manufacturer installation example: three units',use:'Indoor storage for everyday energy management',architecture:'AC-coupled · LFP · indoor installation only',warranty:'10 years or 10,000 cycles; manufacturer terms apply',source:'https://media.sonnengroup.com/ce4d12c8-d0db-4ffb-9274-5017a8fcb6b4-en-download'},
  {id:'sonnen-20',manufacturer:'sonnen',model:'sonnenCore+ · SCORE-P20',capacityKWh:20,continuousKW:4.8,image:'storage-sonnen-core.webp',photoDetail:true,photoCaption:'Manufacturer installation example: three units',use:'More stored energy in the same cabinet size',architecture:'AC-coupled · LFP · indoor installation only',warranty:'10 years or 10,000 cycles; manufacturer terms apply',source:'https://media.sonnengroup.com/ce4d12c8-d0db-4ffb-9274-5017a8fcb6b4-en-download'}
 ].map(p=>Object.freeze({...p,brand:brandModels[p.id][0],brandModel:brandModels[p.id][1]})));
 // User-defined equipment price: 19% below the listed U.S. reference model.
 // This is a planning offer, not verified procurement cost or an installed-site valuation.
 const chargerPricePolicy=Object.freeze({version:'charge-equipment-us-2026-10-03',currency:'USD',market:'US',discount:.19,checkedAt:'2026-10-03',installationIncluded:false});
 const chargerReferences=Object.freeze({
  'tesla-mobile':{priceUsd:300,url:'https://shop.tesla.com/category/configurator-charging',configuration:'Mobile Connector, NEMA 5-15 and 14-50 adapters'},
  'dewalt-16':{priceUsd:299.97,url:'https://www.homedepot.com/p/326991301',configuration:'DXPAEV016, 16 A, 25-foot cable'},
  'tesla-universal':{priceUsd:600,url:'https://shop.tesla.com/product/universal-wall-connector',configuration:'Universal Wall Connector, NACS and J1772'},
  'chargepoint-flex':{priceUsd:549,url:'https://www.alliantenergymarketplace.com/Electric-Vehicle-Chargers/I-CHARGFLEX-01-HARD-WIRE-V1.html',configuration:'CPH50-HARDWIRE-L23-K, J1772, 50 A'},
  'chargepoint-cpf50':{priceUsd:899,url:'https://smartchargeamerica.com/electric-car-chargers/commercial/chargepoint-cpf50/',configuration:'CPF50 standalone charger; pedestal, activation and network scope quoted separately'}
 });
 const chargers=Object.freeze([
  {id:'tesla-mobile',manufacturer:'Tesla',model:'Mobile Connector',kind:'portable',maxKW:7.7,amps:32,connector:'NACS',image:'ev-tesla-mobile.webp',use:'A portable option for home and travel',detail:'120 / 240 V · compatible outlet and adapter required',source:'https://shop.tesla.com/product/mobile-connector'},
  {id:'dewalt-16',manufacturer:'DEWALT',model:'DXPAEV016',kind:'portable',maxKW:3.84,amps:16,connector:'J1772',image:'ev-dewalt-16.webp',use:'Portable charging with a 25-foot cable',detail:'120 / 240 V · Tesla requires a compatible adapter',source:'https://www.dewalt.com/en-us/product/dxpaev016/portable-electric-vehicle-ev-120-240v-level-2-charger-16-amps-csa-certified'},
  {id:'tesla-universal',manufacturer:'Tesla',model:'Universal Wall Connector',kind:'fixed',maxKW:11.5,amps:48,connector:'NACS + J1772',image:'ev-tesla-universal.webp',use:'One wall unit for Tesla and J1772 vehicles',detail:'Hardwired · integrated J1772 adapter · 24-foot cable',source:'https://shop.tesla.com/product/universal-wall-connector'},
  {id:'chargepoint-flex',manufacturer:'ChargePoint',model:'Home Flex · CPH50',kind:'fixed',maxKW:12,amps:50,connector:'NACS or J1772',image:'ev-chargepoint-flex.webp',use:'Scheduled charging for your home',detail:'Connector selected with the quote · 50 A requires hardwiring',source:'https://www.chargepoint.com/drivers/home/installation/flex'},
  {id:'chargepoint-cpf50',manufacturer:'ChargePoint',model:'CPF50',kind:'commercial',maxKW:12,amps:50,connector:'NACS or J1772',image:'ev-chargepoint-cpf50.webp',use:'Charging for workplaces and shared parking',detail:'Wall or pedestal · up to 12 kW per port at 240 V',source:'https://www.chargepoint.com/products/stations/cpf50'}
 ].map(p=>Object.freeze({...p,brand:brandModels[p.id][0],brandModel:brandModels[p.id][1]})));
 const panel=id=>panels.find(p=>p.id===id),battery=id=>batteries.find(b=>b.id===id),charger=id=>chargers.find(c=>c.id===id);
 function chargerPricing(id){const ref=chargerReferences[id],item=charger(id);if(!ref||!item)return null;return {...chargerPricePolicy,referencePriceUsd:ref.priceUsd,equipmentPriceUsd:Math.round(ref.priceUsd*(1-chargerPricePolicy.discount)*100)/100,referenceUrl:ref.url,referenceModel:item.manufacturer+' '+item.model,referenceConfiguration:ref.configuration};}
 function chargerPriceText(id,lang='en'){const p=chargerPricing(id);return p?new Intl.NumberFormat(lang==='ru'?'ru-RU':'en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(p.equipmentPriceUsd)+' USD':'';}
 function arrayFor(systemId,panelId='qcells-440'){const s=find(systemId),p=panel(panelId);if(!s||!p)return null;const count=Math.ceil(s.nominalKw*1000/p.powerW);return {panels:count,arrayKw:count*p.powerW/1000};}
 function validate(v){const kind=v.solarRequestType||'solar',country=v.solarCountry||'US';if(!['solar','storage','charging','consultation'].includes(kind))return 'Choose an inquiry type.';if(!['US','CA'].includes(country))return 'Choose the United States or Canada.';if(kind==='solar'&&!find(v.solarSystem))return 'Choose a solar system.';const zip=String(v.solarZip||'').trim().toUpperCase();if(country==='US'&&!/^\d{5}$/.test(zip))return 'Enter a five-digit U.S. ZIP code.';if(country==='CA'&&!/^[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z] ?\d[ABCEGHJ-NPRSTV-Z]\d$/.test(zip))return 'Enter a Canadian postal code, for example M5V 2T6.';if(!['owner','planning','business','other'].includes(v.solarProperty))return 'Tell us about the property.';if(kind==='solar'&&!['yes','no','undecided'].includes(v.solarBattery))return 'Choose a battery preference.';if(v.solarPanel&&!panel(v.solarPanel))return 'Choose a listed panel model.';if(v.solarBatteryModel&&(!battery(v.solarBatteryModel)||v.solarBattery!=='yes'&&kind!=='storage'))return 'Choose a listed battery model or clear the preference.';if(v.solarCharger&&!charger(v.solarCharger))return 'Choose a listed charger or ask for help.';if(String(v.solarVehicle||'').length>100)return 'Keep vehicle details under 100 characters.';const bill=String(v.solarBill??'').trim();if(bill&&(!/^\d{1,5}(\.\d{1,2})?$/.test(bill)||Number(bill)>10000))return 'Enter a monthly electricity bill from $0 to $10,000, or leave it blank.';return '';}
 function inquiry(v){const error=validate(v);if(error)throw new Error(error);const kind=v.solarRequestType||'solar',country=v.solarCountry||'US',s=kind==='solar'?find(v.solarSystem):null,p=s?panel(v.solarPanel||'qcells-440'):null,b=s||kind==='storage'?battery(v.solarBatteryModel):null,c=kind==='charging'?charger(v.solarCharger):null;let zip=String(v.solarZip).trim().toUpperCase().replace(/\s/g,'');if(country==='CA')zip=zip.slice(0,3)+' '+zip.slice(3);return {catalogVersion:version,requestType:kind,country,systemId:s?.id||null,name:s?.name||(kind==='charging'?'EcoGrid EV charging':kind==='storage'?'EcoGrid energy storage':'EcoGrid specialist consultation'),nominalKw:s?.nominalKw||null,arrayKw:s?.arrayKw||null,panels:s?.panels||null,module:s?moduleSpec.model:null,moduleW:s?moduleSpec.powerW:null,estimateUsd:s?.estimateUsd||null,preferredPanel:p?{id:p.id,brandName:brandName(p),manufacturer:p.manufacturer,model:p.model,powerW:p.powerW,...arrayFor(s.id,p.id)}:null,preferredBattery:b?{id:b.id,brandName:brandName(b),manufacturer:b.manufacturer,model:b.model,capacityKWh:b.capacityKWh,continuousKW:b.continuousKW}:null,preferredCharger:c?{id:c.id,brandName:brandName(c),manufacturer:c.manufacturer,model:c.model,kind:c.kind,maxKW:c.maxKW,connector:c.connector,pricing:chargerPricing(c.id)}:null,vehicle:kind==='charging'?String(v.solarVehicle||'').trim():'',requote:!s||country==='CA'||p.id!=='qcells-440'||v.solarBattery==='yes',zip,property:v.solarProperty,battery:kind==='storage'?'yes':s?v.solarBattery:'undecided',billCurrency:country==='CA'?'CAD':'USD',billMonthly:String(v.solarBill??'').trim()===''?null:Number(v.solarBill)};}
 const consentVersion='energy-equipment-v2';
 const consentText={sms:'I agree to receive automated follow-up texts from EcoGrid at the number provided about my energy equipment request. Up to 2 messages in the first 24 hours. Message and data rates may apply. Reply STOP to opt out or HELP for help. Consent is optional and is not a condition of purchase.',email:'I agree to receive follow-up emails from EcoGrid about this energy equipment request. This is optional; I can unsubscribe at any time.'};
 const consentTextRu={sms:'Я согласен получать от EcoGrid автоматические SMS по указанному номеру по заявке на энергетическое оборудование: до 2 сообщений за первые 24 часа. Возможна плата оператора. Для отказа — STOP, для помощи — HELP. Согласие необязательно и не является условием покупки.',email:'Я согласен получать от EcoGrid письма по этой заявке на энергетическое оборудование. Это необязательно; отказаться можно в любое время.'};
 return {version,brandName,moduleSpec,systems,find,panels,batteries,chargers,panel,battery,charger,chargerPricePolicy,chargerPricing,chargerPriceText,arrayFor,validate,inquiry,consentVersion,consentText,consentTextRu};
});
