'use strict';
// Monthly rates are the single calculation used by the calculator, ledger and documents.
const weeklyCredit=EcoFinance.weekly;
function weekStart(value){const date=new Date(value+'T12:00:00Z');if(!Number.isFinite(date.getTime())||date.toISOString().slice(0,10)!==value)return null;date.setUTCDate(date.getUTCDate()-((date.getUTCDay()+6)%7));return date.toISOString().slice(0,10)}
if(demo.weeklyModelVersion!==1){if(demo.plan){demo.plan.period='week';demo.plan.status='active'}demo.weeklyModelVersion=1;demo.sessions??=[];demo.adjustments??=[];}
updateTariffMath=function(){
 const tier=demo.tariffs.find(t=>t.id===chosenTier),input=$('#investment-amount');if(!tier||!input)return;
 investmentDraft=window.EcoFinance?EcoFinance.parseAmount(input.value):Number(input.value);const valid=input.value.trim()!==''&&validDemoInvestment(investmentDraft);
 input.setAttribute('aria-invalid',String(!valid&&input.value.trim()!==''));$('#allocation-each').textContent=valid?money(investmentDraft/tier.count):'—';$('#allocation-payout').textContent=valid?money(weeklyCredit(investmentDraft,tier.rate)):'—';if($('#allocation-monthly'))$('#allocation-monthly').textContent=valid?money(EcoFinance.monthly(investmentDraft,tier.rate)):'—';
 if($('#scenario-results'))$('#scenario-results').innerHTML=[1,4,12].map(weeks=>`<div><span>${weeks} ${weeks===1?'week':'weeks'}</span><strong>${valid?money(EcoFinance.calendar.centsBetween(investmentDraft,tier.rate,Date.now(),Date.now()+weeks*7*86400000)/100):'—'}</strong><small>${tier.rate}% per calendar month · no compounding</small></div>`).join('');
 $('#tariff-error').textContent=valid||input.value.trim()===''?'':'Check the selected tier minimum: $250 / $500 / $800 / from $1,000. Use up to two decimal places.';
 document.querySelectorAll('[data-action="apply-plan"]').forEach(b=>b.disabled=!valid);
 document.querySelectorAll('[data-investment-preset]').forEach(b=>b.setAttribute('aria-pressed',String(valid&&Number(b.dataset.investmentPreset)===investmentDraft)));
};
document.addEventListener('click',e=>{const b=e.target.closest('[data-investment-preset]');if(!b)return;const input=$('#investment-amount');if(input){investmentDraft=Number(b.dataset.investmentPreset);chosenTier=EcoFinance.tiers.filter(t=>investmentDraft>=t.minimum).at(-1).id;renderTariffs();}});
sessionRows=function(){return demo.sessions.length?`<div class="table-scroll"><table><thead><tr><th>Event</th><th>Period starting</th><th>Capital</th><th>Rate</th><th>Credit</th><th>Record</th></tr></thead><tbody>${demo.sessions.slice().reverse().slice(0,30).map(s=>`<tr><td><strong>${s.period==='week'?'Weekly demo allocation':'Archived '+(s.period==='day'?'daily':'session')+' demo'}</strong><small>${escapeHtml(s.id)}</small></td><td>${escapeHtml(s.weekStart||s.day||s.date.slice(0,10))}</td><td>${money(s.capital??s.allocatedCapital??0)}</td><td>${s.rate.toFixed(1)}% / ${s.ratePeriod===EcoFinance.ratePeriod?'calendar month':s.period==='week'?'week':s.period==='day'?'day':'session'}</td><td class="green-text">+${money(s.payout)}</td><td><button class="text-button credit-detail-button" data-credit-detail="${escapeHtml(s.id)}">View calculation →</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">No weekly allocations recorded yet. Your manager can record a sample week after the plan is active.</div>'};
actions['simulate-session']=()=>{if(role!=='admin'){actions.sessions();return}if(!demo.plan||demo.plan.status!=='active'){toast('Activate a workspace client plan first.');return}const p=demo.plan;openModal(`<h2>Record a model week</h2><p>Credit one weekly allocation to the client balance. Solar, storage, charging, commercial energy contracts and grid sales form the business model; this is a separate sample plan calculation.</p><form id="weekly-credit-form"><label for="credit-week">A date in the week</label><input id="credit-week" type="date" value="${new Date().toISOString().slice(0,10)}" required><div class="allocation-math"><div><span>Invested plan capital</span><strong>${money(p.capital)}</strong></div><div><span>Calendar-month plan rate</span><strong>${p.rate.toFixed(1)}%</strong></div><div class="allocation-total"><span>Sample weekly credit</span><strong>${money(EcoFinance.planWeekly(p))}</strong></div></div><p class="form-hint">A Monday–Sunday week can be credited once. No additional credit is created per vehicle.</p><div id="weekly-error" class="form-error" role="alert"></div><button class="button primary" type="submit">Record weekly model credit</button></form>`)};
document.addEventListener('submit',e=>{if(e.target.id!=='weekly-credit-form')return;e.preventDefault();if(role!=='admin'||!demo.plan||demo.plan.status!=='active')return;const key=weekStart($('#credit-week').value);if(!key){$('#weekly-error').textContent='Choose a valid date.';return}if(demo.sessions.some(s=>s.period==='week'&&s.weekStart===key)){$('#weekly-error').textContent='This week already has an allocation. Choose another week.';return}const p=demo.plan,periodStart=key+'T00:00:00.000Z',periodEnd=new Date(Date.parse(periodStart)+7*86400000).toISOString(),payout=EcoFinance.planWeekly(p,Date.parse(periodStart));demo.sessions.push({id:'WEEK-'+key,period:'week',weekStart:key,capital:p.capital,rate:p.rate,ratePeriod:p.ratePeriod||'week',periodStart,periodEnd,payout,stationIds:p.stationIds.slice(),planName:p.name,date:new Date().toISOString()});demo.balance=Math.round((demo.balance+payout)*100)/100;activity('Manager recorded sample week '+key+': +'+money(payout));persist();$('#modal').close();renderAdmin();toast('Weekly demo allocation recorded.')});
renderSessionWidget=function(){const card=$('.performance-card');let widget=$('#session-widget');if(!widget){card.querySelector('.card-heading').hidden=true;card.querySelector('.performance-body').hidden=true;widget=document.createElement('div');widget.id='session-widget';card.append(widget)}const p=demo.plan,capital=p?.capital||250,rate=p?.rate||demo.tariffs[0].rate;widget.innerHTML=`<div class="session-heading"><h2>Your weekly calculation</h2><span class="simulation-badge">MODEL</span></div><div class="engine-location">${p?escapeHtml(p.name)+' plan':'Example: Single plan'} <span>· ${p?.status==='active'?'Active demo allocation':'Illustration, not yet funded'}</span></div><div class="engine-flow"><button class="engine-node" data-action="tariffs"><span>${icon('assets')}</span><small>${money(capital)} invested</small></button><div class="engine-connector"><i></i></div><button class="engine-node" data-action="tariffs"><span>${rate.toFixed(1)}<em>%</em></span><small>Per calendar month</small></button><div class="engine-connector"><i></i></div><button class="engine-node payout-node" data-action="engine-details"><span>${money(weeklyCredit(capital,rate))}</span><small>Weekly illustration</small></button></div><div class="engine-bottom"><span>Monthly amount prorated by calendar days · no compounding</span><button data-action="engine-details">How it works ${icon('arrow')}</button></div>`};
actions['engine-details']=()=>openModal(EcoBusiness.flow(window.EcoLocale?.language||'en')+'<p>'+EcoBusiness.cadence(window.EcoLocale?.language||'en')+'</p>');
actions.sessions=()=>openModal(`<h2>Weekly allocation history</h2><p>Recorded sample allocations. Historical entries keep their original terms.</p>${sessionRows()}${role==='admin'?'<button class="button primary" data-action="simulate-session">Record a model week</button>':''}`);
const contractBeforeWeekly=contractContent;
contractContent=function(){return contractBeforeWeekly().replaceAll('per completed session','per calendar month on invested capital').replace('The displayed rate is applied to the capital allocated to the station.','The monthly rate is applied once to invested capital, without compounding or an extra per-vehicle credit.').replace('<h2>4. Reference stations','<h2>Energy business model</h2><p>Solar generation and battery storage supply EV charging, commercial energy contracts and grid sales. Asset rights and contracts require documentation. The production split does not change plan accrual.</p><h2>4. Reference stations').replace('<h2>4. Reference stations','<h2>Withdrawal schedule</h2><p>Withdrawals are available every 4 days. The first withdrawal opens 4 days after plan activation. Each successful withdrawal starts a new 4-day period. Requests use the available balance; invested capital is not released automatically. Weekly accruals remain weekly.</p><h2>4. Reference stations')};
const planBarBeforeWeekly=renderPlanBar;
renderPlanBar=function(){planBarBeforeWeekly();const total=demo.sessions.filter(s=>s.period==='week').reduce((sum,s)=>sum+s.payout,0);$('.metrics-grid .metric-card:last-child>span').textContent='Weekly credits';$('.metrics-grid .metric-card:last-child>strong').textContent=money(total);$('.metrics-grid .metric-card:last-child>small').textContent='Recorded demo allocations';renderSessionWidget()};
renderSessionWidget();

// Inspect the values recorded at the time of the credit, not today's plan settings.
document.addEventListener('click',e=>{
 const button=e.target.closest('[data-credit-detail]');if(!button)return;
 const s=demo.sessions.find(record=>record.id===button.dataset.creditDetail);if(!s)return;
 const isWeekly=s.period==='week',capital=s.capital??s.allocatedCapital??0;
 let period=s.weekStart||s.day||s.date.slice(0,10);
 if(s.periodStart&&s.periodEnd){period=new Date(s.periodStart).toLocaleString(window.EcoLocale?.locale||'en-US')+' — '+new Date(s.periodEnd).toLocaleString(window.EcoLocale?.locale||'en-US');}
 else if(isWeekly&&s.weekStart){const end=new Date(s.weekStart+'T12:00:00Z');if(Number.isFinite(end.getTime())){end.setUTCDate(end.getUTCDate()+6);period=s.weekStart+' – '+end.toISOString().slice(0,10);}}
 const monthly=s.ratePeriod===EcoFinance.ratePeriod,expected=isWeekly?weeklyCredit(capital,s.rate,Date.parse(s.periodStart||s.weekStart+'T00:00:00Z'),s.ratePeriod||'week'):null;
 const recordedDate=new Date(s.date);
 const recordedAt=Number.isFinite(recordedDate.getTime())?new Intl.DateTimeFormat('en-US',{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'UTC',timeZoneName:'short'}).format(recordedDate):'Date unavailable';
 openModal(`<h2>${isWeekly?'Weekly credit details':'Archived model credit'}</h2><p>Saved demo record. This entry is not a bank transfer or verified station revenue.</p><dl class="credit-record-details"><div><dt>Record</dt><dd>${escapeHtml(s.id)}</dd></div><div><dt>Period</dt><dd>${escapeHtml(period)}</dd></div><div><dt>Recorded at</dt><dd>${escapeHtml(recordedAt)}</dd></div><div><dt>Plan at recording</dt><dd>${escapeHtml(s.planName||'Not recorded')}</dd></div><div><dt>Capital at recording</dt><dd>${money(capital)}</dd></div><div><dt>Recorded rate</dt><dd>${Number(s.rate).toFixed(1)}% / ${monthly?'calendar month':isWeekly?'week':s.period==='day'?'day':'session'}</dd></div><div><dt>Actual model credit</dt><dd>${money(s.payout)}</dd></div><div><dt>Reference stations</dt><dd>${s.stationIds?.length??'Not recorded'}</dd></div></dl>${isWeekly?`<div class="credit-record-calculation"><small>${monthly?'RECORDED MONTHLY RATE · CALENDAR PRORATION':'RECORDED CAPITAL × RECORDED WEEKLY RATE'}</small><strong>${monthly?money(capital)+' · '+Number(s.rate).toFixed(1)+'% / calendar month → ':money(capital)+' × '+Number(s.rate).toFixed(1)+'% = '}${money(expected)}</strong><p>Rounded to cents. No compounding and no additional payment per charging vehicle.${Math.abs(expected-s.payout)>.005?' The saved credit differs from this formula; ask the manager to review the record.':''}</p></div>`:'<div class="modal-note">This archived entry retains its original period. It is not recalculated using the current weekly model.</div>'}<div class="trust-portal-links"><a href="how-it-works/#cash-flow">Understand the proposed revenue source ↗</a><a href="terms/">Access, fees & risks ↗</a></div><button class="button secondary" data-action="sessions">Back to allocation history</button>`);
});
