// Source material is a supplied concept website, not company or identity evidence.
const story=require('./company-story.json');
module.exports=({esc,icon,kicker,link})=>({
  profile:`<section class="v-founder" id="founder" aria-labelledby="founder-heading">
    <div class="v-founder-identity">${kicker('FOUNDER PROFILE · DEMO CONTENT')}<h2 id="founder-heading" translate="no">${esc(story.founder)}</h2><p class="v-founder-role">${esc(story.role)}</p><span class="v-story-status">Supplied demo biography · Not independently verified</span><div class="v-founder-actions">${link('Read the full story','story/')}${link('View the document register','resources/#company-documents')}</div></div>
    <div class="v-founder-copy"><p>The supplied EcoCharge story introduces James Robert Whitaker, known as Jim, as an electrician from Ohio who built a charging business in Central Florida.</p><p>It describes a progression from commercial electrical work to fleet charging and the launch of EcoCharge. The focus of the story is practical operation: electricity costs, reliable equipment and understandable reporting.</p><dl class="v-founder-facts"><div><dt>Location in the story</dt><dd>${esc(story.location)}</dd></div><div><dt>EcoCharge start in the story</dt><dd>${esc(story.founded)}</dd></div><div><dt>Business focus</dt><dd>EV charging infrastructure</dd></div></dl></div>
  </section>
  <section class="v-company-story" id="company-story" aria-labelledby="story-heading"><div class="v-story-heading"><div>${kicker('THE COMPANY STORY')}<h2 id="story-heading">From electrical work<br>to EV charging.</h2></div><p>Milestones from the supplied demo narrative. Dates, positions and business history await supporting records.</p></div><ol class="v-story-timeline">${story.milestones.map(m=>`<li><span>${esc(m.year)}</span><h3>${esc(m.title)}</h3><p>${esc(m.body)}</p></li>`).join('')}</ol><details class="v-story-source"><summary>About this profile and its source ${icon('arrow')}</summary><p>The profile and timeline were adapted from the supplied EcoCharge concept website. Company registration, the founder's identity and work history have not been independently verified.</p><p>The EcoCharge brand story does not identify the legal entity that would sign an agreement. The legal information below remains pending.</p></details></section>`,
  teaser:`<section class="ec-wrap v-company-teaser" aria-labelledby="company-teaser-heading"><div>${kicker('COMPANY & LEADERSHIP')}<h2 id="company-teaser-heading">Get to know the story<br>behind EcoCharge.</h2><p>Explore the supplied founder profile, company timeline and the documents still to be provided.</p></div><a href="story/" class="v-founder-link"><span class="v-founder-initials" aria-hidden="true">JW</span><span><strong translate="no">${esc(story.founder)}</strong><span>Founder & CEO · Supplied demo profile</span><small>Read the profile & company story</small></span>${icon('arrow')}</a></section>`
});
