// Public explanations use sourced location records and explicitly invented economics.
module.exports = ({esc,icon,kicker,link,button,faq,photo,directory,trust,hardware}) => {
  const partners=require('./partners.cjs').renderPartners({esc,kicker,link});
  const station=directory.stations.find(s=>s.id===371815);
  const explore=(label='Explore the demo',next='dashboard')=>`<a class="ec-button" href="client/?guest=1&tab=${next}" data-funnel-cta="explore">${label}${icon('arrow')}</a>`;
  const home=`<div class="v-hero-shell"><section class="ec-wrap f-hero">
    <div class="f-hero-copy"><div class="v-hero-brand" translate="no">ECO <span>CHARGE</span></div>${kicker('EV INFRASTRUCTURE · INVESTMENT DEMO')}<h1>Explore EV charging.<br><span>Build your own plan.</span></h1><p>Explore real U.S. charging locations. Understand the proposed investment model, choose reference stations and build a sample plan before creating an account.</p><div class="f-actions">${explore('Build my demo plan','tariffs')}${link('Explore stations','stations/')}</div><small class="f-quiet">No sign-up to explore. No payment details.</small><a class="v-hero-model" href="inside-a-station/">How the business works ${icon('arrow')}</a></div>
    <div class="f-hero-location"><div class="f-photo-label">${icon('pin')} CLERMONT, FLORIDA <span>PUBLIC LOCATION</span></div>${photo('371815',true)}<div class="r-hero-steps"><small>YOUR WORKSPACE, AT A GLANCE</small><a href="client/?guest=1&tab=map"><span>${icon('pin')}</span> Inspect a real location ${icon('arrow')}</a><a href="client/?guest=1&tab=tariffs"><span>${icon('grid')}</span> Build your own example ${icon('arrow')}</a><a href="client/?guest=1&tab=dashboard&contact=manager"><span>${icon('chat')}</span> Discuss your questions ${icon('arrow')}</a></div></div>
  </section></div>
  <section class="ec-wrap f-sequence" aria-label="How the proposed business works"><div><span>01</span><strong>A driver charges</strong><p>Charging payments create revenue.</p></div><i aria-hidden="true">→</i><div><span>02</span><strong>The business covers costs</strong><p>Electricity, equipment and site operations.</p></div><i aria-hidden="true">→</i><div><span>03</span><strong>Terms determine distributions</strong><p>Client rights must be set out in an agreement.</p></div></section>
  ${hardware}
  <section class="v-workspace-shell"><div class="ec-wrap v-workspace"><div>${kicker('YOUR PERSONAL WORKSPACE')}<h2>Everything you need<br>to explore your plan.</h2><p>Your station selection, sample calculation and questions stay together. Save your example when you are ready.</p>${explore('Build my demo plan','tariffs')}</div><div class="v-workspace-preview"><div class="v-workspace-top"><strong translate="no">ECO CHARGE</strong><span>WORKSPACE PREVIEW</span></div><a href="client/?guest=1&tab=map">${icon('pin')}<span><strong>Choose your stations</strong><small>Map, real photos and source records</small></span>${icon('arrow')}</a><a href="client/?guest=1&tab=tariffs">${icon('grid')}<span><strong>See your sample calculation</strong><small>Your amount, station group and weekly example</small></span>${icon('arrow')}</a><a href="client/?guest=1&tab=dashboard&contact=manager">${icon('chat')}<span><strong>Keep your questions together</strong><small>Open a demo conversation from your plan</small></span>${icon('arrow')}</a></div></div></section>
  <section class="ec-wrap f-section f-model-preview"><div>${kicker('FOLLOW THE MONEY')}<h2>Revenue is only<br>the beginning.</h2><p>More charging activity can increase receipts. Electricity prices, maintenance and downtime change what remains.</p><p>Try an operating example that shows both a surplus and a shortfall.</p>${button('Explore a station’s economics','inside-a-station/#operating-example',true)}</div><div class="f-business-diagram" aria-label="Revenue minus costs gives an operating balance"><div>${icon('bolt')}<span>Charging receipts<small>Payments from drivers</small></span></div><div><b>−</b><span>Electricity & operating costs<small>Costs continue when activity slows</small></span></div><div><b>=</b><span>Operating balance<small>Before financing, tax and distribution rules</small></span></div><p>A positive balance is not automatically an investor payout.</p></div></section>
  ${partners}
  <section class="f-dark"><div class="ec-wrap f-section"><div class="f-section-heading">${kicker('BEFORE YOU MAKE A DECISION')}<h2>Know what you would own.<br>Know what still needs proof.</h2><p>This is a participation concept. No investment rights are created by this demo.</p></div><div class="f-questions">
    <a href="terms/#client-rights"><span>YOUR PARTICIPATION</span><h3>What am I buying?</h3><p>The proposed instrument and client rights still need a final agreement.</p><b>Review the open terms ${icon('arrow')}</b></a>
    <a href="about/#company"><span>THE COMPANY</span><h3>Who is responsible?</h3><p>EcoCharge is the project brand. The legal issuer and network scope must be documented.</p><b>Company & people ${icon('arrow')}</b></a>
    <a href="terms/#capital-access"><span>ACCESS & RISK</span><h3>How could I exit?</h3><p>Fees, holding periods and withdrawal conditions are not finalized.</p><b>Access, fees & risks ${icon('arrow')}</b></a>
  </div><p class="f-dark-footnote">The proposed 43% company interest remains unverified. Public station listings and photographs do not establish ownership or affiliation.</p></div></section>
  <section class="ec-wrap f-section f-start"><div>${kicker('YOUR NEXT STEP')}<h2>Take a look inside.<br>Keep what interests you.</h2><p>Explore the stations, build a sample plan and read the documents. Create a demo profile when you want to save your plan.</p><div class="f-actions">${explore('Build my demo plan','tariffs')}${link('Company & documents','resources/#company-documents')}</div></div><div><h3>Questions before you start</h3>${faq('Can I explore without registering?','Yes. Open the demo, inspect real public locations and try a plan. You can create a local demo profile when you save your plan. No payment details are needed.')}${faq('Are the stations shown company-owned assets?','Ownership and affiliation have not been established. The photos and station records identify public locations. Documentation must connect a legal issuer to specific assets before any ownership claim can be verified.')}${faq('Can I invest real money here?','No. This is an interactive product demonstration. Accounts, messages and sample finances stay in your browser. No money is collected and no registration email is sent.')}</div></section>`;

  const inside=`<div class="ec-wrap"><header class="f-study-heading">${kicker('INSIDE A CHARGING STATION')}<h1>A real location.<br><span>A clearer view of the business.</span></h1><p>Start with the equipment you can see. Then explore how activity and costs change an illustrative operating result.</p></header>
  <section class="f-study-location"><div>${photo('371815',true)}<button class="ec-text-button" data-station="371815">Open photos & location details ${icon('arrow')}</button></div><div><span class="ec-badge">SOURCED LOCATION RECORD</span><h2>Clermont, Florida</h2><p>${esc(station.name)}<br>${esc(station.address)}, ${esc(station.city)}, ${esc(station.state)}</p><dl class="f-facts"><div><dt>Listed network</dt><dd>${esc(station.network)}</dd></div><div><dt>DC charging ports</dt><dd>${station.ports}</dd></div><div><dt>Directory snapshot</dt><dd>${esc(directory.fetchedAt.slice(0,10))}</dd></div><div><dt>Company ownership</dt><dd>Not established</dd></div></dl><a class="ec-text-link" href="${esc(station.source)}" target="_blank" rel="noopener">Check the public record ↗</a><p class="f-small">The operating example below is invented teaching data. It is not this location’s revenue, price, occupancy or performance.</p></div></section>
  <section class="f-section" id="operating-example"><div class="f-section-heading">${kicker('INTERACTIVE OPERATING EXAMPLE')}<h2>Change the activity.<br>See what remains.</h2><p>All inputs are adjustable assumptions. The calculation covers one 30-day month and does not calculate an investor return.</p></div>
  <div class="f-calculator" id="station-economics"><div class="f-economics-inputs"><div class="f-scenarios" role="group" aria-label="Operating scenarios"><button data-econ-scenario="quiet" aria-pressed="false">Quiet month</button><button data-econ-scenario="example" aria-pressed="true">Example month</button><button data-econ-scenario="busy" aria-pressed="false">Busy month</button></div>
    <label for="econ-sessions">Sessions per day <output id="econ-sessions-value" for="econ-sessions">20</output></label><input id="econ-sessions" type="range" min="0" max="80" step="1" value="20">
    <label for="econ-energy">Energy per session <output id="econ-energy-value" for="econ-energy">30 kWh</output></label><input id="econ-energy" type="range" min="10" max="80" step="1" value="30">
    <label for="econ-price">Charging price per kWh <output id="econ-price-value" for="econ-price">$0.45</output></label><input id="econ-price" type="range" min="0.10" max="0.90" step="0.01" value="0.45">
    <label for="econ-cost">Electricity cost per kWh <output id="econ-cost-value" for="econ-cost">$0.18</output></label><input id="econ-cost" type="range" min="0.05" max="0.60" step="0.01" value="0.18">
    <label for="econ-fixed">Other monthly operating costs <output id="econ-fixed-value" for="econ-fixed">$3,000</output></label><input id="econ-fixed" type="range" min="500" max="10000" step="100" value="3000">
    <details class="f-assumptions"><summary>What this example includes</summary><p>Energy = daily sessions × energy per session × 30 days. Receipts = energy × charging price. Electricity cost = energy × electricity price. Other costs represent an assumed combined allowance for site expenses, maintenance and equipment wear.</p><p>Demand charges, payment fees, financing, tax, capital expenditure and distribution rules are not modeled separately. Real costs require operator records. The unverified 43% interest and weekly plan rates are not applied.</p></details></div>
    <div class="f-economics-result"><span class="ec-badge">ILLUSTRATIVE MONTH · 30 DAYS</span><div class="f-energy-total"><strong id="econ-total-sessions">600</strong><span>sample sessions <i>·</i> <b id="econ-total-energy">18,000</b> kWh</span></div><dl><div><dt>Charging receipts</dt><dd id="econ-receipts">$8,100.00</dd></div><div><dt>Electricity cost</dt><dd id="econ-electricity">−$3,240.00</dd></div><div><dt>Other operating costs</dt><dd id="econ-other">−$3,000.00</dd></div></dl><div class="f-econ-bottom"><span id="econ-result-label">Operating surplus</span><strong id="econ-result">$1,860.00</strong><small>Before financing, tax and distribution rules</small></div><p id="econ-explanation" role="status" aria-live="polite">This operating surplus is not a client payout. An agreement would determine any distribution.</p><div class="f-econ-bars" aria-hidden="true"><i id="econ-bar-electricity"></i><i id="econ-bar-fixed"></i><i id="econ-bar-result"></i></div><small>Costs can exceed receipts. No return is guaranteed by this example.</small></div></div></section>
  <section class="f-section f-proof"><div>${kicker('FROM AN EXAMPLE TO EVIDENCE')}<h2>What makes a location<br>an investment asset?</h2><p>A photograph tells you what a station looks like. Documents establish the business, ownership and your rights.</p></div><div class="f-proof-list"><a href="${esc(station.source)}" target="_blank" rel="noopener"><span>Location & equipment record<small>Public source available</small></span>↗</a><a href="resources/#company-documents"><span>Company ownership & network scope<small>Evidence not supplied</small></span>→</a><a href="resources/#company-documents"><span>Operating statements & expenses<small>Evidence not supplied</small></span>→</a><a href="terms/"><span>Client rights, fees & exit conditions<small>Final terms pending</small></span>→</a></div></section>
  <section class="f-study-finish"><div><h2>Now explore your own example.</h2><p>Inspect reference locations, build a sample plan and keep your questions together.</p></div>${explore('Try the plan builder','tariffs')}</section></div>`;
  return {home,inside};
};
