const fs = require('fs');
const {brand:renderBrand}=require('./brand.cjs');
const photos = JSON.parse(fs.readFileSync('dist/station-photos.json', 'utf8'));
const directory = JSON.parse(fs.readFileSync('dist/stations.json', 'utf8'));
const {featuredIds,illustrations}=JSON.parse(fs.readFileSync('dist/station-visuals.json','utf8'));
const photoCount=featuredIds.filter(id=>photos[id]).length;
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = (name) => {
  const paths = {arrow:'M5 12h14m-6-6 6 6-6 6',bolt:'m13 2-9 12h7l-1 8L21 9h-8z',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0ZM9 10a3 3 0 1 0 6 0 3 3 0 0 0-6 0',file:'M14 2H5v20h14V7zm0 0v6h5M8 12h8M8 16h6',check:'m5 12 4 4L19 6',chat:'M21 11a9 9 0 0 1-9 9H3l2-5a9 9 0 1 1 16-4ZM8 10h8m-8 4h5',grid:'M3 3h7v7H3zm11 0h7v7h-7zM3 14h7v7H3zm11 0h7v7h-7z'};
  return `<svg class="ec-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name] || paths.arrow}"/></svg>`;
};
const button = (label, href='register/', secondary=false) => `<a class="ec-button${secondary?' ec-button-outline':''}" href="${href}">${label}${icon('arrow')}</a>`;
const kicker = label => `<span class="ec-kicker">${label}</span>`;
const heading = (tag, title, copy) => `<div class="ec-page-heading">${kicker(tag)}<h1>${title}</h1><p>${copy}</p></div>`;
const link = (label, href) => `<a class="ec-text-link" href="${href}">${label}${icon('arrow')}</a>`;
const photo = (id, eager=false) => {const p=photos[id];return `<figure class="ec-photo"><img src="assets/public-${id}.webp" alt="${esc(p.alt)}" width="1200" height="800" ${eager?'fetchpriority="high"':'loading="lazy"'} style="object-position:${p.position||'50% 50%'}"><figcaption>${esc(p.location)}<a href="${p.source}" target="_blank" rel="noopener">${esc(p.credit)} ↗</a></figcaption></figure>`;};
const finish = () => `<section class="ec-finish ec-wrap"><div>${kicker('YOUR NEXT STEP')}<h2>Get a clearer picture.<br>Then make your decision.</h2><p>Explore the stations, compare the model and keep your questions in one account.</p></div><div>${button('Create my demo account')}<small>No payment details. No obligation to fund.</small></div></section>`;
const faq = (q,a) => `<details class="ec-faq"${q==='Where is my demo information saved?'?' id="privacy"':''}><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`;
const rates = [{id:'single',name:'Single',count:1,rate:3},{id:'network',name:'Network',count:3,rate:5.6},{id:'portfolio',name:'Portfolio',count:5,rate:7.9},{id:'scale',name:'Scale',count:10,rate:11.2}];
const trust = require('./trust-sections.cjs')({esc,icon,kicker,link,button,faq});
const explain = require('./public-explainer.cjs')({esc,icon,kicker,link,button,faq});

const home = `<section class="ec-hero ec-wrap">
  <div class="ec-hero-copy">${kicker('U.S. EV CHARGING · EXPLORE THE INVESTMENT MODEL')}<h1>Explore investing<br>in <span>EV charging.</span></h1><p>Explore real charging locations and understand the proposed business. See how participation, operating activity and your account fit together.</p>
    <div class="ec-hero-actions"><a class="ec-button" id="hero-build-plan" href="register/?next=tariffs">Build my demo plan ${icon('arrow')}</a>${link('See 50 stations','stations/')}</div><div class="ec-quiet-promise">${icon('check')} Free to explore · No payment details · No obligation</div>
  </div>
  <div class="ec-hero-exhibit"><div class="ec-exhibit-label"><span>${icon('pin')} CLERMONT, FLORIDA</span><span>PUBLIC LOCATION</span></div><div class="ec-hero-photo-wrap">${photo('371815',true)}<button class="ec-hero-station-button" data-station="371815"><span>Explore this location<small>6 DC ports · Clermont, FL</small></span>${icon('arrow')}</button></div>
    <div class="ec-account-preview"><div class="ec-preview-header"><span class="ec-preview-brand">${icon('bolt')} Your EcoCharge account</span><span class="ec-badge">SAMPLE</span></div>
      <div class="ec-preview-tabs" role="tablist" aria-label="Preview your account"><button role="tab" id="preview-tab-plan" aria-controls="preview-panel" aria-selected="true" data-preview="plan">My plan</button><button role="tab" id="preview-tab-stations" aria-controls="preview-panel" aria-selected="false" tabindex="-1" data-preview="stations">My stations</button><button role="tab" id="preview-tab-documents" aria-controls="preview-panel" aria-selected="false" tabindex="-1" data-preview="documents">Documents</button></div>
      ${explain.preview}
    </div>
  </div>
</section>
<div class="ec-reassurance"><div class="ec-wrap"><a href="stations/">${icon('pin')}<span>Real locations<small>With sources you can check</small></span>${icon('arrow')}</a><a href="plans/">${icon('grid')}<span>Visible calculations<small>Amount × weekly model rate</small></span>${icon('arrow')}</a><a href="resources/">${icon('file')}<span>Terms before decisions<small>Preview, read and ask questions</small></span>${icon('arrow')}</a></div></div>
${explain.hardware}
<section class="ec-dark-section"><div class="ec-wrap ec-model-teaser"><div>${kicker('THE MODEL, IN PLAIN ENGLISH')}<h2>Charging activity.<br>Company revenue.<br>Your weekly illustration.</h2>${link('Follow the complete model','how-it-works/')}</div><div><p>The concept connects participation in a charging business with a weekly account allocation. Driver payments are the proposed revenue source.</p><p>Your demo calculation is <strong>invested amount × weekly plan rate</strong>. It does not add a second payment for each car.</p><div class="ec-dark-note">The company’s 43% participation figure is an unverified model assumption. The demo rates are illustrative, not evidence of actual returns.</div></div></div></section>
<section class="ec-section ec-wrap ec-get-started"><div>${kicker('START WITH UNDERSTANDING')}<h2>Your first visit,<br>made simple.</h2><p>No deposit is needed to explore the product.</p></div><ol class="ec-journey"><li><b>1</b><div><h3>Open your demo account</h3><p>Add a display name. No card, bank details or identity documents.</p></div></li><li><b>2</b><div><h3>Build an example</h3><p>Explore locations, compare a plan and follow a sample weekly calculation.</p></div></li><li><b>3</b><div><h3>Review before going further</h3><p>Read the sample documents and try a conversation with the demo manager.</p></div></li></ol></section>
${finish()}`;

const how = `<div class="ec-wrap">${heading('HOW IT WORKS','Follow the money.<br>Understand the model.','Three connected parts: charging activity, company participation and your weekly account illustration.')}<section class="ec-model-explorer"><div class="ec-model-tabs" role="tablist" aria-label="Revenue model"><button role="tab" id="model-tab-drivers" aria-selected="true" aria-controls="model-panel" data-model="drivers"><b>01</b><span>Drivers charge<small>The proposed revenue source</small></span>${icon('arrow')}</button><button role="tab" id="model-tab-company" aria-selected="false" tabindex="-1" aria-controls="model-panel" data-model="company"><b>02</b><span>The company participates<small>The proposed business interest</small></span>${icon('arrow')}</button><button role="tab" id="model-tab-account" aria-selected="false" tabindex="-1" aria-controls="model-panel" data-model="account"><b>03</b><span>You review your account<small>The weekly demo calculation</small></span>${icon('arrow')}</button></div><div id="model-panel" class="ec-model-panel" role="tabpanel" aria-labelledby="model-tab-drivers" tabindex="0">${icon('bolt')}<span class="ec-kicker">OPERATING ACTIVITY</span><h2>A driver pays for a charging session.</h2><p>In the proposed model, charging fees generate business revenue. Electricity, equipment, site costs and other expenses would be deducted before any distributable proceeds are known.</p><div class="ec-formula">Charging payments <span>− operating costs</span></div><small>The demo is not connected to station payment or operating data.</small></div></section>
<section class="ec-section ec-explainer-grid"><div>${kicker('TWO DIFFERENT PARTS OF THE MODEL')}<h2>Company participation.<br>Your client plan.</h2><p>A company interest and the terms offered to a client are different things. Each needs its own documented basis.</p></div><div class="ec-definition-list"><article><b>43%</b><div><h3>Company participation assumption</h3><p>A proposed interest in a network. Its scope and ownership documents are not verified. It does not mean 43% of US charging stations.</p></div></article><article><b>Your plan</b><div><h3>A calculation inside your account</h3><p>Your station group sets the demo rate. You choose the amount, and the account calculates the weekly illustration. It is not derived from the performance of the public stations shown.</p></div></article></div></section>
<section class="ec-example-band"><div>${kicker('YOUR PERSONAL EXAMPLE')}<h2>Build the calculation<br>inside your account.</h2><p>Choose your amount and station group. Review the weekly illustration before saving a demo plan.</p></div>${button('Explore my demo account','register/?next=tariffs')}</section>
<section class="ec-section ec-two-col"><div><h2>What you can do<br>in the account.</h2><p>Try the complete client experience with sample finances.</p></div><ul class="ec-check-list"><li>${icon('check')} Select reference stations and a weekly plan</li><li>${icon('check')} Submit a demo funding request</li><li>${icon('check')} See a sample credit recorded by the demo manager</li><li>${icon('check')} Print sample terms and exchange demo messages</li></ul></section></div>${finish()}`;

const stationIds = featuredIds.map(String);
const stationCards = stationIds.map(id => {const s=directory.stations.find(s=>s.id===Number(id)),p=photos[id]||illustrations[id],isPhoto=!p.kind;return `<article class="ec-station-card" data-station-card data-kind="${isPhoto?'photo':'illustration'}" data-state="${s.state}" data-search="${esc((s.name+' '+s.city+' '+s.state+' '+s.address+' '+s.id).toLowerCase())}"><button class="ec-station-open" data-station="${id}" aria-label="View ${esc(s.city)} station details"><img src="${isPhoto?'assets/public-'+id+'.webp':p.path}" alt="${esc(p.alt)}" width="700" height="480" loading="lazy" style="object-position:${p.position||'center'}"><span class="ec-station-photo-label">${isPhoto?(1+(p.gallery?.length||0))+' '+(p.gallery?.length?'photos':'photo'):'Illustration'} ${icon('arrow')}</span></button><div class="ec-station-content"><div class="ec-station-region">${esc(s.state)} <span>PUBLIC DIRECTORY</span></div><h2>${esc(s.city)}</h2><p>${esc(s.address)}</p><div class="ec-station-specs"><span>${s.ports} DC ports</span><span>${s.maxKw?'Up to '+s.maxKw+' kW':'Power not listed'}</span></div><div class="ec-station-bottom"><span>${esc(s.network)}</span><button data-station="${id}" class="ec-text-button">Details ${icon('arrow')}</button></div></div></article>`}).join('');
const stations = `<div class="ec-wrap">${heading('EXPLORE 50 US LOCATIONS','More places.<br>More to explore.','Browse 50 real US station records with location photos or clearly marked illustrations. Open any card to review the address, equipment and public source.')}<div class="ec-location-disclosure">${icon('pin')}<p>${photoCount} locations have verified location photos. The other cards use concept illustrations, not photos of those stations. Listings do not establish EcoCharge ownership or affiliation. Availability is not live.</p></div><section class="ec-station-browser" aria-label="Station directory with images"><div class="ec-directory-controls"><label>Search locations<input type="search" id="public-station-search" placeholder="City, address or station ID" autocomplete="off"></label><label>State<select id="public-state-filter"><option value="">All states</option>${[...new Set(stationIds.map(id=>directory.stations.find(s=>s.id===Number(id)).state))].sort().map(s=>`<option>${s}</option>`).join('')}</select></label><p id="public-station-count" role="status">50 station locations</p></div><div class="ec-visual-filters" role="group" aria-label="Image type"><button data-visual-filter="all" aria-pressed="true">All locations <span>50</span></button><button data-visual-filter="photo" aria-pressed="false">Real photos <span>${photoCount}</span></button><button data-visual-filter="illustration" aria-pressed="false">Illustrations <span>${50-photoCount}</span></button></div><div class="ec-station-grid">${stationCards}</div><div class="ec-station-pagination"><button class="ec-button ec-button-outline" id="load-more-stations" hidden>Show more locations</button><small id="station-page-count" role="status"></small></div><div class="ec-empty" id="station-empty" hidden><h2>No matching locations</h2><p>Try another city, image type or choose All states.</p><button class="ec-button ec-button-outline" id="clear-station-search">Clear filters</button></div></section><section class="ec-example-band"><div>${kicker('TAKE THE NEXT STEP')}<h2>Explore the wider directory.</h2><p>The account map contains ${directory.stations.length.toLocaleString('en-US')} public station records in this snapshot. Your selected stations stay together in your demo plan.</p></div>${button('Open a demo account','register/?next=map')}</section></div>${finish()}`;

const plans = explain.plans;

const about = `<div class="ec-wrap">${heading('ABOUT ECOCHARGE','Understand the project.<br>Know what you are looking at.','EcoCharge is an EV-charging participation concept presented under the ECO CHARGE brand. This site lets you explore the proposed client experience.')}<section class="ec-about-lead">${photo('371815',true)}<div>${kicker('WHAT WE ARE BUILDING')}<h2>One place to understand<br>your participation.</h2><p>The concept brings station research, plan calculations, documents and manager conversations into a single account.</p><p>Drivers’ charging payments are the proposed business revenue source. The demo shows how a client could review a weekly allocation and track its history.</p>${link('Read how the model works','how-it-works/')}</div></section>
<section class="ec-section"><div class="ec-section-heading"><div>${kicker('PROJECT SCOPE')}<h2>A working product.<br>Explore the core workflows.</h2></div><p>Explore the product features. Financial activity is simulated for the academic project.</p></div><div class="ec-status-table"><div><strong>Interactive client and manager workspaces</strong><span class="ec-status ready">Available</span></div><div><strong>Public station records and attributed photos</strong><span class="ec-status ready">Available</span></div><div><strong>Station selection and weekly plan calculations</strong><span class="ec-status ready">Available</span></div><div><strong>Shared client and team conversations</strong><span class="ec-status ready">Available</span></div><div><strong>Printable agreements and station documents</strong><span class="ec-status ready">Available</span></div><div><strong>English and Russian on desktop and mobile</strong><span class="ec-status ready">Available</span></div></div></section>
<section class="ec-example-band"><div><h2>A useful starting point.</h2><p>Use the demo to evaluate the experience. Company identity, ownership and offering terms need independent verification before any real-money decision.</p></div>${button('Review the resources','resources/')}</section></div>${finish()}`;

const resources = `<div class="ec-wrap">${heading('DOCUMENTS & ANSWERS','Read first.<br>Ask better questions.','Explore sample documents, understand what needs verification and find answers before opening your demo account.')}<section class="ec-resource-grid" aria-label="Documents"><article>${icon('file')}<span class="ec-status ready">Sample available</span><h2>Participation summary</h2><p>See how the demo amount, selected plan and weekly calculation can be presented together.</p><button class="ec-text-button" data-document="summary">Preview sample ${icon('arrow')}</button></article><article>${icon('grid')}<span class="ec-status">Verification pending</span><h2>Company & ownership</h2><p>The issuer, legal structure, network scope and evidence supporting the 43% interest.</p><button class="ec-text-button" data-document="ownership">What to verify ${icon('arrow')}</button></article><article>${icon('chat')}<span class="ec-status">Final terms pending</span><h2>Fees, access & risks</h2><p>Questions about costs, eligibility, withdrawals, revenue shortfalls and client rights.</p><button class="ec-text-button" data-document="terms">Review the questions ${icon('arrow')}</button></article></section>
<section class="ec-section ec-resource-faq"><div>${kicker('FREQUENTLY ASKED QUESTIONS')}<h2>Clear answers.<br>In one place.</h2><p>Still exploring? Create a demo account to try the manager conversation.</p>${link('Open the demo account','register/')}</div><div>
${faq('What happens after I register?','A demo profile opens in this browser. You can explore the map, compare plans, review sample documents and try manager messages. No payment details or identity documents are requested.')}
${faq('Can I deposit or withdraw real money?','No. All balances, funding requests and credits are sample data. Requests can be reviewed in the separate team demo on the same browser. No real transfer takes place.')}
${faq('How is the weekly allocation calculated?','The demo applies the selected weekly percentage to invested demo capital. You can choose your amount and inspect the complete calculation inside your account. It does not add an extra credit for every charging vehicle.')}
${faq('What does the 43% company figure mean?','It is an unverified assumption for a company interest in a proposed network. The network scope and ownership evidence have not been provided. It does not mean ownership of 43% of all US charging stations.')}
${faq('Are the listed stations owned by EcoCharge?','Ownership has not been established. Stations and photos are third-party public references. Operator names identify the public listings and do not imply a partnership or endorsement.')}
${faq('Who answers messages in this demo?','The team demo can read and reply to messages saved in the same browser. The displayed manager is a placeholder until real team details are provided. Messages are not delivered to a live external support team.')}
${faq('Where is my demo information saved?','The profile and demo activity are stored in this browser on this device. No registration email is sent and no server account is created. Use sample details. Clearing site data removes the local demo. Another device starts a separate demo.')}
${faq('What should I verify before investing real money?','Verify the legal issuer, offering terms, eligibility, ownership evidence, revenue records, fees, withdrawal rules and risk disclosures. Sample documents and a working interface do not establish an investment right or prove returns.')}
</div></section></div>${finish()}`;

const register = `<section class="ec-registration ec-wrap"><div class="ec-registration-intro">${kicker('YOUR ECOCHARGE DEMO')}<h1>Keep your choices.<br><span>Continue your research.</span></h1><p>Save your sample plan and return to it in this browser. Your station selection, documents and demo conversations stay together.</p><ul class="ec-check-list"><li>${icon('check')} A station directory with source links</li><li>${icon('check')} Your own weekly plan example</li><li>${icon('check')} Sample documents and manager conversations</li></ul><div class="ec-registration-note">Free to explore. No deposit, bank details or identity documents.</div></div><section class="ec-registration-card"><span class="ec-badge">DEMO REGISTRATION</span><h2>Create your demo account</h2><p>This preview is saved on this device. Use sample details.</p><form id="registration-form"><label for="register-name">Display name</label><input id="register-name" name="name" autocomplete="off" placeholder="Alex" required minlength="2" maxlength="60"><label for="register-email">Email <span>Optional</span></label><input id="register-email" name="email" type="email" autocomplete="off" placeholder="alex@example.com" maxlength="120" aria-describedby="register-email-hint"><small id="register-email-hint">A sample email is fine. No verification email is sent.</small><input type="hidden" id="register-next" name="next" value="dashboard"><div id="registration-plan" class="ec-registration-plan" hidden></div><label class="ec-checkbox"><input type="checkbox" id="register-consent" required><span>I understand this is a demo with sample finances. <a href="resources/#privacy" target="_blank" rel="noopener">How demo data is stored ↗</a></span></label><p id="registration-error" class="ec-form-error" role="alert"></p><button type="submit" class="ec-button">Create my demo account ${icon('arrow')}</button></form><p class="ec-existing-account"><a href="client/?guest=1&tab=tariffs">Keep exploring without a profile →</a></p><p class="ec-existing-account">Already exploring? <a href="login/">Sign in to the demo →</a></p><small class="ec-form-footnote">No real investment or secure server account is created. Use the shared client login to reopen this browser’s saved demo.</small></section></section>`;

// Keep the same page paths and working product flows; add the evidence in context.
const enhancedHome = home
  .replace(/<div class="ec-reassurance">[\s\S]*?<\/div><\/div>/,trust.rights)
  .replace(/<section class="ec-dark-section">[\s\S]*?<\/section>/,trust.video())
  .replace('<section class="ec-section ec-wrap ec-get-started">',trust.cashFlow().replace('</section>','<p class="ec-section-footnote">The proposed 43% company interest is an unverified assumption. Weekly plan rates are demo inputs, not measured station results.</p></section>')+'<section class="ec-section ec-wrap ec-get-started">')
  .replace(finish(),trust.questions+finish());
const enhancedHow = how.replace('<section class="ec-section ec-explainer-grid">',trust.cashFlow(true)+'<section class="ec-section ec-explainer-grid">');
const enhancedPlans = plans.replace('<section class="ec-section ec-two-col">',trust.terms()+'<section class="ec-section ec-two-col">')+finish();
const companyStory = require('./company-story.cjs')({esc,icon,kicker,link});
const enhancedAbout = about
  .replace('Understand the project.<br>Know what you are looking at.','The company story.<br>The people behind it.')
  .replace('EcoCharge is an EV-charging participation concept presented under the ECO CHARGE brand. This site lets you explore the proposed client experience.','Explore the founder profile and company story supplied for this demo, alongside the legal information and documents still to be provided.')
  .replace('<section class="ec-about-lead">',companyStory.profile+'<section class="ec-about-lead">')
  .replace('<section class="ec-section"><div class="ec-section-heading">',trust.company()+trust.team()+'<section class="ec-section"><div class="ec-section-heading">').replace(finish(),trust.video()+finish());
const enhancedResources = resources.replace('<section class="ec-section ec-resource-faq">',trust.documents()+'<section class="ec-section ec-resource-faq">');
const enhancedRegister = register.replace('<form id="registration-form">','<details class="ec-registration-explainer"><summary>What opens after registration?</summary><p>Your station map, sample plan, documents and demo conversations. You only need a display name; email is optional. No card, identity documents or payment are requested.</p><a href="terms/" target="_blank" rel="noopener">Read access, fees & risks ↗</a></details><form id="registration-form">');
const pages = {'':{title:'EV charging, clearly explained',body:enhancedHome},'how-it-works':{title:'How participation works',body:enhancedHow.replace('<section class="ec-model-explorer">','<div class="ec-example-band"><div><h2>Try the operating model.</h2><p>Change charging activity and electricity costs. See a surplus or a shortfall.</p></div>'+button('Inside a charging station','inside-a-station/')+'</div><section class="ec-model-explorer">')},stations:{title:'Explore US charging locations',body:stations},plans:{title:'Explore your demo plan',body:enhancedPlans},about:{title:'About the EcoCharge project',body:enhancedAbout},resources:{title:'Documents and answers',body:enhancedResources},terms:{title:'Access, fees and risks',body:trust.termsPage+finish()},register:{title:'Create your demo account',body:enhancedRegister}};
const navItems=[['','Overview'],['how-it-works','How it works'],['stations','Stations'],['plans','Plans'],['about','About us'],['resources','Resources']];
const brand=renderBrand();
const funnelPages=require('./funnel-pages.cjs')({esc,icon,kicker,link,button,faq,photo,directory,trust,hardware:explain.hardware});
pages[''].body=funnelPages.home;
pages['inside-a-station']={title:'Inside a charging station',body:funnelPages.inside};
function renderPage(route,p){return `<!doctype html>
<html lang="en-US" data-page="${route||'home'}"><head><meta charset="utf-8">${route?'<base href="../">':''}<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#152b39"><title>EcoCharge — ${p.title}</title><meta name="description" content="Explore the EcoCharge demo: real public charging locations, transparent weekly calculations, sample documents and your own client workspace."><link rel="icon" type="image/svg+xml" href="assets/ecocharge-mark.svg"><link rel="preload" href="assets/manrope-regular.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="site.css"><link rel="stylesheet" href="brand.css"><link rel="stylesheet" href="funnel.css"><link rel="stylesheet" href="site-refinements.css"><script src="station-visuals.js" defer></script><script src="funnel-events.js" defer></script><script src="site.js" defer></script><script src="funnel.js" defer></script></head>
<body><a class="ec-skip" href="#main">Skip to content</a><div class="ec-demo-bar"><div class="ec-wrap"><span>PRODUCT DEMO</span><p>Explore with sample finances. No real payments.</p><a href="about/">Project status ↗</a></div></div><header class="ec-header"><div class="ec-header-inner ec-wrap">${brand}<nav class="ec-nav" aria-label="Main navigation">${navItems.map(([path,label])=>`<a href="${path?path+'/':'./'}" ${route===path?'aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="ec-header-actions"><button class="ec-menu-trigger" id="open-site-menu" aria-label="Open navigation menu" aria-controls="site-menu" aria-expanded="false"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button><a href="login/" class="ec-sign-in">Sign in</a><a href="client/?guest=1&amp;tab=dashboard" class="ec-button ec-button-small" ${route==='register'?'aria-current="page"':''}>Explore demo${icon('arrow')}</a></div></div></header>
<main id="main">${route&&route!=='register'?`<div class="ec-breadcrumb ec-wrap"><a href="./">Home</a><span>/</span>${navItems.find(n=>n[0]===route)?.[1]||p.title}</div>`:''}${p.body}</main>
<footer class="ec-footer"><div class="ec-wrap ec-footer-main"><div>${brand}<p>Understand the infrastructure.<br>Explore your participation.</p><span class="ec-footer-demo">Interactive product demo</span></div><div><h2>Explore</h2><a href="how-it-works/">How it works</a><a href="stations/">Charging stations</a><a href="inside-a-station/">Inside a station</a><a href="plans/">Participation model</a></div><div><h2>Get clarity</h2><a href="about/">About the project</a><a href="resources/">Documents & answers</a><a href="resources/#privacy">Demo privacy</a></div><div><h2>Your workspace</h2><a href="register/">Create demo account</a><a href="login/">Client sign-in</a><a href="team/">Team sign-in ↗</a></div></div><div class="ec-wrap ec-footer-legal"><p>ECO CHARGE is a project brand in this demo. Company identity, ownership and offering terms are not verified. Public station listings do not imply affiliation. Sample rates and balances are not actual returns or an offer to invest.</p><span>USD · English (US)</span></div></footer>
${route==='register'?'':`<div class="ec-mobile-action"><span>Take a look inside<small>Free demo · No payment details</small></span><a href="client/?guest=1&amp;tab=dashboard" class="ec-button ec-button-small">Explore demo ${icon('arrow')}</a></div>`}
<dialog id="site-menu" aria-label="Site navigation"><div class="ec-menu-top">${brand}<button id="close-site-menu" aria-label="Close navigation menu">✕</button></div><nav aria-label="All pages">${navItems.map(([path,label],i)=>`<a href="${path?path+'/':'./'}" ${route===path?'aria-current="page"':''}><span><strong>${label}</strong><small>${['Start with the full picture','Follow the participation model','Explore real public locations','Understand your account choices','Get to know the project','Documents and answers'][i]}</small></span>${icon('arrow')}</a>`).join('')}</nav><div class="ec-menu-account">${button('Explore the demo','client/?guest=1&tab=dashboard')}<div><a href="login/">Client sign-in</a><a href="team/">Team sign-in ↗</a></div></div></dialog>
<dialog id="site-dialog" aria-labelledby="site-dialog-title"><div class="ec-dialog-toolbar"><span>ECO CHARGE / STATIONS</span><button id="close-site-dialog" aria-label="Close dialog">✕</button></div><div id="site-dialog-content"></div></dialog><noscript><div class="ec-noscript">The pages are readable without JavaScript. Enable JavaScript to use calculators, photo previews and demo registration.</div></noscript></body></html>`;}
module.exports={pages,renderPage:(route,page)=>renderPage(route,page)
  .replace('<a href="inside-a-station/">Inside a station</a>','<a href="inside-a-station/">Inside a station</a><a href="./#technology">AI & computing</a>')
  .replace('<link rel="stylesheet" href="site-refinements.css">','<link rel="stylesheet" href="site-refinements.css"><link rel="stylesheet" href="site-presence.css">')
  .replace('<a href="about/">About the project</a>','<a href="about/">About the project</a><a href="./#partners">Our partners</a>')
  .replace('<link rel="stylesheet" href="brand.css">','<link rel="stylesheet" href="brand.css"><link rel="stylesheet" href="trust.css">')
  .replace('<script src="site.js" defer></script>','<script src="site.js" defer></script><script src="trust-content.js" defer></script><script src="trust.js" defer></script>')
  .replace('<a href="resources/#privacy">','<a href="terms/">Access, fees & risks</a><a href="resources/#privacy">')};
