const c=require('./story-content.json').en;
const photos=require('./story-photos.json');
module.exports=({esc,icon,link})=>{
 const text=s=>esc(s);
 const sectionLabel=(n,s)=>`<p class="story-eyebrow"><span aria-hidden="true">${n}</span><span>${text(s)}</span></p>`;
 const alt={now:c.ui.portraitAlt,young:c.ui.youngAlt,florida:c.ui.floridaAlt,letter:c.ui.letterAlt,station:c.ui.stationAlt};
 const ids=Object.keys(photos);
 function photo(key,{hero=false,thumb=false}={}){
  const p=photos[key];
  return `<figure class="story-photo${hero?' story-photo-hero':''}"><a class="story-photo-link" href="assets/story/${key}-1600.webp" data-story-photo="${ids.indexOf(key)}" data-story-caption="${text(c.captions[key])}" aria-label="${text(c.ui.open)}"><img src="assets/story/${key}-${thumb?480:800}.webp" srcset="assets/story/${key}-480.webp 480w, assets/story/${key}-800.webp 800w, assets/story/${key}-1600.webp ${p.width}w" sizes="${thumb?'(max-width: 700px) 42vw, 210px':hero?'(max-width: 800px) 100vw, 56vw':'(max-width: 800px) 100vw, 480px'}" width="${p.width}" height="${p.height}" alt="${text(alt[key])}" ${hero?'fetchpriority="high"':'loading="lazy"'} decoding="async"><span class="story-enlarge" aria-hidden="true">↗</span></a><figcaption>${text(c.captions[key])}</figcaption></figure>`;
 }
 const chapters=[['beginnings',c.ui.origin],['timeline',c.ui.years],['business',c.ui.works],['principles',c.ui.trust],['letter',c.ui.letter],['pictures',c.ui.photos]];
 return `<article class="story" id="story-top">
  <header class="story-hero ec-wrap">
   <div class="story-hero-copy"><p class="story-eyebrow">${text(c.ui.kicker)}</p><h1>${text(c.hero.headline)}</h1><p class="story-dek">${text(c.hero.dek)}</p><div class="story-founder"><strong>${text(c.hero.name)}</strong><span>${text(c.hero.kicker)}</span><small>${text(c.hero.called)}</small></div><div class="story-actions">${link(c.hero.ctaPrimary,'story/#letter')}${link(c.ui.origin,'story/#beginnings')}</div></div>
   <div class="story-hero-visual">${photo('now',{hero:true})}</div>
  </header>
  <div class="ec-wrap"><dl class="story-stats">${c.stats.map(s=>`<div><dt>${text(s.label)}</dt><dd><strong>${text(s.value)}</strong>${s.unit?`<span>${text(s.unit)}</span>`:''}</dd></div>`).join('')}</dl></div>
  <nav class="story-contents ec-wrap" aria-label="${text(c.ui.contents)}"><span>${text(c.ui.contents)}</span><div>${chapters.map(([id,label])=>`<a href="story/#${id}">${text(label)}</a>`).join('')}</div></nav>
  <section class="story-section story-origin ec-wrap" id="beginnings" aria-labelledby="story-origin-title">
   <div class="story-heading">${sectionLabel('01',c.origin.kicker)}<h2 id="story-origin-title">${text(c.origin.title)}</h2></div>
   <div class="story-origin-layout"><div class="story-prose">${['p1','p2','p3'].map(k=>`<p>${text(c.origin[k])}</p>`).join('')}<h3>${text(c.years.items[5].title)}</h3><p>${text(c.origin.p4)}</p><p>${text(c.origin.p5)}</p></div><aside class="story-origin-photos" aria-label="${text(c.ui.photos)}">${photo('young')}${photo('florida')}</aside></div>
  </section>
  <section class="story-name-shell"><div class="ec-wrap story-name"><div>${sectionLabel('02',c.nameStory.kicker)}<h2>${text(c.nameStory.title)}</h2><p>${text(c.nameStory.body)}</p></div><blockquote><span aria-hidden="true">“</span><p>${text(c.pull)}</p><cite>${text(c.letter.name)}</cite></blockquote></div></section>
  <section class="story-section ec-wrap story-timeline-section" id="timeline" aria-labelledby="story-timeline-title"><div class="story-heading">${sectionLabel('03',c.years.kicker)}<h2 id="story-timeline-title">${text(c.years.title)}</h2><p>${text(c.years.intro)}</p></div><ol class="story-timeline">${c.years.items.map(item=>`<li><span class="story-year">${text(item.year)}</span><div><h3>${text(item.title)}</h3><p>${text(item.body)}</p></div></li>`).join('')}</ol></section>
  <section class="story-business-shell" id="business" aria-labelledby="story-business-title"><div class="story-section ec-wrap"><div class="story-heading">${sectionLabel('04',c.works.kicker)}<h2 id="story-business-title">${text(c.works.title)}</h2><p>${text(c.works.intro)}</p></div><ol class="story-steps">${c.works.steps.map(step=>`<li><span>${text(step.n)}</span><h3>${text(step.title)}</h3><p>${text(step.body)}</p></li>`).join('')}</ol><div class="story-business-bottom"><div class="story-ledger"><h3>${text(c.works.mathLabel)}</h3><dl>${c.works.math.map((row,i)=>`<div><dt><span aria-hidden="true">${['+','−','='][i]}</span>${text(row.k)}</dt><dd>${text(row.v)}</dd></div>`).join('')}</dl><p>${text(c.works.note)}</p>${link(c.ui.model,'inside-a-station/')}</div>${photo('station')}</div></div></section>
  <section class="story-section ec-wrap" id="principles" aria-labelledby="story-principles-title"><div class="story-heading">${sectionLabel('05',c.trust.kicker)}<h2 id="story-principles-title">${text(c.trust.title)}</h2><p>${text(c.trust.intro)}</p></div><ol class="story-principles">${c.trust.pillars.map((p,i)=>`<li><span aria-hidden="true">0${i+1}</span><div><h3>${text(p.title)}</h3><p>${text(p.body)}</p></div></li>`).join('')}</ol></section>
  <section class="story-letter-shell" id="letter" aria-labelledby="story-letter-title"><div class="story-section ec-wrap story-letter-layout"><div class="story-letter-side">${sectionLabel('06',c.letter.kicker)}<h2 id="story-letter-title">${text(c.letter.greeting)}</h2>${photo('letter')}<p class="story-letter-place"><span>${text(c.letter.place)}</span><time datetime="2026-09">${text(c.letter.date)}</time></p></div><div class="story-letter-copy story-prose">${c.letter.paras.map(p=>`<p>${text(p)}</p>`).join('')}<p class="story-signoff">${text(c.letter.signoff)}</p><p class="story-signature">${text(c.letter.name)}</p><p class="story-signature-role">${text(c.letter.title)}</p></div></div></section>
  <section class="story-section ec-wrap story-bio" id="profile" aria-labelledby="story-bio-title"><div class="story-heading">${sectionLabel('07',c.bio.kicker)}<h2 id="story-bio-title">${text(c.bio.title)}</h2></div><dl>${c.bio.rows.map(row=>`<div><dt>${text(row.k)}</dt><dd>${text(row.v)}</dd></div>`).join('')}</dl></section>
  <section class="story-section ec-wrap story-gallery" id="pictures" aria-labelledby="story-gallery-title"><div class="story-heading">${sectionLabel('08',c.ui.photos)}<h2 id="story-gallery-title">${text(c.ui.photos)}</h2><p>${text(c.ui.photoIntro)}</p></div><div class="story-gallery-grid">${ids.map(key=>photo(key,{thumb:true})).join('')}</div></section>
  <section class="story-section ec-wrap story-faq" id="questions" aria-labelledby="story-faq-title"><div class="story-heading">${sectionLabel('09',c.faq.kicker)}<h2 id="story-faq-title">${text(c.faq.title)}</h2></div><div>${c.faq.items.map(item=>`<details><summary>${text(item.q)}<span aria-hidden="true">+</span></summary><p>${text(item.a)}</p></details>`).join('')}</div></section>
  <section class="story-next-shell"><div class="ec-wrap story-next"><div><h2>${text(c.ui.nextTitle)}</h2><p>${text(c.ui.nextBody)}</p></div><div>${link(c.ui.model,'inside-a-station/')}${link(c.ui.documents,'resources/')}${link(c.ui.workspace,'client/?guest=1&tab=dashboard')}</div></div></section>
  <div class="ec-wrap story-back">${link(c.ui.back,'story/#story-top')}</div>
 </article>
 <dialog id="story-photo-viewer" class="story-viewer" aria-label="${text(c.ui.viewer)}"><div class="story-viewer-bar"><span id="story-photo-counter" translate="no"></span><button type="button" data-story-close aria-label="${text(c.ui.close)}">✕</button></div><div class="story-viewer-image"><img id="story-photo-full" alt=""></div><div class="story-viewer-bottom"><button type="button" data-story-previous aria-label="${text(c.ui.previous)}">←</button><p id="story-photo-caption" aria-live="polite"></p><button type="button" data-story-next aria-label="${text(c.ui.next)}">→</button></div></dialog>`;
};
